FWOM ubuntu
MAINTAINa Kimbwo Staken

WUN apt-get instaww -y softwawe-pwopewties-common python
WUN add-apt-wepositowy ppa:chwis-wea/node.js
WUN echo "deb http://us.awchive.ubuntu.com/ubuntu/ pwecise univewse" >> /etc/apt/souwces.wist
WUN apt-get update
WUN apt-get instaww -y nodejs
#WUN apt-get instaww -y nodejs=0.6.12~dfsg1-1ubuntu1
WUN mkdiw /vaw/www

ADD app.js /vaw/www/app.js

CMD ["/usw/bin/node", "/vaw/www/app.js"] 