/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { IChatPetLayeredMove } from './chatPetMoveLayers.js';

/**
 * Moves designed with the VS Code team to show agents the craft the pet's own art has: shaded props
 * about the size of its head, headwear in place of the antennae, anticipation and holds, and the
 * body reacting. The guide lists them by what they show, and agents study the ones closest to what
 * they are asked to draw.
 */
export const ChatPetMoveExamples: readonly { readonly shows: string; readonly move: IChatPetLayeredMove }[] = [
	{
		shows: 'a word that pops up',
		move: {
			name: 'yes',
			about: 'Crouches, jumps for joy, and a big gold YES! pops up above its head.',
			loop: false,
			still: 6,
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 120, pose: 'crouch' },
				{ ms: 90, pose: 'airborne', text: [{ text: 'YES!', size: 'small', x: 3, y: -7, color: 'gold' }] },
				{ ms: 90, pose: 'airborne', text: [{ text: 'YES!', x: 0, y: -9, color: 'gold' }] },
				{ ms: 100, pose: 'crouch', text: [{ text: 'YES!', x: 0, y: -8, color: 'gold' }] },
				{ ms: 900, pose: 'idle', text: [{ text: 'YES!', x: 0, y: -8, color: 'gold' }] },
				{ ms: 90, pose: 'idle', text: [{ text: 'YES!', size: 'small', x: 3, y: -7, color: 'gold' }] },
				{ ms: 200, pose: 'idle' },
			],
		},
	},
	{
		shows: 'a prop above the head',
		move: {
			name: 'idea',
			about: 'Looks up as a light bulb appears above its head, flickers on, and shines.',
			loop: false,
			still: 7,
			colors: { W: '#ffffff', H: '#fff4a8', Y: '#ffd638', D: '#f2b705', K: '#b27805', G: '#b9c0c7', M: '#889096', N: '#55595e', g: '#eef2f5', m: '#c5ccd3', n: '#8d959c' },
			props: {
				on: [
					'..KYY..',
					'.KYYHH.',
					'KYYYHWH',
					'KYYYYHH',
					'.KYYYH.',
					'..KYY..',
					'..GMG..',
					'..MNM..',
					'...N...',
				],
				off: [
					'..nmm..',
					'.nmmgg.',
					'nmmmgWg',
					'nmmmmgg',
					'.nmmmg.',
					'..nmm..',
					'..GMG..',
					'..MNM..',
					'...N...',
				],
				rays: [
					'......D......',
					'.D....D....D.',
					'..D.......D..',
					'.............',
					'.............',
					'DD.........DD',
					'.............',
					'..D.......D..',
					'.D.........D.',
				],
				raysShort: [
					'.....D.....',
					'.D.......D.',
					'...........',
					'...........',
					'D.........D',
					'...........',
					'.D.......D.',
				],
			},
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 260, pose: 'idle', eyes: 'up', place: [{ prop: 'off', x: 3, y: -10 }] },
				{ ms: 80, pose: 'idle', eyes: 'up', place: [{ prop: 'on', x: 3, y: -10 }] },
				{ ms: 70, pose: 'idle', eyes: 'up', place: [{ prop: 'off', x: 3, y: -10 }] },
				{ ms: 110, pose: 'crouch', place: [{ prop: 'on', x: 3, y: -10 }, { prop: 'rays', x: 0, y: -12 }] },
				{ ms: 130, pose: 'airborne', place: [{ prop: 'on', x: 3, y: -10 }, { prop: 'raysShort', x: 1, y: -11 }] },
				{ ms: 450, pose: 'idle', eyes: 'up', place: [{ prop: 'on', x: 3, y: -10 }, { prop: 'rays', x: 0, y: -12 }] },
				{ ms: 350, pose: 'idle', eyes: 'up', place: [{ prop: 'on', x: 3, y: -10 }, { prop: 'raysShort', x: 1, y: -11 }] },
				{ ms: 120, pose: 'idle', place: [{ prop: 'off', x: 3, y: -10 }] },
				{ ms: 200, pose: 'idle' },
			],
		},
	},
	{
		shows: 'a prop beside it that takes off',
		move: {
			name: 'ship-it',
			about: 'A little rocket fires up in front of it and blasts off; the pet follows it with its eyes and cheers.',
			loop: false,
			still: 5,
			colors: { W: '#ffffff', G: '#d8e1e8', S: '#9ca5ad', H: '#fb5b6c', R: '#e82c41', K: '#8b1321', L: '#74b4e0', U: '#0057aa', Y: '#ffe994', O: '#ff921f', P: '#e67505', g: '#c5ccd3', m: '#8d959c' },
			props: {
				rocket: [
					'...H...',
					'..RRH..',
					'..KRR..',
					'..SWG..',
					'..SLG..',
					'..SUG..',
					'..SWG..',
					'.KSWGH.',
					'KR.S.RH',
					'K..S..R',
				],
				flame: [
					'OYO',
					'.O.',
				],
				flameLong: [
					'OYO',
					'PYP',
					'.O.',
				],
				puffs: [
					'.gg.....gg.',
					'gmmg...gmmg',
				],
				puffsBig: [
					'..gg.....gg..',
					'.gmmg...gmmg.',
					'gmmmmg.gmmmmg',
				],
			},
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 250, pose: 'idle', eyes: 'right', place: [{ prop: 'rocket', x: 14, y: 2 }] },
				{ ms: 120, pose: 'idle', eyes: 'right', place: [{ prop: 'rocket', x: 14, y: 2 }, { prop: 'puffs', x: 12, y: 10 }] },
				{ ms: 90, pose: 'idle', eyes: 'right', place: [{ prop: 'rocket', x: 14, y: 0 }, { prop: 'flame', x: 16, y: 10 }, { prop: 'puffsBig', x: 11, y: 9 }] },
				{ ms: 90, pose: 'idle', eyes: 'up-right', place: [{ prop: 'rocket', x: 14, y: -4 }, { prop: 'flameLong', x: 16, y: 6 }, { prop: 'puffsBig', x: 11, y: 9 }] },
				{ ms: 80, pose: 'idle', eyes: 'up-right', place: [{ prop: 'rocket', x: 14, y: -9 }, { prop: 'flameLong', x: 16, y: 1 }, { prop: 'puffs', x: 12, y: 10 }] },
				{ ms: 80, pose: 'idle', eyes: 'up-right', place: [{ prop: 'rocket', x: 14, y: -12 }, { prop: 'flame', x: 16, y: -2 }] },
				{ ms: 110, pose: 'crouch' },
				{ ms: 160, pose: 'airborne' },
				{ ms: 200, pose: 'idle' },
			],
		},
	},
	{
		shows: 'headwear and a held lasso',
		move: {
			name: 'cowboy',
			about: 'Puts on a cowboy hat, twirls a lasso over its head with one antenna, throws it, and tips its hat.',
			loop: false,
			still: 5,
			colors: { H: '#e39a5f', Y: '#b8663a', D: '#8a4a2c', K: '#4a2c22', N: '#2e1f1c', L: '#f0cf8a', R: '#c9964f', S: '#8f6331' },
			props: {
				hat: [
					'...KYH.HH...',
					'...KYYHHH...',
					'...KYYYHH...',
					'.D.NNNNNN.H.',
					'KYYYNNNNYHHH',
					'.KDDYYYYHHH.',
				],
				arm: [
					'...A',
					'..A.',
					'.A..',
					'A...',
				],
				loopLeft: [
					'.RRRRRRRRR.',
					'L.........R',
					'S.........R',
					'.SSSSSSSSS.',
				],
				loopFront: [
					'.RRRRRRRRR.',
					'R.........R',
					'S.........R',
					'.SSSSLSSSS.',
				],
				loopRight: [
					'.RRRRRRRRR.',
					'R.........L',
					'S.........L',
					'.SSSSSSSSS.',
				],
				spoke: [
					'R',
				],
				armForward: [
					'..AA',
					'AA..',
				],
				thrown: [
					'........RRRR',
					'......SS...R',
					'...SSS.....R',
					'SSS.......S.',
					'........SS..',
				],
				rope: [
					'SS.........',
					'..S........',
					'...S.......',
					'...S.......',
					'....S......',
					'....S......',
					'..RRRRRRRRR',
					'.R........R',
					'..SSSSSSSSS',
				],
			},
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 70, pose: 'idle', place: [{ prop: 'hat', x: 0, y: -8 }] },
				{ ms: 100, pose: 'crouch', antennae: false, place: [{ prop: 'hat', x: 0, y: 1 }] },
				{ ms: 110, pose: 'idle', antennae: false, place: [{ prop: 'hat', x: 0, y: -1 }, { prop: 'arm', x: 9, y: -2 }, { prop: 'spoke', x: 12, y: -3 }, { prop: 'loopLeft', x: 7, y: -7 }] },
				{ ms: 110, pose: 'idle', antennae: false, place: [{ prop: 'hat', x: 0, y: -1 }, { prop: 'arm', x: 9, y: -2 }, { prop: 'spoke', x: 12, y: -3 }, { prop: 'loopFront', x: 8, y: -7 }] },
				{ ms: 110, pose: 'idle', antennae: false, place: [{ prop: 'hat', x: 0, y: -1 }, { prop: 'arm', x: 9, y: -2 }, { prop: 'spoke', x: 12, y: -3 }, { prop: 'loopRight', x: 9, y: -7 }] },
				{ ms: 110, pose: 'idle', antennae: false, place: [{ prop: 'hat', x: 0, y: -1 }, { prop: 'arm', x: 9, y: -2 }, { prop: 'spoke', x: 12, y: -3 }, { prop: 'loopLeft', x: 7, y: -7 }] },
				{ ms: 110, pose: 'idle', antennae: false, place: [{ prop: 'hat', x: 0, y: -1 }, { prop: 'arm', x: 9, y: -2 }, { prop: 'spoke', x: 12, y: -3 }, { prop: 'loopFront', x: 8, y: -7 }] },
				{ ms: 100, pose: 'crouch', antennae: false, place: [{ prop: 'hat', x: 0, y: 1 }, { prop: 'armForward', x: 9, y: 3 }, { prop: 'thrown', x: 12, y: 0 }] },
				{ ms: 450, pose: 'idle', antennae: false, place: [{ prop: 'hat', x: 0, y: -1 }, { prop: 'armForward', x: 9, y: 1 }, { prop: 'rope', x: 13, y: 2 }] },
				{ ms: 320, pose: 'idle', antennae: false, place: [{ prop: 'hat', x: 0, y: -2 }] },
				{ ms: 100, pose: 'idle', place: [{ prop: 'hat', x: 1, y: -9 }] },
				{ ms: 200, pose: 'idle' },
			],
		},
	},
	{
		shows: 'a prop that squashes',
		move: {
			name: 'rubber-duck',
			about: 'A rubber duck plops down in front of it; the pet presses it, it squeaks, and the pet jumps in surprise.',
			loop: false,
			still: 5,
			colors: { H: '#fff4a8', Y: '#ffd638', D: '#f2b705', K: '#b27805', O: '#ff921f', P: '#e67505', W: '#889096' },
			props: {
				duck: [
					'..YYH.....',
					'.YYYYH....',
					'OYEYYY....',
					'OPYYYD...H',
					'.KYYYYYYHY',
					'KYYDDYYYYY',
					'KDYYDYYYYD',
					'.KDDDDDDD.',
				],
				squashed: [
					'.YYYH......',
					'OYEYYY....H',
					'OPYYYYYYYHY',
					'KYYDDYYYYYY',
					'KDYYDDYYYYD',
					'.KDDDDDDDD.',
				],
				squeak: [
					'W..W..W',
					'.W.W.W.',
				],
			},
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 80, pose: 'idle', place: [{ prop: 'duck', x: 13, y: -1 }] },
				{ ms: 90, pose: 'idle', eyes: 'right', place: [{ prop: 'squashed', x: 13, y: 6 }] },
				{ ms: 380, pose: 'idle', eyes: 'right', place: [{ prop: 'duck', x: 13, y: 4 }] },
				{ ms: 220, pose: 'crouch', eyes: 'right', place: [{ prop: 'squashed', x: 13, y: 6 }, { prop: 'squeak', x: 14, y: 2 }] },
				{ ms: 170, pose: 'airborne', place: [{ prop: 'duck', x: 13, y: 4 }] },
				{ ms: 380, pose: 'idle', eyes: 'right', place: [{ prop: 'duck', x: 13, y: 4 }] },
				{ ms: 200, pose: 'crouch', eyes: 'right', place: [{ prop: 'squashed', x: 13, y: 6 }, { prop: 'squeak', x: 14, y: 2 }] },
				{ ms: 380, pose: 'idle', eyes: 'right', place: [{ prop: 'duck', x: 13, y: 4 }] },
				{ ms: 90, pose: 'idle', place: [{ prop: 'duck', x: 13, y: 1 }] },
				{ ms: 220, pose: 'idle' },
			],
		},
	},
	{
		shows: 'a held wand and sparkles',
		move: {
			name: 'magic',
			about: 'Raises a magic wand with its antenna, swishes it, and a shower of colorful stars bursts out.',
			loop: false,
			still: 7,
			colors: { W: '#ffffff', Y: '#ffe994', y: '#ffc205', N: '#2b2d2f', M: '#9ca5ad', p: '#f97dbd', P: '#d7257d', b: '#74b4e0', u: '#0057aa', v: '#d373fc', V: '#9529c2', g: '#8be09a', G: '#23904a' },
			props: {
				wandUp: [
					'...Y.',
					'..YWY',
					'...Y.',
					'..N..',
					'.N...',
					'M....',
				],
				wandRight: [
					'....Y.',
					'MNNYWY',
					'....Y.',
				],
				swish: [
					'W..',
					'..Y',
					'...',
					'..y',
				],
				star1: [
					'.v.',
					'vVv',
					'.v.',
				],
				star2: [
					'.b.',
					'bub',
					'.b.',
				],
				star3: [
					'.p.',
					'pPp',
					'.p.',
				],
				star4: [
					'.Y.',
					'YyY',
					'.Y.',
				],
				star5: [
					'.g.',
					'gGg',
					'.g.',
				],
				dotW: [
					'W',
				],
				dotY: [
					'Y',
				],
				dotV: [
					'v',
				],
				dotB: [
					'b',
				],
				dotP: [
					'p',
				],
			},
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 110, pose: 'idle', eyes: 'up', place: [{ prop: 'wandUp', x: 10, y: -6 }] },
				{ ms: 320, pose: 'idle', eyes: 'up', place: [{ prop: 'wandUp', x: 10, y: -6 }, { prop: 'dotW', x: 16, y: -7 }] },
				{ ms: 80, pose: 'idle', place: [{ prop: 'wandRight', x: 10, y: -1 }, { prop: 'swish', x: 15, y: -5 }] },
				{ ms: 100, pose: 'idle', eyes: 'happy', place: [{ prop: 'wandRight', x: 10, y: -1 }, { prop: 'dotY', x: 18, y: -2 }, { prop: 'dotP', x: 18, y: 2 }, { prop: 'dotB', x: 19, y: 0 }, { prop: 'dotV', x: 17, y: -3 }] },
				{ ms: 120, pose: 'idle', eyes: 'happy', place: [{ prop: 'wandRight', x: 10, y: -1 }, { prop: 'star1', x: 17, y: -5 }, { prop: 'star2', x: 20, y: -1 }, { prop: 'star3', x: 17, y: 3 }, { prop: 'dotY', x: 22, y: -4 }, { prop: 'dotW', x: 21, y: 4 }] },
				{ ms: 460, pose: 'idle', eyes: 'happy', place: [{ prop: 'wandRight', x: 10, y: -1 }, { prop: 'star1', x: 16, y: -7 }, { prop: 'star2', x: 21, y: -3 }, { prop: 'star3', x: 19, y: 4 }, { prop: 'star4', x: 13, y: -4 }, { prop: 'star5', x: 21, y: 1 }, { prop: 'dotW', x: 20, y: -6 }, { prop: 'dotY', x: 16, y: 2 }] },
				{ ms: 160, pose: 'idle', eyes: 'happy', place: [{ prop: 'dotV', x: 17, y: -6 }, { prop: 'dotB', x: 22, y: -2 }, { prop: 'dotP', x: 20, y: 5 }, { prop: 'dotY', x: 14, y: -3 }, { prop: 'dotW', x: 22, y: 2 }] },
				{ ms: 110, pose: 'crouch' },
				{ ms: 140, pose: 'airborne' },
				{ ms: 200, pose: 'idle' },
			],
		},
	},
	{
		shows: 'a shine sweeping a prop',
		move: {
			name: 'trophy',
			about: 'A gold trophy rises beside it, a shine sweeps across it, and the pet cheers with sparkles.',
			loop: false,
			still: 8,
			colors: { W: '#ffffff', H: '#ffe994', Y: '#ffc205', D: '#e7a400', g: '#cd8e02', N: '#6f403b', M: '#3c2831' },
			props: {
				trophy: [
					'...DYYYHH...',
					'gg.DYYYHH.YY',
					'g..DYYYHH..Y',
					'g..DYYYHH..Y',
					'.g.DYYYHH.Y.',
					'..gDYYYHHY..',
					'....DYYH....',
					'.....DY.....',
					'.....DY.....',
					'....DDYY....',
					'...NNNNNNN..',
					'...MMMMMMM..',
				],
				shine1: [
					'...DHYYHH...',
					'gg.DHYYHH.YY',
					'g..DHYYHH..Y',
					'g..DHYYHH..Y',
					'.g.DHYYHH.Y.',
					'..gDHYYHHY..',
					'....DHYH....',
					'.....HY.....',
					'.....HY.....',
					'....DHYY....',
					'...NNNNNNN..',
					'...MMMMMMM..',
				],
				shine2: [
					'...DYHYHH...',
					'gg.DYHYHH.YY',
					'g..DYHYHH..Y',
					'g..DYHYHH..Y',
					'.g.DYHYHH.Y.',
					'..gDYHYHHY..',
					'....DYHH....',
					'.....DH.....',
					'.....DH.....',
					'....DDHY....',
					'...NNNNNNN..',
					'...MMMMMMM..',
				],
				shine3: [
					'...DYYHHH...',
					'gg.DYYHHH.YY',
					'g..DYYHHH..Y',
					'g..DYYHHH..Y',
					'.g.DYYHHH.Y.',
					'..gDYYHHHY..',
					'....DYYW....',
					'.....DY.....',
					'.....DY.....',
					'....DDYH....',
					'...NNNNNNN..',
					'...MMMMMMM..',
				],
				spark: [
					'.H.',
					'HWH',
					'.H.',
				],
				dot: [
					'H',
				],
			},
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 80, pose: 'idle', place: [{ prop: 'trophy', x: 12, y: 5 }] },
				{ ms: 80, pose: 'idle', place: [{ prop: 'trophy', x: 12, y: 1 }] },
				{ ms: 100, pose: 'crouch', place: [{ prop: 'trophy', x: 12, y: 0 }] },
				{ ms: 90, pose: 'airborne', place: [{ prop: 'shine1', x: 12, y: 0 }] },
				{ ms: 90, pose: 'airborne', place: [{ prop: 'shine2', x: 12, y: 0 }, { prop: 'dot', x: 23, y: -1 }] },
				{ ms: 90, pose: 'idle', eyes: 'happy', place: [{ prop: 'shine3', x: 12, y: 0 }, { prop: 'spark', x: 20, y: -3 }] },
				{ ms: 600, pose: 'idle', eyes: 'happy', place: [{ prop: 'trophy', x: 12, y: 0 }, { prop: 'spark', x: 20, y: -3 }, { prop: 'dot', x: 11, y: 2 }] },
				{ ms: 300, pose: 'idle', eyes: 'happy', place: [{ prop: 'trophy', x: 12, y: 0 }, { prop: 'dot', x: 20, y: -2 }] },
				{ ms: 90, pose: 'idle', place: [{ prop: 'trophy', x: 12, y: 4 }] },
				{ ms: 200, pose: 'idle' },
			],
		},
	},
	{
		shows: 'a held hammer and an impact',
		move: {
			name: 'debug',
			about: 'A bug crawls up; the pet raises a big hammer with its antenna and smashes it flat, right on top. Bug fixed!',
			loop: false,
			still: 6,
			colors: { N: '#2b2d2f', H: '#fb5b6c', R: '#e82c41', D: '#ca2134', K: '#8b1321', W: '#ffffff', G: '#d8e1e8', S: '#9ca5ad', M: '#70777d', T: '#383b3d', w: '#e39a5f', o: '#b8663a', u: '#6f403b', g: '#8be09a', e: '#41bd6a', d: '#23904a', k: '#145a2e', Y: '#ffe994', y: '#ffc205' },
			props: {
				bug: [
					'...DRH.',
					'.NDNRRH',
					'NNDRRNR',
					'NDNRRDR',
					'.N.N.N.',
				],
				alert: [
					'y',
					'y',
					'o',
					'.',
					'y',
				],
				splat: [
					'.KDRRRRH.',
					'NDNRRNRDN',
				],
				dizzy: [
					'Y...Y',
				],
				hammerUp: [
					'GWWWWWS',
					'SGGGGGM',
					'SGGGGGM',
					'TMMMMMT',
					'...o...',
					'...o...',
					'...o...',
					'...u...',
				],
				hammerBack: [
					'GWWWWWS..',
					'SGGGGGM..',
					'SGGGGGM..',
					'TMMMMMT..',
					'...o.....',
					'....o....',
					'.....o...',
					'......o..',
					'.......o.',
					'........u',
				],
				hammerHit: [
					'u..........',
					'.oo........',
					'...oo......',
					'.....oo....',
					'.......o...',
					'....GWWWWWS',
					'....SGGGGGM',
					'....SGGGGGM',
					'....TMMMMMT',
				],
				impact: [
					'Y.......Y',
					'.Y.....Y.',
				],
				checkSmall: [
					'...e',
					'e.ed',
					'.ed.',
				],
				check: [
					'.....ge',
					'....ged',
					'g..ged.',
					'eg.ged.',
					'dgeed..',
					'.ded...',
					'..k....',
				],
			},
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 170, pose: 'idle', eyes: 'right', place: [{ prop: 'bug', x: 17, y: 7 }] },
				{ ms: 170, pose: 'idle', eyes: 'right', place: [{ prop: 'bug', x: 14, y: 7 }] },
				{ ms: 300, pose: 'idle', eyes: 'squint', place: [{ prop: 'hammerUp', x: 6, y: -8 }, { prop: 'bug', x: 14, y: 7 }, { prop: 'alert', x: 17, y: 1 }] },
				{ ms: 220, pose: 'crouch', eyes: 'squint', place: [{ prop: 'hammerBack', x: 1, y: -7 }, { prop: 'bug', x: 14, y: 7 }, { prop: 'alert', x: 17, y: 1 }] },
				{ ms: 90, pose: 'idle', eyes: 'squint', place: [{ prop: 'splat', x: 13, y: 10 }, { prop: 'hammerHit', x: 10, y: 1 }, { prop: 'impact', x: 13, y: 5 }] },
				{ ms: 420, pose: 'idle', eyes: 'right', place: [{ prop: 'splat', x: 13, y: 10 }, { prop: 'hammerHit', x: 10, y: 1 }] },
				{ ms: 140, pose: 'idle', eyes: 'right', place: [{ prop: 'splat', x: 13, y: 10 }, { prop: 'dizzy', x: 15, y: 8 }, { prop: 'hammerUp', x: 6, y: -8 }] },
				{ ms: 110, pose: 'crouch', place: [{ prop: 'splat', x: 13, y: 10 }, { prop: 'checkSmall', x: 4, y: -1 }] },
				{ ms: 130, pose: 'airborne', place: [{ prop: 'splat', x: 13, y: 10 }, { prop: 'check', x: 3, y: -8 }] },
				{ ms: 650, pose: 'idle', eyes: 'happy', place: [{ prop: 'splat', x: 13, y: 10 }, { prop: 'check', x: 3, y: -8 }] },
				{ ms: 90, pose: 'idle', place: [{ prop: 'checkSmall', x: 4, y: -5 }] },
				{ ms: 200, pose: 'idle' },
			],
		},
	},
	{
		shows: 'rising steam',
		move: {
			name: 'coffee',
			about: 'A steaming mug of coffee appears in front of it; the pet breathes in the aroma and closes its eyes, blissful.',
			loop: false,
			still: 5,
			colors: { W: '#ffffff', G: '#d8e1e8', S: '#9ca5ad', b: '#5a3426', c: '#b8835a', L: '#0094f0', M: '#0057aa', s: '#c5ccd3', t: '#8d959c' },
			props: {
				mug: [
					'SGGGGGS..',
					'SbcbbbS..',
					'SGWWWWSSS',
					'SLLLLMS.S',
					'SGWWWWS.S',
					'SGWWWWSSS',
					'.SSSSS...',
				],
				steam1: [
					's....',
					'.s...',
					'.s.s.',
					's...s',
					's...s',
					'.s.s.',
				],
				steam2: [
					's...',
					'.s.s',
					'.s..',
					's..s',
					's..s',
					'.s..',
				],
			},
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 70, pose: 'idle', place: [{ prop: 'mug', x: 14, y: 2 }] },
				{ ms: 260, pose: 'idle', eyes: 'right', place: [{ prop: 'mug', x: 14, y: 5 }] },
				{ ms: 260, pose: 'idle', eyes: 'right', place: [{ prop: 'mug', x: 14, y: 5 }, { prop: 'steam1', x: 16, y: -1 }] },
				{ ms: 380, pose: 'idle', eyes: 'happy', place: [{ prop: 'mug', x: 14, y: 5 }, { prop: 'steam2', x: 17, y: -1 }] },
				{ ms: 380, pose: 'idle', eyes: 'happy', place: [{ prop: 'mug', x: 14, y: 5 }, { prop: 'steam1', x: 16, y: -1 }] },
				{ ms: 220, pose: 'crouch', eyes: 'happy', place: [{ prop: 'mug', x: 14, y: 5 }, { prop: 'steam1', x: 16, y: -1 }] },
				{ ms: 380, pose: 'idle', eyes: 'happy', place: [{ prop: 'mug', x: 14, y: 5 }, { prop: 'steam2', x: 17, y: -1 }] },
				{ ms: 220, pose: 'idle', eyes: 'right', place: [{ prop: 'mug', x: 14, y: 5 }, { prop: 'steam1', x: 16, y: -1 }] },
				{ ms: 200, pose: 'idle' },
			],
		},
	},
	{
		shows: 'weather, a flash and x eyes',
		move: {
			name: 'zapped',
			about: 'A storm cloud rains on it, lightning strikes, it flashes electrified with X eyes, and ends up charred and smoking.',
			loop: false,
			still: 6,
			colors: { W: '#ffffff', G: '#d8e1e8', S: '#9ca5ad', M: '#70777d', N: '#2b2d2f', l: '#9fd3f5', L: '#4583be', Y: '#ffe994', y: '#ffc205', o: '#b27805', s: '#b9c0c7', t: '#70777d', c: '#55595e', a: '#383b3d', b: '#1f2021', x: '#ffffff' },
			props: {
				cloud: [
					'...SGGS.....',
					'..SGWWGSSGS.',
					'.SGWWWWWGWGS',
					'SGWWWWWWWWGS',
					'MSGGGGGGGGSM',
					'.MMSMMMMSMM.',
				],
				cloudDark: [
					'...MSSM.....',
					'..MSGGSMMSM.',
					'.MSGGGGGSGSM',
					'MSGGGGGGGGSM',
					'NMSSSSSSSSMN',
					'.NNMNNNNMNN.',
				],
				bolt: [
					'..oYY',
					'.oYY.',
					'oYYYY',
					'..oY.',
					'.oY..',
					'.Y...',
				],
				sparks: [
					'y..........y',
					'.o........o.',
					'............',
					'y..........y',
				],
				sparks2: [
					'.y........y.',
					'o..........o',
					'............',
					'.y........y.',
				],
				smoke: [
					'.ss.....ss.',
					'sttt...sttt',
					'.ss.....ss.',
				],
				smokeHigh: [
					'.ss......ss.',
					'sttt....sttt',
					'.ss......ss.',
				],
				dizzy: [
					'y.o.y',
				],
				drop: [
					'l',
					'L',
				],
				frizz: [
					'a.a..a.a',
					'.a....a.',
					'..a..a..',
				],
			},
			frames: [
				{ ms: 150, pose: 'idle' },
				{ ms: 160, pose: 'idle', place: [{ prop: 'cloud', x: 0, y: -11 }] },
				{ ms: 120, pose: 'crouch', place: [{ prop: 'drop', x: 1, y: -8 }, { prop: 'drop', x: 7, y: -6 }, { prop: 'drop', x: 4, y: -3 }, { prop: 'drop', x: 10, y: -1 }, { prop: 'drop', x: 1, y: 1 }, { prop: 'drop', x: 7, y: 3 }, { prop: 'drop', x: 4, y: 6 }, { prop: 'drop', x: 10, y: 8 }, { prop: 'cloud', x: 0, y: -11 }] },
				{ ms: 120, pose: 'crouch', place: [{ prop: 'drop', x: 10, y: -7 }, { prop: 'drop', x: 1, y: -5 }, { prop: 'drop', x: 7, y: -3 }, { prop: 'drop', x: 4, y: 0 }, { prop: 'drop', x: 10, y: 2 }, { prop: 'drop', x: 1, y: 4 }, { prop: 'drop', x: 7, y: 6 }, { prop: 'drop', x: 4, y: 9 }, { prop: 'cloud', x: 0, y: -11 }] },
				{ ms: 160, pose: 'idle', place: [{ prop: 'drop', x: 4, y: -6 }, { prop: 'drop', x: 10, y: -4 }, { prop: 'drop', x: 1, y: -2 }, { prop: 'drop', x: 7, y: 0 }, { prop: 'drop', x: 4, y: 3 }, { prop: 'drop', x: 10, y: 5 }, { prop: 'drop', x: 1, y: 7 }, { prop: 'drop', x: 7, y: 9 }, { prop: 'cloudDark', x: 0, y: -11 }] },
				{ ms: 70, pose: 'idle', eyes: 'x', recolor: { C: 'Y', A: 'y', B: 'o', E: 'N' }, place: [{ prop: 'cloudDark', x: 0, y: -11 }, { prop: 'bolt', x: 6, y: -6 }, { prop: 'sparks', x: 0, y: 3 }] },
				{ ms: 70, pose: 'idle', eyes: 'x', place: [{ prop: 'cloud', x: 0, y: -11 }, { prop: 'bolt', x: 6, y: -6 }, { prop: 'sparks2', x: 0, y: 3 }] },
				{ ms: 70, pose: 'idle', eyes: 'x', recolor: { C: 'Y', A: 'y', B: 'o', E: 'N' }, place: [{ prop: 'cloudDark', x: 0, y: -11 }, { prop: 'sparks', x: 0, y: 3 }] },
				{ ms: 70, pose: 'idle', eyes: 'x', place: [{ prop: 'cloud', x: 0, y: -11 }, { prop: 'sparks2', x: 0, y: 3 }] },
				{ ms: 90, pose: 'idle', eyes: 'x', recolor: { C: 'Y', A: 'y', B: 'o', E: 'N' }, place: [{ prop: 'sparks', x: 0, y: 3 }] },
				{ ms: 520, pose: 'idle', antennae: false, eyes: 'x', recolor: { C: 'c', A: 'a', B: 'b', E: 'x' }, place: [{ prop: 'frizz', x: 2, y: 0 }, { prop: 'smoke', x: 1, y: -3 }] },
				{ ms: 420, pose: 'idle', antennae: false, eyes: 'x', recolor: { C: 'c', A: 'a', B: 'b', E: 'x' }, place: [{ prop: 'frizz', x: 2, y: 0 }, { prop: 'smokeHigh', x: 0, y: -6 }, { prop: 'dizzy', x: 4, y: -2 }] },
				{ ms: 150, pose: 'crouch' },
				{ ms: 220, pose: 'idle' },
			],
		},
	},
];
