global class MessageDefinitionInputParameter {
	global Boolean booleanParameterValue;
	global Boolean booleanValue;
	global List<Boolean> booleanValues;
	global Date dateParameterValue;
	global Datetime dateTimeValue;
	global List<Datetime> dateTimeValues;
	global Date dateValue;
	global List<Date> dateValues;
	global String name;
	global Double numberParameterValue;
	global Double numberValue;
	global List<Double> numberValues;
	global String parameterName;
	global String recordIdParameterValue;
	global String recordIdValue;
	global List<String> recordIdValues;
	global String textParameterValue;
	global String textValue;
	global List<String> textValues;
	global MessageDefinitionInputParameter() { }
	global Object clone() { }

}