{
    perform: true,
    alwaysRequireAssignee: false,
    labelsRequiringAssignee: [ feature-request ],
    autoAssignees: {
        accessibility: [],
        api: [],
        css-less-sass: [],
        debug: [ weinand ],
        editor: [],
        editor-brackets: [],
        editor-clipboard: [],
        editor-colors: [],
        editor-contrib: [],
        editor-core: [],
        editor-find-widget: [],
        editor-folding: [],
        editor-ime: [],
        editor-indentation: [],
        editor-input: [],
        editor-minimap: [],
        editor-multicursor: [],
        editor-wrapping: [],
        emmet: [ ramya-rao-a ],
        error-list: [],
        git: [ joaomoreno ],
        hot-exit: [ Tyriar ],
        html: [ aeschli ],
        i18n: [],
        install-update: [],
        integrated-terminal: [ Tyriar ],
        javascript: [ mjbvz ],
        json: [],
        languages basic: [],
        markdown: [ mjbvz ],
        merge-conflict: [ chrmarti ],
        perf-profile: [],
        php: [ roblourens ],
        search: [ roblourens ],
        snippets: [ jrieken ],
        tasks: [ dbaeumer ],
        typescript: [ mjbvz ],
        workbench: [ bpasero, isidorn, sandy081]
    }
}
