{
    perform: true,
    commands: [
        {
            type: 'comment',
            name: 'question',
            allowUsers: ['cleidigh', 'usernamehw', 'gjsjohnmurray', 'IllusionMH'],
            action: 'updateLabels',
            addLabel: '*question'
        },
        {
            type: 'label',
            name: '*question',
            allowTriggerByBot: true,
            action: 'close',
            comment: "Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*dev-question',
            action: 'close',
            comment: "We have a great developer community [over on slack](https://aka.ms/vscode-dev-community) where extension authors help each other. This is a great place for you to ask questions and find support.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*extension-candidate',
            action: 'close',
            comment: "We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*not-reproducible',
            action: 'close',
            comment: "We closed this issue because we are unable to reproduce the problem with the steps you describe. Chances are we've already fixed your problem in a recent version of VS Code. If not, please ask us to reopen the issue and provide us with more detail. Our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines might help you with that.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*out-of-scope',
            action: 'close',
            comment: "This issue is being closed to keep the number of issues in our inbox on a manageable level, we are closing issues that are not going to be addressed in the foreseeable future: We look at the number of votes the issue has received and the number of duplicate issues filed. More details [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.\n\nIf you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nThanks for your understanding and happy coding!"
        },
        {
            type: 'label',
            name: '*caused-by-extension',
            action: 'close',
            comment: "This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*as-designed',
            action: 'close',
            comment: "The described behavior is how it is expected to work. If you disagree, please explain what is expected and what is not in more detail. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*english-please',
            action: 'close',
            comment: "This issue is being closed because its description is not in English, that makes it hard for us to work on it. Please open a new issue with an English description. You might find [Bing Translator](https://www.bing.com/translator) useful."
        },
        {
            type: 'comment',
            name: 'duplicate',
            allowUsers: ['cleidigh', 'usernamehw', 'gjsjohnmurray', 'IllusionMH'],
            action: 'updateLabels',
            addLabel: '*duplicate'
        },
        {
            type: 'label',
            name: '*duplicate',
            allowTriggerByBot: true,
            action: 'close',
            comment: "Thanks for creating this issue! We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate. You can search for existing issues [here](https://aka.ms/vscodeissuesearch). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'comment',
            name: 'confirm',
            allowUsers: ['cleidigh', 'usernamehw', 'gjsjohnmurray', 'IllusionMH'],
            action: 'updateLabels',
            addLabel: 'confirmed',
            removeLabel: 'confirmation-pending'
        },
        {
            type: 'comment',
            name: 'confirmationPending',
            allowUsers: ['cleidigh', 'usernamehw'],
            action: 'updateLabels',
            addLabel: 'confirmation-pending',
            removeLabel: 'confirmed'
        },
        {
            type: 'comment',
            name: 'findDuplicates',
            allowUsers: ['cleidigh', 'usernamehw', 'gjsjohnmurray', 'IllusionMH'],
            action: 'comment',
            comment: "Potential duplicates:\n${potentialDuplicates}"
        },
        {
            type: 'comment',
            name: 'needsMoreInfo',
            allowUsers: ['cleidigh', 'usernamehw', 'gjsjohnmurray', 'IllusionMH'],
            action: 'updateLabels',
            addLabel: 'needs more info',
            comment: "Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.\n\nHappy Coding!"
        },
        {
            type: 'comment',
            name: 'a11ymas',
            allowUsers: ['AccessibilityTestingTeam-TCS', 'dixitsonali95', 'Mohini78', 'ChitrarupaSharma', 'mspatil110', 'umasarath52', 'v-umnaik'],
            action: 'updateLabels',
            addLabel: 'a11ymas'
        },
    ]
}
