version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers" # https://containers.dev/guide/dependabot
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/extensions/markdown-language-features"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@vscode/markdown-editor"
