{
  perform: true,
  whenCreatedByTeam: false,
  comment: "(Experimental duplicate detection)\nThanks for submitting this issue! Please check if it is already covered by an existing one, such as:\n${potentialDuplicates}"
}
