global class PlaceQuoteRLMApexProcessor {
	global PlaceQuoteRLMApexProcessor() { }
	global Object clone() { }
	global static placequote.PlaceQuoteResponse execute(placequote.PricingPreferenceEnum pricingPreferenceEnum, placequote.CatalogRatesPreferenceEnum catalogRatesPreferenceEnum, placequote.GraphRequest graphRequest, placequote.ConfigurationInputEnum configurationInputEnum, placequote.ConfigurationOptionsInput configurationOptionsInput) { }
	global static placequote.PlaceQuoteResponse execute(placequote.PricingPreferenceEnum pricingPreferenceEnum, placequote.GraphRequest graphRequest, placequote.ConfigurationInputEnum configurationInputEnum, placequote.ConfigurationOptionsInput configurationOptionsInput) { }

}