image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
tasks:
  - init: |
      yarn
      yarn gitpod:init
    command: |
      gp sync-done init
      export NODE_ENV=development
      export VSCODE_DEV=1
      yarn gulp watch-init
    name: watch app
  - command: |
      export NODE_ENV=development
      export VSCODE_DEV=1
      gp sync-await init
      node out/server.js
    name: run app
    openMode: split-right
github:
  prebuilds:
    pullRequestsFromForks: true
vscode:
  extensions:
    - dbaeumer.vscode-eslint
