allowBuilds:
  '@bazel/concatjs': true
  '@parcel/watcher': true
  '@playwright/browser-chromium': true
  '@vscode/deviceid': true
  '@vscode/fs-copyfile': true
  '@vscode/native-watchdog': true
  '@vscode/policy-watcher': true
  '@vscode/spdlog': true
  '@vscode/sqlite3': true
  '@vscode/windows-mutex': true
  '@vscode/windows-process-tree': true
  '@vscode/windows-registry': true
  bufferutil: true
  cpu-features: true
  es5-ext: true
  esbuild: true
  foundry-local-sdk: true
  husky: true
  kerberos: true
  koffi: true
  native-is-elevated: true
  native-keymap: true
  node-pty: true
  protobufjs: true
  ssh2: true
  utf-8-validate: true
  windows-foreground-love: true
