sonar.projectKey=kimphanh-org_vscode-ci
sonar.organization=kimphanh-org


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=vscode-ci
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
