global class AbstractCheckoutAddressInput {
	global String city;
	global String companyName;
	global String country;
	global String firstName;
	global String id;
	global String lastName;
	global String name;
	global String postalCode;
	global String region;
	global String shipToPhoneNumber;
	global String street;
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}