global class AbstractGatewayCommonResponse {
	global String gatewayAvsCode;
	global Datetime gatewayDate;
	global String gatewayMessage;
	global String gatewayResultCode;
	global String gatewayResultCodeDescription;
	global String salesforceResultCode;
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}