global class AchievementContributor {
	global ConnectApi.EduExternalIdDetails courseExternalId;
	global String id;
	global Double minimumGrade;
	global ConnectApi.EduExternalIdDetails programExternalId;
	global ConnectApi.AchievementContributorTypeEnum type;
	global AchievementContributor() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}