global class ActionLauncherRecommendationsOutput {
	global List<ConnectApi.ActionLauncherIntentActionsMappingOutput> intentsActionMapping;
	global String mode;
	global ConnectApi.EngagementStatusOutput status;
	global ActionLauncherRecommendationsOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}