global class ActivationContactPointSourceConfig {
	global String dataSourceId;
	global String dataSourceName;
	global ConnectApi.ContactPointPref dataSourcePreference;
	global Integer dataSourcePriority;
	global ActivationContactPointSourceConfig() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}