global class ActivationData {
	global String activatedEntityFqk;
	global String activatedOnId;
	global String activationRecord;
	global ConnectApi.AudienceDMODeltaType deltaType;
	global String publishDate;
	global String segmentId;
	global String segmentOnId;
	global String segmentedEntityFqk;
	global ActivationData() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}