global class AddressResultRepresentation {
	global String city;
	global String country;
	global String countryCode;
	global Double latitude;
	global Double longitude;
	global String postalCode;
	global String state;
	global String stateCode;
	global String street;
	global AddressResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}