global class AdjustOrderItemSummaryInputRepresentation {
	global List<ConnectApi.AdjustItemInputRepresentation> adjustItems;
	global String allocatedItemsChangeOrderType;
	global Boolean individualLineItemTaxAdjustments;
	global AdjustOrderItemSummaryInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}