global class AdQuoteLineCreativeSizeTypeInputRepresentation {
	global String adCreativeSizeTypeId;
	global String adQuoteLineCreativeSizeTypeId;
	global String adSpaceCreativeSizeTypeId;
	global String adSpaceSpecificationId;
	global List<ConnectApi.CompanionAdQuoteLineCreativeSizeTypeInputRepresentation> companions;
	global Integer count;
	global Map<String,ConnectApi.MediaPlanObjectInputRepresentation> customFields;
	global String mediaOrientation;
	global ConnectApi.HttpMethodEnum method;
	global AdQuoteLineCreativeSizeTypeInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}