global class AdQuoteLineAdSpaceSpecOutputRepresentation {
	global String adQuoteLineAdSpaceSpecId;
	global String adQuoteLineId;
	global String adSpaceSpecificationId;
	global Boolean included;
	global AdQuoteLineAdSpaceSpecOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}