global class AdQuoteLineAdSpaceSpecInputRepresentation {
	global String adQuoteLineAdSpaceSpecId;
	global String adQuoteLineId;
	global String adSpaceSpecificationId;
	global Boolean included;
	global ConnectApi.HttpMethodEnum method;
	global AdQuoteLineAdSpaceSpecInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}