global class AdQuoteLineAdSpaceCreativeInputRepresentation {
	global List<ConnectApi.AdQuoteLineAdSpaceSpecInputRepresentation> adQuoteLineAdSpaceSpecs;
	global List<ConnectApi.AdQuoteLineCreativeSizeTypeInputRepresentation> adQuoteLineCreativeSizeTypes;
	global String adQuoteLineId;
	global Boolean updatePricing;
	global AdQuoteLineAdSpaceCreativeInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}