global class AdQuoteLineAdSpaceCreativeOutputRepresentation {
	global List<ConnectApi.AdQuoteLineAdSpaceSpecOutputRepresentation> adQuoteLineAdSpaceSpecs;
	global List<ConnectApi.AdQuoteLineCreativeSizeTypeOutputRepresentation> adQuoteLineCreativeSizeTypes;
	global AdQuoteLineAdSpaceCreativeOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}