global class AgreementItemOutputRepresentation {
	global List<ConnectApi.AssociatedAgreementOutputRepresentation> productOffering;
	global List<ConnectApi.TermOrConditionOutputRepresentation> termOrCondition;
	global AgreementItemOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}