global class AgreementSpecificationOutputRepresentation {
	global List<ConnectApi.AttachmentOutputRepresentation> attachment;
	global String description;
	global String lifecycleStatus;
	global String name;
	global List<ConnectApi.UserOutputRepresentation> relatedParty;
	global String type;
	global String version;
	global AgreementSpecificationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}