global class AgreementSpecificationInputRepresentation {
	global List<ConnectApi.RelatedPartyInputRepresentation> attachment;
	global String lifecycleStatus;
	global String name;
	global List<ConnectApi.RelatedPartyInputRepresentation> relatedParty;
	global String version;
	global AgreementSpecificationInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}