global class AlternativePaymentMethodOutput {
	global String accountId;
	global String comments;
	global String email;
	global String gatewayToken;
	global String gatewayTokenDetails;
	global String name;
	global AlternativePaymentMethodOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}