global class AppFormProductContractDocuments {
	global String applicationFormProductId;
	global List<ConnectApi.AppFormContractDocumentVersionResponse> documents;
	global String productId;
	global String productName;
	global AppFormProductContractDocuments() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}