global class ApplicationFormAccountInput {
	global String accountNumber;
	global String accountSite;
	global String accountSource;
	global Integer annualRevenue;
	global ConnectApi.ApplicationFormAccountAddress billingAddress;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsInputRepresentation> customFields;
	global String description;
	global String fax;
	global String firstName;
	global String industry;
	global String jigsaw;
	global String lastName;
	global String middleName;
	global String name;
	global Integer numberOfEmployees;
	global String ownerId;
	global String ownership;
	global String parentId;
	global String personBirthDate;
	global String personContactId;
	global String personEmail;
	global String personGenderIdentity;
	global String personHomePhone;
	global ConnectApi.ApplicationFormAccountAddress personMailingAddress;
	global String personMobilePhone;
	global ConnectApi.ApplicationFormAccountAddress personOtherAddress;
	global String personOtherPhone;
	global String phone;
	global String rating;
	global String recordTypeId;
	global String salutation;
	global ConnectApi.ApplicationFormAccountAddress shippingAddress;
	global String sic;
	global String sicDesc;
	global String suffix;
	global String tickerSymbol;
	global String type;
	global String website;
	global applicationFormAccountInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}