global class ApplicationFormSellerItemInput {
	global Integer addlProductTermInMonths;
	global Integer builtUpArea;
	global String builtUpAreaUnit;
	global String constructionStage;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsInputRepresentation> customFields;
	global String engineNumber;
	global String intendedUse;
	global Boolean isAdditionalProduct;
	global String itemCondition;
	global String make;
	global Integer mileage;
	global String model;
	global String partyFinancialAssetId;
	global Double price;
	global ConnectApi.ApplicationFormAccountAddress propertyAddress;
	global Double propertyAge;
	global String propertyUnitIdentifier;
	global String recordTypeId;
	global String referenceObjectId;
	global String scheduledDeliveryDate;
	global String sellerId;
	global String trim;
	global String type;
	global String vehicleIdentificationNumber;
	global String vehicleRegistrationNumber;
	global Integer year;
	global applicationFormSellerItemInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}