global class ApplyTargetingOutputRepresentation {
	global String asynchronousJobId;
	global String asynchronousJobStatus;
	global Boolean isSuccessful;
	global List<ConnectApi.TargetingConfigurationErrorRepresentation> messageList;
	global ApplyTargetingOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}