global class ApplicationFormProductResultRepresentation {
	global String applicantVisibleStatus;
	global String createdById;
	global Datetime createdDate;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String disbursementMethod;
	global Double downPayment;
	global Boolean hasAutomaticPayment;
	global Boolean hasElectronicStatement;
	global String id;
	global Boolean isAtmCardRequired;
	global Boolean isCheckbookRequired;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String loanPurpose;
	global String loanType;
	global String name;
	global String ownerId;
	global String ownershipType;
	global String partnerVisibleStatus;
	global String productId;
	global String recordTypeId;
	global Double requestedAmount;
	global Double requestedMonthlyPayment;
	global Integer requestedTerm;
	global String stage;
	global Double totalBrandOwnedItemAmt;
	global Double totalVendorOwnedItemAmt;
	global ApplicationFormProductResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}