global class ApplicationFormSellerItemResultRepresentation {
	global Integer addlProductTermInMonths;
	global Integer builtUpArea;
	global String builtUpAreaUnit;
	global String constructionStage;
	global String createdById;
	global Datetime createdDate;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String engineNumber;
	global String id;
	global String intendedUse;
	global Boolean isAdditionalProduct;
	global String itemCondition;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String make;
	global Integer mileage;
	global String model;
	global String name;
	global String partyFinancialAssetId;
	global Double price;
	global ConnectApi.AddressResultRepresentation propertyAddress;
	global Double propertyAge;
	global String propertyUnitIdentifier;
	global String recordTypeId;
	global String referenceObjectId;
	global String scheduledDeliveryDate;
	global String sellerId;
	global String trim;
	global String type;
	global String vehicleIdentificationNumber;
	global String vehicleRegistrationNumber;
	global Integer year;
	global ApplicationFormSellerItemResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}