global class ApplicationFormResultRepresentation {
	global String accountId;
	global String branchUnitId;
	global String createdById;
	global Datetime createdDate;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String id;
	global String intakeChannelType;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String leadId;
	global String name;
	global String opportunityId;
	global String ownerId;
	global String recordTypeId;
	global String stage;
	global String thirdPartyLoanProviderAccountId;
	global String tierType;
	global Double totalDebtToIncomePercent;
	global Double totalIncomeToExpenseRatio;
	global Double totalLoanToValuePercent;
	global String usageType;
	global ApplicationFormResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}