global class ApplicationFormProductWrapResultRepresentation {
	global ConnectApi.ApplicationFormProductResultRepresentation applicationFormProduct;
	global ConnectApi.ApplicationFormSellerItemResultRepresentation applicationFormSellerItem;
	global ApplicationFormProductWrapResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}