global class ApplicantResultRepresentation {
	global String accountId;
	global String birthDate;
	global String contactId;
	global String createdById;
	global Datetime createdDate;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String email;
	global String firstName;
	global Double groupExposure;
	global String id;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String lastName;
	global String middleName;
	global String name;
	global String ownerId;
	global String partyProfileId;
	global String phone;
	global String phoneType;
	global String recordTypeId;
	global String role;
	global String salutation;
	global String stage;
	global String suffix;
	global String uniqueReferenceNumber;
	global ApplicantResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}