global class ApplicantWrapperInput {
	global ConnectApi.applicantInput applicant;
	global List<ConnectApi.partyExpenseInputRepresentation> partyExpense;
	global List<ConnectApi.partyFinancialAssetInput> partyFinancialAsset;
	global List<ConnectApi.partyFinancialLiabilityInputRepresentation> partyFinancialLiability;
	global List<ConnectApi.partyIncomeInputRepresentation> partyIncome;
	global ConnectApi.partyProfileInput partyProfile;
	global List<ConnectApi.personEmploymentInputRepresentation> personEmployment;
	global applicantWrapperInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}