global class AppointmentSlotResult {
	global String externalSlotId;
	global Boolean isPreferredSlot;
	global Boolean isSuggestedSlot;
	global String slotEnd;
	global String slotStart;
	global String sourceSystem;
	global AppointmentSlotResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}