global class ArticleRecommendationsRuntimeMetric {
	global Integer activeUserCount;
	global Integer attachCount;
	global Integer detachCount;
	global Integer dismissCount;
	global Integer engagementCount;
	global Integer engagementUserCount;
	global Integer hoverOrOpenCount;
	global Datetime metricsDate;
	global Integer recommendationCount;
	global Integer recommendationDisplayedRecordsCount;
	global Integer recommendationEngagementRecordsCount;
	global ArticleRecommendationsRuntimeMetric() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}