global class ArticleFeedbackResponseRepresentation {
	global List<ConnectApi.ArticleFeedbackQuestionResponseRepresentation> articleFeedbackQuestionResponseRepresentationList;
	global String assignedTo;
	global String completionDate;
	global String knowledgeArticleFeedbackId;
	global String knowledgeArticleFeedbackName;
	global String likeStatus;
	global String responseId;
	global String responseName;
	global String reviewStatus;
	global String submitterId;
	global String submitterName;
	global ArticleFeedbackResponseRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}