global class ArticleFeedbackQuestionResponseRepresentation {
	global String questionName;
	global Integer questionOrder;
	global String questionResponse;
	global String questionType;
	global ArticleFeedbackQuestionResponseRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}