global class ArticleSummary {
	global String articleType;
	global String knowledgeArticleVersionId;
	global Datetime lastPublishedDate;
	global Double rating;
	global String summary;
	global String title;
	global String urlName;
	global Integer viewCount;
	global ArticleSummary() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}