global class AssetMgmtInitiateAmendQtyInput {
	global ConnectApi.AssetMgmtAmendmentType amendmentOutputType;
	global List<String> assetIds;
	global String opportunityId;
	global Double quantityChange;
	global ConnectApi.AssetMgmtReturnPolicyType returnPolicyType;
	global Datetime startDate;
	global AssetMgmtInitiateAmendQtyInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}