global class AudienceTargetAssignment {
	global ConnectApi.FormulaScope formulaScope;
	global String groupName;
	global String id;
	global Boolean isMatch;
	global Integer priority;
	global ConnectApi.PublishStatus publishStatus;
	global String targetType;
	global String targetValue;
	global String url;
	global AudienceTargetAssignment() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}