global class AudienceCriterionInput {
	global List<ConnectApi.AudienceCriterionValueInput> criterion;
	global Integer criterionNumber;
	global ConnectApi.AudienceCriteriaOperator criterionOperator;
	global ConnectApi.AudienceCriteriaType criterionType;
	global AudienceCriterionInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}