global class AudienceCriteriaDetail {
	global List<ConnectApi.AudienceCriterionDetail> criterion;
	global Integer criterionNumber;
	global ConnectApi.AudienceCriteriaOperator criterionOperator;
	global ConnectApi.AudienceCriteriaType criterionType;
	global AudienceCriteriaDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}