global class BalanceStatePreviewOutputRepresentation {
	global Double grandTotalAmount;
	global Double totalAdjustmentAmount;
	global Double totalAdjustmentAmountWithTax;
	global Double totalAmount;
	global Double totalAmountWithTax;
	global Double totalDeliveryAmount;
	global Double totalDeliveryAmountWithTax;
	global Double totalFeeAmount;
	global Double totalFeeAmountWithTax;
	global Double totalTaxAmount;
	global BalanceStatePreviewOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}