global class BaseEndpointExtension {
	global BaseEndpointExtension() { }
	global ConnectApi.EndpointExtensionResponse afterDelete(ConnectApi.EndpointExtensionResponse response, ConnectApi.EndpointExtensionRequest request) { }
	global ConnectApi.EndpointExtensionResponse afterGet(ConnectApi.EndpointExtensionResponse response, ConnectApi.EndpointExtensionRequest request) { }
	global ConnectApi.EndpointExtensionResponse afterPatch(ConnectApi.EndpointExtensionResponse response, ConnectApi.EndpointExtensionRequest request) { }
	global ConnectApi.EndpointExtensionResponse afterPost(ConnectApi.EndpointExtensionResponse response, ConnectApi.EndpointExtensionRequest request) { }
	global ConnectApi.EndpointExtensionResponse afterPut(ConnectApi.EndpointExtensionResponse response, ConnectApi.EndpointExtensionRequest request) { }
	global ConnectApi.EndpointExtensionRequest beforeDelete(ConnectApi.EndpointExtensionRequest request) { }
	global ConnectApi.EndpointExtensionRequest beforeGet(ConnectApi.EndpointExtensionRequest request) { }
	global ConnectApi.EndpointExtensionRequest beforePatch(ConnectApi.EndpointExtensionRequest request) { }
	global ConnectApi.EndpointExtensionRequest beforePost(ConnectApi.EndpointExtensionRequest request) { }
	global ConnectApi.EndpointExtensionRequest beforePut(ConnectApi.EndpointExtensionRequest request) { }
	global Object clone() { }

}