global class BaseManagedSocialAccount {
	global String defaultResponseAccountId;
	global String displayName;
	global String externalPictureUrl;
	global String id;
	global String label;
	global String profileUrl;
	global ConnectApi.SocialNetworkProvider socialNetwork;
	global String uniqueName;
	global String username;
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}