global class BasicTemplateAttachment {
	global String description;
	global ConnectApi.Icon icon;
	global String linkRecordId;
	global String linkUrl;
	global String subtype;
	global String title;
	global BasicTemplateAttachment() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}