global class BatchPaymentsItem {
	global Double amount;
	global String authorizationId;
	global String comments;
	global String currencyIsoCode;
	global String idempotencyKey;
	global String paymentGatewayId;
	global String savedPaymentMethodId;
	global batchPaymentsItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}