global class BookMultiSlotResult {
	global List<ConnectApi.BookAppointmentResult> appointmentResults;
	global ConnectApi.ErrorRepresentation error;
	global Boolean isSuccess;
	global String serviceAppointmentGroupId;
	global BookMultiSlotResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}