global class BookAppointmentResult {
	global String appointmentId;
	global ConnectApi.ErrorRepresentation error;
	global Boolean isSuccess;
	global String jsonResponse;
	global String patientId;
	global String sourceAppointmentId;
	global ConnectApi.BookingStatus status;
	global BookAppointmentResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}