global class BrandExtractionResultOutputRepresentation {
	global String backgroundColor;
	global String brandColor;
	global String domainName;
	global ConnectApi.BrandExtractionResultOutputRepresentationLogo logo;
	global String networkId;
	global String primaryFont;
	global String textColor;
	global BrandExtractionResultOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}