global class BulkRecordRollupDefinitionDetailsOutputRepresentation {
	global List<ConnectApi.RecordRollupDefinitionDetailsOutputRepresentation> definitions;
	global Boolean errors;
	global String message;
	global String statusCode;
	global BulkRecordRollupDefinitionDetailsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}