global class BusObjOutputRepresentation {
	global List<ConnectApi.BusObjAssociationsOutputRepresentation> associations;
	global String description;
	global String displayName;
	global String id;
	global BusObjOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}