global class BusObjSummaryOutputRepresentation {
	global String description;
	global String id;
	global ConnectApi.BusObjInsightsOutputRepresentation insightSummary;
	global String kpi;
	global String labelName;
	global ConnectApi.BusObjRecommendationsOutputRepresentation recommendationSummary;
	global BusObjSummaryOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}