global class BuyerProfileDetail {
	global String email;
	global String firstName;
	global Boolean isEmailVerified;
	global Boolean isPhoneVerified;
	global String lastName;
	global String phoneNumber;
	global String userName;
	global BuyerProfileDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}