global class BuyerProfileVerificationResponse {
	global String identifier;
	global String message;
	global ConnectApi.BuyerProfileInitMethodEnum method;
	global String recipient;
	global String status;
	global BuyerProfileVerificationResponse() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}