global class CancelPolicyOutputRepresentation {
	global ConnectApi.ErrorOutputRepresentation error;
	global List<String> impactedPolicyVersions;
	global ConnectApi.RefundOutputRepresentation refund;
	global CancelPolicyOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}