global class CancelAppointmentResult {
	global ConnectApi.ErrorRepresentation error;
	global String externalAppointmentId;
	global Boolean isSuccess;
	global String jsonResponse;
	global String serviceAppointmentId;
	global ConnectApi.BookingStatus status;
	global CancelAppointmentResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}