global class CancelAllOrderItemsInputRepresentation {
	global List<ConnectApi.ChangeItemFeeWithTaxInputRepresentation> changeItemFees;
	global List<String> excludedItems;
	global String reason;
	global String reasonText;
	global CancelAllOrderItemsInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}