global class CancelAllAppointmentsResult {
	global ConnectApi.ErrorRepresentation error;
	global Boolean isSuccess;
	global String serviceAppointmentGroupId;
	global ConnectApi.BookingStatus status;
	global CancelAllAppointmentsResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}