global class CanvasCapability {
	global String description;
	global String developerName;
	global String height;
	global ConnectApi.Icon icon;
	global String namespacePrefix;
	global String parameters;
	global String thumbnailUrl;
	global String title;
	global CanvasCapability() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}