global class CardDetailOutput {
	global String configurationDeveloperName;
	global String contextObjectId;
	global String indirectRelationshipObjectId;
	global String relatedObjectId;
	global List<ConnectApi.CardRowOutput> rows;
	global CardDetailOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}