global class CareProcessingErrorOutput {
	global String actionCode;
	global String actionCodeDescription;
	global String actionCodeId;
	global String actionCodeName;
	global String actionCodeSourceSystem;
	global String actionCodeSystemVersion;
	global String description;
	global String errorCode;
	global String errorCodeDescription;
	global String errorCodeId;
	global String errorCodeName;
	global String errorCodeSourceSystem;
	global String errorCodeSystemVersion;
	global String id;
	global String name;
	global String referenceObjectId;
	global String referenceObjectName;
	global CareProcessingErrorOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}