global class CareRequestReviewerOutput {
	global ConnectApi.ContentDocumentOutput contentDocument;
	global String id;
	global Datetime reviewDate;
	global String reviewer;
	global String reviewerNotes;
	global String reviewerType;
	global String status;
	global CareRequestReviewerOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}