global class CareAuthorizationCaseOutput {
	global String accountName;
	global String caseNumber;
	global String caseOrigin;
	global String caseOwner;
	global String caseReason;
	global Boolean closed;
	global String contactName;
	global String createdBy;
	global Datetime dateClosed;
	global Datetime dateOpened;
	global String description;
	global Boolean escalated;
	global String lastModifiedBy;
	global Datetime lastModifiedDate;
	global Datetime lastReferencedDate;
	global Datetime lastViewedDate;
	global String parentCase;
	global String priority;
	global String status;
	global String subject;
	global String type;
	global String webCompany;
	global String webEmail;
	global String webName;
	global String webPhone;
	global CareAuthorizationCaseOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}