global class CartItem {
	global ConnectApi.CartItemCollection cartData;
	global String currencyIsoCode;
	global String firstPymtTotalAmount;
	global String firstPymtTotalListPrice;
	global String firstPymtTotalPrice;
	global String firstPymtTotalTax;
	global String itemizedAdjustmentAmount;
	global String listPrice;
	global ConnectApi.ProductClass productClass;
	global String salesPrice;
	global String totalAdjustmentAmount;
	global String totalAmount;
	global String totalListPrice;
	global String totalPrice;
	global String totalTax;
	global String unitAdjustedPrice;
	global String unitAdjustedPriceWithItemAdj;
	global String unitAdjustmentAmount;
	global String unitItemAdjustmentAmount;
	global CartItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global ConnectApi.CartItemCollection getCartData() { }
	global String getCurrencyIsoCode() { }
	global String getFirstPymtTotalAmount() { }
	global String getFirstPymtTotalListPrice() { }
	global String getFirstPymtTotalPrice() { }
	global String getFirstPymtTotalTax() { }
	global String getItemizedAdjustmentAmount() { }
	global String getListPrice() { }
	global ConnectApi.ProductClass getProductClass() { }
	global String getSalesPrice() { }
	global String getTotalAdjustmentAmount() { }
	global String getTotalAmount() { }
	global String getTotalListPrice() { }
	global String getTotalPrice() { }
	global String getTotalTax() { }
	global String getUnitAdjustedPrice() { }
	global String getUnitAdjustedPriceWithItemAdj() { }
	global String getUnitAdjustmentAmount() { }
	global String getUnitItemAdjustmentAmount() { }
	global Integer hashCode() { }
	global void setCartData(ConnectApi.CartItemCollection value) { }
	global void setCurrencyIsoCode(String value) { }
	global void setFirstPymtTotalAmount(String value) { }
	global void setFirstPymtTotalListPrice(String value) { }
	global void setFirstPymtTotalPrice(String value) { }
	global void setFirstPymtTotalTax(String value) { }
	global void setItemizedAdjustmentAmount(String value) { }
	global void setListPrice(String value) { }
	global void setProductClass(ConnectApi.ProductClass value) { }
	global void setSalesPrice(String value) { }
	global void setTotalAdjustmentAmount(String value) { }
	global void setTotalAmount(String value) { }
	global void setTotalListPrice(String value) { }
	global void setTotalPrice(String value) { }
	global void setTotalTax(String value) { }
	global void setUnitAdjustedPrice(String value) { }
	global void setUnitAdjustedPriceWithItemAdj(String value) { }
	global void setUnitAdjustmentAmount(String value) { }
	global void setUnitItemAdjustmentAmount(String value) { }
	global String toString() { }

}