global class CartToExchangeOrderOutputRepresentation {
	global ConnectApi.BalanceStatePreviewOutputRepresentation balanceStateExchangeWebCart;
	global ConnectApi.BalanceStatePreviewOutputRepresentation balanceStateOriginalOrderSummary;
	global ConnectApi.BalanceStatePreviewOutputRepresentation balanceStateReturnOrder;
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}