global class CartPromotionOutputRepresentation {
	global String adjustmentAmount;
	global String couponCode;
	global String currencyIsoCode;
	global String displayName;
	global String promotionId;
	global ConnectApi.CartPromotionType targetType;
	global String termsAndConditions;
	global CartPromotionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}