global class CartMessagesSummary {
	global Integer errorCount;
	global Boolean hasErrors;
	global List<ConnectApi.CartMessage> limitedMessages;
	global String relatedEntityId;
	global Integer totalLineItemsWithErrors;
	global CartMessagesSummary() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}