global class CaseFileProcessExecution {
	global String batchJobId;
	global String caseFileProcessExecutionId;
	global String createdDate;
	global String dpeBatchJobStatus;
	global String dpeDeveloperName;
	global String dpeMasterLabel;
	global String dpeProcessingOrder;
	global List<ConnectApi.FileBasedDataImport> fileBasedDataImports;
	global String flowInterviewId;
	global String lastModifiedDate;
	global String processingType;
	global CaseFileProcessExecution() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}