global class CaseCommentCapability {
	global ConnectApi.CaseActorType actorType;
	global ConnectApi.Actor createdBy;
	global Datetime createdDate;
	global ConnectApi.CaseCommentEventType eventType;
	global String id;
	global Boolean published;
	global String text;
	global CaseCommentCapability() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}