global class CdpIdentityResolutionReconciliationRule {
	global String entityName;
	global List<ConnectApi.CdpIdentityResolutionReconciliationFieldRule> fields;
	global ConnectApi.CdpIdentityResolutionReconciliationRuleType ruleType;
	global Boolean shouldIgnoreEmptyValue;
	global List<ConnectApi.CdpIdentityResolutionReconciliationSource> sources;
	global CdpIdentityResolutionReconciliationRule() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}