global class CdpIdentityResolutionMatchCriterion {
	global Boolean caseSensitiveMatch;
	global String entityName;
	global String fieldName;
	global String fieldValue;
	global ConnectApi.CdpIdentityResolutionMatchMethodType matchMethodType;
	global ConnectApi.CdpIdentityResolutionMatchCriterionPartyIdentificationInfo partyIdentificationInfo;
	global Boolean shouldMatchOnBlank;
	global String targetEntityName;
	global String targetFieldName;
	global ConnectApi.CdpIdentityResolutionMatchCriterionPartyIdentificationInfo targetPartyIdentificationInfo;
	global CdpIdentityResolutionMatchCriterion() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}