global class CdpIdentityResolutionMatchCriterionOutput {
	global Boolean caseSensitiveMatch;
	global String entityName;
	global String fieldName;
	global String fieldValue;
	global ConnectApi.CdpIdentityResolutionMatchMethodType matchMethodType;
	global ConnectApi.CdpIdentityResolutionMatchCriterionPartyIdentificationInfoOutput partyIdentificationInfo;
	global Boolean shouldMatchOnBlank;
	global String targetEntityName;
	global String targetFieldName;
	global ConnectApi.CdpIdentityResolutionMatchCriterionPartyIdentificationInfoOutput targetPartyIdentificationInfo;
	global CdpIdentityResolutionMatchCriterionOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}