global class CdpIdentityResolutionReconciliationFieldRuleOutput {
	global String fieldName;
	global ConnectApi.CdpIdentityResolutionReconciliationRuleType ruleType;
	global Boolean shouldIgnoreEmptyValue;
	global List<ConnectApi.CdpIdentityResolutionReconciliationSourceOutput> sources;
	global CdpIdentityResolutionReconciliationFieldRuleOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}