global class CdpQueryOutput {
	global List<Object> data;
	global Boolean done;
	global String endTime;
	global Map<String,Object> metadata;
	global String queryId;
	global Integer rowCount;
	global String startTime;
	global CdpQueryOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}