global class CdpSegmentActionOutput {
	global String errorCode;
	global String errorMessage;
	global String jobId;
	global String partitionId;
	global String publishStatus;
	global String segmentApiName;
	global String segmentId;
	global CdpSegmentActionOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}