global class ChangeItemOutputRepresentation {
	global Double grandTotalAmount;
	global Double totalAdjDeliveryAmtWithTax;
	global Double totalAdjDistAmountWithTax;
	global Double totalAdjProductAmtWithTax;
	global Double totalAdjustedDeliveryAmount;
	global Double totalAdjustedDeliveryTaxAmount;
	global Double totalAdjustedProductAmount;
	global Double totalAdjustedProductTaxAmount;
	global Double totalAdjustmentDistributedAmount;
	global Double totalAdjustmentDistributedTaxAmount;
	global Double totalAmount;
	global Double totalExcessFundsAmount;
	global Double totalFeeAmount;
	global Double totalFeeTaxAmount;
	global Double totalRefundableAmount;
	global Double totalRequiredFundsAmount;
	global Double totalTaxAmount;
	global ChangeItemOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}