global class ChangeItemFeeWithTaxInputRepresentation {
	global Double amount;
	global List<ConnectApi.ChangeItemFeeTaxInputRepresentation> changeItemFeeTaxes;
	global String description;
	global String orderDeliveryGroupSummaryId;
	global String priceBookEntryId;
	global String product2Id;
	global String reason;
	global String reasonText;
	global ChangeItemFeeWithTaxInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}