global class ChangeItemInputRepresentation {
	global List<ConnectApi.ChangeItemFeeInputRepresentation> changeItemFees;
	global String orderItemSummaryId;
	global Double quantity;
	global String reason;
	global String reasonForChangeText;
	global Boolean shippingReductionFlag;
	global ChangeItemInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}