global class ChatterLikesCapability {
	global Boolean isLikedByCurrentUser;
	global ConnectApi.MessageBody likesMessage;
	global ConnectApi.Reference myLike;
	global ConnectApi.ChatterLikePage page;
	global ChatterLikesCapability() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}