global class ChatterStream {
	global ConnectApi.CommunitySummary community;
	global Datetime createdDate;
	global String description;
	global String id;
	global String name;
	global List<ConnectApi.FeedEnabledEntity> subscriptions;
	global String url;
	global ChatterStream() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}