global class ChatterMessagePage {
	global String currentPageToken;
	global String currentPageUrl;
	global List<ConnectApi.ChatterMessage> messages;
	global String nextPageToken;
	global String nextPageUrl;
	global ChatterMessagePage() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}