global class CheckProductOfferingQualificationItemInputRepresentation {
	global String action;
	global String expectedActivationDate;
	global ConnectApi.CPQItemProductOfferingInputRepresentation productOffering;
	global String type;
	global CheckProductOfferingQualificationItemInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}