global class CheckProductOfferingOutputRepresentation {
	global List<ConnectApi.CheckProductOfferingQualificationItemOutputRepresentation> checkProductOfferingQualificationItem;
	global String creationDate;
	global List<ConnectApi.OpenAPIRelatedPartyOutputRepresentation> relatedParty;
	global String state;
	global String type;
	global CheckProductOfferingOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}