global class CheckProductOfferingQualificationItemOutputRepresentation {
	global ConnectApi.CheckProductOfferingResponseOutputRepresentation productOffering;
	global String qualificationItemResult;
	global String state;
	global String type;
	global CheckProductOfferingQualificationItemOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}