global class CheckProductOfferingQualificationInputRepresentation {
	global List<ConnectApi.CheckProductOfferingQualificationItemInputRepresentation> checkProductOfferingQualificationItem;
	global List<ConnectApi.RelatedPartyOrPartyRoleInputRepresentation> relatedParty;
	global CheckProductOfferingQualificationInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}