global class ChimeMediaPlacementResult {
	global String audioFallbackUrl;
	global String audioHostUrl;
	global String eventIngestionUrl;
	global String screenDataUrl;
	global String screenSharingUrl;
	global String screenViewingUrl;
	global String signalingUrl;
	global String turnControlUrl;
	global ChimeMediaPlacementResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}