global class ClaimDetailOutputRep {
	global ConnectApi.ClaimAttributeOutputRep attributes;
	global String claimReason;
	global String claimReasonType;
	global String claimType;
	global String incidentTypeId;
	global String lossType;
	global ClaimDetailOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}