global class ClaimParticipantInputRep {
	global String accountId;
	global String action;
	global List<ConnectApi.AdditionalFieldInputRep> additionalFields;
	global String contactId;
	global String instanceKey;
	global String insurancePolicyParticipantId;
	global String isInjured;
	global List<String> roles;
	global ClaimParticipantInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}