global class ClaimParticipantOutputRepresentation {
	global String accountId;
	global String contactId;
	global String id;
	global String instanceKey;
	global String insurancePolicyParticipantId;
	global List<String> roles;
	global ClaimParticipantOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}