global class ClaimParticipantInputRepresentation {
	global String accountId;
	global String action;
	global Object additionalFields;
	global String contactId;
	global String instanceKey;
	global String insurancePolicyParticipantId;
	global String isInjured;
	global List<String> roles;
	global ClaimParticipantInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}