global class ClubMemberBenefitsRepresentation {
	global String benefitId;
	global String benefitName;
	global String benefitTypeId;
	global String benefitTypeName;
	global String description;
	global Boolean isActive;
	global ClubMemberBenefitsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}