global class ClubMemberPromotionsRepresentation {
	global Datetime endDate;
	global String imageUrl;
	global String loyaltyPromotionType;
	global String memberEligibilityCategory;
	global Boolean promotionEnrollmentRqr;
	global String promotionId;
	global String promotionName;
	global Datetime startDate;
	global ClubMemberPromotionsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}