global class CommerceStorefrontContextProductCategoryOutputRepresentation {
	global String id;
	global String name;
	global List<ConnectApi.CommerceStorefrontContextProductCategoryOutputRepresentation> subCategories;
	global CommerceStorefrontContextProductCategoryOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}