global class CommerceStorefrontContextOutputRepresentation {
	global List<ConnectApi.CommerceStorefrontContextProductCategoryOutputRepresentation> categories;
	global ConnectApi.CommerceStorefrontContextSearchLiveIndexSnapshotOutputRepresentation searchLiveIndexSnapshot;
	global CommerceStorefrontContextOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}