global class CommitmentPaymentUpdatesOutputRepresentation {
	global List<ConnectApi.CommitmentPaymentUpdatesResponse> details;
	global Integer failures;
	global Integer notProcessed;
	global Integer successes;
	global CommitmentPaymentUpdatesOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}