global class CommentCapabilities {
	global ConnectApi.CommentsCapability comments;
	global ConnectApi.ContentCapability content;
	global ConnectApi.EditCapability edit;
	global ConnectApi.ExtensionsCapability extensions;
	global ConnectApi.FeedEntityShareCapability feedEntityShare;
	global ConnectApi.RecordCapability record;
	global ConnectApi.StatusCapability status;
	global ConnectApi.UpDownVoteCapability upDownVote;
	global ConnectApi.VerifiedCapability verified;
	global CommentCapabilities() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}