global class CommerceSearchIndexErrors {
	global String errorFileId;
	global Datetime indexCreatedDate;
	global Integer indexErrorsCount;
	global Datetime indexLastUpdatedDate;
	global Integer itemLevelErrorsCount;
	global CommerceSearchIndexErrors() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}