global class Community {
	global Boolean allowChatterAccessWithoutLogin;
	global Boolean allowMembersToFlag;
	global Boolean builderBasedSnaEnabled;
	global String builderUrl;
	global String contentSpaceId;
	global String description;
	global Boolean guestMemberVisibilityEnabled;
	global String id;
	global Boolean imageOptimizationCDNEnabled;
	global Boolean invitationsEnabled;
	global Boolean knowledgeableEnabled;
	global String loginUrl;
	global Boolean memberVisibilityEnabled;
	global String name;
	global Boolean nicknameDisplayEnabled;
	global Boolean privateMessagesEnabled;
	global Boolean reputationEnabled;
	global Boolean sendWelcomeEmail;
	global Boolean siteAsContainerEnabled;
	global String siteUrl;
	global ConnectApi.CommunityStatus status;
	global String templateName;
	global String url;
	global String urlPathPrefix;
	global Community() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}