global class CommerceShopperAgentContextMIAWConfigOutputRepresentation {
	global String embeddedWebDeployment;
	global String enhancedServiceURL;
	global String siteEndpoint;
	global CommerceShopperAgentContextMIAWConfigOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}