global class CommerceAddressInput {
	global String addressType;
	global String city;
	global List<ConnectApi.CommerceAddressFieldInput> commerceAddressFieldInputList;
	global String companyName;
	global String country;
	global String countryCode;
	global String firstName;
	global Boolean isDefault;
	global String lastName;
	global String middleName;
	global String name;
	global String phoneNumber;
	global String postalCode;
	global String region;
	global String regionCode;
	global String street;
	global commerceAddressInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global String getAddressType() { }
	global String getCity() { }
	global List<ConnectApi.CommerceAddressFieldInput> getCommerceAddressFieldInputList() { }
	global String getCompanyName() { }
	global String getCountry() { }
	global String getCountryCode() { }
	global String getFirstName() { }
	global Boolean getIsDefault() { }
	global String getLastName() { }
	global String getMiddleName() { }
	global String getName() { }
	global String getPhoneNumber() { }
	global String getPostalCode() { }
	global String getRegion() { }
	global String getRegionCode() { }
	global String getStreet() { }
	global Integer hashCode() { }
	global void setAddressType(String value) { }
	global void setCity(String value) { }
	global void setCommerceAddressFieldInputList(List<ConnectApi.CommerceAddressFieldInput> value) { }
	global void setCompanyName(String value) { }
	global void setCountry(String value) { }
	global void setCountryCode(String value) { }
	global void setFirstName(String value) { }
	global void setIsDefault(Boolean value) { }
	global void setLastName(String value) { }
	global void setMiddleName(String value) { }
	global void setName(String value) { }
	global void setPhoneNumber(String value) { }
	global void setPostalCode(String value) { }
	global void setRegion(String value) { }
	global void setRegionCode(String value) { }
	global void setStreet(String value) { }
	global String toString() { }

}