global class CommerceProductSummaryPage {
	global Integer pageSize;
	global List<ConnectApi.CommerceProductSummary> products;
	global Long total;
	global CommerceProductSummaryPage() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer getPageSize() { }
	global List<ConnectApi.CommerceProductSummary> getProducts() { }
	global Long getTotal() { }
	global Integer hashCode() { }
	global void setPageSize(Integer value) { }
	global void setProducts(List<ConnectApi.CommerceProductSummary> value) { }
	global void setTotal(Long value) { }
	global String toString() { }

}