global class CompanionAdQuoteLineCreativeSizeTypeInputRepresentation {
	global String adQuoteLineCreativeSizeTypeId;
	global String adSpaceCreativeSizeTypeId;
	global ConnectApi.HttpMethodEnum method;
	global CompanionAdQuoteLineCreativeSizeTypeInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}