global class CompositeCommerceVariationAsyncOutputRepresentation {
	global ConnectApi.ErrorResponse error;
	global String parentProductId;
	global Boolean success;
	global String taskId;
	global CompositeCommerceVariationAsyncOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}