global class ComplianceControlEvaluation {
	global String complianceControlId;
	global String complianceControlVersionId;
	global String complianceMessage;
	global String errorId;
	global String errorMessage;
	global Boolean isCompliant;
	global ConnectApi.ComplianceControlStatus status;
	global ComplianceControlEvaluation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}