global class ComplaintInfoWrapper {
	global String accountId;
	global Map<String,ConnectApi.GenericObjectWrapper> additionalInfo;
	global String complaintSubType;
	global String complaintType;
	global String description;
	global String email;
	global String incidentDate;
	global String priority;
	global String productType;
	global String receivedDate;
	global String status;
	global String subject;
	global ComplaintInfoWrapper() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}