global class CompositeCommerceProductOutputRepresentation {
	global List<ConnectApi.CompositeErrorResponseRepresentation> errorDetails;
	global List<ConnectApi.ErrorResponse> errors;
	global String productId;
	global Boolean success;
	global CompositeCommerceProductOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}