global class ComplianceProcedureEvaluationResponse {
	global String complianceProcedureId;
	global String complianceProcedureVersionId;
	global List<ConnectApi.ComplianceProcedureEvaluation> evaluations;
	global ComplianceProcedureEvaluationResponse() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}