global class CompositeVariationAsyncTaskDetailRepresentation {
	global Map<String,Object> createPayload;
	global Map<String,List<ConnectApi.CompositeErrorResponseRepresentation>> errors;
	global String status;
	global CompositeVariationAsyncTaskDetailRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}