global class ContentHubFieldDefinition {
	global String displayName;
	global Boolean isMandatory;
	global Integer maxLength;
	global String name;
	global ConnectApi.ContentHubVariableType type;
	global ContentHubFieldDefinition() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}