global class CreateAppFormPartyFinancialAssetOutputRep {
	global List<String> partyFinancialAssetAdditionalOwner;
	global String partyFinancialAssetId;
	global List<String> partyFinancialAssetLien;
	global CreateAppFormPartyFinancialAssetOutputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}