global class CreateContractDocumentVersionReviewOutputRepresentation {
	global String contractDocumentVersionId;
	global Boolean isSuccess;
	global String message;
	global CreateContractDocumentVersionReviewOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}