global class CreateGiftOutputRepresentation {
	global List<ConnectApi.CreateGiftResponseDetails> details;
	global Integer failures;
	global Integer notProcessed;
	global Integer successes;
	global CreateGiftOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}