global class DatacloudCompanies {
	global List<ConnectApi.DatacloudCompany> companies;
	global String currentPageUrl;
	global String nextPageUrl;
	global String previousPageUrl;
	global Integer total;
	global DatacloudCompanies() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}