global class DecisionTableSourceCriteriaInput {
	global ConnectApi.DecisionTableOperatorString operator;
	global Integer sequenceNumber;
	global String sourceFieldName;
	global String value;
	global ConnectApi.DecisionTableSourceConditionValueType valueType;
	global DecisionTableSourceCriteriaInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}