global class DecisioningPersonalizationDiagnosticsRepresentation {
	global String code;
	global String description;
	global DecisioningPersonalizationDiagnosticsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global String getCode() { }
	global String getDescription() { }
	global Integer hashCode() { }
	global void setCode(String value) { }
	global void setDescription(String value) { }
	global String toString() { }

}