global class DecisionTableOutcome {
	global Integer errorCode;
	global String errorMessage;
	global List<ConnectApi.DecisionTableOutcomeItem> outcomeList;
	global String outcomeType;
	global Boolean successStatus;
	global DecisionTableOutcome() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}