global class DecisioningPersonalizationDataRepresentation {
	global List<String> additionalProperties;
	global String personalizationContentId;
	global DecisioningPersonalizationDataRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global List<String> getAdditionalProperties() { }
	global Double getBuildVersion() { }
	global String getPersonalizationContentId() { }
	global Integer hashCode() { }
	global void setAdditionalProperties(List<String> value) { }
	global void setPersonalizationContentId(String value) { }
	global String toString() { }

}