global class DecisioningContextInputRepresentation {
	global String anchorId;
	global String anchorType;
	global String correlationId;
	global String dataSpaceName;
	global String individualId;
	global String unifiedIndividualId;
	global DecisioningContextInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}