global class DecisionTableSourceCriteriaOutput {
	global ConnectApi.DecisionTableOperatorString operator;
	global Integer sequenceNumber;
	global String sourceFieldName;
	global String value;
	global ConnectApi.DecisionTableSourceConditionValueType valueType;
	global DecisionTableSourceCriteriaOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}