global class DependencyDetailOutputRepresentation {
	global String apiName;
	global String id;
	global Datetime lastModifiedDate;
	global String name;
	global ConnectApi.ExpressionSetVersionDependencyEnumRepresentation type;
	global DependencyDetailOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}