global class DetailedProjectedRebateAmountCalc {
	global String aggregateId;
	global Double benefitQualifierValue;
	global String benefitTier;
	global String error;
	global Double measureFieldValue;
	global String payoutPeriod;
	global Double projectedRebateAmount;
	global List<String> qualifiedTiers;
	global String rebateTypeBenefit;
	global DetailedProjectedRebateAmountCalc() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}