global class DigitalVerificationInputRequest {
	global String digitalVerificationId;
	global Map<String,String> digitalVerificationInputFieldsMap;
	global String sessionId;
	global ConnectApi.UserCredentialsInputRepresentation userCredentials;
	global DigitalVerificationInputRequest() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}