global class DirectMessageCapability {
	global ConnectApi.DirectMessageMemberActivityPage memberChanges;
	global ConnectApi.DirectMessageMemberPage members;
	global ConnectApi.DirectMessageMemberPage originalMembers;
	global String subject;
	global DirectMessageCapability() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}