global class DirectMessageMemberActivityPage {
	global List<ConnectApi.DirectMessageMemberActivity> activities;
	global String currentPageToken;
	global String currentPageUrl;
	global String nextPageToken;
	global String nextPageUrl;
	global DirectMessageMemberActivityPage() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}