global class DirectMessageMemberActivity {
	global Datetime activityDate;
	global ConnectApi.UserSummary actor;
	global ConnectApi.DirectMessageMemberPage membersAdded;
	global ConnectApi.DirectMessageMemberPage membersRemoved;
	global DirectMessageMemberActivity() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}