global class DiscoverySearchProductRepresentation {
	global String description;
	global String id;
	global String name;
	global Map<String,String> productFieldDecorations;
	global String stockKeepingUnit;
	global String unitPrice;
	global String url;
	global DiscoverySearchProductRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}