global class DispenserAddressOutput {
	global String dispenserCity;
	global String dispenserCountry;
	global String dispenserPostalCode;
	global String dispenserState;
	global String dispenserStreet;
	global DispenserAddressOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}