global class DocumentGenerateRepresentationResponse {
	global List<ConnectApi.ContentDocumentResponse> contentDocuments;
	global String contractDocumentVersionId;
	global String contractId;
	global String jobId;
	global DocumentGenerateRepresentationResponse() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}