global class DocumentOutputRepresentation {
	global List<ConnectApi.DocumentAttachmentOutputRepresentation> attachment;
	global String contentDocumentId;
	global String creationDate;
	global String description;
	global String documentType;
	global String lastUpdate;
	global String name;
	global String status;
	global String type;
	global String version;
	global DocumentOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}