global class EinsteinPromptRecordCollectionOutputRepresentation {
	global Boolean hasMoreRecords;
	global List<ConnectApi.EinsteinPromptRecordRepresentation> promptRecords;
	global Integer totalPromptRecords;
	global EinsteinPromptRecordCollectionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}