global class EinsteinRecommendationValue {
	global Double confidence;
	global String id;
	global String sobjectLookupType;
	global String sobjectLookupValueId;
	global String value;
	global String valueType;
	global EinsteinRecommendationValue() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}