global class EinsteinRecommendation {
	global Double confidence;
	global String id;
	global List<ConnectApi.EinsteinRecommendationValue> insightValues;
	global String mlPredictionDefinitionId;
	global String predictionDefinitionId;
	global String predictionField;
	global String runGuid;
	global Datetime runStartTime;
	global String targetId;
	global String targetSobjectType;
	global String type;
	global Datetime validUtil;
	global EinsteinRecommendation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}