global class EinsteinLlmGenAiSourceReference {
	global List<ConnectApi.EinsteinLlmGenerationGenAiSourceContentInfo> contents;
	global List<ConnectApi.EinsteinLlmGenerationGenAiSourceReferenceInfo> metadata;
	global EinsteinLlmGenAiSourceReference() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}