global class EinsteinLlmFeedbackInput {
	global Map<String,ConnectApi.WrappedValue> appFeedback;
	global String appGeneration;
	global String appGenerationId;
	global String applicationName;
	global String feedback;
	global String feedbackText;
	global String generationId;
	global String id;
	global String source;
	global EinsteinLlmFeedbackInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}