global class EinsteinLlmGenerationSafetyScoreOutput {
	global Double hateScore;
	global Double physicalScore;
	global Double profanityScore;
	global Double safetyScore;
	global Double sexualScore;
	global Double toxicityScore;
	global Double violenceScore;
	global EinsteinLlmGenerationSafetyScoreOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}