global class EinsteinLlmGenerationCitationOutput {
	global List<ConnectApi.EinsteinLlmGenerationGenAiCitedReference> citedReferences;
	global List<ConnectApi.EinsteinLlmGenAiSourceReference> sourceReferences;
	global EinsteinLlmGenerationCitationOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}