global class EligibleProgramRebateTypesOutput {
	global Integer appliedRebateTypesLimit;
	global Integer appliedRebateTypesOffset;
	global Integer limitValue;
	global Integer offsetValue;
	global List<ConnectApi.ProgramRebateTypes> programRebateTypes;
	global EligibleProgramRebateTypesOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}