global class EngagementAttendeeCreateInput {
	global List<ConnectApi.EngagementCustomFieldsInput> customFieldsList;
	global String endDateTime;
	global String engagementInteractionId;
	global String externalAttendeeId;
	global String id;
	global String internalAttendeeId;
	global Boolean isAuthenticated;
	global Boolean isVerified;
	global String ownerId;
	global String role;
	global String startDateTime;
	global String verificationTime;
	global EngagementAttendeeCreateInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}