global class EngagementsUpdateInput {
	global List<ConnectApi.EngagementAttendeeCreateInput> engagementAttendees;
	global ConnectApi.EngagementInteractionUpdateInput engagementInteraction;
	global List<ConnectApi.EngagementTopicCreateInput> engagementTopics;
	global EngagementsUpdateInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}