global class EngagementsUpdateOutput {
	global List<ConnectApi.EngagementsIdOutput> engagementAttendees;
	global ConnectApi.EngagementsIdOutput engagementInteraction;
	global List<ConnectApi.EngagementsIdOutput> engagementTopics;
	global ConnectApi.EngagementStatusOutput status;
	global EngagementsUpdateOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}