global class EnsureRefundsAsyncInputRepresentation {
	global String creditMemoId;
	global Double excessFundsAmount;
	global List<ConnectApi.InvoiceToPayInputRepresentation> invoicesToPay;
	global Boolean isAllowPartial;
	global Boolean isReservedBalanceAmountConsidered;
	global List<ConnectApi.SequenceOrderPaymentSummaryInputRepresentation> sequences;
	global EnsureRefundsAsyncInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}