global class EstimateDeliveryDateOutputRepresentation {
	global List<ConnectApi.DeliveryEstimateOutputRepresentation> deliveryEstimates;
	global String estimatedDeliveryReference;
	global EstimateDeliveryDateOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}