global class ExampleListRepresentation {
	global List<SObject> customList;
	global List<Datetime> dateList;
	global List<Object> objectList;
	global List<ConnectApi.ExampleEntityRepresentation> repListOne;
	global List<String> stringList;
	global ExampleListRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}