global class ExampleSerializationRepresentation {
	global String deserializationMessage;
	global String deserializationResult;
	global String input;
	global String serializationMessage;
	global String serializationResult;
	global ExampleSerializationRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}