global class ExampleEntityInputRepresentation {
	global SObject customObject;
	global String exampleId;
	global Integer exampleInteger;
	global Object exampleObject;
	global ConnectApi.ExampleStatus exampleStatusEnum;
	global String exampleString;
	global ExampleEntityInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}