global class ExplainabilityLogDetail {
	global String actionContextCode;
	global String actionLog;
	global String applicationLogCalendarDate;
	global String applicationLogDate;
	global String applicationSubtype;
	global String applicationType;
	global Boolean isChunked;
	global String name;
	global String processType;
	global String uniqueIdentifier;
	global ExplainabilityLogDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}