global class ExplainabilityDetailedActionLogDetail {
	global String actionContextCode;
	global String actionLog;
	global String additionalFilter;
	global String applicationLogDate;
	global String applicationSubtype;
	global String applicationType;
	global String explainabilitySpecName;
	global String name;
	global String primaryFilter;
	global String processType;
	global String secondaryFilter;
	global String uniqueIdentifier;
	global ExplainabilityDetailedActionLogDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}