global class ExternalCredentialParameterInput {
	global String id;
	global String parameterDescription;
	global String parameterName;
	global ConnectApi.ExternalCredentialParameterType parameterType;
	global String parameterValue;
	global ExternalCredentialParameterInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}