global class ExternalAuthIdentityProviderParameterInput {
	global String parameterName;
	global ConnectApi.ExternalAuthIdentityProviderParamType parameterType;
	global String parameterValue;
	global Integer sequenceNumber;
	global ExternalAuthIdentityProviderParameterInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}