global class ExternalCredentialParameter {
	global String id;
	global String parameterDescription;
	global String parameterName;
	global ConnectApi.ExternalCredentialParameterType parameterType;
	global String parameterValue;
	global ExternalCredentialParameter() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}