global class ExternalManagedAccountAddressOutput {
	global String city;
	global String country;
	global String geolocationAccuracy;
	global String latitude;
	global String longitude;
	global String state;
	global String street;
	global String zip;
	global ExternalManagedAccountAddressOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}