global class ExternalAuthIdentityProviderParameter {
	global String parameterName;
	global ConnectApi.ExternalAuthIdentityProviderParamType parameterType;
	global String parameterValue;
	global Integer sequenceNumber;
	global ExternalAuthIdentityProviderParameter() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}