global class ExtendedRewardDetails {
	global String extendedRewardDefinition;
	global String extendedRewardId;
	global String extendedRewardImageUrl;
	global String extendedRewardName;
	global String status;
	global String transactionJournalId;
	global ExtendedRewardDetails() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global String getExtendedRewardDefinition() { }
	global String getExtendedRewardId() { }
	global String getExtendedRewardImageUrl() { }
	global String getExtendedRewardName() { }
	global String getStatus() { }
	global String getTransactionJournalId() { }
	global Integer hashCode() { }
	global void setExtendedRewardDefinition(String value) { }
	global void setExtendedRewardId(String value) { }
	global void setExtendedRewardImageUrl(String value) { }
	global void setExtendedRewardName(String value) { }
	global void setStatus(String value) { }
	global void setTransactionJournalId(String value) { }
	global String toString() { }

}