global class ExtensionDefinitions {
	global String currentPageToken;
	global String currentPageUrl;
	global List<ConnectApi.ExtensionDefinition> extensionDefinitions;
	global String nextPageToken;
	global String nextPageUrl;
	global Integer total;
	global ExtensionDefinitions() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}