global class ExternalDocumentOutputRepresentation {
	global String contentVersionId;
	global String externalDocumentId;
	global String externalUserId;
	global String referenceObject;
	global String referenceObjectId;
	global String url;
	global ExternalDocumentOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}