global class ExtractionContextUseCaseMappingRepresentation {
	global ConnectApi.ExtractionContextDefinitionRepresentation contextDefinition;
	global ConnectApi.ExtractionContextMappingRepresentation contextMapping;
	global String recordType;
	global String targetObject;
	global String templateName;
	global ExtractionContextUseCaseMappingRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}