global class ExtractionContextMappingOutputRepresentation {
	global List<ConnectApi.ExtractionContextAttributeMappingRepresentation> contextAttributeMapping;
	global ConnectApi.ExtractionContextUseCaseMappingRepresentation contextUseCaseMapping;
	global String contextUseCaseMappingId;
	global Boolean isSuccess;
	global ExtractionContextMappingOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}