global class Features {
	global Boolean activityReminderNotificationsEnabled;
	global Boolean chatter;
	global Boolean chatterActivity;
	global Boolean chatterAnswers;
	global Boolean chatterGlobalInfluence;
	global Boolean chatterGroupRecordSharing;
	global Boolean chatterGroupRecords;
	global Boolean chatterMessages;
	global Boolean chatterTopics;
	global Boolean communitiesEnabled;
	global Boolean communityModeration;
	global Boolean communityReputation;
	global Boolean connectRecords;
	global Boolean customFiscalCalendarEnabled;
	global Boolean dashboardComponentSnapshots;
	global String defaultCurrencyIsoCode;
	global String defaultLocale;
	global Boolean einsteinVoiceEnabled;
	global Boolean einsteinVoiceInPilotEnabled;
	global Boolean einsteinVoiceLoggingEnabled;
	global Integer einsteinVoiceProviderId;
	global Boolean favoritesEnabled;
	global Integer favoritesLimit;
	global Boolean feedPolling;
	global Boolean feedStreamEnabled;
	global Boolean files;
	global Boolean filesOnComments;
	global Integer fiscalYearStartMonth;
	global Boolean forecasting3AggregatedEnabled;
	global Boolean forecastingEnabled;
	global Integer forecastingPeriodRange;
	global Integer forecastingPeriodStart;
	global ConnectApi.PeriodTypesEnum forecastingPeriodType;
	global Boolean groupsCanFollow;
	global Boolean ideas;
	global String liveAgentHostName;
	global Boolean managedTopicsEnabled;
	global Integer maxEntitySubscriptionsPerStream;
	global Integer maxFilesPerFeedItem;
	global Integer maxStreamsPerPerson;
	global Boolean mobileNotificationsEnabled;
	global Boolean multiCurrency;
	global Boolean offlineEditEnabled;
	global Boolean publisherActions;
	global Boolean storeDataOnDevicesEnabled;
	global Boolean thanksAllowed;
	global Boolean trendingTopics;
	global Boolean userNavItemsEnabled;
	global Integer userNavItemsMax;
	global Boolean usesStartDateAsFiscalYearName;
	global Boolean viralInvitesAllowed;
	global Boolean wave;
	global Features() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}