global class FeedElementCapabilitiesInput {
	global ConnectApi.AssociatedActionsCapabilityInput associatedActions;
	global ConnectApi.BookmarksCapabilityInput bookmarks;
	global ConnectApi.CanvasCapabilityInput canvas;
	global ConnectApi.ContentCapabilityInput content;
	global ConnectApi.DirectMessageCapabilityInput directMessage;
	global ConnectApi.ExtensionsCapabilityInput extensions;
	global ConnectApi.FeedEntityShareCapabilityInput feedEntityShare;
	global ConnectApi.FilesCapabilityInput files;
	global ConnectApi.LinkCapabilityInput link;
	global ConnectApi.PollCapabilityInput poll;
	global ConnectApi.QuestionAndAnswersCapabilityInput questionAndAnswers;
	global ConnectApi.StatusCapabilityInput status;
	global ConnectApi.TopicsCapabilityInput topics;
	global FeedElementCapabilitiesInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}