global class FeedElementPage {
	global String currentPageToken;
	global String currentPageUrl;
	global List<ConnectApi.FeedElement> elements;
	global String isModifiedToken;
	global String isModifiedUrl;
	global String nextPageToken;
	global String nextPageUrl;
	global String searchQueryId;
	global String updatesToken;
	global String updatesUrl;
	global FeedElementPage() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}