global class FeedDirectoryItem {
	global String feedElementsUrl;
	global String feedItemsUrl;
	global ConnectApi.FeedType feedType;
	global String feedUrl;
	global String keyPrefix;
	global String label;
	global FeedDirectoryItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}