global class FeedEntitySummary {
	global ConnectApi.Actor actor;
	global ConnectApi.FeedBody body;
	global Datetime createdDate;
	global ConnectApi.FeedElementType feedElementType;
	global String id;
	global Boolean isEntityAvailable;
	global ConnectApi.ActorWithId parent;
	global String relativeCreatedDate;
	global String url;
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}