global class FeedElementCapabilities {
	global ConnectApi.ApprovalCapability approval;
	global ConnectApi.AssociatedActionsCapability associatedActions;
	global ConnectApi.BannerCapability banner;
	global ConnectApi.BookmarksCapability bookmarks;
	global ConnectApi.BundleCapability bundle;
	global ConnectApi.CallCollaborationCapability callCollaboration;
	global ConnectApi.CanvasCapability canvas;
	global ConnectApi.CaseCommentCapability caseComment;
	global ConnectApi.ChatterLikesCapability chatterLikes;
	global ConnectApi.CloseCapability close;
	global ConnectApi.CommentsCapability comments;
	global ConnectApi.ContentCapability content;
	global ConnectApi.DashboardComponentSnapshotCapability dashboardComponentSnapshot;
	global ConnectApi.DirectMessageCapability directMessage;
	global ConnectApi.EditCapability edit;
	global ConnectApi.EmailMessageCapability emailMessage;
	global ConnectApi.EnhancedLinkCapability enhancedLink;
	global ConnectApi.ExtensionsCapability extensions;
	global ConnectApi.FeedEntityShareCapability feedEntityShare;
	global ConnectApi.FilesCapability files;
	global ConnectApi.InteractionsCapability interactions;
	global ConnectApi.LinkCapability link;
	global ConnectApi.MediaReferenceCapability mediaReferences;
	global ConnectApi.ModerationCapability moderation;
	global ConnectApi.MuteCapability mute;
	global ConnectApi.OriginCapability origin;
	global ConnectApi.PinCapability pin;
	global ConnectApi.PollCapability poll;
	global ConnectApi.QuestionAndAnswersCapability questionAndAnswers;
	global ConnectApi.ReadByCapability readBy;
	global ConnectApi.RecommendationsCapability recommendations;
	global ConnectApi.RecordSnapshotCapability recordSnapshot;
	global ConnectApi.SocialPostCapability socialPost;
	global ConnectApi.StatusCapability status;
	global ConnectApi.TopicsCapability topics;
	global ConnectApi.TrackedChangesCapability trackedChanges;
	global ConnectApi.UpDownVoteCapability upDownVote;
	global FeedElementCapabilities() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}