global class FeedFavorite {
	global ConnectApi.Reference community;
	global ConnectApi.UserSummary createdBy;
	global String feedUrl;
	global String id;
	global Datetime lastViewDate;
	global String name;
	global String searchText;
	global ConnectApi.Reference target;
	global ConnectApi.FeedFavoriteType type;
	global String url;
	global ConnectApi.UserSummary user;
	global FeedFavorite() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}