global class FileAsset {
	global String baseAssetUrl;
	global String baseUnauthenticatedAssetUrl;
	global String id;
	global Boolean isVisibleByExternalUsers;
	global String masterLabel;
	global String name;
	global String namespacePrefix;
	global String type;
	global FileAsset() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}