global class FilePreview {
	global ConnectApi.FilePreviewFormat format;
	global Integer previewUrlCount;
	global List<ConnectApi.FilePreviewUrl> previewUrls;
	global ConnectApi.FilePreviewStatus status;
	global String url;
	global FilePreview() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}