global class File {
	global String checksum;
	global Datetime contentModifiedDate;
	global Integer contentSize;
	global String contentUrl;
	global String contentVersionId;
	global Datetime createdDate;
	global String description;
	global String downloadUrl;
	global String fileExtension;
	global String fileType;
	global String flashRenditionStatus;
	global Boolean isFileAsset;
	global Boolean isInMyFileSync;
	global Boolean isMajorVersion;
	global String mimeType;
	global ConnectApi.ModerationFlags moderationFlags;
	global Datetime modifiedDate;
	global String origin;
	global ConnectApi.UserSummary owner;
	global String pdfRenditionStatus;
	global ConnectApi.FilePublishStatus publishStatus;
	global String renditionUrl;
	global String renditionUrl240By180;
	global String renditionUrl720By480;
	global ConnectApi.FileSharingOption sharingOption;
	global ConnectApi.FileSharingPrivacy sharingPrivacy;
	global ConnectApi.FileSharingType sharingRole;
	global Datetime systemModstamp;
	global String textPreview;
	global String thumb120By90RenditionStatus;
	global String thumb240By180RenditionStatus;
	global String thumb720By480RenditionStatus;
	global String title;
	global String versionNumber;
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}