global class FindRoutesWithFewestSplitsGroupUsingOCIInputRepresentation {
	global List<String> excludeLocations;
	global Integer maximumNumberOfSplits;
	global List<ConnectApi.FindRoutesWithFewestSplitsUsingOCIItemInputRepresentation> orderedItems;
	global FindRoutesWithFewestSplitsGroupUsingOCIInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}