global class FindRoutesWithFewestSplitsInputRepresentation {
	global List<ConnectApi.LocationAvailabilityInputRepresentation> locationAvailableInventory;
	global Integer maximumNumberOfSplits;
	global List<ConnectApi.QuantityWithSkuInputRepresentation> orderedQuantities;
	global FindRoutesWithFewestSplitsInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}