global class FindRoutesWithFewestSplitsWithInventoryOutputRepresentation {
	global ConnectApi.OCIGetInventoryAvailabilityOutputRepresentation inventory;
	global List<ConnectApi.AvailableLocationOutputRepresentation> targetLocations;
	global FindRoutesWithFewestSplitsWithInventoryOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}