global class FrequencyCadenceOptions {
	global ConnectApi.RecurringSubTypeEnum recurringSubType;
	global ConnectApi.RecursOnEnum recursOn;
	global String recursOnDate;
	global ConnectApi.RecursOnDayEnum recursOnDay;
	global Boolean shouldExcludeWkendAndHldy;
	global Boolean shouldStartRunImmediately;
	global FrequencyCadenceOptions() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}