global class FulfillmentOrderInputRepresentation {
	global String defaultActivationStatus;
	global List<ConnectApi.FulfillmentGroupInputRepresentation> fulfillmentGroups;
	global String orderDeliveryGroupSummaryId;
	global String orderSummaryId;
	global FulfillmentOrderInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}