global class GetApplicationFormResult {
	global List<ConnectApi.ApplicantWrapperResultRepresentation> applicants;
	global ConnectApi.ApplicationFormResultRepresentation applicationForm;
	global List<ConnectApi.ApplicationFormProductWrapResultRepresentation> applicationFormProducts;
	global GetApplicationFormResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}