global class GetClaimOutputRepresentation {
	global String accountId;
	global ConnectApi.ClaimDetailOutputRep claimDetails;
	global String claimId;
	global String insurancePolicyId;
	global String lossDate;
	global String name;
	global String productCode;
	global GetClaimOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}