global class GiftCommitmenteDetails {
	global String campaignId;
	global String commitmentId;
	global String commitmentType;
	global String name;
	global Double nextGiftAmount;
	global Datetime nextGiftDate;
	global String status;
	global String transactionId;
	global GiftCommitmenteDetails() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}