global class GiftWrapProductCollection {
	global List<String> productIds;
	global Integer total;
	global GiftWrapProductCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global List<String> getProductIds() { }
	global Integer getTotal() { }
	global Integer hashCode() { }
	global void setProductIds(List<String> value) { }
	global void setTotal(Integer value) { }
	global String toString() { }

}