global class GiftCampaignDefaultDesignationsOutputRepresentation {
	global List<ConnectApi.GiftCampaignDefaultDesignationRecordOutputRepresentation> campaignDefaultDesignations;
	global GiftCampaignDefaultDesignationsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}