global class GiftTransactionRecordOutputRepresentation {
	global Double amount;
	global String commitmentId;
	global String commitmentScheduleId;
	global String paymentMethod;
	global String status;
	global Datetime transactionDate;
	global GiftTransactionRecordOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}