global class GuardrailDetailRepresentation {
	global String guardRailCurrentValue;
	global String guardRailMaxValue;
	global String guardRailMinValue;
	global String guardRailName;
	global String guardRailRestrictionType;
	global ConnectApi.MessageListRepresentation messages;
	global GuardrailDetailRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}