global class IndividualMemberOutput {
	global String contactId;
	global String loyaltyProgramMemberId;
	global String loyaltyProgramName;
	global String membershipNumber;
	global List<ConnectApi.TransactionJournalOutput> transactionJournals;
	global IndividualMemberOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}