global class IndividualApplicationObjectOutputRepresentation {
	global String accountId;
	global String accountName;
	global String applicationName;
	global String applicationType;
	global Datetime appliedDate;
	global Datetime approvedDate;
	global String category;
	global String description;
	global String externalProject;
	global String id;
	global Boolean isSubmittedByThirdParty;
	global String locationId;
	global String parentApplicationId;
	global String programId;
	global String rejectionReason;
	global String status;
	global String submittedByAccountId;
	global String submittedByContactId;
	global Boolean wasReturned;
	global IndividualApplicationObjectOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}