global class IndustriesRedeemVoucherInput {
	global String accountId;
	global ConnectApi.ReserveActionResource action;
	global String contactId;
	global String currencyIsoCode;
	global String memberId;
	global String membershipNumber;
	global String programName;
	global Double redemptionAmount;
	global String reservationKey;
	global Double reservedValue;
	global IndustriesRedeemVoucherInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}