global class InsightsOutputRepresentation {
	global String dashboardUrl;
	global String insightSummaryText;
	global String name;
	global List<ConnectApi.InsightValuesOutputRepresentation> values;
	global InsightsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}