global class InsuranceKpiDetailsOutput {
	global String errorMessage;
	global Boolean isPercent;
	global Boolean isSuccess;
	global String metricsCurrencyIsoCode;
	global String metricsName;
	global Double metricsValue;
	global InsuranceKpiDetailsOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}