global class IntegrationProcedureCacheOutputRepresentation {
	global String error;
	global List<ConnectApi.IntegrationProcedureCacheResponse> responseList;
	global Boolean status;
	global IntegrationProcedureCacheOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}