global class IntegrationProcedureServiceRunOptionsRepresentation {
	global Boolean chainable;
	global Boolean ignoreCache;
	global Boolean ignoreMetadataPermissions;
	global Boolean isDebug;
	global Boolean queueableChainable;
	global Boolean resetCache;
	global Boolean shouldSendLegacyResponse;
	global Boolean useFuture;
	global Boolean useQueueable;
	global Boolean useQueueableApexRemoting;
	global Boolean vlcApexResponse;
	global String vlcIPData;
	global String vlcMessage;
	global String vlcStatus;
	global IntegrationProcedureServiceRunOptionsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}