global class IntegrationProcedureCacheInputRepresentation {
	global List<String> cacheKeys;
	global ConnectApi.CacheStorageType cacheStorageType;
	global List<ConnectApi.IntegrationProcedureCacheInputData> iPInput;
	global IntegrationProcedureCacheInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}