global class InventoryProductCheckAvailabilityOutputRepresentation {
	global Boolean available;
	global ConnectApi.InventoryOutputRepresentation inventory;
	global String product2Id;
	global InventoryProductCheckAvailabilityOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}