global class InventoryLevelsOutputRepresentation {
	global List<ConnectApi.LocationGroupLevelsOutputRepresentation> locationGroups;
	global List<ConnectApi.LocationLevelsOutputRepresentation> locations;
	global List<ConnectApi.InventoryProductOutputRepresentation> totalInventory;
	global InventoryLevelsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}