global class InventoryCheckAvailabilityInputRepresentation {
	global String inventoryDimension;
	global List<ConnectApi.LocationGroupCheckAvailabilityInputRepresentation> locationGroups;
	global List<ConnectApi.LocationCheckAvailabilityInputRepresentation> locations;
	global InventoryCheckAvailabilityInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}