global class InventoryCheckAvailabilityOutputRepresentation {
	global List<ConnectApi.LocationGroupCheckAvailabilityOutputRepresentation> locationGroups;
	global List<ConnectApi.LocationCheckAvailabilityOutputRepresentation> locations;
	global InventoryCheckAvailabilityOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}