global class InvocableInternalTestNestedOutputRepresentation {
	global String id;
	global List<ConnectApi.InvocableInternalTestOutputRepresentation> invocableInternalTestOutputRepresentationList;
	global String name;
	global InvocableInternalTestNestedOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}