global class IssuePolicyInputRepresentation {
	global List<ConnectApi.AdditionalFieldsMapValue> additionalFields;
	global String contextId;
	global ConnectApi.InsurancePolicyInputRepresentation insurancePolicy;
	global ConnectApi.InsurancePolicyTransactionInputRepresentation transactionRecord;
	global IssuePolicyInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}