global class ItempricePrice {
	global ConnectApi.TaxIncludedOrDutyFreeAmountInputRepresentation dutyFreeAmount;
	global ConnectApi.TaxIncludedOrDutyFreeAmountInputRepresentation taxIncludedAmount;
	global Double taxRate;
	global String type;
	global itempricePrice() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}