global class KnowledgeArticleVersion {
	global String articleType;
	global String id;
	global String knowledgeArticleId;
	global Datetime lastPublishedDate;
	global String summary;
	global String title;
	global String urlName;
	global KnowledgeArticleVersion() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}