global class LearningFulfiller {
	global Boolean isRepeat;
	global ConnectApi.LearningOutput learning;
	global ConnectApi.LearningOutcomeItemOutput learningOutcomeItem;
	global ConnectApi.LearningStatus learningStatus;
	global List<ConnectApi.LearningStatus> otherLearningStatus;
	global LearningFulfiller() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}