global class LearningOutcomeItemOutput {
	global String category;
	global Double duration;
	global String durationUnit;
	global Boolean isPrimary;
	global String learningAchievementId;
	global String learningId;
	global String learningOutcomeId;
	global Double minimumNumericGrade;
	global String name;
	global LearningOutcomeItemOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}