global class LearningCourse {
	global String courseLevelDescription;
	global String courseNumber;
	global String fieldOfStudy;
	global Map<String,ConnectApi.EduObjectWrapper> learningCourseCustomFields;
	global String learningCourseId;
	global String subjectAbbreviation;
	global LearningCourse() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}