global class LearningOutput {
	global String academicLevel;
	global Boolean active;
	global Datetime activeFromDate;
	global Datetime activeToDate;
	global String cipCode;
	global String description;
	global Double duration;
	global String durationUnit;
	global String learningId;
	global String name;
	global String provider;
	global String type;
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}