global class LearningCourseOutput {
	global String courseLevelDescription;
	global String courseNumber;
	global String fieldOfStudy;
	global Map<String,Object> learningCourseCustomFields;
	global String learningCourseId;
	global String subjectAbbreviation;
	global LearningCourseOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}