global class LinkMetadata {
	global String description;
	global String frameSource;
	global Integer height;
	global String originalUrl;
	global String providerUrl;
	global ConnectApi.LinkMetadataSource source;
	global String thumbnailUrl;
	global String title;
	global ConnectApi.LinkMetadataType type;
	global String url;
	global Integer width;
	global LinkMetadata() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}