global class LocationGroupCheckAvailabilityInputRepresentation {
	global Boolean includeInventoryLevel;
	global String locationGroupId;
	global List<ConnectApi.ProductCheckAvailabilityInputRepresentation> products;
	global LocationGroupCheckAvailabilityInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}