global class LocationGroupCheckAvailabilityOutputRepresentation {
	global List<ConnectApi.InventoryProductCheckAvailabilityOutputRepresentation> inventoryProducts;
	global String locationGroupId;
	global LocationGroupCheckAvailabilityOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}