global class LocationCapacityOutputRepresentation {
	global Integer assigned;
	global Integer capacity;
	global ConnectApi.ErrorResponse error;
	global Integer heldCapacity;
	global String locationId;
	global LocationCapacityOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}