global class LocationCheckAvailabilityOutputRepresentation {
	global List<ConnectApi.InventoryProductCheckAvailabilityOutputRepresentation> inventoryProducts;
	global String locationId;
	global LocationCheckAvailabilityOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}