global class LookupTableParametersOutputRepresentation {
	global String lookupTableId;
	global List<ConnectApi.ParametersOutputRepresentation> parameters;
	global String pricingComponentType;
	global String processType;
	global LookupTableParametersOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}