global class LoyaltyProgramMemberRepresentation {
	global List<ConnectApi.ClubMemberRepresentation> clubMembers;
	global String loyaltyMembershipId;
	global String loyaltyMembershipNumber;
	global LoyaltyProgramMemberRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}