global class ManagedContentSpace {
	global String apiName;
	global String createdBy;
	global Datetime createdDate;
	global String defaultLanguage;
	global String description;
	global String fullyQualifiedName;
	global String id;
	global Boolean isEnhancedSpace;
	global String lastModifiedBy;
	global Datetime lastModifiedDate;
	global String name;
	global String rootFolderId;
	global ConnectApi.ManagedContentSpaceBaseType spaceType;
	global ManagedContentSpace() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}