global class ManagedContentProviderCollection {
	global String currentPageUrl;
	global String nextPageUrl;
	global List<ConnectApi.ManagedContentProvider> providers;
	global Integer total;
	global ManagedContentProviderCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}