global class ManagedContentDocumentInput {
	global String apiName;
	global ConnectApi.ManagedContentBodyInput contentBody;
	global String contentKey;
	global String contentSpaceOrFolderId;
	global String contentType;
	global String externalId;
	global String title;
	global String urlName;
	global ManagedContentDocumentInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}