global class ManagedContentDeliveryChannelSummaryRepresentation {
	global String domainUrl;
	global String id;
	global String name;
	global String resourceUrl;
	global ConnectApi.ManagedContentChannelTargetSummary target;
	global ConnectApi.ConnectManagedContentChannelType type;
	global ManagedContentDeliveryChannelSummaryRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}