global class ManagedContentMediaSourceNodeValue {
	global String fileName;
	global Boolean isExternal;
	global ConnectApi.ConnectManagedContentMediaType mediaType;
	global String mimeType;
	global String referenceId;
	global String resourceUrl;
	global String unauthenticatedUrl;
	global String url;
	global ManagedContentMediaSourceNodeValue() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}