global class ManagedContentChannelCreateRepresentation {
	global Long cacheControlMaxAge;
	global String domain;
	global Boolean isCrossApi;
	global Boolean isDedicatedContentDelivery;
	global Boolean isDomainLocked;
	global Boolean isSearchable;
	global Long mediaCacheControlMaxAge;
	global String name;
	global String targetId;
	global ConnectApi.ConnectManagedContentChannelType type;
	global ManagedContentChannelCreateRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}