global class ManagedContentCollectionMetadataAuthoring {
	global String collectionKey;
	global Map<String,Object> collectionMetadata;
	global ConnectApi.ManagedContentTypeSummary collectionType;
	global String id;
	global String language;
	global Map<String,Object> schema;
	global String spaceId;
	global String title;
	global String urlName;
	global ManagedContentCollectionMetadataAuthoring() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}