global class ManagedContentMediaNodeValue {
	global String altText;
	global String altUrl;
	global String contentKey;
	global String fileName;
	global ConnectApi.ConnectManagedContentMediaType mediaType;
	global String mimeType;
	global String resourceUrl;
	global String thumbnailUrl;
	global String title;
	global String unauthenticatedUrl;
	global String url;
	global ManagedContentMediaNodeValue() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}