global class ManagedContentVersionInput {
	global ConnectApi.ManagedContentBodyInput body;
	global String externalId;
	global String managedContentId;
	global String spaceFolderId;
	global String title;
	global String type;
	global String urlName;
	global ManagedContentVersionInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}