global class ManagedContentCollectionItems {
	global ConnectApi.ManagedContentChannelSummary channelInfo;
	global ConnectApi.ManagedContentDeliveryChannelSummaryRepresentation channelSummary;
	global String collectionKey;
	global ConnectApi.ManagedContentTypeSummary collectionType;
	global String currentPageUrl;
	global String id;
	global List<ConnectApi.ManagedContentCollectionItem> items;
	global String language;
	global String nextPageUrl;
	global String previousPageUrl;
	global Datetime publishedDate;
	global String title;
	global Integer total;
	global String urlName;
	global ManagedContentCollectionItems() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}