global class ManagedContentDeliveryChannelsRepresentation {
	global List<ConnectApi.ManagedContentDeliveryChannelSummaryRepresentation> channels;
	global String currentPageUrl;
	global String nextPageUrl;
	global String previousPageUrl;
	global Integer totalChannels;
	global ManagedContentDeliveryChannelsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}