global class ManagedContentSpaceChannelRepresentation {
	global ConnectApi.ManagedContentChannelSummary channelSummary;
	global ConnectApi.ManagedContentUserSummary createdBy;
	global Datetime createdDate;
	global ConnectApi.ConnectManagedContentSpaceChannelStatus status;
	global ManagedContentSpaceChannelRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}