global class ManagedContentSpaceChannelsRepresentation {
	global String currentPageUrl;
	global String nextPageUrl;
	global String previousPageUrl;
	global List<ConnectApi.ManagedContentSpaceChannelRepresentation> spaceChannels;
	global Integer totalSpaceChannels;
	global ManagedContentSpaceChannelsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}