global class ManagedContentDeliveryChannelRepresentation {
	global String domain;
	global String domainName;
	global String id;
	global Boolean isDedicatedContentDelivery;
	global Boolean isDomainLocked;
	global Boolean isSearchable;
	global String name;
	global ConnectApi.ConnectManagedContentChannelType type;
	global ManagedContentDeliveryChannelRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}