global class ManagedContentProvider {
	global String icon;
	global String label;
	global String name;
	global String providerId;
	global List<ConnectApi.ManagedContentProviderInstance> providerInstances;
	global String providerLightningComponentId;
	global ConnectApi.ConnectManagedContentPickerMenuItemType type;
	global ManagedContentProvider() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}