global class ManagedContentChannelDetail {
	global String channelId;
	global String channelName;
	global ConnectApi.ConnectManagedContentChannelType channelType;
	global String domain;
	global String domainName;
	global Boolean isChannelSearchable;
	global Boolean isDomainLocked;
	global ManagedContentChannelDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}