global class MbrEngmtAttributeOutputRepresentation {
	global String attributeStatus;
	global String currentValue;
	global String defaultValue;
	global String description;
	global Datetime endDate;
	global String name;
	global Datetime startDate;
	global String targetValue;
	global MbrEngmtAttributeOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}