global class MediaConfiguredDecisionTableOutputRepresentation {
	global String fieldConfigurationDecisionTableAPIName;
	global String fieldConfigurationDecisionTableId;
	global String gridDecisionTableAPIName;
	global String gridDecisionTableId;
	global MediaConfiguredDecisionTableOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}