global class MediaASMCloneOutputRepresentation {
	global List<String> cloneIds;
	global List<ConnectApi.errorOutputRepresentations> errorOutputRepresentations;
	global String id;
	global Boolean success;
	global MediaASMCloneOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}