global class MemberEnrollmentTransactionJournalOutput {
	global Datetime activityDate;
	global String journalSubType;
	global String journalType;
	global String membershipNumber;
	global String programName;
	global ConnectApi.JournalStatusResource status;
	global String transactionJournalId;
	global MemberEnrollmentTransactionJournalOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}