global class MemberTierOutput {
	global Map<String,Object> additionalLoyaltyMemberTierFields;
	global Boolean areTierBenefitsAssigned;
	global String loyaltyMemberTierId;
	global String loyaltyMemberTierName;
	global String tierChangeReason;
	global String tierChangeReasonType;
	global Datetime tierEffectiveDate;
	global Datetime tierExpirationDate;
	global String tierGroupId;
	global String tierGroupName;
	global String tierId;
	global Integer tierSequenceNumber;
	global MemberTierOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}