global class MemberBenefitOutput {
	global String benefitId;
	global String benefitName;
	global String benefitTypeId;
	global String benefitTypeName;
	global String createdRecordId;
	global String createdRecordName;
	global String description;
	global Datetime endDate;
	global Boolean isActive;
	global String memberBenefitStatus;
	global Datetime startDate;
	global MemberBenefitOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}