global class MentionCompletion {
	global String additionalLabel;
	global String description;
	global String name;
	global ConnectApi.OutOfOffice outOfOffice;
	global String photoUrl;
	global String recordId;
	global ConnectApi.UserType userType;
	global MentionCompletion() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}