global class MetadataContentOutputRepresentation {
	global String code;
	global String contentVersionId;
	global Boolean isSuccess;
	global String message;
	global ConnectApi.MetadataContentVersionOutputRepresentation metadataContentVersionInfo;
	global ConnectApi.UserSpecificPermissionOutputRepresentation userSpecificPermissions;
	global MetadataContentOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}