global class MlRetrieverQueryResultDocumentContentRepresentation {
	global String fieldApiKey;
	global String fieldName;
	global String resultFieldApiKey;
	global String sourceObjectApiKey;
	global String sourceObjectName;
	global Object value;
	global MlRetrieverQueryResultDocumentContentRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}