global class MobilePublisherServiceAccountAuthRepresentation {
	global String auth_provider_x509_cert_url;
	global String auth_uri;
	global String client_email;
	global String client_id;
	global String client_x509_cert_url;
	global String private_key;
	global String private_key_id;
	global String project_id;
	global String token_uri;
	global String type;
	global MobilePublisherServiceAccountAuthRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}