global class ModerationFlagItemDetail {
	global String createdBy;
	global Datetime createdDate;
	global String id;
	global ConnectApi.CommunityFlagType moderationType;
	global String note;
	global ConnectApi.CommunityFlagVisibility visibility;
	global ModerationFlagItemDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}