global class NamedCredentialParameterManagedByFeatureCapabilities {
	global Boolean globalNamedPrincipalCredential;
	global Boolean managedFeatureEnabledCallout;
	global Boolean readOnlyNamedCredential;
	global Boolean systemUserNamedCredential;
	global NamedCredentialParameterManagedByFeatureCapabilities() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}