global class NamedCredentialParameter {
	global String id;
	global ConnectApi.NamedCredentialParameterManagedByFeatureCapabilities managedByFeatureCapabilities;
	global String parameterName;
	global ConnectApi.NamedCredentialParameterType parameterType;
	global String parameterValue;
	global NamedCredentialParameter() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}