global class NetworkDataCategory {
	global String categoryGroupName;
	global String categoryName;
	global String categoryOrGroupLabel;
	global List<ConnectApi.NetworkDataCategory> childCategories;
	global String description;
	global String id;
	global String imageUrl;
	global String label;
	global String relativeUrl;
	global NetworkDataCategory() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}