global class NftSettingsOutput {
	global Boolean isMainnet;
	global Boolean isMultisigEnabled;
	global Integer minContractAdminSignatures;
	global Integer minFinanceAdminSignatures;
	global String productVariationPriceField;
	global NftSettingsOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}