global class NotifyAccessResult {
	global String accessKey;
	global String endpoint;
	global String externalUserId;
	global Boolean isModeratorOnCall;
	global String keyId;
	global String region;
	global String sessionToken;
	global NotifyAccessResult() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}