global class NoWrapperRepresentation {
	global Integer id;
	global String name;
	global Map<String,ConnectApi.NoWrapperRepresentation> repMap;
	global List<String> stringList;
	global Map<String,String> stringMap;
	global String tag;
	global NoWrapperRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}