global class NoWrapperInputRepresentation {
	global List<SObject> customListDirect;
	global String name;
	global List<ConnectApi.NoWrapperInputRepresentation> repListDirect;
	global List<String> stringListDirect;
	global Map<String,String> stringMapDirect;
	global String tag;
	global NoWrapperInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}