global class ObjectPermissionOutputRepresentation {
	global Boolean allowCreate;
	global Boolean allowDelete;
	global Boolean allowEdit;
	global Boolean allowRead;
	global Boolean modifyAllRecords;
	global String objectName;
	global Boolean viewAllFields;
	global Boolean viewAllRecords;
	global ObjectPermissionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}