global class OCICreateReservationOutputRepresentation {
	global List<ConnectApi.OCICreateReservationSingleOutputRepresentation> details;
	global List<ConnectApi.OCICreateReservationErrorOutputRepresentation> errors;
	global String expirationTime;
	global String reservationTime;
	global Boolean success;
	global OCICreateReservationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}