global class OCIFulfillReservationErrorOutputRepresentation {
	global ConnectApi.OCIFulfillReservationSingleOutputRepresentation details;
	global String errorCode;
	global String message;
	global OCIFulfillReservationErrorOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}