global class OCIFulfillReservationSingleOutputRepresentation {
	global String actionRequestId;
	global String externalRefId;
	global String locationIdentifier;
	global Double quantity;
	global String stockKeepingUnit;
	global OCIFulfillReservationSingleOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}