global class OCIGetInventoryAvailabilityInputRepresentation {
	global List<String> expand;
	global String locationGroupIdentifier;
	global List<String> locationGroupIdentifiers;
	global List<String> locationIdentifiers;
	global String stockKeepingUnit;
	global List<String> stockKeepingUnits;
	global Boolean useCache;
	global OCIGetInventoryAvailabilityInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}