global class OCIGetInventoryAvailabilityOutputRepresentation {
	global List<ConnectApi.OCILocationGroupAvailabilityOutputRepresentation> locationGroups;
	global List<ConnectApi.OCILocationAvailabilityOutputRepresentation> locations;
	global OCIGetInventoryAvailabilityOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}