global class OCILocationGroupAvailabilityOutputRepresentation {
	global List<ConnectApi.OCIInventoryRecordOutputRepresentation> inventoryRecords;
	global String locationGroupIdentifier;
	global OCILocationGroupAvailabilityOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}