global class OCILocationAvailabilityOutputRepresentation {
	global List<ConnectApi.OCIInventoryRecordOutputRepresentation> inventoryRecords;
	global String locationIdentifier;
	global OCILocationAvailabilityOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}