global class OCIReleaseReservationErrorOutputRepresentation {
	global ConnectApi.OCIReleaseReservationSingleOutputRepresentation details;
	global String errorCode;
	global String message;
	global OCIReleaseReservationErrorOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}