global class OCIReleaseReservationSingleInputRepresentation {
	global String actionRequestId;
	global String externalRefId;
	global String locationGroupIdentifier;
	global String locationIdentifier;
	global Double quantity;
	global String reservationId;
	global String stockKeepingUnit;
	global OCIReleaseReservationSingleInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}