global class OCITransferReservationInputRepresentation {
	global String allOrNothingTransferId;
	global String reservationId;
	global List<ConnectApi.OCITransferReservationSingleInputRepresentation> transferRecords;
	global OCITransferReservationInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}