global class OCITransferReservationSingleInputRepresentation {
	global String actionRequestId;
	global String externalRefId;
	global String fromLocationGroupIdentifier;
	global String fromLocationIdentifier;
	global Boolean ignoreAvailabilityCheck;
	global Double quantity;
	global String reservationId;
	global String stockKeepingUnit;
	global String toLocationGroupIdentifier;
	global String toLocationIdentifier;
	global OCITransferReservationSingleInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}