global class OCITransferReservationErrorOutputRepresentation {
	global ConnectApi.OCITransferReservationSingleOutputRepresentation details;
	global String errorCode;
	global String message;
	global OCITransferReservationErrorOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}