global class OCIUploadInventoryAvailabilityStatusOutputRepresentation {
	global String endTimeUTC;
	global Integer recordsProcessedCount;
	global Integer recordsReadCount;
	global Integer recordsSkippedCount;
	global String startTimeUTC;
	global String status;
	global String uploadId;
	global List<String> validationErrors;
	global String validationStatus;
	global OCIUploadInventoryAvailabilityStatusOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}