global class OCIUpdateReservationSingleOutputRepresentation {
	global Double adjustment;
	global String errorCode;
	global String locationGroupIdentifier;
	global String locationIdentifier;
	global Double quantity;
	global String stockKeepingUnit;
	global OCIUpdateReservationSingleOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}