global class OCIUpdateReservationOutputRepresentation {
	global List<ConnectApi.OCIUpdateReservationSingleOutputRepresentation> details;
	global List<ConnectApi.OCIUpdateReservationErrorOutputRepresentation> errors;
	global String reservationTime;
	global Boolean success;
	global OCIUpdateReservationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}