global class OmniAnalyticsLogDetailRepresentation {
	global String applicationLogDate;
	global String applicationName;
	global String componentId;
	global String componentType;
	global String eventType;
	global String name;
	global String omniAnalyticsLog;
	global OmniAnalyticsLogDetailRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}