global class OmniDesignerDataraptorMappingItemInfoRepresentation {
	global List<ConnectApi.OmniDesignerDataraptorMappingItemInfoDetailRepresentation> mappingItemParams;
	global String omniDataTransformItemId;
	global OmniDesignerDataraptorMappingItemInfoRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}