global class OmniDesignerDataraptorRepresentation {
	global List<ConnectApi.OmniDesignerDataraptorInfoRepresentation> dataraptorInfo;
	global List<ConnectApi.OmniDesignerDataraptorMappingItemInfoRepresentation> mappingInfo;
	global String name;
	global String omniDataTransformationId;
	global OmniDesignerDataraptorRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}