global class OmniAnalyticsTrackingExternalDefRepresentation {
	global String description;
	global String identifier;
	global String isActive;
	global String name;
	global String omniExtTrackingDefKey;
	global String trackingFrameworkInformation;
	global String trackingServiceProvider;
	global OmniAnalyticsTrackingExternalDefRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}