global class OmniProcessOutputRepresentation {
	global String createdById;
	global String createdByName;
	global String createdDate;
	global String customHtmlTemplates;
	global String customJavaScript;
	global String description;
	global String id;
	global Boolean isActive;
	global Boolean isIntegrationProcedure;
	global Boolean isMetadataCacheDisabled;
	global String isOmniScriptEmbeddable;
	global Boolean isTestProcedure;
	global Boolean isWebCompEnabled;
	global String language;
	global String lastModifiedById;
	global String lastModifiedByName;
	global String lastModifiedDate;
	global String name;
	global String propertySetConfig;
	global String responseCacheType;
	global String subType;
	global String type;
	global String versionNumber;
	global OmniProcessOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}