global class OmniAnalyticsMetadataRepresentation {
	global List<ConnectApi.OmniAnalyticsSettingRepresentation> omniAnalyticsSettings;
	global List<ConnectApi.OmniAnalyticsTrackingComponentRepresentation> trackingComponents;
	global List<ConnectApi.OmniAnalyticsTrackingExternalDefRepresentation> trackingExternalDefintions;
	global List<ConnectApi.OmniAnalyticsTrackingExternalEventDefRepresentation> trackingExternalEventDefintions;
	global List<ConnectApi.OmniAnalyticsTrackingGroupRepresentation> trackingGroups;
	global OmniAnalyticsMetadataRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}