global class OmniAnalyticsTrackingComponentRepresentation {
	global String componentIdentifier;
	global String componentType;
	global String componentVersion;
	global String identifier;
	global String name;
	global String omniTrackingCompGroupId;
	global String omniTrackingComponentDefKey;
	global OmniAnalyticsTrackingComponentRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}