global class OmniAnalyticsTrackingExternalEventDefRepresentation {
	global String componentType;
	global String description;
	global String identifier;
	global String inclusionRule;
	global String name;
	global String omniExtTrackingDefId;
	global String omniExtTrackingEventDefKey;
	global String payloadTemplate;
	global OmniAnalyticsTrackingExternalEventDefRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}