global class OmniAnalyticsTrackingGroupRepresentation {
	global String description;
	global String endDate;
	global String groupType;
	global String identifier;
	global String isActive;
	global String maxAgeInDays;
	global String name;
	global String omniExtTrackingDefId;
	global String omniTrackingGroupKey;
	global String startDate;
	global OmniAnalyticsTrackingGroupRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}