global class OmniDesignerDataraptorUpsertInputRepresentation {
	global String expectedInputJson;
	global String inputType;
	global String name;
	global String outputType;
	global String sourceObject;
	global String type;
	global String xmlOutputTagsOrder;
	global OmniDesignerDataraptorUpsertInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}