global class OpenAPIProductDetailsOutputRepresentation {
	global String id;
	global List<ConnectApi.OpenAPICharacteristicOutputRepresentation> productCharacteristic;
	global ConnectApi.ProductOfferingOutputRepresentation productSpecification;
	global String type;
	global OpenAPIProductDetailsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}