global class OrderItemSummaryAdjustmentAggregates {
	global Boolean available;
	global ConnectApi.OrderSummaryAdjustmentAggregatesStatus status;
	global String totalLinePromotionAmount;
	global String totalPromotionDistAmount;
	global OrderItemSummaryAdjustmentAggregates() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}