global class OrderDeliveryGroupSummaryCollection {
	global String currentPageToken;
	global String currentPageUrl;
	global String nextPageToken;
	global String nextPageUrl;
	global List<ConnectApi.OrderDeliveryGroupSummary> orderDeliveryGroups;
	global String previousPageToken;
	global String previousPageUrl;
	global OrderDeliveryGroupSummaryCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}