global class OrderSummaryAdjustment {
	global String amount;
	global String basisReferenceDisplayName;
	global String currencyIsoCode;
	global String displayName;
	global ConnectApi.OrderSummaryAdjustmentTargetType targetType;
	global String type;
	global OrderSummaryAdjustment() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}