global class OrderSummaryInputRepresentation {
	global String businessModel;
	global String externalReferenceIdentifier;
	global String name;
	global String orderId;
	global String orderLifeCycleType;
	global String sourceProcess;
	global String status;
	global OrderSummaryInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}