global class OrderToCartFailedProduct {
	global String errorCode;
	global String errorMessage;
	global ConnectApi.ProductMedia media;
	global String productId;
	global String productName;
	global String productSKU;
	global OrderToCartFailedProduct() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}