global class OrderSummaryAdjustmentAggregates {
	global Boolean available;
	global ConnectApi.OrderSummaryAdjustmentAggregatesStatus status;
	global String totalDeliveryPromotionDistAmount;
	global String totalDeliveryPromotionLineAmount;
	global String totalDeliveryPromotionTotalAmount;
	global String totalProductPromotionDistAmount;
	global String totalProductPromotionLineAmount;
	global String totalProductPromotionTotalAmount;
	global OrderSummaryAdjustmentAggregates() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}