global class OrderShipment {
	global Datetime expectedDeliveryDate;
	global Map<String,ConnectApi.RecordField> fields;
	global String orderSummaryId;
	global String shipmentId;
	global String shipmentNumber;
	global String status;
	global OrderShipment() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}