global class PardotBusinessUnitMetadataOutput {
	global String apiVersion;
	global String entityTypePlural;
	global Boolean isSuccess;
	global String json;
	global String orgId;
	global String params;
	global String pardotTenantId;
	global String timestamp;
	global String traceId;
	global PardotBusinessUnitMetadataOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}