global class PartyProfileRiskInput {
	global List<ConnectApi.CustomFieldsInputRepresentation> customFields;
	global Boolean isRiskOverridden;
	global String name;
	global String overriddenRiskCategory;
	global String recordTypeId;
	global String riskCategory;
	global String riskOverriddenById;
	global String riskOverrideReason;
	global String type;
	global partyProfileRiskInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}