global class PartyFinancialAssetLienResultRepresentation {
	global String createdById;
	global Datetime createdDate;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String id;
	global Boolean isActive;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global Double lienAmount;
	global String lienHolder;
	global String maturityDate;
	global String name;
	global String partyFinancialAssetId;
	global String recordTypeId;
	global PartyFinancialAssetLienResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}