global class PartyFinancialAssetAdditionalOwnerResultRepresentation {
	global String accountId;
	global String applicantId;
	global String contactId;
	global String createdById;
	global Datetime createdDate;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String id;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String name;
	global Double ownershipSharePercent;
	global String partyFinancialAssetId;
	global String partyProfileId;
	global String recordTypeId;
	global String sourceSystemIdentifier;
	global PartyFinancialAssetAdditionalOwnerResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}