global class PartyProfileRiskResultRepresentation {
	global String createdById;
	global Datetime createdDate;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String id;
	global Boolean isRiskOverridden;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String name;
	global String overriddenRiskCategory;
	global String ownerId;
	global String partyProfileId;
	global String recordTypeId;
	global String riskCategory;
	global String riskOverriddenById;
	global String riskOverrideReason;
	global String type;
	global PartyProfileRiskResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}