global class PartyIdentityVerificationStepInput {
	global List<ConnectApi.CustomFieldsInputRepresentation> customFields;
	global String identityVerificationArtifactId;
	global String name;
	global String recordTypeId;
	global String reportUrl;
	global String status;
	global String type;
	global String verificationDecision;
	global partyIdentityVerificationStepInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}