global class PartyIncomeResultRepresentation {
	global String applicationFormId;
	global String createdById;
	global Datetime createdDate;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String id;
	global Double incomeAmount;
	global String incomeAsOfDate;
	global String incomeFrequency;
	global String incomeSourceId;
	global String incomeType;
	global Boolean isReadOnly;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String name;
	global String ownerId;
	global String partyId;
	global String partyProfileId;
	global String recordTypeId;
	global String usageType;
	global String verificationStatus;
	global PartyIncomeResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}