global class PartyExpenseResultRepresentation {
	global String applicationFormId;
	global String createdById;
	global Datetime createdDate;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String expenseAsOfDate;
	global String id;
	global Boolean isReadOnly;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String name;
	global String ownerId;
	global String partyFinancialLiabilityId;
	global String partyId;
	global String partyProfileId;
	global String recordTypeId;
	global String recurrenceInterval;
	global Double totalAmount;
	global String type;
	global String usageType;
	global String verificationStatus;
	global PartyExpenseResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}