global class PartyFinancialAssetAdditionalOwnerInput {
	global String accountId;
	global String applicantId;
	global String contactId;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsInputRepresentation> customFields;
	global Double ownershipSharePercent;
	global String partyProfileId;
	global String recordTypeId;
	global String sourceSystemIdentifier;
	global partyFinancialAssetAdditionalOwnerInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}