global class PartyFinancialAssetLien {
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsInputRepresentation> customFields;
	global Boolean isActive;
	global Double lienAmount;
	global String lienHolder;
	global String maturityDate;
	global String recordTypeId;
	global partyFinancialAssetLien() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}