global class PartyCreditProfileResultRepresentation {
	global String createdById;
	global Datetime createdDate;
	global String creditBureauName;
	global String creditPrflReportIdentifier;
	global Integer creditScore;
	global Datetime creditScoreDate;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String id;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String name;
	global String ownerId;
	global String partyProfileId;
	global String recordTypeId;
	global String referenceObjectId;
	global PartyCreditProfileResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}