global class PartyProfileAddressResultRepresentation {
	global String addressType;
	global String city;
	global String country;
	global String countryCode;
	global String createdById;
	global Datetime createdDate;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global String geocodeAccuracy;
	global String id;
	global Boolean isPrimaryAddress;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global Double latitude;
	global Double longitude;
	global String name;
	global String ownerId;
	global String postalCode;
	global String recordTypeId;
	global String state;
	global String stateCode;
	global String street;
	global String validityEndDate;
	global String validityStartDate;
	global PartyProfileAddressResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}