global class PaymentInitiationSourceInputRepresentation {
	global ConnectApi.Application application;
	global String channel;
	global Map<String,String> customFields;
	global String process;
	global Map<String,String> standardReferences;
	global PaymentInitiationSourceInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}