global class PaymentInstrumentDetails {
	global String accountHolderName;
	global String bankAccountHolderType;
	global String bankAccountNumber;
	global String bankAccountType;
	global String bankCode;
	global String bankName;
	global String cardBrand;
	global String digitalWalletProvider;
	global String expiryMonth;
	global String expiryYear;
	global String gatewayName;
	global String gatewayReference;
	global String last4;
	global String processorName;
	global String processorPaymentReference;
	global String type;
	global PaymentInstrumentDetails() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}