global class PaymentMethodDetails {
	global ConnectApi.AlternativePaymentMethodOutput alternativePaymentMethod;
	global ConnectApi.CardPaymentMethodOutput cardPaymentMethod;
	global ConnectApi.DigitalWalletOutput digitalWallet;
	global PaymentMethodDetails() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}