global class PersnlAttributeRepresentation {
	global String attributeName;
	global String attributeValue;
	global PersnlAttributeRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global String getAttributeName() { }
	global String getAttributeValue() { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global void setAttributeName(String value) { }
	global void setAttributeValue(String value) { }
	global String toString() { }

}