global class PersnlFieldRepresentation {
	global String fieldName;
	global String fieldValue;
	global PersnlFieldRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global String getFieldName() { }
	global String getFieldValue() { }
	global Integer hashCode() { }
	global void setFieldName(String value) { }
	global void setFieldValue(String value) { }
	global String toString() { }

}