global class PersnlRecommendationsOutputRepresentation {
	global List<ConnectApi.PersnlFieldRepresentation> additionalFields;
	global List<String> additionalProperties;
	global String personalizationContentId;
	global PersnlRecommendationsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global List<ConnectApi.PersnlFieldRepresentation> getAdditionalFields() { }
	global List<String> getAdditionalProperties() { }
	global Double getBuildVersion() { }
	global String getPersonalizationContentId() { }
	global Integer hashCode() { }
	global void setAdditionalFields(List<ConnectApi.PersnlFieldRepresentation> value) { }
	global void setAdditionalProperties(List<String> value) { }
	global void setPersonalizationContentId(String value) { }
	global String toString() { }

}