global class PersonEmploymentResultRepresentation {
	global String createdById;
	global Datetime createdDate;
	global String currencyIsoCode;
	global List<ConnectApi.CustomFieldsResultRepresentation> customFields;
	global ConnectApi.AddressResultRepresentation employerAddress;
	global String employerPhone;
	global String employmentStatus;
	global String employmentType;
	global String endDate;
	global Double hourlyWage;
	global String id;
	global String lastModifiedById;
	global Datetime lastModifiedDate;
	global String name;
	global String occupation;
	global String ownerId;
	global String position;
	global String recordTypeId;
	global String relatedPersonId;
	global String startDate;
	global Integer weeklyHourCount;
	global String workerType;
	global PersonEmploymentResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}