global class PersnlDiagnosticsRepresentation {
	global String diagnosticsCode;
	global String diagnosticsDescription;
	global PersnlDiagnosticsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global String getDiagnosticsCode() { }
	global String getDiagnosticsDescription() { }
	global Integer hashCode() { }
	global void setDiagnosticsCode(String value) { }
	global void setDiagnosticsDescription(String value) { }
	global String toString() { }

}