global class Photo {
	global String fullEmailPhotoUrl;
	global String largePhotoUrl;
	global String mediumPhotoUrl;
	global String photoVersionId;
	global String smallPhotoUrl;
	global String standardEmailPhotoUrl;
	global String url;
	global Photo() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}