global class PlaceSalesTransactionOutputRepresentation {
	global ConnectApi.ContextDetails contextDetails;
	global List<ConnectApi.PlaceSalesTransactionErrorResponse> errorResponse;
	global Boolean isSuccess;
	global String salesTransactionId;
	global String statusUrl;
	global String trackerId;
	global PlaceSalesTransactionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}