global class PlatformActionGroup {
	global ConnectApi.PlatformActionGroupCategory category;
	global String id;
	global Datetime modifiedDate;
	global List<ConnectApi.PlatformAction> platformActions;
	global String url;
	global PlatformActionGroup() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}