global class PreviewBenefitSessionInputRepresentation {
	global String benefitScheduleName;
	global Datetime firstSessionEndDate;
	global Datetime firstSessionStartDate;
	global String mode;
	global Integer noOfSessions;
	global Integer scheduleDays;
	global Datetime scheduleEndDate;
	global String scheduleFrequency;
	global Integer totalRecurrencesCount;
	global PreviewBenefitSessionInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}