global class PricingRecipeOutputRepresentation {
	global Boolean active;
	global String businessVertical;
	global String createdBy;
	global Datetime createdOn;
	global List<ConnectApi.PricingRecipeLookUpTableResponseRepresentation> decisionTables;
	global String developerName;
	global String id;
	global Boolean isSuccess;
	global String name;
	global String procedureCreatedBy;
	global Datetime procedureCreatedOn;
	global String procedureId;
	global String procedureName;
	global PricingRecipeOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}