global class PricingActionParamValuesOutputRepresentation {
	global String contextDefinition;
	global String contextMapping;
	global String developerName;
	global Datetime effectiveFrom;
	global Datetime effectiveTo;
	global String id;
	global String objectName;
	global String pricingProcedure;
	global PricingActionParamValuesOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}