global class PricingApiExecutionOutputRepresentation {
	global String apiEndpoint;
	global String apiType;
	global String createdDate;
	global String executionId;
	global String referenceId;
	global String status;
	global PricingApiExecutionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}