global class PricingProcessExecutionOutputRepresentation {
	global String executionId;
	global String executionType;
	global String executionTypeId;
	global String message;
	global String status;
	global PricingProcessExecutionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}