global class PricingApexClassOutputRepresentation {
	global List<ConnectApi.ApexClassRepresentation> apexClassList;
	global ConnectApi.PricingErrorResponse error;
	global Boolean isSuccess;
	global PricingApexClassOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}