global class PricingResultLineItem {
	global ConnectApi.ErrorResponse error;
	global String listPrice;
	global String lowestUnitPrice;
	global String pricebookEntryId;
	global String productId;
	global Boolean success;
	global String unitPrice;
	global PricingResultLineItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}