global class ProcedurePlanEvaluationResponseRepresentation {
	global String errorMessage;
	global Boolean isSuccess;
	global String procedurePlanDefinitionName;
	global List<ConnectApi.ProcedurePlanEvaluationRepresentation> procedurePlanEvaluations;
	global ProcedurePlanEvaluationResponseRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}