global class ProcessDetailOutputRepresentation {
	global String apexClassName;
	global String dataSourceType;
	global String developerName;
	global String displayRecordFieldName;
	global Boolean isRetryAllowedAfterLimit;
	global String label;
	global String linkedVerificationProcessDetailName;
	global Integer optionalVerifierCount;
	global Integer retryLimit;
	global String searchObjectName;
	global String searchResultFilter;
	global String searchResultSortOrder;
	global String searchResultUniqueIdField;
	global Integer searchSequenceNo;
	global String searchType;
	global ConnectApi.VerificationProcessFieldListOutputRepresentation verificationProcessFieldList;
	global ProcessDetailOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}