global class ProcedureConfigOutputRepresentation {
	global ConnectApi.PricingErrorResponse error;
	global String executionId;
	global String procedureName;
	global Integer sequence;
	global Boolean success;
	global String usageType;
	global ProcedureConfigOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}