global class ProcedurePlanDefinitionsOutputRepresentation {
	global ConnectApi.ProcedurePlanGenericErrorRepresentation error;
	global Boolean isSuccess;
	global List<ConnectApi.ProcedurePlanDefinitionOutputRepresentation> procedurePlanDefinitions;
	global ProcedurePlanDefinitionsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}