global class ProcedurePlanOptionOutputRepresentation {
	global String apexClass;
	global String apexClassName;
	global String ctxDefinitionOutputField;
	global String ctxMappingOutputField;
	global String decisionTable;
	global ConnectApi.ProcedurePlanGenericErrorRepresentation error;
	global String expressionSetApiName;
	global String expressionSetDefinition;
	global String expressionSetLabel;
	global String expressionSetOutputField;
	global Boolean isSuccess;
	global String logic;
	global String primaryObject;
	global Integer priority;
	global List<ConnectApi.ProcedurePlanCriterionOutputRepresentation> procedurePlanCriterion;
	global String readContextMapping;
	global String recordId;
	global String saveContextMapping;
	global ProcedurePlanOptionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}