global class ProcedurePlanEvaluationRepresentation {
	global String errorMessage;
	global String id;
	global Boolean isSuccess;
	global String primaryObject;
	global ConnectApi.ProcedurePlanEvaluationResultRepresentation result;
	global ProcedurePlanEvaluationRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}