global class ProcedurePlanCriterionOutputRepresentation {
	global Integer conditionSequence;
	global String dataType;
	global String decisionTableParameter;
	global ConnectApi.ProcedurePlanGenericErrorRepresentation error;
	global String fieldObject;
	global String fieldPath;
	global Boolean isSuccess;
	global String literalValue;
	global String operator;
	global String procedurePlanDefnVariable;
	global String recordId;
	global ProcedurePlanCriterionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}