global class ProcedurePlanEvaluationResultRepresentation {
	global String contextDefinition;
	global List<ConnectApi.ProcedurePlanSectionEvaluationRuntimeRepresentation> procedurePlanSections;
	global String readContextMapping;
	global String saveContextMapping;
	global ProcedurePlanEvaluationResultRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}