global class ProductVariationAttributeOutputRepresentation {
	global String apiName;
	global String label;
	global List<ConnectApi.ProductVariationAttributeValueOutputRepresentation> variationAttributeValues;
	global ProductVariationAttributeOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}