global class ProductVariantAttributeSetOutputRepresentation {
	global Map<String,ConnectApi.ProductVariantAttributeValueOutputRepresentation> attributes;
	global String description;
	global String developerName;
	global String id;
	global String label;
	global ProductVariantAttributeSetOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}