global class ProductCategoryDetail {
	global ConnectApi.ProductCategoryMedia bannerImage;
	global Map<String,String> fields;
	global String id;
	global List<ConnectApi.ProductCategoryMediaGroup> mediaGroups;
	global ConnectApi.ProductCategoryMedia tileImage;
	global String urlName;
	global ProductCategoryDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}