global class ProductAttributeSetInfo {
	global Map<String,ConnectApi.ProductAttributeInfo> attributeInfo;
	global String description;
	global String developerName;
	global String id;
	global String masterLabel;
	global Integer sequence;
	global ProductAttributeSetInfo() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}