global class ProductPriceEntry {
	global ConnectApi.ErrorResponse error;
	global String listPrice;
	global String lowestUnitPrice;
	global ConnectApi.PriceAdjustmentSchedule priceAdjustment;
	global String pricebookEntryId;
	global String productSellingModelId;
	global Boolean success;
	global String unitPrice;
	global ProductPriceEntry() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}