global class ProductAttributeSummary {
	global String apiName;
	global String label;
	global Integer sequence;
	global String value;
	global ProductAttributeSummary() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global String getApiName() { }
	global Double getBuildVersion() { }
	global String getLabel() { }
	global Integer getSequence() { }
	global String getValue() { }
	global Integer hashCode() { }
	global void setApiName(String value) { }
	global void setLabel(String value) { }
	global void setSequence(Integer value) { }
	global void setValue(String value) { }
	global String toString() { }

}