global class ProductSearchGroupingInput {
	global ConnectApi.CommerceSearchGroupingOption groupingOption;
	global ConnectApi.CommerceSearchTopProductType topProductType;
	global ProductSearchGroupingInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global ConnectApi.CommerceSearchGroupingOption getGroupingOption() { }
	global ConnectApi.CommerceSearchTopProductType getTopProductType() { }
	global Integer hashCode() { }
	global void setGroupingOption(ConnectApi.CommerceSearchGroupingOption value) { }
	global void setTopProductType(ConnectApi.CommerceSearchTopProductType value) { }
	global String toString() { }

}