global class ProductCategoryMediaGroup {
	global String developerName;
	global String id;
	global List<ConnectApi.ProductCategoryMedia> mediaItems;
	global String name;
	global ConnectApi.ProductMediaUsageType usageType;
	global ProductCategoryMediaGroup() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}