global class ProductSearchProductOutputRepresentation {
	global String description;
	global ConnectApi.ProductSearchImageOutputRepresentation image;
	global String name;
	global String productClass;
	global String stockKeepingUnit;
	global List<ConnectApi.ProductVariationAttributeOutputRepresentation> variationAttributeSet;
	global ProductSearchProductOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}