global class ProductOverviewCollection {
	global List<ConnectApi.ProductOverview> products;
	global Integer total;
	global ProductOverviewCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global List<ConnectApi.ProductOverview> getProducts() { }
	global Integer getTotal() { }
	global Integer hashCode() { }
	global void setProducts(List<ConnectApi.ProductOverview> value) { }
	global void setTotal(Integer value) { }
	global String toString() { }

}