global class ProductVariantOutputRepresentation {
	global Double listPrice;
	global Double price;
	global String productId;
	global String stockKeepingUnit;
	global Double unitPrice;
	global Map<String,String> variationValues;
	global ProductVariantOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}