global class ProductSellingModel {
	global String description;
	global String displayName;
	global String id;
	global String name;
	global Integer pricingTerm;
	global ConnectApi.PricingTermUnit pricingTermUnit;
	global ConnectApi.SellingModelType sellingModelType;
	global ConnectApi.SubscriptionTermRule subscriptionTermRule;
	global ProductSellingModel() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}