global class ProductBundleChildOutputRepresentation {
	global String description;
	global String name;
	global String productId;
	global Double quantity;
	global String stockKeepingUnit;
	global ProductBundleChildOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}