global class ProductAttributeCustomFieldInputRepresentation {
	global String apiName;
	global String description;
	global String name;
	global Boolean sortValuesAlphabetically;
	global List<ConnectApi.ProductAttributeCustomFieldPicklistValueRepresentation> values;
	global ConnectApi.ProductAttributeViewType viewType;
	global ProductAttributeCustomFieldInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}