global class ProductSearchFacetOutputRepresentation {
	global String attributeType;
	global String displayName;
	global Integer displayRank;
	global String displayType;
	global String facetType;
	global String nameOrId;
	global List<ConnectApi.ProductSearchFacetValueOutputRepresentation> values;
	global ProductSearchFacetOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}