global class ProgramIndividualApplicationOutputRepresentation {
	global List<ConnectApi.IndividualApplicationStatusOutputRepresentation> aggregateByStatus;
	global List<ConnectApi.IndividualApplicationObjectOutputRepresentation> applications;
	global Integer totalCount;
	global ProgramIndividualApplicationOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}