global class ProgramsRepresentation {
	global String applicationId;
	global String applicationStatus;
	global String businessSector;
	global String defaultImageComment;
	global String defaultImageUrl;
	global Boolean isActive;
	global Boolean isRegulatoryProgram;
	global String name;
	global String programDeliveryType;
	global String programId;
	global String programManagerId;
	global String programType;
	global String regulatoryProgramName;
	global String shortForm;
	global String summary;
	global ProgramsRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}