global class ProjectedRebateAmountCalc {
	global List<ConnectApi.DetailedProjectedRebateAmountCalc> detailedProjectedRebateAmountCalc;
	global String error;
	global String programRebateTypeId;
	global String referenceRecordId;
	global Double totalProjectedRebateAmount;
	global ProjectedRebateAmountCalc() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}