global class PromotionActionOutputRepresentation {
	global ConnectApi.PromotionActionEntityRefOutputRepresentation actionEntityRef;
	global String actionType;
	global String actionValue;
	global String id;
	global String type;
	global PromotionActionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}