global class PromotionCartDeliveryMethodAdjustment {
	global ConnectApi.AdjustmentType adjustmentType;
	global String adjustmentValue;
	global String baseAmount;
	global String priceAdjustmentCauseId;
	global Integer priority;
	global PromotionCartDeliveryMethodAdjustment() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}