global class PromotionCartAdjustmentGroupInput {
	global String adjustmentBasisReference;
	global String adjustmentDescription;
	global ConnectApi.AdjustmentType adjustmentType;
	global String adjustmentValue;
	global String baseAmount;
	global String cartId;
	global String id;
	global String priceAdjustmentCauseId;
	global Integer priority;
	global PromotionCartAdjustmentGroupInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}