global class PromotionCriteriaOutputRepresentation {
	global String criteriaOperator;
	global String criteriaParameter;
	global String criteriaValue;
	global String id;
	global String type;
	global PromotionCriteriaOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}