global class PromotionRecommendations {
	global String loyaltyProgramMemberId;
	global String loyaltyProgramName;
	global String membershipNumber;
	global String personalizationId;
	global Integer recommendationCount;
	global List<ConnectApi.RecommendationDetails> recommendationList;
	global PromotionRecommendations() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}