global class PromotionRecommendationInput {
	global String dataspace;
	global ConnectApi.ChannelInput eligibleChannel;
	global String individualId;
	global String loyaltyProgramId;
	global String loyaltyProgramMemberId;
	global String membershipNumber;
	global String personalizationPoint;
	global PromotionRecommendationInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}