global class PromotionPatternInputRepresentation {
	global List<ConnectApi.ActionInputRepresentation> action;
	global List<ConnectApi.CriteriaGroupInputRepresentation> criteriaGroup;
	global String name;
	global Integer priority;
	global String type;
	global PromotionPatternInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}