global class PromotionManagementInputRepresentation {
	global String description;
	global String name;
	global List<ConnectApi.PromotionPatternInputRepresentation> pattern;
	global ConnectApi.ValidForInputRepresentation validFor;
	global PromotionManagementInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}