global class PromotionCartAdjustmentGroup {
	global String adjustmentBasisReference;
	global String adjustmentDescription;
	global ConnectApi.AdjustmentType adjustmentType;
	global String adjustmentValue;
	global String baseAmount;
	global String cartId;
	global String id;
	global String priceAdjustmentCauseId;
	global Integer priority;
	global PromotionCartAdjustmentGroup() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}