global class PromotionCriteriaGroupOutputRepresentation {
	global List<ConnectApi.PromotionCriteriaOutputRepresentation> criteria;
	global String criteriaLogicalRelationship;
	global String groupName;
	global String id;
	global String type;
	global PromotionCriteriaGroupOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}