global class PromotionCartDeliveryGroupMethod {
	global List<ConnectApi.PromotionCartDeliveryMethodAdjustment> cartDeliveryMethodAdjustments;
	global String cartDeliveryMethodId;
	global String price;
	global String shippingRateId;
	global String totalAdjustmentBaseAmount;
	global String totalNetAmount;
	global PromotionCartDeliveryGroupMethod() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}