global class ProviderInputRepresentation {
	global ConnectApi.ApexClassInputRepresentation apexClass;
	global String configUrl;
	global String description;
	global String epn;
	global String iconUri;
	global Boolean isApplication;
	global String name;
	global String type;
	global ProviderInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}