global class ProviderOutputRepresentation {
	global ConnectApi.ApexClassOutputRepresentation apexClass;
	global String configUrl;
	global String description;
	global List<ConnectApi.EffectiveMappingRepresentation> effectiveMappings;
	global String epn;
	global String iconUri;
	global String id;
	global Boolean isApplication;
	global String name;
	global String type;
	global ProviderOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}