global class QualifiedProductOfferingItemOutputRepresentation {
	global String id;
	global ConnectApi.OpenAPIQueryProductOfferingProductDetails product;
	global ConnectApi.ProductOfferingOutputRepresentation productOffering;
	global String type;
	global QualifiedProductOfferingItemOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}