global class QuerySqlMetadataItem {
	global ConnectApi.QuerySqlMetadataItem innerElement;
	global String name;
	global Boolean nullable;
	global Integer precision;
	global Integer scale;
	global ConnectApi.TypeEnum type;
	global QuerySqlMetadataItem() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}