global class QueryProductOfferingQualificationInputRepresentation {
	global ConnectApi.CategoryInputRepresentation category;
	global Integer productLimit;
	global List<ConnectApi.RelatedPartyOrPartyRoleInputRepresentation> relatedParty;
	global QueryProductOfferingQualificationInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}