global class QuestionAttachment {
	global ConnectApi.Comment bestAnswer;
	global ConnectApi.UserSummary bestAnswerSelectedBy;
	global Boolean canCurrentUserSelectOrRemoveBestAnswer;
	global String questionTitle;
	global QuestionAttachment() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}