global class RADNodeOutputRepresentation {
	global ConnectApi.RADNodeFilterOutputRepresentation filterDetails;
	global ConnectApi.RADJoinFieldOutputRepresentation nextObjectJoinDetails;
	global ConnectApi.RADNodeObjectOutputRepresentation objectDetails;
	global ConnectApi.RADJoinFieldOutputRepresentation previousObjectJoinDetails;
	global Integer sequence;
	global RADNodeOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}