global class RADNodeFilterOutputRepresentation {
	global List<ConnectApi.RADFieldFilterOutputRepresentation> filterConditions;
	global String filterCriteria;
	global String filterCriteriaDescription;
	global RADNodeFilterOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}