global class RADOutputRepresentation {
	global List<ConnectApi.RADNodeOutputRepresentation> aggregationObjects;
	global Boolean canDeleteDefinition;
	global Boolean canEditDefinition;
	global Boolean canManageOnDemand;
	global String description;
	global String displayName;
	global Boolean isOnDemandEnabled;
	global String message;
	global String recordAggregationDefinitionId;
	global String status;
	global String statusCode;
	global RADOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}