global class RankAverageDistanceInputRepresentation {
	global String deliveryCountryCode;
	global String deliveryPostalCode;
	global String distanceUnit;
	global String sortResult;
	global List<ConnectApi.TargetLocationInputRepresentation> targetLocations;
	global RankAverageDistanceInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}