global class RecordRollupDefinitionDetailsOutputRepresentation {
	global String developerName;
	global ConnectApi.RecordRollupDefinitionDetailsErrorOutputRepresentation error;
	global String id;
	global Boolean isOnDemandEnabled;
	global ConnectApi.RecordRollupDefinitionLastUpdatedDetailsOutputRepresentation lastUpdatedDetails;
	global String name;
	global String resolvedAnchorId;
	global String status;
	global RecordRollupDefinitionDetailsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}