global class RecordRollupResultColumnOutputRepresentation {
	global String displayFormatType;
	global String fieldApiName;
	global String fieldLabel;
	global Boolean isRedirectionEnabled;
	global Boolean isSortable;
	global Boolean isTypeName;
	global Integer sequence;
	global String sortByField;
	global RecordRollupResultColumnOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}