global class RecordRollupSyncExecutionOutputRepresentation {
	global ConnectApi.RecordRollupSyncExecutionErrorOutputRepresentation error;
	global String id;
	global String status;
	global RecordRollupSyncExecutionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}