global class RecordAlertActionSingleOutputRepresentation {
	global String actionName;
	global List<ConnectApi.RecordAlertErrorRepresentation> errors;
	global ConnectApi.RecordAlertRepresentation recordAlert;
	global String recordAlertId;
	global String status;
	global RecordAlertActionSingleOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}