global class RecordAggregationDefinitionOutputRepresentation {
	global String apiName;
	global String id;
	global String label;
	global String rollupFromObjectApiName;
	global String rollupFromObjectLabel;
	global RecordAggregationDefinitionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}