global class RecordAggregationAllowedObjectsOutputRepresentation {
	global String message;
	global List<ConnectApi.RecordAggregationAllowedObjectOutputRepresentation> objects;
	global String statusCode;
	global RecordAggregationAllowedObjectsOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}