global class RecordAlertActionOutputRepresentation {
	global ConnectApi.RecordAlertRepresentation recordAlert;
	global List<ConnectApi.RecordAlertErrorRepresentation> recordAlertErrors;
	global String status;
	global RecordAlertActionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}