global class RecordSeoProperties {
	global String canonicalUrl;
	global Map<String,String> complexFields;
	global Map<String,String> fields;
	global Map<String,String> hrefLangUrls;
	global Boolean isSeoIndexed;
	global String objectName;
	global String recordId;
	global String recordName;
	global Map<String,String> translations;
	global RecordSeoProperties() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}