global class RecommendationDefinition {
	global String actionUrl;
	global String actionUrlName;
	global String explanation;
	global String id;
	global String name;
	global ConnectApi.Photo photo;
	global String title;
	global String url;
	global RecommendationDefinition() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}