global class RecordAlertCollectionRepresentation {
	global List<ConnectApi.RecordAlertErrorRepresentation> recordAlertErrors;
	global List<ConnectApi.RecordAlertRepresentation> recordAlerts;
	global String status;
	global RecordAlertCollectionRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}