global class Recommendation {
	global String acceptanceLabel;
	global String actionReference;
	global String description;
	global String externalId;
	global String id;
	global ConnectApi.FileAsset image;
	global String name;
	global String rejectionLabel;
	global String url;
	global Recommendation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}