global class RecordAggregationDefinitionPartialUpdateInputRepresentation {
	global String definitionDescription;
	global String definitionDisplayName;
	global Boolean enableOnDemand;
	global String status;
	global RecordAggregationDefinitionPartialUpdateInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}