global class RecRepresentation {
	global String acceptanceLabel;
	global ConnectApi.ActionInfoOutputRepresentation actionInfo;
	global String businessObjectiveId;
	global String channelId;
	global Datetime createdDate;
	global String description;
	global String domain;
	global String externalName;
	global String externalState;
	global String grouping;
	global String iconName;
	global String id;
	global String imageId;
	global Datetime lastModifiedDate;
	global String name;
	global ConnectApi.ActionInfoOutputRepresentation output;
	global String rejectionLabel;
	global Integer score;
	global String secondaryState;
	global String state;
	global String tertiaryState;
	global RecRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}