global class RedeemVoucherOutput {
	global String currencyIsoCode;
	global Double remainingAmount;
	global String reservationKey;
	global Double reservedValue;
	global ConnectApi.VoucherStatusResource status;
	global RedeemVoucherOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}