global class ReferralAdvocateProfileInput {
	global ConnectApi.ReferralAdvocateContactInput contactDetails;
	global String contactId;
	global String memberId;
	global String membershipNumber;
	global String programId;
	global String programName;
	global String promotionCode;
	global String promotionId;
	global Boolean shouldGetReferralSummary;
	global Boolean shouldGetReferrals;
	global ReferralAdvocateProfileInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}