global class ReferralInfoOutput {
	global String promotionId;
	global String promotionName;
	global String promotionStageName;
	global Datetime referralCreationDate;
	global String referralId;
	global Datetime referralLastModifiedDate;
	global String referredPartyContactId;
	global String referredPartyName;
	global ReferralInfoOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}