global class ReferralStatisticsOutput {
	global Integer extendedRewardIssuedCount;
	global Integer referralCount;
	global Integer referralOnStageFiveCount;
	global Integer referralOnStageFourCount;
	global Integer voucherIssuedCount;
	global ReferralStatisticsOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}