global class ReferralPromotionOutput {
	global Boolean isMemberPromotionEnrollementActive;
	global String memberId;
	global ConnectApi.ReferralStatisticsOutput memberPromotionSummary;
	global String memberReferralCode;
	global String memberReferralUrl;
	global String membershipNumber;
	global String programId;
	global String programName;
	global String promotionCode;
	global String promotionDescription;
	global Datetime promotionEndDate;
	global String promotionId;
	global String promotionImageUrl;
	global String promotionName;
	global String promotionPageUrl;
	global Datetime promotionStartDate;
	global ReferralPromotionOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}