global class ReferralMemberEnrolmentOutput {
	global String contactId;
	global String memberId;
	global String membershipNumber;
	global String programName;
	global String promotionReferralCode;
	global List<ConnectApi.MemberEnrollmentTransactionJournalOutput> transactionJournals;
	global ReferralMemberEnrolmentOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}