global class ReferralAdvocateProfileOutput {
	global List<ConnectApi.ReferralPromotionOutput> eligiblePromotionList;
	global List<ConnectApi.ReferralPromotionOutput> enrolledPromotionList;
	global ConnectApi.ReferralStatisticsOutput programSummary;
	global List<ConnectApi.ReferralInfoOutput> referralSummaryList;
	global ReferralAdvocateProfileOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}