global class RenewInsPolicyAsyncIAInputRep {
	global Boolean executeConfigurationRules;
	global Boolean executeQualificationRules;
	global ConnectApi.FieldSetIDsInputRep fieldSetIds;
	global String flowAPINameWithNamespace;
	global Boolean issueQuote;
	global String jobIdentifier;
	global String policyId;
	global String priceBookId;
	global String productSellingModel;
	global Boolean sameTenure;
	global RenewInsPolicyAsyncIAInputRep() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}