global class ReplyRecommendationsMetric {
	global Integer activeAgentCount;
	global Integer agentsEngaged;
	global Integer conversationsCount;
	global Integer conversationsWithEngagements;
	global Datetime metricsDate;
	global Integer predictionsCount;
	global Integer recommendationsCount;
	global Integer recommendationsEditCount;
	global Integer recommendationsNotHelpfulCount;
	global Integer recommendationsPostCount;
	global ReplyRecommendationsMetric() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}