global class RepositoryFolderItemsCollection {
	global String currentPageUrl;
	global List<ConnectApi.RepositoryFolderItem> items;
	global String nextPageUrl;
	global String previousPageUrl;
	global RepositoryFolderItemsCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}