global class RescheduleSlotChainOutput {
	global String code;
	global Boolean isSuccess;
	global String message;
	global String serviceAppointmentGroupIdBookedSlots;
	global List<String> serviceAppointmentIdsBookedSlots;
	global RescheduleSlotChainOutput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}