global class ResponseSuggestion {
	global String appGenerationId;
	global String generationId;
	global String generativeSourceEntity;
	global String generativeSourceEntityId;
	global String generativeType;
	global String response;
	global Double score;
	global ConnectApi.EinsteinResponseType type;
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}