global class ResponseSuggestions {
	global Boolean isError;
	global String message;
	global String modelStatus;
	global String requestId;
	global List<ConnectApi.ResponseSuggestion> responseSuggestions;
	global ResponseSuggestions() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}