global class ReturnItemsInputRepresentation {
	global List<ConnectApi.ReturnOrderItemDeliveryChargeInputRepresentation> returnOrderItemDeliveryCharges;
	global List<ConnectApi.ReturnOrderItemFeeInputRepresentation> returnOrderItemFees;
	global List<ConnectApi.ReturnOrderItemInputRepresentation> returnOrderItems;
	global ReturnItemsInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}