global class RevenueScheduleInput {
	global String calendarType;
	global String endDate;
	global String opportunityLineItemId;
	global String period;
	global String revenueDistributionType;
	global String splitAmount;
	global String startDate;
	global RevenueScheduleInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}