global class RulesetVersionCreateUpdateErrorDetail {
	global String errorCode;
	global String errorMessage;
	global String fieldName;
	global String path;
	global String resourceType;
	global RulesetVersionCreateUpdateErrorDetail() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}