global class ScopedSearchResults {
	global ConnectApi.ObjectMetadata metadata;
	global ConnectApi.ObjectQueryInfo objectQueryInfo;
	global List<ConnectApi.SearchResult> results;
	global ConnectApi.SearchObject searchObject;
	global ScopedSearchResults() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}