global class SearchResultGroups {
	global Map<String,ConnectApi.ObjectMetadata> metadata;
	global ConnectApi.QueryInfo queryInfo;
	global List<ConnectApi.SearchResultGroup> resultGroups;
	global List<ConnectApi.SearchObject> searchObjects;
	global SearchResultGroups() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}