global class ServiceRequestInput {
	global Object attributes;
	global String businessObjectId;
	global Object context;
	global List<ConnectApi.ServiceAutomationProductAttributeInputRepresentation> productAttributes;
	global String productId;
	global ServiceRequestInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}