global class SmartDataDiscoveryProjectedPredictionsHistoricalDatasetSourceInput {
	global ConnectApi.SmartDataDiscoveryAssetReferenceInput dataset;
	global ConnectApi.SmartDataDiscoveryAssetReferenceInput datasetVersion;
	global SmartDataDiscoveryProjectedPredictionsHistoricalDatasetSourceInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}