global class SmartDataDiscoveryAIModelDiscoverySource {
	global ConnectApi.SmartDataDiscoveryAssetReference story;
	global ConnectApi.SmartDataDiscoveryAssetReference storyHistory;
	global SmartDataDiscoveryAIModelDiscoverySource() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}