global class SmartDataDiscoveryAIModelCoefficientCollection {
	global List<ConnectApi.SmartDataDiscoveryPredictCondition> coefficients;
	global String nextPageUrl;
	global Integer totalSize;
	global String url;
	global SmartDataDiscoveryAIModelCoefficientCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}