global class SmartDataDiscoveryCustomizableField {
	global List<ConnectApi.SmartDataDiscoveryCustomizableFieldDefinition> customDefinitions;
	global ConnectApi.AbstractSmartDataDiscoveryModelField field;
	global SmartDataDiscoveryCustomizableField() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}