global class SmartDataDiscoveryMulticlassClassificationPredictionProperty {
	global ConnectApi.SmartDataDiscoveryClassificationAlgorithmTypeEnum algorithmType;
	global SmartDataDiscoveryMulticlassClassificationPredictionProperty() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}