global class SmartDataDiscoveryAIModelCollection {
	global List<ConnectApi.SmartDataDiscoveryAIModel> models;
	global String nextPageUrl;
	global Integer totalSize;
	global String url;
	global SmartDataDiscoveryAIModelCollection() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}