global class TargetCategoryFilterRepresentation {
	global List<ConnectApi.TargetCategoryRepresentation> categories;
	global String entityId;
	global String entityName;
	global Boolean includeSegments;
	global Boolean includeValues;
	global TargetCategoryFilterRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}