global class TargetSegmentValueOutputRepresentation {
	global String adTargetSegmentValueId;
	global Boolean editable;
	global Boolean included;
	global String name;
	global String targetValues;
	global TargetSegmentValueOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}