global class UmaDataSpacesOutputRepresentation {
	global String dataSpaceApiName;
	global String dataSpaceDescription;
	global String dataSpaceId;
	global String dataSpaceName;
	global String dataSpaceStatus;
	global UmaDataSpacesOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}