global class UpdateAccountOutputRepresentation {
	global Map<String,List<ConnectApi.ResponseResultOutputRepresentation>> additionalResults;
	global String message;
	global String requestId;
	global String status;
	global UpdateAccountOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}