global class UserGroupDetailPage {
	global String currentPageUrl;
	global List<ConnectApi.ChatterGroupDetail> groups;
	global String nextPageUrl;
	global String previousPageUrl;
	global Integer total;
	global UserGroupDetailPage() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}