global class UserSpecificPermissionOutputRepresentation {
	global Map<String,List<String>> availableFields;
	global List<ConnectApi.FieldPermissionOutputRepresentation> fieldPermissions;
	global List<ConnectApi.ObjectPermissionOutputRepresentation> objectPermissions;
	global UserSpecificPermissionOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}