global class UserCapabilities {
	global Boolean canChat;
	global Boolean canDirectMessage;
	global Boolean canEdit;
	global Boolean canFollow;
	global Boolean canViewFeed;
	global Boolean canViewFullProfile;
	global Boolean isModerator;
	global UserCapabilities() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}