global class ValidateTargetSegmentValueOutputRepresentation {
	global List<String> invalidValues;
	global Map<String,ConnectApi.AdTargetSegmentValueOutputRepresentation> validValues;
	global ValidateTargetSegmentValueOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}