global class ValidateTargetingOutputRepresentation {
	global String message;
	global Map<String,ConnectApi.ValidateTargetSegmentValueOutputRepresentation> segmentToValidatedTargetSegmentValue;
	global Boolean success;
	global ValidateTargetingOutputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}