global class VoucherDetails {
	global Datetime effectiveDate;
	global Datetime expirationDate;
	global String transactionJournalId;
	global String voucherCode;
	global String voucherDefinition;
	global String voucherId;
	global String voucherImageUrl;
	global VoucherDetails() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Datetime getEffectiveDate() { }
	global Datetime getExpirationDate() { }
	global String getTransactionJournalId() { }
	global String getVoucherCode() { }
	global String getVoucherDefinition() { }
	global String getVoucherId() { }
	global String getVoucherImageUrl() { }
	global Integer hashCode() { }
	global void setEffectiveDate(Datetime value) { }
	global void setExpirationDate(Datetime value) { }
	global void setTransactionJournalId(String value) { }
	global void setVoucherCode(String value) { }
	global void setVoucherDefinition(String value) { }
	global void setVoucherId(String value) { }
	global void setVoucherImageUrl(String value) { }
	global String toString() { }

}