/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// allow-any-unicode-comment-file
// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts

import type { BaseParams, PaginatedParams, PaginatedResult } from '../common/commands.js';
import type { URI } from '../common/state.js';
import type { AutomationDefinition, AutomationSchedule, AutomationSessionTemplate, AutomationSummary, AutomationTrigger, AutomationTriggerDefinition } from './state.js';
import type { Message } from '../channels-chat/state.js';

/**
 * List the host's automation catalogue without subscribing to every
 * automation channel.
 *
 * Results are lightweight {@link AutomationSummary} entries. Clients SHOULD
 * re-run this command after reconnect because root catalogue notifications are
 * not replayed.
 *
 * @category Commands
 * @method listAutomations
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface ListAutomationsParams extends BaseParams, PaginatedParams {
	/** Automation catalogues are listed from the root channel. */
	channel: 'ahp-root://';
	/** Optional exact filter on {@link AutomationDefinition.enabled}. */
	enabled?: boolean;
}

/**
 * One page of the automation catalogue.
 *
 * @category Commands
 */
export interface ListAutomationsResult extends PaginatedResult {
	/** Automation summaries in host-defined catalogue order. */
	items: AutomationSummary[];
}

/**
 * Discover event-trigger types available for a prospective session template.
 *
 * Hosts may vary definitions by provider, workspace, and session
 * configuration. Schedule triggers are protocol-defined and therefore do not
 * appear in this result.
 *
 * @category Commands
 * @method listAutomationTriggerDefinitions
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface ListAutomationTriggerDefinitionsParams extends BaseParams {
	/** Trigger definitions are discovered from the root channel. */
	channel: 'ahp-root://';
	/** Prospective provider id, or omitted for the host default. */
	provider?: string;
	/** Prospective ordered working-directory list. */
	workingDirectories?: URI[];
	/** Prospective resolved session configuration values. */
	sessionConfig?: Record<string, unknown>;
}

/**
 * Host-defined event trigger types available for the supplied context.
 *
 * @category Commands
 */
export interface ListAutomationTriggerDefinitionsResult {
	/** Available event trigger definitions. */
	items: AutomationTriggerDefinition[];
}

/**
 * Stable source identity used to make legacy automation import idempotent.
 *
 * The host remembers this identity independently of the client-chosen
 * automation URI. Retrying an interrupted migration with the same values MUST
 * resolve to the previously imported item rather than creating a duplicate.
 *
 * @category Commands
 */
export interface AutomationImportIdentity {
	/** Stable namespace identifying the source implementation or store. */
	source: string;
	/** Identifier shared by every item in one import attempt. */
	batchId: string;
	/** Stable source-side identifier for this definition within the batch. */
	itemId: string;
}

/**
 * Create a durable automation at a client-chosen URI.
 *
 * `channel` MUST use the `ahp-automation:` scheme and MUST NOT already identify
 * an unrelated automation. The host validates the complete definition,
 * persists it, and makes it visible through the root catalogue before
 * returning success.
 *
 * @category Commands
 * @method createAutomation
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface CreateAutomationParams extends BaseParams {
	/** Client-chosen `ahp-automation:` URI for the new definition. */
	channel: URI;
	/** Complete initial definition. */
	definition: AutomationDefinition;
	/** Optional idempotency identity when importing a legacy definition. */
	import?: AutomationImportIdentity;
}

/**
 * Partial replacement of editable {@link AutomationDefinition} fields.
 *
 * Omitted fields are unchanged. Supplied arrays and objects replace their
 * corresponding values in full; they are not merged recursively.
 *
 * @category Commands
 */
export interface AutomationDefinitionPatch {
	/** Replacement human-readable title. */
	title?: string;
	/** Replacement initial user message. */
	message?: Message;
	/** Replacement session template. */
	session?: AutomationSessionTemplate;
	/** Replacement automatic-trigger enabled state. */
	enabled?: boolean;
	/** Complete replacement trigger list. */
	triggers?: AutomationTrigger[];
	/** Complete replacement implementation-defined metadata. */
	_meta?: Record<string, unknown>;
}

/**
 * Update editable fields of an existing automation using optimistic
 * concurrency.
 *
 * The host accepts the patch only when `expectedRevision` equals the current
 * {@link AutomationState.revision}. A stale revision is rejected; clients
 * SHOULD reconcile the latest state before retrying.
 *
 * @category Commands
 * @method updateAutomation
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface UpdateAutomationParams extends BaseParams {
	/** Target `ahp-automation:` URI. */
	channel: URI;
	/** Revision on which the client based {@link changes}. */
	expectedRevision: number;
	/** Editable fields to replace. */
	changes: AutomationDefinitionPatch;
}

/**
 * Permanently remove an automation.
 *
 * The target is supplied by {@link BaseParams.channel}. The host rejects the
 * command when {@link AutomationOperation.Dispose} is not currently
 * advertised, for example while a non-terminal run prevents disposal.
 *
 * @category Commands
 * @method disposeAutomation
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface DisposeAutomationParams extends BaseParams { }

/**
 * Start a manual run of an automation.
 *
 * Manual execution is independent of {@link AutomationDefinition.enabled}.
 * The host persists the run before beginning session side effects.
 *
 * @category Commands
 * @method runAutomation
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface RunAutomationParams extends BaseParams {
	/**
	 * Durable client-generated idempotency key. Retrying with the same key and
	 * automation MUST return the original run URI rather than create another
	 * run.
	 */
	requestId: string;
}

/**
 * Result identifying the existing or newly created run.
 *
 * @category Commands
 */
export interface RunAutomationResult {
	/** Subscribable `ahp-automation-run:` URI. */
	run: URI;
}

/**
 * Load one older page into the subscribed automation's run-history state.
 *
 * The response only acknowledges the request. Loaded entries arrive through
 * `automation/runsLoaded`, keeping all subscribers synchronized through the
 * normal action stream.
 *
 * @category Commands
 * @method fetchAutomationRuns
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface FetchAutomationRunsParams extends BaseParams {
	/**
	 * Cursor previously received as {@link AutomationState.runsNextCursor}.
	 * Omit to request the first page not already included by the snapshot.
	 */
	cursor?: string;
}

/**
 * Empty acknowledgement; run summaries are delivered by action.
 *
 * @category Commands
 */
export interface FetchAutomationRunsResult { }

/**
 * Ask the host to evaluate a schedule without creating an automation.
 *
 * Clients SHOULD use this command for validation and preview instead of
 * implementing their own cron evaluator, especially around time-zone
 * transitions.
 *
 * @category Commands
 * @method previewAutomationSchedule
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface PreviewAutomationScheduleParams extends BaseParams {
	/** Schedule preview is requested from the root channel. */
	channel: 'ahp-root://';
	/** Portable AHP cron schedule to evaluate. */
	schedule: AutomationSchedule;
	/** Requested maximum number of future occurrences; the host MAY cap it. */
	count?: number;
}

/**
 * Host-canonical future schedule occurrences.
 *
 * @category Commands
 */
export interface PreviewAutomationScheduleResult {
	/** Ascending ISO 8601 timestamps. */
	items: string[];
}
