declare class BufferPolyfill extends Uint8Array {
    static readonly BYTES_PER_ELEMENT = 1;
    static from(source: ArrayLike<number>): BufferPolyfill;
    static from<T>(source: ArrayLike<T>, mapper: (v: T, i: number) => number, ctx?: unknown): BufferPolyfill;
    static from(source: string, enc?: string): BufferPolyfill;
    static from(source: ArrayBuffer | Uint8Array): BufferPolyfill;
    static from(source: Iterable<number>): BufferPolyfill;
    static alloc(len: number, fillValue?: number): BufferPolyfill;
    static allocUnsafe(len: number): BufferPolyfill;
    static allocUnsafeSlow(len: number): BufferPolyfill;
    static concat(list: (Uint8Array | BufferPolyfill)[]): BufferPolyfill;
    static isBuffer(candidate: unknown): candidate is BufferPolyfill;
    static isEncoding(enc: string): boolean;
    static byteLength(text: string, enc?: string): number;
    toString(enc?: BufferEncoding): string;
    slice(begin?: number, end?: number): BufferPolyfill;
    subarray(begin?: number, end?: number): BufferPolyfill;
    write(string: string, encoding?: BufferEncoding): number;
    write(string: string, offset: number, encoding?: BufferEncoding): number;
    write(string: string, offset: number, length: number, encoding?: BufferEncoding): number;
    copy(dest: BufferPolyfill, destStart?: number, srcStart?: number, srcEnd?: number): number;
    compare(other: Uint8Array): number;
    equals(other: Uint8Array): boolean;
    toJSON(): {
        type: string;
        data: number[];
    };
    hasOwnProperty(key: PropertyKey): boolean;
    indexOf(needle: number | Uint8Array | string, fromIndex?: number): number;
    includes(needle: number | Uint8Array | string, fromIndex?: number): boolean;
    readUInt8(pos: number): number;
    readUInt16BE(pos: number): number;
    readUInt16LE(pos: number): number;
    readUInt32BE(pos: number): number;
    readUInt32LE(pos: number): number;
    writeUInt8(val: number, pos: number): number;
    writeUInt16BE(val: number, pos: number): number;
    writeUInt16LE(val: number, pos: number): number;
    writeUInt32BE(val: number, pos: number): number;
    writeUInt32LE(val: number, pos: number): number;
    readUint8(pos: number): number;
    readUint16BE(pos: number): number;
    readUint16LE(pos: number): number;
    readUint32BE(pos: number): number;
    readUint32LE(pos: number): number;
    writeUint8(val: number, pos: number): number;
    writeUint16BE(val: number, pos: number): number;
    writeUint16LE(val: number, pos: number): number;
    writeUint32BE(val: number, pos: number): number;
    writeUint32LE(val: number, pos: number): number;
    readInt8(pos: number): number;
    readInt16BE(pos: number): number;
    readInt16LE(pos: number): number;
    readInt32BE(pos: number): number;
    readInt32LE(pos: number): number;
    writeInt8(val: number, pos: number): number;
    writeInt16BE(val: number, pos: number): number;
    writeInt16LE(val: number, pos: number): number;
    writeInt32BE(val: number, pos: number): number;
    writeInt32LE(val: number, pos: number): number;
    readBigUInt64LE(pos: number): bigint;
    readBigUInt64BE(pos: number): bigint;
    readBigInt64LE(pos: number): bigint;
    readBigInt64BE(pos: number): bigint;
    writeBigUInt64LE(val: bigint, pos: number): number;
    writeBigUInt64BE(val: bigint, pos: number): number;
    writeBigInt64LE(val: bigint, pos: number): number;
    writeBigInt64BE(val: bigint, pos: number): number;
    readBigUint64LE(pos: number): bigint;
    readBigUint64BE(pos: number): bigint;
    writeBigUint64LE(val: bigint, pos: number): number;
    writeBigUint64BE(val: bigint, pos: number): number;
    readFloatLE(pos: number): number;
    readFloatBE(pos: number): number;
    readDoubleLE(pos: number): number;
    readDoubleBE(pos: number): number;
    writeFloatLE(val: number, pos: number): number;
    writeFloatBE(val: number, pos: number): number;
    writeDoubleLE(val: number, pos: number): number;
    writeDoubleBE(val: number, pos: number): number;
    readUIntLE(pos: number, width: number): number;
    readUintLE(pos: number, width: number): number;
    readUIntBE(pos: number, width: number): number;
    readUintBE(pos: number, width: number): number;
    readIntLE(pos: number, width: number): number;
    readIntBE(pos: number, width: number): number;
    writeUIntLE(val: number, pos: number, width: number): number;
    writeUintLE(val: number, pos: number, width: number): number;
    writeUIntBE(val: number, pos: number, width: number): number;
    writeUintBE(val: number, pos: number, width: number): number;
    writeIntLE(val: number, pos: number, width: number): number;
    writeIntBE(val: number, pos: number, width: number): number;
    swap16(): this;
    swap32(): this;
    swap64(): this;
}
declare const Buffer: BufferConstructor & typeof BufferPolyfill;
export { Buffer };
export declare const SlowBuffer: BufferConstructor & typeof BufferPolyfill;
export declare const kMaxLength = 2147483647;
export declare const INSPECT_MAX_BYTES = 50;
export declare const constants: {
    MAX_LENGTH: number;
    MAX_STRING_LENGTH: number;
};
export declare function transcode(src: Uint8Array, _fromEnc: string, _toEnc: string): InstanceType<typeof BufferPolyfill>;
export declare function resolveObjectURL(_id: string): undefined;
export declare function atob(data: string): string;
export declare function btoa(data: string): string;
declare const bufferModule: Record<string, unknown>;
export default bufferModule;
