export declare const SIGKILL = 9;
export declare const SIGTERM = 15;
export declare const SIGINT = 2;
export declare const SIGHUP = 1;
export declare const SIGQUIT = 3;
export declare const SIGABRT = 6;
export declare const SIGALRM = 14;
export declare const SIGUSR1 = 10;
export declare const SIGUSR2 = 12;
export declare const SIGPIPE = 13;
export declare const SIGCHLD = 17;
export declare const SIGCONT = 18;
export declare const SIGSTOP = 19;
export declare const SIGTSTP = 20;
export declare const F_OK = 0;
export declare const R_OK = 4;
export declare const W_OK = 2;
export declare const X_OK = 1;
export declare const O_RDONLY = 0;
export declare const O_WRONLY = 1;
export declare const O_RDWR = 2;
export declare const O_CREAT = 64;
export declare const O_EXCL = 128;
export declare const O_TRUNC = 512;
export declare const O_APPEND = 1024;
export declare const O_DIRECTORY = 65536;
export declare const O_NOFOLLOW = 131072;
export declare const O_SYNC = 1052672;
export declare const S_IFMT = 61440;
export declare const S_IFREG = 32768;
export declare const S_IFDIR = 16384;
export declare const S_IFCHR = 8192;
export declare const S_IFBLK = 24576;
export declare const S_IFIFO = 4096;
export declare const S_IFLNK = 40960;
export declare const S_IFSOCK = 49152;
export declare const EACCES = -13;
export declare const EEXIST = -17;
export declare const EISDIR = -21;
export declare const EMFILE = -24;
export declare const ENOENT = -2;
export declare const ENOTDIR = -20;
export declare const ENOTEMPTY = -39;
export declare const EPERM = -1;
export declare const EBADF = -9;
export declare const os: {
    constants: {
        signals: {
            SIGKILL: number;
            SIGTERM: number;
            SIGINT: number;
            SIGHUP: number;
            SIGQUIT: number;
            SIGABRT: number;
            SIGALRM: number;
            SIGUSR1: number;
            SIGUSR2: number;
            SIGPIPE: number;
            SIGCHLD: number;
            SIGCONT: number;
            SIGSTOP: number;
            SIGTSTP: number;
        };
        errno: {
            EACCES: number;
            EEXIST: number;
            EISDIR: number;
            EMFILE: number;
            ENOENT: number;
            ENOTDIR: number;
            ENOTEMPTY: number;
            EPERM: number;
            EBADF: number;
        };
    };
};
export declare const fs: {
    constants: {
        F_OK: number;
        R_OK: number;
        W_OK: number;
        X_OK: number;
        O_RDONLY: number;
        O_WRONLY: number;
        O_RDWR: number;
        O_CREAT: number;
        O_EXCL: number;
        O_TRUNC: number;
        O_APPEND: number;
        O_DIRECTORY: number;
        O_NOFOLLOW: number;
        O_SYNC: number;
        S_IFMT: number;
        S_IFREG: number;
        S_IFDIR: number;
        S_IFCHR: number;
        S_IFBLK: number;
        S_IFIFO: number;
        S_IFLNK: number;
        S_IFSOCK: number;
    };
};
declare const _default: {
    os: {
        constants: {
            signals: {
                SIGKILL: number;
                SIGTERM: number;
                SIGINT: number;
                SIGHUP: number;
                SIGQUIT: number;
                SIGABRT: number;
                SIGALRM: number;
                SIGUSR1: number;
                SIGUSR2: number;
                SIGPIPE: number;
                SIGCHLD: number;
                SIGCONT: number;
                SIGSTOP: number;
                SIGTSTP: number;
            };
            errno: {
                EACCES: number;
                EEXIST: number;
                EISDIR: number;
                EMFILE: number;
                ENOENT: number;
                ENOTDIR: number;
                ENOTEMPTY: number;
                EPERM: number;
                EBADF: number;
            };
        };
    };
    fs: {
        constants: {
            F_OK: number;
            R_OK: number;
            W_OK: number;
            X_OK: number;
            O_RDONLY: number;
            O_WRONLY: number;
            O_RDWR: number;
            O_CREAT: number;
            O_EXCL: number;
            O_TRUNC: number;
            O_APPEND: number;
            O_DIRECTORY: number;
            O_NOFOLLOW: number;
            O_SYNC: number;
            S_IFMT: number;
            S_IFREG: number;
            S_IFDIR: number;
            S_IFCHR: number;
            S_IFBLK: number;
            S_IFIFO: number;
            S_IFLNK: number;
            S_IFSOCK: number;
        };
    };
    F_OK: number;
    R_OK: number;
    W_OK: number;
    X_OK: number;
    O_RDONLY: number;
    O_WRONLY: number;
    O_RDWR: number;
    O_CREAT: number;
    O_EXCL: number;
    O_TRUNC: number;
    O_APPEND: number;
    O_DIRECTORY: number;
    O_NOFOLLOW: number;
    O_SYNC: number;
    S_IFMT: number;
    S_IFREG: number;
    S_IFDIR: number;
    S_IFCHR: number;
    S_IFBLK: number;
    S_IFIFO: number;
    S_IFLNK: number;
    S_IFSOCK: number;
    EACCES: number;
    EEXIST: number;
    EISDIR: number;
    EMFILE: number;
    ENOENT: number;
    ENOTDIR: number;
    ENOTEMPTY: number;
    EPERM: number;
    EBADF: number;
    SIGKILL: number;
    SIGTERM: number;
    SIGINT: number;
    SIGHUP: number;
    SIGQUIT: number;
    SIGABRT: number;
    SIGALRM: number;
    SIGUSR1: number;
    SIGUSR2: number;
    SIGPIPE: number;
    SIGCHLD: number;
    SIGCONT: number;
    SIGSTOP: number;
    SIGTSTP: number;
};
export default _default;
