export declare const Features: {
    readonly Nesting: 1;
    readonly NotSelectorList: 2;
    readonly DirSelector: 4;
    readonly LangSelectorList: 8;
    readonly IsSelector: 16;
    readonly TextDecorationThicknessPercent: 32;
    readonly MediaIntervalSyntax: 64;
    readonly MediaRangeSyntax: 128;
    readonly CustomMediaQueries: 256;
    readonly ClampFunction: 512;
    readonly ColorFunction: 1024;
    readonly OklabColors: 2048;
    readonly LabColors: 4096;
    readonly P3Colors: 8192;
    readonly HexAlphaColors: 16384;
    readonly SpaceSeparatedColorNotation: 32768;
    readonly FontFamilySystemUi: 65536;
    readonly DoublePositionGradients: 131072;
    readonly VendorPrefixes: 262144;
    readonly LogicalProperties: 524288;
    readonly LightDark: 1048576;
    readonly Selectors: 31;
    readonly MediaQueries: 448;
    readonly Colors: 1113088;
};
declare function ensureInit(): Promise<void>;
export declare function transform(opts: any): any;
export declare function transformStyleAttribute(opts: any): any;
export declare function bundle(opts: any): any;
export declare function bundleAsync(opts: any): Promise<any>;
export declare function composeVisitors(visitors: any[]): any;
export declare function browserslistToTargets(browserslist: any): any;
export { ensureInit as init };
declare const _default: {
    transform: typeof transform;
    transformStyleAttribute: typeof transformStyleAttribute;
    bundle: typeof bundle;
    bundleAsync: typeof bundleAsync;
    composeVisitors: typeof composeVisitors;
    Features: {
        readonly Nesting: 1;
        readonly NotSelectorList: 2;
        readonly DirSelector: 4;
        readonly LangSelectorList: 8;
        readonly IsSelector: 16;
        readonly TextDecorationThicknessPercent: 32;
        readonly MediaIntervalSyntax: 64;
        readonly MediaRangeSyntax: 128;
        readonly CustomMediaQueries: 256;
        readonly ClampFunction: 512;
        readonly ColorFunction: 1024;
        readonly OklabColors: 2048;
        readonly LabColors: 4096;
        readonly P3Colors: 8192;
        readonly HexAlphaColors: 16384;
        readonly SpaceSeparatedColorNotation: 32768;
        readonly FontFamilySystemUi: 65536;
        readonly DoublePositionGradients: 131072;
        readonly VendorPrefixes: 262144;
        readonly LogicalProperties: 524288;
        readonly LightDark: 1048576;
        readonly Selectors: 31;
        readonly MediaQueries: 448;
        readonly Colors: 1113088;
    };
    browserslistToTargets: typeof browserslistToTargets;
    init: typeof ensureInit;
};
export default _default;
