export declare function hostname(): string;
export declare function platform(): string;
export declare function arch(): string;
export declare function type(): string;
export declare function release(): string;
export declare function version(): string;
export declare function machine(): string;
export declare function tmpdir(): string;
export declare function homedir(): string;
interface CpuEntry {
    model: string;
    speed: number;
    times: {
        user: number;
        nice: number;
        sys: number;
        idle: number;
        irq: number;
    };
}
export declare function cpus(): CpuEntry[];
export declare function totalmem(): number;
export declare function freemem(): number;
export declare function uptime(): number;
export declare function loadavg(): [number, number, number];
interface NetIface {
    address: string;
    netmask: string;
    family: string;
    mac: string;
    internal: boolean;
    cidr: string;
}
export declare function networkInterfaces(): Record<string, NetIface[]>;
export declare function userInfo(): {
    username: string;
    uid: number;
    gid: number;
    shell: string;
    homedir: string;
};
export declare function endianness(): 'BE' | 'LE';
export declare function getPriority(_pid?: number): number;
export declare function setPriority(_pidOrPriority: number, _priority?: number): void;
export declare const EOL = "\n";
export declare const devNull = "/dev/null";
export declare const constants: {
    signals: {
        SIGHUP: number;
        SIGINT: number;
        SIGQUIT: number;
        SIGILL: number;
        SIGTRAP: number;
        SIGABRT: number;
        SIGBUS: number;
        SIGFPE: number;
        SIGKILL: number;
        SIGUSR1: number;
        SIGSEGV: number;
        SIGUSR2: number;
        SIGPIPE: number;
        SIGALRM: number;
        SIGTERM: number;
        SIGCHLD: number;
        SIGCONT: number;
        SIGSTOP: number;
        SIGTSTP: number;
        SIGTTIN: number;
        SIGTTOU: number;
        SIGURG: number;
        SIGXCPU: number;
        SIGXFSZ: number;
        SIGVTALRM: number;
        SIGPROF: number;
        SIGWINCH: number;
        SIGIO: number;
        SIGPWR: number;
        SIGSYS: number;
    };
    errno: {
        EPERM: number;
        ENOENT: number;
        ESRCH: number;
        EINTR: number;
        EIO: number;
        ENXIO: number;
        E2BIG: number;
        ENOEXEC: number;
        EBADF: number;
        ECHILD: number;
        EAGAIN: number;
        ENOMEM: number;
        EACCES: number;
        EFAULT: number;
        EBUSY: number;
        EEXIST: number;
        EXDEV: number;
        ENODEV: number;
        ENOTDIR: number;
        EISDIR: number;
        EINVAL: number;
        ENFILE: number;
        EMFILE: number;
        ENOTTY: number;
        EFBIG: number;
        ENOSPC: number;
        ESPIPE: number;
        EROFS: number;
        EMLINK: number;
        EPIPE: number;
        EDOM: number;
        ERANGE: number;
        ENOTEMPTY: number;
        ENOSYS: number;
        ELOOP: number;
        ENAMETOOLONG: number;
        ECONNRESET: number;
        ECONNREFUSED: number;
        EADDRINUSE: number;
        EADDRNOTAVAIL: number;
        ETIMEDOUT: number;
    };
    priority: {
        PRIORITY_LOW: number;
        PRIORITY_BELOW_NORMAL: number;
        PRIORITY_NORMAL: number;
        PRIORITY_ABOVE_NORMAL: number;
        PRIORITY_HIGH: number;
        PRIORITY_HIGHEST: number;
    };
};
declare const _default: {
    hostname: typeof hostname;
    platform: typeof platform;
    arch: typeof arch;
    type: typeof type;
    release: typeof release;
    version: typeof version;
    machine: typeof machine;
    tmpdir: typeof tmpdir;
    homedir: typeof homedir;
    cpus: typeof cpus;
    totalmem: typeof totalmem;
    freemem: typeof freemem;
    uptime: typeof uptime;
    loadavg: typeof loadavg;
    networkInterfaces: typeof networkInterfaces;
    userInfo: typeof userInfo;
    endianness: typeof endianness;
    getPriority: typeof getPriority;
    setPriority: typeof setPriority;
    EOL: string;
    devNull: string;
    constants: {
        signals: {
            SIGHUP: number;
            SIGINT: number;
            SIGQUIT: number;
            SIGILL: number;
            SIGTRAP: number;
            SIGABRT: number;
            SIGBUS: number;
            SIGFPE: number;
            SIGKILL: number;
            SIGUSR1: number;
            SIGSEGV: number;
            SIGUSR2: number;
            SIGPIPE: number;
            SIGALRM: number;
            SIGTERM: number;
            SIGCHLD: number;
            SIGCONT: number;
            SIGSTOP: number;
            SIGTSTP: number;
            SIGTTIN: number;
            SIGTTOU: number;
            SIGURG: number;
            SIGXCPU: number;
            SIGXFSZ: number;
            SIGVTALRM: number;
            SIGPROF: number;
            SIGWINCH: number;
            SIGIO: number;
            SIGPWR: number;
            SIGSYS: number;
        };
        errno: {
            EPERM: number;
            ENOENT: number;
            ESRCH: number;
            EINTR: number;
            EIO: number;
            ENXIO: number;
            E2BIG: number;
            ENOEXEC: number;
            EBADF: number;
            ECHILD: number;
            EAGAIN: number;
            ENOMEM: number;
            EACCES: number;
            EFAULT: number;
            EBUSY: number;
            EEXIST: number;
            EXDEV: number;
            ENODEV: number;
            ENOTDIR: number;
            EISDIR: number;
            EINVAL: number;
            ENFILE: number;
            EMFILE: number;
            ENOTTY: number;
            EFBIG: number;
            ENOSPC: number;
            ESPIPE: number;
            EROFS: number;
            EMLINK: number;
            EPIPE: number;
            EDOM: number;
            ERANGE: number;
            ENOTEMPTY: number;
            ENOSYS: number;
            ELOOP: number;
            ENAMETOOLONG: number;
            ECONNRESET: number;
            ECONNREFUSED: number;
            EADDRINUSE: number;
            EADDRNOTAVAIL: number;
            ETIMEDOUT: number;
        };
        priority: {
            PRIORITY_LOW: number;
            PRIORITY_BELOW_NORMAL: number;
            PRIORITY_NORMAL: number;
            PRIORITY_ABOVE_NORMAL: number;
            PRIORITY_HIGH: number;
            PRIORITY_HIGHEST: number;
        };
    };
};
export default _default;
