export declare const sep = "/";
export declare const delimiter = ":";
export declare function normalize(inputPath: string): string;
export declare function join(...fragments: string[]): string;
export declare function resolve(...segments: string[]): string;
export declare function isAbsolute(targetPath: string): boolean;
export declare function dirname(targetPath: string): string;
export declare function basename(targetPath: string, suffix?: string): string;
export declare function extname(targetPath: string): string;
export declare function relative(fromPath: string, toPath: string): string;
export declare function parse(targetPath: string): {
    root: string;
    dir: string;
    base: string;
    ext: string;
    name: string;
};
export declare function format(components: {
    root?: string;
    dir?: string;
    base?: string;
    ext?: string;
    name?: string;
}): string;
export declare const posix: {
    sep: string;
    delimiter: string;
    normalize: typeof normalize;
    join: typeof join;
    resolve: typeof resolve;
    isAbsolute: typeof isAbsolute;
    dirname: typeof dirname;
    basename: typeof basename;
    extname: typeof extname;
    relative: typeof relative;
    parse: typeof parse;
    format: typeof format;
};
export declare const win32: {
    sep: string;
    delimiter: string;
    normalize: typeof normalize;
    join: typeof join;
    resolve: typeof resolve;
    isAbsolute: typeof isAbsolute;
    dirname: typeof dirname;
    basename: typeof basename;
    extname: typeof extname;
    relative: typeof relative;
    parse: typeof parse;
    format: typeof format;
};
declare const _default: {
    sep: string;
    delimiter: string;
    normalize: typeof normalize;
    join: typeof join;
    resolve: typeof resolve;
    isAbsolute: typeof isAbsolute;
    dirname: typeof dirname;
    basename: typeof basename;
    extname: typeof extname;
    relative: typeof relative;
    parse: typeof parse;
    format: typeof format;
    posix: {
        sep: string;
        delimiter: string;
        normalize: typeof normalize;
        join: typeof join;
        resolve: typeof resolve;
        isAbsolute: typeof isAbsolute;
        dirname: typeof dirname;
        basename: typeof basename;
        extname: typeof extname;
        relative: typeof relative;
        parse: typeof parse;
        format: typeof format;
    };
    win32: {
        sep: string;
        delimiter: string;
        normalize: typeof normalize;
        join: typeof join;
        resolve: typeof resolve;
        isAbsolute: typeof isAbsolute;
        dirname: typeof dirname;
        basename: typeof basename;
        extname: typeof extname;
        relative: typeof relative;
        parse: typeof parse;
        format: typeof format;
    };
};
export default _default;
