global class PlatformCacheInvalidOperationException extends Exception {
	global PlatformCacheInvalidOperationException(String param0, Exception param1) { }
	global PlatformCacheInvalidOperationException(Exception param0) { }
	global PlatformCacheInvalidOperationException(String param0) { }
	global PlatformCacheInvalidOperationException() { }
	global Object clone() { }
	global String getTypeName() { }

}