<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dot</string>
		<string>DOT</string>
	</array>
	<key>firstLineMatch</key>
	<string>digraph.*</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Graphviz (DOT)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.dot</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.dot</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.dot</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>named digraph declaration: "digraph NAME {"</string>
			<key>match</key>
			<string> ?(digraph)[ \t]+([A-Za-z0-9]+) ?(\{)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>edge definition: &lt;- -&gt; --</string>
			<key>match</key>
			<string>(&lt;|-)(&gt;|-)</string>
			<key>name</key>
			<string>keyword.operator.dot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(node|edge|graph|digraph|subgraph|strict)\b</string>
			<key>name</key>
			<string>storage.type.dot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bottomlabel|color|comment|distortion|fillcolor|fixedsize|fontcolor|fontname|fontsize|group|height|label|layer|orientation|peripheries|regular|shape|shapefile|sides|skew|style|toplabel|URL|width|z)\b</string>
			<key>name</key>
			<string>support.constant.attribute.node.dot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(arrowhead|arrowsize|arrowtail|color|comment|constraint|decorate|dir|fontcolor|fontname|fontsize|headlabel|headport|headURL|label|labelangle|labeldistance|labelfloat|labelcolor|labelfontname|labelfontsize|layer|lhead|ltail|minlen|samehead|sametail|splines|style|taillabel|tailport|tailURL|weight)\b</string>
			<key>name</key>
			<string>support.constant.attribute.edge.dot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bgcolor|center|clusterrank|color|comment|compound|concentrate|fillcolor|fontname|fontpath|fontsize|label|labeljust|labelloc|layers|margin|mclimit|nodesep|nslimit|nslimit1|ordering|orientation|page|pagedir|quantum|rank|rankdir|ranksep|ratio|remincross|rotate|samplepoints|searchsize|size|style|URL)\b</string>
			<key>name</key>
			<string>support.constant.attribute.graph.dot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(box|polygon|ellipse|circle|point|egg|triangle|plaintext|diamond|trapezium|parallelogram|house|pentagon|hexagon|septagon|octagon|doublecircle|doubleoctagon|tripleoctagon|invtriangle|invtrapezium|invhouse|Mdiamond|Msquare|Mcircle|rect|rectangle|none|note|tab|folder|box3d|component|max|min|same)\b</string>
			<key>name</key>
			<string>variable.other.dot</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.dot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.dot</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.dot</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.dot</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=//)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.dot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dot</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.dot</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.dot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dot</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.dot</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.dot</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.dot</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dot</string>
	<key>uuid</key>
	<string>1A53D54E-6B1D-11D9-A006-000D93589AF6</string>
</dict>
</plist>
