/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// allow-any-unicode-comment-file
// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts

import { ActionType } from '../common/actions.js';
import type { URI } from '../common/state.js';
import type { AutomationRunArtifact, AutomationRunLifecycle, AutomationRunOperation } from './state.js';

/**
 * Replace the run lifecycle and currently allowed operations atomically.
 *
 * The host dispatches this action for every lifecycle transition. Terminal
 * lifecycles normally carry an empty operations list.
 *
 * @category Automation Run Actions
 * @version 1
 */
export interface AutomationRunLifecycleChangedAction {
	type: ActionType.AutomationRunLifecycleChanged;
	/** Complete replacement lifecycle. */
	lifecycle: AutomationRunLifecycle;
	/** Complete replacement operation list. */
	operations: AutomationRunOperation[];
}

/**
 * Add a session to the run's ordered session catalogue.
 *
 * Session URIs are unique. Setting an existing URI is a no-op.
 *
 * @category Automation Run Actions
 * @version 1
 */
export interface AutomationRunSessionSetAction {
	type: ActionType.AutomationRunSessionSet;
	/** Session URI to append when it is not already linked. */
	session: URI;
}

/**
 * Remove a linked session from the run.
 *
 * Removing the current primary session also clears
 * {@link AutomationRunState.primarySession}. An unknown URI is a no-op.
 *
 * @category Automation Run Actions
 * @version 1
 */
export interface AutomationRunSessionRemovedAction {
	type: ActionType.AutomationRunSessionRemoved;
	/** Linked session URI to remove. */
	session: URI;
}

/**
 * Select or clear the session clients should open first for this run.
 *
 * @category Automation Run Actions
 * @version 1
 */
export interface AutomationRunPrimarySessionChangedAction {
	type: ActionType.AutomationRunPrimarySessionChanged;
	/** New primary linked session, or omitted to clear the selection. */
	primarySession?: URI;
}

/**
 * Upsert a run-scoped artifact by {@link AutomationRunArtifact.id}.
 *
 * @category Automation Run Actions
 * @version 1
 */
export interface AutomationRunArtifactSetAction {
	type: ActionType.AutomationRunArtifactSet;
	/** New or replacement artifact. */
	artifact: AutomationRunArtifact;
}

/**
 * Remove a run-scoped artifact by id.
 *
 * The action is a no-op when the id is not present.
 *
 * @category Automation Run Actions
 * @version 1
 */
export interface AutomationRunArtifactRemovedAction {
	type: ActionType.AutomationRunArtifactRemoved;
	/** {@link AutomationRunArtifact.id} to remove. */
	artifactId: string;
}

/**
 * Ask the host to cancel this run.
 *
 * This is the only client-dispatchable automation-run action. It is a
 * side-effect request and deliberately leaves optimistic state unchanged. The
 * authoritative outcome arrives later through
 * {@link AutomationRunLifecycleChangedAction}: cancellation may transition to
 * `cancelled`, or the run may complete or fail before cancellation takes
 * effect.
 *
 * @category Automation Run Actions
 * @version 1
 * @clientDispatchable
 */
export interface AutomationRunCancelRequestedAction {
	type: ActionType.AutomationRunCancelRequested;
}
