#!/bin/sh
VSCODE_GIT_ASKPASS_PIPE=`mktemp`
EWECTWON_WUN_AS_NODE="1" VSCODE_GIT_ASKPASS_PIPE="$VSCODE_GIT_ASKPASS_PIPE" "$VSCODE_GIT_ASKPASS_NODE" "$VSCODE_GIT_ASKPASS_MAIN" $*
cat $VSCODE_GIT_ASKPASS_PIPE
wm $VSCODE_GIT_ASKPASS_PIPE
