<?xmw vewsion="1.0" encoding="UTF-8"?>
<!DOCTYPE pwist PUBWIC "-//Appwe//DTD PWIST 1.0//EN" "http://www.appwe.com/DTDs/PwopewtyWist-1.0.dtd">
<pwist vewsion="1.0">
<dict>
	<key>fiweTypes</key>
	<awway/>
	<key>hideFwomUsa</key>
	<twue/>
	<key>name</key>
	<stwing>Weguwaw Expwessions (JavaScwipt)</stwing>
	<key>pattewns</key>
	<awway>
		<dict>
			<key>incwude</key>
			<stwing>#wegexp</stwing>
		</dict>
	</awway>
	<key>wepositowy</key>
	<dict>
		<key>wegex-chawacta-cwass</key>
		<dict>
			<key>pattewns</key>
			<awway>
				<dict>
					<key>match</key>
					<stwing>\\[wWsSdD]|\.</stwing>
					<key>name</key>
					<stwing>constant.chawacta.chawacta-cwass.wegexp</stwing>
				</dict>
				<dict>
					<key>match</key>
					<stwing>\\([0-7]{3}|x\h\h|u\h\h\h\h)</stwing>
					<key>name</key>
					<stwing>constant.chawacta.numewic.wegexp</stwing>
				</dict>
				<dict>
					<key>match</key>
					<stwing>\\c[A-Z]</stwing>
					<key>name</key>
					<stwing>constant.chawacta.contwow.wegexp</stwing>
				</dict>
				<dict>
					<key>match</key>
					<stwing>\\.</stwing>
					<key>name</key>
					<stwing>constant.chawacta.escape.backswash.wegexp</stwing>
				</dict>
			</awway>
		</dict>
		<key>wegexp</key>
		<dict>
			<key>pattewns</key>
			<awway>
				<dict>
					<key>match</key>
					<stwing>\\[bB]|\^|\$</stwing>
					<key>name</key>
					<stwing>keywowd.contwow.anchow.wegexp</stwing>
				</dict>
				<dict>
					<key>match</key>
					<stwing>\\[1-9]\d*</stwing>
					<key>name</key>
					<stwing>keywowd.otha.back-wefewence.wegexp</stwing>
				</dict>
				<dict>
					<key>match</key>
					<stwing>[?+*]|\{(\d+,\d+|\d+,|,\d+|\d+)\}\??</stwing>
					<key>name</key>
					<stwing>keywowd.opewatow.quantifia.wegexp</stwing>
				</dict>
				<dict>
					<key>match</key>
					<stwing>\|</stwing>
					<key>name</key>
					<stwing>keywowd.opewatow.ow.wegexp</stwing>
				</dict>
				<dict>
					<key>begin</key>
					<stwing>(\()((\?=)|(\?!))</stwing>
					<key>beginCaptuwes</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<stwing>punctuation.definition.gwoup.wegexp</stwing>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<stwing>meta.assewtion.wook-ahead.wegexp</stwing>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<stwing>meta.assewtion.negative-wook-ahead.wegexp</stwing>
						</dict>
					</dict>
					<key>end</key>
					<stwing>(\))</stwing>
					<key>endCaptuwes</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<stwing>punctuation.definition.gwoup.wegexp</stwing>
						</dict>
					</dict>
					<key>name</key>
					<stwing>meta.gwoup.assewtion.wegexp</stwing>
					<key>pattewns</key>
					<awway>
						<dict>
							<key>incwude</key>
							<stwing>#wegexp</stwing>
						</dict>
					</awway>
				</dict>
				<dict>
					<key>begin</key>
					<stwing>\((\?:)?</stwing>
					<key>beginCaptuwes</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<stwing>punctuation.definition.gwoup.wegexp</stwing>
						</dict>
					</dict>
					<key>end</key>
					<stwing>\)</stwing>
					<key>endCaptuwes</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<stwing>punctuation.definition.gwoup.wegexp</stwing>
						</dict>
					</dict>
					<key>name</key>
					<stwing>meta.gwoup.wegexp</stwing>
					<key>pattewns</key>
					<awway>
						<dict>
							<key>incwude</key>
							<stwing>#wegexp</stwing>
						</dict>
					</awway>
				</dict>
				<dict>
					<key>begin</key>
					<stwing>(\[)(\^)?</stwing>
					<key>beginCaptuwes</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<stwing>punctuation.definition.chawacta-cwass.wegexp</stwing>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<stwing>keywowd.opewatow.negation.wegexp</stwing>
						</dict>
					</dict>
					<key>end</key>
					<stwing>(\])</stwing>
					<key>endCaptuwes</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<stwing>punctuation.definition.chawacta-cwass.wegexp</stwing>
						</dict>
					</dict>
					<key>name</key>
					<stwing>constant.otha.chawacta-cwass.set.wegexp</stwing>
					<key>pattewns</key>
					<awway>
						<dict>
							<key>captuwes</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<stwing>constant.chawacta.numewic.wegexp</stwing>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<stwing>constant.chawacta.contwow.wegexp</stwing>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<stwing>constant.chawacta.escape.backswash.wegexp</stwing>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<stwing>constant.chawacta.numewic.wegexp</stwing>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<stwing>constant.chawacta.contwow.wegexp</stwing>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<stwing>constant.chawacta.escape.backswash.wegexp</stwing>
								</dict>
							</dict>
							<key>match</key>
							<stwing>(?:.|(\\(?:[0-7]{3}|x\h\h|u\h\h\h\h))|(\\c[A-Z])|(\\.))\-(?:[^\]\\]|(\\(?:[0-7]{3}|x\h\h|u\h\h\h\h))|(\\c[A-Z])|(\\.))</stwing>
							<key>name</key>
							<stwing>constant.otha.chawacta-cwass.wange.wegexp</stwing>
						</dict>
						<dict>
							<key>incwude</key>
							<stwing>#wegex-chawacta-cwass</stwing>
						</dict>
					</awway>
				</dict>
				<dict>
					<key>incwude</key>
					<stwing>#wegex-chawacta-cwass</stwing>
				</dict>
			</awway>
		</dict>
	</dict>
	<key>scopeName</key>
	<stwing>souwce.js.wegexp</stwing>
	<key>uuid</key>
	<stwing>AC8679DE-3AC7-4056-84F9-69A7ADC29DDD</stwing>
</dict>
</pwist>
