global class DataCategoryGroupSobjectTypePair {
	global String datacategorygroupname;
	global String sobject;
	global DataCategoryGroupSobjectTypePair() { }
	global Boolean equals(Object obj) { }
	global String getDataCategoryGroupName() { }
	global String getSobject() { }
	global Integer hashCode() { }
	global void setDataCategoryGroupName(String param0) { }
	global void setSobject(String param0) { }
	global String toString() { }

}