global class DescribeDataCategoryGroupResult {
	global Integer categorycount;
	global String description;
	global String label;
	global String name;
	global String sobject;
	global Boolean equals(Object obj) { }
	global Integer getCategoryCount() { }
	global String getDescription() { }
	global String getLabel() { }
	global String getName() { }
	global String getSobject() { }
	global Integer hashCode() { }
	global String toString() { }

}