global class DescribeDataCategoryGroupStructureResult {
	global String description;
	global String label;
	global String name;
	global String sobject;
	global List<Schema.DataCategory> topcategories;
	global Boolean equals(Object obj) { }
	global String getDescription() { }
	global String getLabel() { }
	global String getName() { }
	global String getSobject() { }
	global List<Schema.DataCategory> getTopCategories() { }
	global Integer hashCode() { }
	global String toString() { }

}