global class DescribeFieldResult {
	global Boolean accessible;
	global Boolean aggregatable;
	global Boolean aipredictionfield;
	global Boolean autonumber;
	global Integer bytelength;
	global Boolean calculated;
	global String calculatedformula;
	global Boolean cascadedelete;
	global Boolean casesensitive;
	global String compoundfieldname;
	global Schema.SObjectField controller;
	global Boolean createable;
	global Boolean custom;
	global Boolean datatranslationenabled;
	global Boolean defaultedoncreate;
	global Object defaultvalue;
	global String defaultvalueformula;
	global Boolean dependentpicklist;
	global Boolean deprecatedandhidden;
	global Integer digits;
	global Boolean displaylocationindecimal;
	global Boolean encrypted;
	global Boolean externalid;
	global Boolean filterable;
	global Schema.FilteredLookupInfo filteredlookupinfo;
	global Boolean formulatreatnullnumberaszero;
	global Boolean groupable;
	global Boolean highscalenumber;
	global Boolean htmlformatted;
	global Boolean idlookup;
	global String inlinehelptext;
	global String label;
	global Integer length;
	global String localname;
	global String mask;
	global String masktype;
	global String name;
	global Boolean namefield;
	global Boolean namepointing;
	global Boolean nillable;
	global Boolean permissionable;
	global List<Schema.PicklistEntry> picklistvalues;
	global Integer precision;
	global Boolean querybydistance;
	global String referencetargetfield;
	global List<Schema.SObjectType> referenceto;
	global String relationshipname;
	global Integer relationshiporder;
	global Boolean restricteddelete;
	global Boolean restrictedpicklist;
	global Integer scale;
	global Boolean searchprefilterable;
	global Schema.SoapType soaptype;
	global Schema.SObjectField sobjectfield;
	global Schema.SObjectType sobjecttype;
	global Boolean sortable;
	global Schema.DisplayType type;
	global Boolean unique;
	global Boolean updateable;
	global Boolean writerequiresmasterread;
	global Boolean equals(Object obj) { }
	global Integer getByteLength() { }
	global String getCalculatedFormula() { }
	global String getCompoundFieldName() { }
	global Schema.SObjectField getController() { }
	global Boolean getDataTranslationEnabled() { }
	global Object getDefaultValue() { }
	global String getDefaultValueFormula() { }
	global Integer getDigits() { }
	global Schema.FilteredLookupInfo getFilteredLookupInfo() { }
	global String getInlineHelpText() { }
	global String getLabel() { }
	global Integer getLength() { }
	global String getLocalName() { }
	global String getMask() { }
	global String getMaskType() { }
	global String getName() { }
	global List<Schema.PicklistEntry> getPicklistValues() { }
	global Integer getPrecision() { }
	global String getReferenceTargetField() { }
	global List<Schema.SObjectType> getReferenceTo() { }
	global String getRelationshipName() { }
	global Integer getRelationshipOrder() { }
	global Schema.SObjectType getSObjectType() { }
	global Integer getScale() { }
	global Schema.SoapType getSoapType() { }
	global Schema.SObjectField getSobjectField() { }
	global Schema.DisplayType getType() { }
	global Integer hashCode() { }
	global Boolean isAccessible() { }
	global Boolean isAggregatable() { }
	global Boolean isAiPredictionField() { }
	global Boolean isAutoNumber() { }
	global Boolean isCalculated() { }
	global Boolean isCascadeDelete() { }
	global Boolean isCaseSensitive() { }
	global Boolean isCreateable() { }
	global Boolean isCustom() { }
	global Boolean isDefaultedOnCreate() { }
	global Boolean isDependentPicklist() { }
	global Boolean isDeprecatedAndHidden() { }
	global Boolean isDisplayLocationInDecimal() { }
	global Boolean isEncrypted() { }
	global Boolean isExternalId() { }
	global Boolean isFilterable() { }
	global Boolean isFormulaTreatNullNumberAsZero() { }
	global Boolean isGroupable() { }
	global Boolean isHighScaleNumber() { }
	global Boolean isHtmlFormatted() { }
	global Boolean isIdLookup() { }
	global Boolean isNameField() { }
	global Boolean isNamePointing() { }
	global Boolean isNillable() { }
	global Boolean isPermissionable() { }
	global Boolean isQueryByDistance() { }
	global Boolean isRestrictedDelete() { }
	global Boolean isRestrictedPicklist() { }
	global Boolean isSearchPrefilterable() { }
	global Boolean isSortable() { }
	global Boolean isUnique() { }
	global Boolean isUpdateable() { }
	global Boolean isWriteRequiresMasterRead() { }
	global String toString() { }

}