global class DescribeTabResult {
	global List<Schema.DescribeColorResult> colors;
	global Boolean custom;
	global List<Schema.DescribeIconResult> icons;
	global String iconurl;
	global String label;
	global String miniiconurl;
	global String mobileurl;
	global String name;
	global String sobjectname;
	global String tabenumorid;
	global String url;
	global Boolean equals(Object obj) { }
	global List<Schema.DescribeColorResult> getColors() { }
	global String getIconUrl() { }
	global List<Schema.DescribeIconResult> getIcons() { }
	global String getLabel() { }
	global String getMiniIconUrl() { }
	global String getMobileUrl() { }
	global String getName() { }
	global String getSobjectName() { }
	global String getTabEnumOrId() { }
	global String getUrl() { }
	global Integer hashCode() { }
	global Boolean isCustom() { }
	global String toString() { }

}