global class DescribeIconResult {
	global String contenttype;
	global Integer height;
	global String theme;
	global String url;
	global Integer width;
	global Boolean equals(Object obj) { }
	global String getContentType() { }
	global Integer getHeight() { }
	global String getTheme() { }
	global String getUrl() { }
	global Integer getWidth() { }
	global Integer hashCode() { }
	global String toString() { }

}