/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// allow-any-unicode-comment-file
// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts
// Synced from agent-host-protocol @ 69603e5

import type { URI, ISessionSummary } from './state.js';

/**
 * Reason why authentication is required.
 *
 * @category Protocol Notifications
 */
export const enum AuthRequiredReason {
	/** The client has not yet authenticated for the resource */
	Required = 'required',
	/** A previously valid token has expired or been revoked */
	Expired = 'expired',
}

// ─── Protocol Notifications ──────────────────────────────────────────────────

/**
 * Discriminant values for all protocol notifications.
 *
 * @category Protocol Notifications
 */
export const enum NotificationType {
	SessionAdded = 'notify/sessionAdded',
	SessionRemoved = 'notify/sessionRemoved',
	AuthRequired = 'notify/authRequired',
}

/**
 * Broadcast to all connected clients when a new session is created.
 *
 * @category Protocol Notifications
 * @version 1
 * @example
 * ```json
 * {
 *   "jsonrpc": "2.0",
 *   "method": "notification",
 *   "params": {
 *     "notification": {
 *       "type": "notify/sessionAdded",
 *       "summary": {
 *         "resource": "copilot:/<uuid>",
 *         "provider": "copilot",
 *         "title": "New Session",
 *         "status": "idle",
 *         "createdAt": 1710000000000,
 *         "modifiedAt": 1710000000000
 *       }
 *     }
 *   }
 * }
 * ```
 */
export interface ISessionAddedNotification {
	type: NotificationType.SessionAdded;
	/** Summary of the new session */
	summary: ISessionSummary;
}

/**
 * Broadcast to all connected clients when a session is disposed.
 *
 * @category Protocol Notifications
 * @version 1
 * @example
 * ```json
 * {
 *   "jsonrpc": "2.0",
 *   "method": "notification",
 *   "params": {
 *     "notification": {
 *       "type": "notify/sessionRemoved",
 *       "session": "copilot:/<uuid>"
 *     }
 *   }
 * }
 * ```
 */
export interface ISessionRemovedNotification {
	type: NotificationType.SessionRemoved;
	/** URI of the removed session */
	session: URI;
}

/**
 * Sent by the server when a protected resource requires (re-)authentication.
 *
 * This notification is sent when a previously valid token expires or is
 * revoked, or when the server discovers a new authentication requirement.
 * Clients should obtain a fresh token and push it via the `authenticate`
 * command.
 *
 * @category Protocol Notifications
 * @version 1
 * @see {@link /specification/authentication | Authentication}
 * @example
 * ```json
 * {
 *   "jsonrpc": "2.0",
 *   "method": "notification",
 *   "params": {
 *     "notification": {
 *       "type": "notify/authRequired",
 *       "resource": "https://api.github.com",
 *       "reason": "expired"
 *     }
 *   }
 * }
 * ```
 */
export interface IAuthRequiredNotification {
	type: NotificationType.AuthRequired;
	/** The protected resource identifier that requires authentication */
	resource: string;
	/** Why authentication is required */
	reason?: AuthRequiredReason;
}

/**
 * Discriminated union of all protocol notifications.
 */
export type IProtocolNotification =
	| ISessionAddedNotification
	| ISessionRemovedNotification
	| IAuthRequiredNotification;
