/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// DO NOT EDIT — auto-generated by scripts/sync-agent-host-protocol.ts
// Synced from agent-host-protocol @ abf4599

// Generated revive/serialize helpers for converting between wire-format
// (URI as string) and VS Code types (URI as class instance).

import { URI } from '../../../../../base/common/uri.js';
import type { ISessionSummary, ISnapshot } from './state.js';
import type { ISessionActiveClientChangedAction, ISessionActiveClientToolsChangedAction, ISessionCreationFailedAction, ISessionDeltaAction, ISessionErrorAction, ISessionModelChangedAction, ISessionPermissionRequestAction, ISessionPermissionResolvedAction, ISessionReadyAction, ISessionReasoningAction, ISessionResponsePartAction, ISessionServerToolsChangedAction, ISessionTitleChangedAction, ISessionTurnCancelledAction, ISessionTurnCompleteAction, ISessionTurnStartedAction, ISessionUsageAction } from './actions.js';
import type { ICreateSessionParams, IDisposeSessionParams, IFetchTurnsParams, IInitializeParams, IReconnectParams, ISubscribeParams, IUnsubscribeParams } from './commands.js';
import type { ISessionRemovedNotification } from './notifications.js';

// ---- Wire<T> helper --------------------------------------------------------

/**
 * Maps a protocol type to its JSON wire format by replacing URI fields with
 * plain strings. Use at the JSON-RPC boundary.
 */
export type Wire<T> = {
	[K in keyof T]:
		T[K] extends URI ? string :
		T[K] extends URI | undefined ? string | undefined :
		T[K] extends URI[] ? string[] :
		T[K] extends (URI[] | undefined) ? string[] | undefined :
		T[K];
};

// ---- Session action helpers (all have `session: URI`) ----------------------

type SessionAction = ISessionReadyAction | ISessionCreationFailedAction | ISessionTurnStartedAction | ISessionDeltaAction | ISessionResponsePartAction | ISessionPermissionRequestAction | ISessionPermissionResolvedAction | ISessionTurnCompleteAction | ISessionTurnCancelledAction | ISessionErrorAction | ISessionTitleChangedAction | ISessionUsageAction | ISessionReasoningAction | ISessionModelChangedAction | ISessionServerToolsChangedAction | ISessionActiveClientChangedAction | ISessionActiveClientToolsChangedAction | ICreateSessionParams | IDisposeSessionParams | IFetchTurnsParams | ISessionRemovedNotification;

/** Revive any action whose only URI field is `session`. */
export function reviveSessionAction<T extends SessionAction>(wire: Wire<T>): T {
	return { ...wire, session: URI.parse(wire.session as string) } as T;
}

/** Serialize any action whose only URI field is `session`. */
export function serializeSessionAction<T extends SessionAction>(obj: T): Wire<T> {
	return { ...obj, session: obj.session.toString() } as Wire<T>;
}

// ---- Individual helpers for types with non-trivial URI fields ---------------

export function reviveSessionSummary(wire: Wire<ISessionSummary>): ISessionSummary {
	return {
		...wire,
		resource: URI.parse(wire.resource),
	};
}

export function serializeSessionSummary(obj: ISessionSummary): Wire<ISessionSummary> {
	return {
		...obj,
		resource: obj.resource.toString(),
	};
}

export function reviveSnapshot(wire: Wire<ISnapshot>): ISnapshot {
	return {
		...wire,
		resource: URI.parse(wire.resource),
	};
}

export function serializeSnapshot(obj: ISnapshot): Wire<ISnapshot> {
	return {
		...obj,
		resource: obj.resource.toString(),
	};
}

export function reviveInitializeParams(wire: Wire<IInitializeParams>): IInitializeParams {
	return {
		...wire,
		initialSubscriptions: wire.initialSubscriptions?.map(s => URI.parse(s)),
	};
}

export function serializeInitializeParams(obj: IInitializeParams): Wire<IInitializeParams> {
	return {
		...obj,
		initialSubscriptions: obj.initialSubscriptions?.map(u => u.toString()),
	};
}

export function reviveReconnectParams(wire: Wire<IReconnectParams>): IReconnectParams {
	return {
		...wire,
		subscriptions: wire.subscriptions.map(s => URI.parse(s)),
	};
}

export function serializeReconnectParams(obj: IReconnectParams): Wire<IReconnectParams> {
	return {
		...obj,
		subscriptions: obj.subscriptions.map(u => u.toString()),
	};
}

export function reviveSubscribeParams(wire: Wire<ISubscribeParams>): ISubscribeParams {
	return {
		...wire,
		resource: URI.parse(wire.resource),
	};
}

export function serializeSubscribeParams(obj: ISubscribeParams): Wire<ISubscribeParams> {
	return {
		...obj,
		resource: obj.resource.toString(),
	};
}

export function reviveUnsubscribeParams(wire: Wire<IUnsubscribeParams>): IUnsubscribeParams {
	return {
		...wire,
		resource: URI.parse(wire.resource),
	};
}

export function serializeUnsubscribeParams(obj: IUnsubscribeParams): Wire<IUnsubscribeParams> {
	return {
		...obj,
		resource: obj.resource.toString(),
	};
}

