server {
  listen 80;
  server_name hemayatvam.ir;
  return 301 https://$host$request_uri;
}
server {
  listen 443 ssl;
  server_name hemayatvam.ir;
  gzip on;
  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;
  location /api/ { proxy_pass http://app:5000/; }
  location / { proxy_pass http://client:80/; }
}
