blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/getnodus/solo/discussions
    about: Please ask questions and discuss ideas here.
  - name: Extension Development
    url: https://github.com/getnodus/solo/discussions/categories/extensions
    about: Questions and ideas for building extensions and customizations.
