global class SubmitFormData {
	global SubmitFormData() { }
	global Object clone() { }
	global String getButtonClicked() { }
	global String getOldSelectedValue(String fieldId) { }
	global List<String> getOldSelectedValues(String fieldId) { }
	global String getOldStringValue(String fieldId) { }
	global String getSelectedValue(String fieldId) { }
	global List<String> getSelectedValues(String fieldId) { }
	global String getStringValue(String fieldId) { }

}