/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { localize } from '../../../nls.js';

export function createSessionComparisonJudgePrompt(comparisonId: string): string {
	return localize('sessionComparison.judgePrompt', "Judge implementation comparison `{0}`.\n\n1. Call `#readAttemptComparison` exactly once with this comparison ID.\n2. Review every attempt's code changes and validation evidence. Use `get_session_context` with the exact manifest target to identify validation that the attempt already completed. Terminal commands start in the Judge worktree, not an attempt worktree, so explicitly `cd` to the exact `worktree.workingDirectory` from the manifest in every command that inspects or validates an attempt.\n3. Do not rerun a validation category when the attempt report contains a clear result. Run only missing targeted tests, build, lint, or diagnostics needed to make a reliable recommendation. If required dependencies or build artifacts are unavailable, record that validation as unavailable; do not install or build dependencies, and do not substitute a different validation category.\n4. For each validation category, record one consistent `state` and `source` evidence pair. Known `passed` or `failed` results must use `attemptReport` or `judgeRun`; use `unavailable` only with `notRun` or `unknown`, and use `notApplicable` for both fields when the category genuinely does not apply.\n5. Keep `explanation` to one sentence. Fill `rationale` with exactly four concise points in this order: `comparison`, `validation`, `codeQuality`, and `solution`. Each point must cite concrete evidence, contain no line breaks, and stay within the tool schema length limit. For every other attempt, record its strongest reusable points in `notableDifferences`.\n6. Identify semantic `decisionSections` where attempts make meaningfully different implementation choices. Each section may span related files. Give it a stable ID, short title, plain-language summary, affected repository-relative files, one concise option per relevant `attemptNumber`, and a recommended `attemptNumber`. Rate every option as `better`, `neutral`, or `worse` relative to the other approaches using concrete code and validation evidence; the recommended option must be rated `better`. Return an empty array when there are no meaningful choices. Do not use raw line numbers as section identity.\n7. Do not modify, merge, apply, or delete any attempt.\n8. Call `#completeAttemptComparison` with the recommendation and supporting evidence. Refer to attempts only by the `attemptNumber` values returned by `#readAttemptComparison`; do not copy participant or session UUIDs. If it rejects invalid input, correct the reported fields and retry; do not submit again after success.\n9. After the tool returns, identify the winner as `Attempt N (agent, model, effort)` and use the same rationale order, followed by the strongest reusable points from every other attempt.", comparisonId);
}
