global class PlaceSalesTransactionExecutor {
	global PlaceSalesTransactionExecutor() { }
	global Object clone() { }
	global static RevSalesTrxn.PlaceSalesTransactionResponse execute(RevSalesTrxn.GraphRequest graphRequest, RevSalesTrxn.PricingPreferenceEnum pricingPreferenceEnum, RevSalesTrxn.ConfigurationExecutionEnum configurationExecutionEnum, RevSalesTrxn.ConfigurationOptionsInput configuratorOptions, String id, RevSalesTrxn.CatalogRatesPreferenceEnum catalogRatesPreferenceEnum) { }
	global static RevSalesTrxn.PlaceSalesTransactionResponse execute(RevSalesTrxn.GraphRequest graphRequest, RevSalesTrxn.PricingPreferenceEnum pricingPreferenceEnum, RevSalesTrxn.ConfigurationExecutionEnum configurationExecutionEnum, RevSalesTrxn.ConfigurationOptionsInput configuratorOptions, String id) { }

}