FROM node:20-alpine AS deps
WORKDIR /app
COPY server/package*.json ./
RUN npm ci

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY server .
EXPOSE 5000
CMD ["node", "server.js"]
