/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
'use strict';

import * as assert from 'assert';
import {decodeTextMateToken, DecodeMap} from 'vs/editor/node/textMate/TMSyntax';

suite('textMate', () => {

	test('decodeTextMateToken', () => {
		let decodeMap = new DecodeMap();

		let input = getTestScopes();
		let actual:string[] = [];
		for (let i = 0, len = input.length; i < len; i++) {
			actual.push(decodeTextMateToken(decodeMap, input[i]));
		}

		let expected = [
			'meta function js decl block type parameters paren cover object method declaration field member entity ',
			'meta function js decl block type parameters paren cover object method declaration field member parameter brace ',
			'meta function js decl block type parameters paren cover object method declaration field member parameter ',
			'meta function js decl block type parameters paren cover object method declaration field member name parameter ',
			'meta function js decl block type parameters paren cover object method declaration field member parameter ',
			'meta function js decl block type parameters paren cover object method declaration field member name parameter ',
			'meta function js decl block type parameters paren cover object method declaration field member parameter ',
			'meta function js decl block type parameters paren cover object method declaration field member name parameter ',
			'meta function js decl block type parameters paren cover object method declaration field member parameter brace round ',
			'meta function js decl block type parameters paren cover object method declaration field member ',
			'meta function js decl block type parameters paren cover object method declaration field member entity name ',
			'meta function js decl block type parameters paren cover object method declaration field member parameter brace round ',
			'meta function js decl block type parameters paren cover object method declaration field member name parameter variable ',
			'meta function js decl block type parameters paren cover object method declaration field member parameter brace round ',
			'meta function js decl block type parameters paren cover object method declaration field member ',
			'meta function js decl block type parameters paren cover object method declaration field member brace ',
			'meta function js decl block type parameters paren cover object method declaration field member ',
			'meta function js decl block type parameters paren cover object method declaration field member keyword operator ',
			'meta function js decl block type parameters paren cover object method declaration field member string ',
			'meta function js decl block type parameters paren cover object method declaration field member string ',
			'meta function js decl block type parameters paren cover object method declaration field member string ',
			'meta function js decl block type parameters paren cover object method declaration field member keyword operator ',
			'meta function js decl block type parameters paren cover object method declaration field member ',
			'meta function js decl block type parameters paren cover object method declaration field member keyword operator ',
			'meta function js decl block type parameters paren cover object method declaration field member string double ',
			'meta function js decl block type parameters paren cover object method declaration field member string double ',
			'meta function js decl block type parameters paren cover object method declaration field member string double ',
			'meta function js decl block type parameters paren cover object method declaration field member ',
			'meta function js decl block type parameters paren cover object method declaration field member brace array literal ',
			'meta function js decl block type parameters paren cover object method declaration field member array literal ',
			'meta function js decl block type parameters paren cover object method declaration field member brace array literal ',
			'meta function js decl block type parameters paren cover object method declaration field member keyword operator comparison ',
			'meta function js decl block type parameters paren cover object method declaration field member ',
			'meta function js decl block type parameters paren cover object method declaration field member brace curly ',
			'meta function js decl block type parameters paren cover object method declaration field member brace curly ',
			'meta function js decl block type parameters paren cover object method declaration field member name ',
			'meta function js decl block type parameters paren cover object method declaration field member ',
			'meta function js decl block type parameters paren cover object method declaration field member name ',
			'meta function js decl block type parameters paren cover object method declaration field member ',
			'meta function js decl block type parameters paren cover object method declaration field member '
		];

		assert.deepEqual(actual, expected);
	});
});

function getTestScopes():string[][] {
	return [
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','entity.name.function.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js','meta.brace.round.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js','parameter.name.js','variable.parameter.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js','parameter.name.js','variable.parameter.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js','parameter.name.js','variable.parameter.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js','meta.brace.round.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.method.overload.declaration.js','entity.name.function.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js','meta.brace.round.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js','parameter.name.js','variable.parameter.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.function.type.parameter.js','meta.brace.round.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.brace.curly.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','keyword.operator.comparison.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','string.double.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','string.double.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','string.double.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','keyword.operator.arithmetic.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','keyword.operator.arithmetic.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','string.double.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','string.double.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','string.double.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.array.literal.js','meta.brace.square.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.array.literal.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.array.literal.js','meta.brace.square.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','keyword.operator.comparison.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.brace.curly.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.brace.curly.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.type.name.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.type.name.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js'],
		['source.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.block.js','meta.type.parameters.js','meta.type.paren.cover.js','meta.object.type.js','meta.field.declaration.js','meta.block.js','meta.object.member.js','meta.function.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.object.type.js','meta.method.declaration.js','meta.decl.block.js','meta.type.parameters.js','meta.type.paren.cover.js']
	];
}
