global class LayoutItem {
	global Metadata.AnalyticsCloudComponentLayoutItem analyticsCloudComponent;
	global Metadata.UiBehavior behavior;
	global String canvas;
	global String component;
	global String customLink;
	global Boolean emptySpace;
	global String field;
	global Integer height;
	global String page_x;
	global Metadata.ReportChartComponentLayoutItem reportChartComponent;
	global String scontrol;
	global Boolean showLabel;
	global Boolean showScrollbars;
	global String width;
	global LayoutItem() { }
	global Object clone() { }

}