global class OmniInteractionAccessConfig {
	global String configName;
	global Boolean isAsyncCardCachingEnabled;
	global Boolean isCardApexRemoteDisabled;
	global Boolean isCardCacheDisabled;
	global Boolean isCardDataTfrmDisabled;
	global Boolean isCardIntegrationProcDisabled;
	global Boolean isCardRestApiDisabled;
	global Boolean isCardSoqlDisabled;
	global Boolean isCardSoslDisabled;
	global Boolean isCardStreamingApiDisabled;
	global Boolean isDataTfrmEncrpFieldsDisabled;
	global String masterLabel;
	global String setupOwner;
	global OmniInteractionAccessConfig() { }
	global Object clone() { }

}