global class SidebarComponent {
	global String componentType;
	global String createAction;
	global Boolean enableLinking;
	global Integer height;
	global Boolean knowledgeOneEnable;
	global String label;
	global String lookup;
	global String page_x;
	global List<Metadata.RelatedList> relatedLists;
	global String unit;
	global String updateAction;
	global Integer width;
	global SidebarComponent() { }
	global Object clone() { }

}