# :Actions''
Actions :AUTOMATE''
AUTOMATE:-'Step''
__reactFiber$15n3m9f9xh1
: 
TC {tag: 5, key: null, elementType: 'div', type: 'div', stateNode: div.sc-bcXHqe.sc-gswNZR.dEwKFb.bbLVwL, …}
__reactProps$15n3m9f9xh1
: 
{children: {…}, className: 'sc-bcXHqe sc-gswNZR dEwKFb bbLVwL'}
_fs
: 
94
accessKey
: 
""
align
: 
""
ariaAtomic
: 
null
ariaAutoComplete
: 
null
ariaBrailleLabel
: 
null
ariaBrailleRoleDescription
: 
null
ariaBusy
: 
null
ariaChecked
: 
null
ariaColCount
: 
null
ariaColIndex
: 
null
ariaColSpan
: 
null
ariaCurrent
: 
null
ariaDescription
: 
null
ariaDisabled
: 
null
ariaExpanded
: 
null
ariaHasPopup
: 
null
ariaHidden
: 
null
ariaInvalid
: 
null
ariaKeyShortcuts
: 
null
ariaLabel
: 
null
ariaLevel
: 
null
ariaLive
: 
null
ariaModal
: 
null
ariaMultiLine
: 
null
ariaMultiSelectable
: 
null
ariaOrientation
: 
null
ariaPlaceholder
: 
null
ariaPosInSet
: 
null
ariaPressed
: 
null
ariaReadOnly
: 
null
ariaRelevant
: 
null
ariaRequired
: 
null
ariaRoleDescription
: 
null
ariaRowCount
: 
null
ariaRowIndex
: 
null
ariaRowSpan
: 
null
ariaSelected
: 
null
ariaSetSize
: 
null
ariaSort
: 
null
ariaValueMax
: 
null
ariaValueMin
: 
null
ariaValueNow
: 
null
ariaValueText
: 
null
assignedSlot
: 
null
attributeStyleMap
: 
StylePropertyMap {size: 0}
attributes
: 
NamedNodeMap {0: class, class: class, length: 1}
autocapitalize
: 
""
autofocus
: 
false
baseURI
: 
"https://intuit.chilipiper.com/book/reschedule?rescheduleId=63df43e2c6223b3d924de7b6"
childElementCount
: 
1
childNodes
: 
NodeList [div.sc-bcXHqe.sc-gswNZR.eCJhfc.bbLVwL]
children
: 
HTMLCollection [div.sc-bcXHqe.sc-gswNZR.eCJhfc.bbLVwL]
classList
: 
DOMTokenList(4) ['sc-bcXHqe', 'sc-gswNZR', 'dEwKFb', 'bbLVwL', value: 'sc-bcXHqe sc-gswNZR dEwKFb bbLVwL']
className
: 
"sc-bcXHqe sc-gswNZR dEwKFb bbLVwL"
clientHeight
: 
140
clientLeft
: 
0
clientTop
: 
0
clientWidth
: 
746
contentEditable
: 
"inherit"
dataset
: 
DOMStringMap {}
dir
: 
""
draggable
: 
false
elementTiming
: 
""
enterKeyHint
: 
""
firstChild
: 
div.sc-bcXHqe.sc-gswNZR.eCJhfc.bbLVwL
firstElementChild
: 
div.sc-bcXHqe.sc-gswNZR.eCJhfc.bbLVwL
hidden
: 
false
id
: 
""
inert
: 
false
innerHTML
: 
"<div data-chili-css=\"previous-pick\" class=\"sc-bcXHqe sc-gswNZR eCJhfc bbLVwL\"><div class=\"sc-bcXHqe\"><div class=\"sc-bcXHqe\"><span data-test-id=\"previous-date-time-pick\" color=\"neutral-dark-80\" font-size=\"12\" font-weight=\"600\" data-chili-css=\"previous-pick-title\" class=\"sc-gKPRtg sc-iBYQkv UlkmW\">Previous schedule</span></div><div class=\"sc-bcXHqe\"><span data-chili-css=\"previous-pick-date\" font-weight=\"500\" color=\"neutral-dark-100\" class=\"sc-gKPRtg sc-iBYQkv cHQEiy\">Tuesday, Feb 7th 8:30 AM - 9:00 AM</span></div></div></div>"
innerText
: 
"Previous schedule\nTuesday, Feb 7th 8:30 AM - 9:00 AM"
inputMode
: 
""
isConnected
: 
true
isContentEditable
: 
false
lang
: 
""
lastChild
: 
div.sc-bcXHqe.sc-gswNZR.eCJhfc.bbLVwL
lastElementChild
: 
div.sc-bcXHqe.sc-gswNZR.eCJhfc.bbLVwL
localName
: 
"div"
namespaceURI
: 
"http://www.w3.org/1999/xhtml"
nextElementSibling
: 
div.fabe-days-chooser-holder
nextSibling
: 
div.fabe-days-chooser-holder
nodeName
: 
"DIV"
nodeType
: 
1
nodeValue
: 
null
nonce
: 
""
offsetHeight
: 
140
offsetLeft
: 
0
offsetParent
: 
div#root.mount
offsetTop
: 
68
offsetWidth
: 
746
onabort
: 
null
onanimationend
: 
null
onanimationiteration
: 
null
onanimationstart
: 
null
onauxclick
: 
null
onbeforecopy
: 
null
onbeforecut
: 
null
onbeforeinput
: 
null
onbeforematch
: 
null
onbeforepaste
: 
null
onbeforexrselect
: 
null
onblur
: 
null
oncancel
: 
null
oncanplay
: 
null
oncanplaythrough
: 
null
onchange
: 
null
onclick
: 
null
onclose
: 
null
oncontentvisibilityautostatechange
: 
null
oncontextlost
: 
null
oncontextmenu
: 
null
oncontextrestored
: 
null
oncopy
: 
null
oncuechange
: 
null
oncut
: 
null
ondblclick
: 
null
ondrag
: 
null
ondragend
: 
null
ondragenter
: 
null
ondragleave
: 
null
ondragover
: 
null
ondragstart
: 
null
ondrop
: 
null
ondurationchange
: 
null
onemptied
: 
null
onended
: 
null
onerror
: 
null
onfocus
: 
null
onformdata
: 
null
onfullscreenchange
: 
null
onfullscreenerror
: 
null
ongotpointercapture
: 
null
oninput
: 
null
oninvalid
: 
null
onkeydown
: 
null
onkeypress
: 
null
onkeyup
: 
null
onload
: 
null
onloadeddata
: 
null
onloadedmetadata
: 
null
onloadstart
: 
null
onlostpointercapture
: 
null
onmousedown
: 
null
onmouseenter
: 
null
onmouseleave
: 
null
onmousemove
: 
null
onmouseout
: 
null
onmouseover
: 
null
onmouseup
: 
null
onmousewheel
: 
null
onpaste
: 
null
onpause
: 
null
onplay
: 
null
onplaying
: 
null
onpointercancel
: 
null
onpointerdown
: 
null
onpointerenter
: 
null
onpointerleave
: 
null
onpointermove
: 
null
onpointerout
: 
null
onpointerover
: 
null
onpointerrawupdate
: 
null
onpointerup
: 
null
onprogress
: 
null
onratechange
: 
null
onreset
: 
null
onresize
: 
null
onscroll
: 
null
onsearch
: 
null
onsecuritypolicyviolation
: 
null
onseeked
: 
null
onseeking
: 
null
onselect
: 
null
onselectionchange
: 
null
onselectstart
: 
null
onslotchange
: 
null
onstalled
: 
null
onsubmit
: 
null
onsuspend
: 
null
ontimeupdate
: 
null
ontoggle
: 
null
ontransitioncancel
: 
null
ontransitionend
: 
null
ontransitionrun
: 
null
ontransitionstart
: 
null
onvolumechange
: 
null
onwaiting
: 
null
onwebkitanimationend
: 
null
onwebkitanimationiteration
: 
null
onwebkitanimationstart
: 
null
onwebkitfullscreenchange
: 
null
onwebkitfullscreenerror
: 
null
onwebkittransitionend
: 
null
onwheel
: 
null
outerHTML
: 
"<div class=\"sc-bcXHqe sc-gswNZR dEwKFb bbLVwL\"><div data-chili-css=\"previous-pick\" class=\"sc-bcXHqe sc-gswNZR eCJhfc bbLVwL\"><div class=\"sc-bcXHqe\"><div class=\"sc-bcXHqe\"><span data-test-id=\"previous-date-time-pick\" color=\"neutral-dark-80\" font-size=\"12\" font-weight=\"600\" data-chili-css=\"previous-pick-title\" class=\"sc-gKPRtg sc-iBYQkv UlkmW\">Previous schedule</span></div><div class=\"sc-bcXHqe\"><span data-chili-css=\"previous-pick-date\" font-weight=\"500\" color=\"neutral-dark-100\" class=\"sc-gKPRtg sc-iBYQkv cHQEiy\">Tuesday, Feb 7th 8:30 AM - 9:00 AM</span></div></div></div></div>"
outerText
: 
"Previous schedule\nTuesday, Feb 7th 8:30 AM - 9:00 AM"
ownerDocument
: 
document
parentElement
: 
div.fabe-availability-mobile
parentNode
: 
div.fabe-availability-mobile
part
: 
DOMTokenList [value: '']
prefix
: 
null
previousElementSibling
: 
div.sc-bcXHqe.sc-gswNZR.sc-cjibBx.haApEU.bbLVwL.gVzCvX.fabe-book-with-holder-wrapper
previousSibling
: 
div.sc-bcXHqe.sc-gswNZR.sc-cjibBx.haApEU.bbLVwL.gVzCvX.fabe-book-with-holder-wrapper
role
: 
null
scrollHeight
: 
140
scrollLeft
: 
0
scrollTop
: 
0
scrollWidth
: 
746
shadowRoot
: 
null
slot
: 
""
spellcheck
: 
true
style
: 
CSSStyleDeclaration {accentColor: '', additiveSymbols: '', alignContent: '', alignItems: '', alignSelf: '', …}
tabIndex
: 
-1
tagName
: 
"DIV"
textContent
: 
"Previous scheduleTuesday, Feb 7th 8:30 AM - 9:00 AM"
title
: 
""
translate
: 
true
virtualKeyboardPolicy
: 
:Build::"
:BEGIN::
:GLOW4::
:Build::
:__reactEventHandlers$6obajd0qf4v
: 
{className: 'trial-learn-image', src: 'https://plugin.intuitcdn.net/qbo-qblive-ui/ceb40a3fd37f4ea18e0b.jpg', alt: 'Smiling bookkeeper image'}
__reactInternalInstance$6obajd0qf4v
: 
Fj {tag: 5, key: null, elementType: 'img', type: 'img', stateNode: img.trial-learn-image, …}
accessKey
: 
""
align
: 
""
alt
: 
"Smiling bookkeeper image"
ariaAtomic
: 
null
ariaAutoComplete
: 
null
ariaBrailleLabel
: 
null
ariaBrailleRoleDescription
: 
null
ariaBusy
: 
null
ariaChecked
: 
null
ariaColCount
: 
null
ariaColIndex
: 
null
ariaColSpan
: 
null
ariaCurrent
: 
null
ariaDescription
: 
null
ariaDisabled
: 
null
ariaExpanded
: 
null
ariaHasPopup
: 
null
ariaHidden
: 
null
ariaInvalid
: 
null
ariaKeyShortcuts
: 
null
ariaLabel
: 
null
ariaLevel
: 
null
ariaLive
: 
null
ariaModal
: 
null
ariaMultiLine
: 
null
ariaMultiSelectable
: 
null
ariaOrientation
: 
null
ariaPlaceholder
: 
null
ariaPosInSet
: 
null
ariaPressed
: 
null
ariaReadOnly
: 
null
ariaRelevant
: 
null
ariaRequired
: 
null
ariaRoleDescription
: 
null
ariaRowCount
: 
null
ariaRowIndex
: 
null
ariaRowSpan
: 
null
ariaSelected
: 
null
ariaSetSize
: 
null
ariaSort
: 
null
ariaValueMax
: 
null
ariaValueMin
: 
null
ariaValueNow
: 
null
ariaValueText
: 
null
assignedSlot
: 
null
attributeStyleMap
: 
StylePropertyMap
size
: 
0
[[Prototype]]
: 
StylePropertyMap
attributes
: 
NamedNodeMap
0
: 
class
1
: 
src
2
: 
alt
alt
: 
alt
class
: 
class
src
: 
src
length
: 
3
[[Prototype]]
: 
NamedNodeMap
autocapitalize
: 
""
autofocus
: 
false
baseURI
: 
"https://app.qbo.intuit.com/app/livebookkeeping-triallearnmore"
border
: 
""
childElementCount
: 
0
childNodes
: 
NodeList []
children
: 
HTMLCollection(0)
length
: 
0
[[Prototype]]
: 
HTMLCollection
classList
: 
DOMTokenList(1)
0
: 
"trial-learn-image"
length
: 
1
value
: 
"trial-learn-image"
[[Prototype]]
: 
DOMTokenList
className
: 
"trial-learn-image"
clientHeight
: 
0
clientLeft
: 
0
clientTop
: 
0
clientWidth
: 
0
complete
: 
true
contentEditable
: 
"inherit"
crossOrigin
: 
null
currentSrc
: 
"https://plugin.intuitcdn.net/qbo-qblive-ui/ceb40a3fd37f4ea18e0b.jpg"
dataset
: 
DOMStringMap
[[Prototype]]
: 
DOMStringMap
constructor
: 
ƒ DOMStringMap()
arguments
: 
null
caller
: 
null
length
: 
0
name
: 
"DOMStringMap"
prototype
: 
DOMStringMap {Symbol(Symbol.toStringTag): 'DOMStringMap', constructor: ƒ}
[[Prototype]]
: 
ƒ ()
Symbol(Symbol.toStringTag)
: 
"DOMStringMap"
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()
decoding
: 
"auto"
dir
: 
""
draggable
: 
true
elementTiming
: 
""
enterKeyHint
: 
""
fetchPriority
: 
"auto"
firstChild
: 
null
firstElementChild
: 
null
height
: 
863
hidden
: 
false
hspace
: 
0
id
: 
""
inert
: 
false
innerHTML
: 
""
innerText
: 
""
inputMode
: 
""
isConnected
: 
true
isContentEditable
: 
false
isMap
: 
false
lang
: 
""
lastChild
: 
null
lastElementChild
: 
null
loading
: 
"auto"
localName
: 
"img"
longDesc
: 
""
lowsrc
: 
""
name
: 
""
namespaceURI
: 
"http://www.w3.org/1999/xhtml"
naturalHeight
: 
863
naturalWidth
: 
943
nextElementSibling
: 
null
nextSibling
: 
null
nodeName
: 
"IMG"
nodeType
: 
1
nodeValue
: 
null
nonce
: 
""
offsetHeight
: 
0
offsetLeft
: 
0
offsetParent
: 
null
offsetTop
: 
0
offsetWidth
: 
0
onabort
: 
null
onanimationend
: 
null
onanimationiteration
: 
null
onanimationstart
: 
null
onauxclick
: 
null
onbeforecopy
: 
null
onbeforecut
: 
null
onbeforeinput
: 
null
onbeforematch
: 
null
onbeforepaste
: 
null
onbeforexrselect
: 
null
onblur
: 
null
oncancel
: 
null
oncanplay
: 
null
oncanplaythrough
: 
null
onchange
: 
null
onclick
: 
null
onclose
: 
null
oncontentvisibilityautostatechange
: 
null
oncontextlost
: 
null
oncontextmenu
: 
null
oncontextrestored
: 
null
oncopy
: 
null
oncuechange
: 
null
oncut
: 
null
ondblclick
: 
null
ondrag
: 
null
ondragend
: 
null
ondragenter
: 
null
ondragleave
: 
null
ondragover
: 
null
ondragstart
: 
null
ondrop
: 
null
ondurationchange
: 
null
onemptied
: 
null
onended
: 
null
onerror
: 
null
onfocus
: 
null
onformdata
: 
null
onfullscreenchange
: 
null
onfullscreenerror
: 
null
ongotpointercapture
: 
null
oninput
: 
null
oninvalid
: 
null
onkeydown
: 
null
onkeypress
: 
null
onkeyup
: 
null
onload
: 
null
onloadeddata
: 
null
onloadedmetadata
: 
null
onloadstart
: 
null
onlostpointercapture
: 
null
onmousedown
: 
null
onmouseenter
: 
null
onmouseleave
: 
null
onmousemove
: 
null
onmouseout
: 
null
onmouseover
: 
null
onmouseup
: 
null
onmousewheel
: 
null
onpaste
: 
null
onpause
: 
null
onplay
: 
null
onplaying
: 
null
onpointercancel
: 
null
onpointerdown
: 
null
onpointerenter
: 
null
onpointerleave
: 
null
onpointermove
: 
null
onpointerout
: 
null
onpointerover
: 
null
onpointerrawupdate
: 
null
onpointerup
: 
null
onprogress
: 
null
onratechange
: 
null
onreset
: 
null
onresize
: 
null
onscroll
: 
null
onsearch
: 
null
onsecuritypolicyviolation
: 
null
onseeked
: 
null
onseeking
: 
null
onselect
: 
null
onselectionchange
: 
null
onselectstart
: 
null
onslotchange
: 
null
onstalled
: 
null
onsubmit
: 
null
onsuspend
: 
null
ontimeupdate
: 
null
ontoggle
: 
null
ontransitioncancel
: 
null
ontransitionend
: 
null
ontransitionrun
: 
null
ontransitionstart
: 
null
onvolumechange
: 
null
onwaiting
: 
null
onwebkitanimationend
: 
null
onwebkitanimationiteration
: 
null
onwebkitanimationstart
: 
null
onwebkitfullscreenchange
: 
null
onwebkitfullscreenerror
: 
null
onwebkittransitionend
: 
null
onwheel
: 
null
outerHTML
: 
"<img class=\"trial-learn-image\" src=\"https://plugin.intuitcdn.net/qbo-qblive-ui/ceb40a3fd37f4ea18e0b.jpg\" alt=\"Smiling bookkeeper image\">"
outerText
: 
""
ownerDocument
: 
document
location
: 
Location
ancestorOrigins
: 
DOMStringList {length: 0}
assign
: 
ƒ assign()
hash
: 
""
host
: 
"app.qbo.intuit.com"
hostname
: 
"app.qbo.intuit.com"
href
: 
"https://app.qbo.intuit.com/app/livebookkeeping-triallearnmore"
origin
: 
"https://app.qbo.intuit.com"
pathname
: 
"/app/livebookkeeping-triallearnmore"
port
: 
""
protocol
: 
"https:"
reload
: 
ƒ reload()
replace
: 
ƒ replace()
search
: 
""
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
Symbol(Symbol.toPrimitive)
: 
undefined
[[Prototype]]
: 
Location
registerElement
: 
ƒ (n,r)
length
: 
2
name
: 
""
prototype
: 
{constructor: ƒ}
arguments
: 
(...)
caller
: 
(...)
[[FunctionLocation]]
: 
<unknown>
[[Prototype]]
: 
ƒ ()
URL
: 
"https://app.qbo.intuit.com/app/livebookkeeping-triallearnmore"
activeElement
: 
body
aLink
: 
""
accessKey
: 
""
ariaAtomic
: 
null
ariaAutoComplete
: 
null
ariaBrailleLabel
: 
null
ariaBrailleRoleDescription
: 
null
ariaBusy
: 
null
ariaChecked
: 
null
ariaColCount
: 
null
ariaColIndex
: 
null
ariaColSpan
: 
null
ariaCurrent
: 
null
ariaDescription
: 
null
ariaDisabled
: 
null
ariaExpanded
: 
null
ariaHasPopup
: 
null
ariaHidden
: 
null
ariaInvalid
: 
null
ariaKeyShortcuts
: 
null
ariaLabel
: 
null
ariaLevel
: 
null
ariaLive
: 
null
ariaModal
: 
null
ariaMultiLine
: 
null
ariaMultiSelectable
: 
null
ariaOrientation
: 
null
ariaPlaceholder
: 
null
ariaPosInSet
: 
null
ariaPressed
: 
null
ariaReadOnly
: 
null
ariaRelevant
: 
null
ariaRequired
: 
null
ariaRoleDescription
: 
null
ariaRowCount
: 
null
ariaRowIndex
: 
null
ariaRowSpan
: 
null
ariaSelected
: 
null
ariaSetSize
: 
null
ariaSort
: 
null
ariaValueMax
: 
null
ariaValueMin
: 
null
ariaValueNow
: 
null
ariaValueText
: 
null
assignedSlot
: 
null
attributeStyleMap
: 
StylePropertyMap {size: 0}
attributes
: 
NamedNodeMap {length: 0}
autocapitalize
: 
""
autofocus
: 
false
background
: 
""
baseURI
: 
"https://app.qbo.intuit.com/app/livebookkeeping-triallearnmore"
bgColor
: 
""
childElementCount
: 
38
childNodes
: 
NodeList(38) [div#web-shell-spinner.idsTSIShortSpinner.IndeterminateShort-wrapper.hide-spinner, script, div#___appshell, div#independentWidgetManagerNode, div#leftNavPortal, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div.after-navigation-container, div, div#adsbox.adsbox, div.vep-collab-smlk-ui-host, div#smartlook-tto-widget.CobrowseHostStyledstyled__NowSharingBorder-mf5w7t-2.jTALEn, script#cobrowsescript, iframe#ensighten-iframe]
children
: 
HTMLCollection(38) [div#web-shell-spinner.idsTSIShortSpinner.IndeterminateShort-wrapper.hide-spinner, script, div#___appshell, div#independentWidgetManagerNode, div#leftNavPortal, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div, div.after-navigation-container, div, div#adsbox.adsbox, div.vep-collab-smlk-ui-host, div#smartlook-tto-widget.CobrowseHostStyledstyled__NowSharingBorder-mf5w7t-2.jTALEn, script#cobrowsescript, iframe#ensighten-iframe, web-shell-spinner: div#web-shell-spinner.idsTSIShortSpinner.IndeterminateShort-wrapper.hide-spinner, ___appshell: div#___appshell, independentWidgetManagerNode: div#independentWidgetManagerNode, leftNavPortal: div#leftNavPortal, adsbox: div#adsbox.adsbox, …]
classList
: 
DOMTokenList [value: '']
className
: 
""
clientHeight
: 
817
clientLeft
: 
0
clientTop
: 
0
clientWidth
: 
994
contentEditable
: 
"inherit"
dataset
: 
DOMStringMap {}
dir
: 
""
draggable
: 
false
elementTiming
: 
""
enterKeyHint
: 
""
firstChild
: 
div#web-shell-spinner.idsTSIShortSpinner.IndeterminateShort-wrapper.hide-spinner
firstElementChild
: 
div#web-shell-spinner.idsTSIShortSpinner.IndeterminateShort-wrapper.hide-spinner
hidden
: 
false
id
: 
""
inert
: 
false
innerHTML
: 
"<div id=\"web-shell-spinner\" class=\"idsTSIShort
innerText
: 
"＋\nNew\nMENU\nGet things done\nBusiness overview\nBanking\nGet paid & pay\nCustomers & leads\nCommerce\nPayroll\nBookkeeping\nTaxes\nApps\nMore (0)\nBOOKMARKS\nBank transactions\nLive Bookkeeping\nPPP center\nCapital\nBusiness overview\nCash flow\nReports\nWorkers' comp\nVendors\nTime overview\nTime entries\nTags\nSales tax\nRules\nReconcile\nReceipts\nQuickBooks Checking\nProducts & services\nPayouts\nPayment links\nOrders\nMy policies\nFind apps\nContractors\nApp transactions\nAll sales\nMenu settings\nZACHRY T WOOD\nZ\nTrusted experts. Guaranteed accurate books.\nGet paired with a QuickBooks-certified bookkeeper who understands your business and does your books for you with guaranteed accuracy.\nGet your price\nGet a free consultation\n;\nFocus on your business, not your books\nMore time each day\nCustomers who use QuickBooks Live report saving an average of 10 hours every month, so they can focus more on their business.\nProven expertise\n8 out of 10 customers recommend QuickBooks Live Bookkeeping to manage and maintain their books.\nTotal peace of mind\n86% of customers agree QuickBooks Live Bookkeeping gives them peace of mind their books will be ready by tax time.\nWhat Live Bookkeepers do for you\nA QuickBooks-certified bookkeeper will bring your existing financials up to date to get you started with a clean slate. Next, you’ll get matched with a virtual bookkeeper who will maintain your books and connect with you via video chat.\n81% of our customers agree they can seamlessly collaborate with their QuickBooks Live Bookkeepers on their books.\nHow it works\n1\nStart with a clean slate\nFirst, a bookkeeper reviews your chart of accounts and past transactions to bring your books up to date.\n2\nWork together on the go\nNext, you’ll be matched with a dedicated bookkeeper that’s the right fit to manage your monthly books. Get updates, set up video calls, or send questions via messages.\n3\nFocus on your business\nYour bookkeeper can run detailed reports that give you a clear view of your business, so you have the info you need to make informed decisions and feel confident at tax time.\nGet your price\nThousands of businesses use QuickBooks Live Bookkeeping\n\nWith QuickBooks Live bookkeeping, I have more time to focus on the happiness and well-being for my employees.\n\nJaclyn Wenaas, Owner of Little John's Yarn\n\nWhen I asked a question to my bookkeeper, she broke it down very well so I could understand how my books were doing.\n\nAlysha Littlejohn, Owner of Bronzed Denver\n\nWith bookkeeping in the back of my mind, I have more time to work with more clients for my business.\n\nDavid Lampe, Principal Team Inc.\n\nWe do your books, so you can get back to business.\nFull-Service Bookkeeping\nGet your past books clean and up to date. Then, get paired with a dedicated bookkeeper who keeps your books accurate and ready for tax time.\nGet your price\nCleanup\nYour one-time fee for cleanup is based on how long it's been since you filed business taxes.\nMonthly bookkeeping\nYour monthly price is based on your average business expenses for the last 3 months.\nExpense levels\tMonthly price\n$0 - 10,000/month\t$200\n$10,001 - 50,000/month\t$300\n$50,001+/month\t$400\nCleanup\n$500\nbased on last filed tax year\nOne-time fee due at signup\nReconcile your past books and bring them up to date\nCustomize chart of accounts for your business\nCheck profit & loss and balance sheet for accuracy\nConnect bank and credit card accounts\nDeliver updated, accurate historical reports\nMonthly bookkeeping\n$200/month\nbased on business expenses\nFirst payment due in 30 days\nCategorize transactions\nReconcile accounts to ensure ongoing accuracy\nGenerate detailed business reports\nClose your books to ensure accuracy for tax time\nConvenient virtual support\nGet started\nIs QuickBooks Live Bookkeeping right for you?\nGet a free consultation\nFrequently Asked Questions\nWhat’s included in QuickBooks Live Full-Service Bookkeeping?\nFull-Service Bookkeeping includes three service phases: cleanup/setup, ongoing bookkeeping, and closed books.\nIn the cleanup/setup phase, your bookkeeper helps you set up your chart of accounts, connects your banks, and teaches you the basics of QuickBooks. If you have information in QuickBooks already, your bookkeeper will help clean it up in the first month of service.\nAs part of ongoing bookkeeping, your bookkeeper categorizes your transactions and reconciles your accounts.\nOnce that is completed, your bookkeeper closes your books and confirms they’re accurate by preparing a trial balance. They then send you PDF copies of key financial reports, including your profit and loss statement and balance sheet.\nWhat’s not included in the service?\nFull-Service Bookkeeping doesn’t include sending invoices, paying bills, or management of inventory, accounts receivable, or accounts payable. The service doesn’t include financial advisory services, tax advice, facilitating the filing of income or sales tax returns, creating or sending 1099s, or management of payroll. QuickBooks Online offers Full Service Payroll for an additional cost.\nHow is my team of bookkeepers organized?\nOnce you select QuickBooks Live Full-Service Bookkeeping, you’ll be connected with one of our certified bookkeeping teams based in the U.S. You can talk to your primary bookkeeper via one-way video chat.\nWhat qualifications do my bookkeepers have?\nBookkeeper qualifications include:\nExpertise in accounting, finance, or bookkeeping\nActive QuickBooks Online ProAdvisor certification\nMinimum one year of experience working with QuickBooks Online\nBookkeeper qualifications also include at least one of the following:\nActive Certified Public Accountant\nActive Certified Public Bookkeeper\nBachelor’s degree in Accounting/Finance\nHow often can I connect with my QuickBooks Live Bookkeeper?\nFor the best Full-Service bookkeeping experience, we recommend you check in with a member of your team at least once a month. Schedule a video call right inside QuickBooks Online or leave messages for your team whenever you have questions.\nWhat business information does my bookkeeper have access to?\nYour bookkeeping team only has access to your QuickBooks files, including the information you’ve uploaded into your QuickBooks account.\nWhen are my bookkeepers available?\nQuickBooks Live Bookkeepers schedule their availability for a set number of hours per week between 6:00 AM (PT) and 6:00 PM (PT) Mon–Fri. For example, one bookkeeper may be available 8 hours per day, 3 days a week, while another may be available 5 hours per day, 5 days a week. During the onboarding process, we’ll work to match you with a bookkeeper whose availability best matches yours.\nThere’s no contract, correct?\nThat’s right. There’s no contract or commitment for QuickBooks Live Full-Service Bookkeeping. You’re free to switch plans or cancel anytime.\nWhat’s the difference between QuickBooks Live Guided Setup and QuickBooks Full-Service Bookkeeping?\nQuickBooks Live Guided Setup is a one-time service in which a bookkeeper shows you how to get started in QuickBooks Online. Full-Service Bookkeeping is a monthly subscription for those who want a bookkeeper to manage their books for them on an ongoing basis. Full-service bookkeeping includes an initial setup.\nImportant offers, pricing details & disclaimers\nBookkeeping help is just a call away\n\nGet the most out of your QuickBooks experience. Call 800-682-2172 to speak with a bookkeeping specialist.\n\n "
inputMode
: 
""
isConnected
: 
true
isContentEditable
: 
false
lang
: 
""
lastChild
: 
iframe#ensighten-iframe
lastElementChild
: 
iframe#ensighten-iframe
link
: 
""
localName
: 
"body"
namespaceURI
: 
"http://www.w3.org/1999/xhtml"
nextElementSibling
: 
null
nextSibling
: 
null
nodeName
: 
"BODY"
nodeType
: 
1
nodeValue
: 
null
nonce
: 
""
offsetHeight
: 
817
offsetLeft
: 
0
offsetParent
: 
null
offsetTop
: 
0
offsetWidth
: 
994
onabort
: 
null
onafterprint
: 
null
onanimationend
: 
null
onanimationiteration
: 
null
onanimationstart
: 
null
onauxclick
: 
null
onbeforecopy
: 
null
onbeforecut
: 
null
onbeforeinput
: 
null
onbeforematch
: 
null
onbeforepaste
: 
null
onbeforeprint
: 
null
onbeforeunload
: 
null
onbeforexrselect
: 
null
onblur
: 
null
oncancel
: 
null
oncanplay
: 
null
oncanplaythrough
: 
null
onchange
: 
null
onclick
: 
ƒ uc()
onclose
: 
null
oncontentvisibilityautostatechange
: 
null
oncontextlost
: 
null
oncontextmenu
: 
null
oncontextrestored
: 
null
oncopy
: 
null
oncuechange
: 
null
oncut
: 
null
ondblclick
: 
null
ondrag
: 
null
ondragend
: 
null
ondragenter
: 
null
ondragleave
: 
null
ondragover
: 
null
ondragstart
: 
null
ondrop
: 
null
ondurationchange
: 
null
onemptied
: 
null
onended
: 
null
onerror
: 
(n,l,o,r,t)=> {…}
onfocus
: 
null
onformdata
: 
null
onfullscreenchange
: 
null
onfullscreenerror
: 
null
ongotpointercapture
: 
null
onhashchange
: 
null
oninput
: 
null
oninvalid
: 
null
onkeydown
: 
null
onkeypress
: 
null
onkeyup
: 
null
onlanguagechange
: 
null
onload
: 
null
onloadeddata
: 
null
onloadedmetadata
: 
null
onloadstart
: 
null
onlostpointercapture
: 
null
onmessage
: 
null
onmessageerror
: 
null
onmousedown
: 
null
onmouseenter
: 
null
onmouseleave
: 
null
onmousemove
: 
null
onmouseout
: 
null
onmouseover
: 
null
onmouseup
: 
null
onmousewheel
: 
null
onoffline
: 
null
ononline
: 
null
onpagehide
: 
null
onpageshow
: 
null
onpaste
: 
null
onpause
: 
null
onplay
: 
null
onplaying
: 
null
onpointercancel
: 
null
onpointerdown
: 
null
onpointerenter
: 
null
onpointerleave
: 
null
onpointermove
: 
null
onpointerout
: 
null
onpointerover
: 
null
onpointerrawupdate
: 
null
onpointerup
: 
null
onpopstate
: 
null
onprogress
: 
null
onratechange
: 
null
onrejectionhandled
: 
null
onreset
: 
null
onresize
: 
null
onscroll
: 
null
onsearch
: 
null
onsecuritypolicyviolation
: 
null
onseeked
: 
null
onseeking
: 
null
onselect
: 
null
onselectionchange
: 
null
onselectstart
: 
null
onslotchange
: 
null
onstalled
: 
null
onstorage
: 
null
onsubmit
: 
null
onsuspend
: 
null
ontimeupdate
: 
null
ontoggle
: 
null
ontransitioncancel
: 
null
ontransitionend
: 
null
(...)
adoptedStyleSheets
: 
Proxy
[[Handler]]
: 
Object
[[Target]]
: 
Array(0)
[[IsRevoked]]
: 
false
alinkColor
: 
""
all
: 
HTMLAllCollection(926)
[0 … 99]
[100 … 199]
[200 … 299]
[300 … 399]
[400 … 499]
[500 … 599]
[600 … 699]
[700 … 799]
[800 … 899]
[900 … 925]
L1-nav-items-holder
: 
div#L1-nav-items-holder.LeftNavList__NavItemsHolder-as1dpq-3.hOuldB
Navigation
: 
nav#Navigation.LeftNavClassicHubSpokeBranch__LeftNavStyled-sc-1n10zee-2.nygIf
adsbox
: 
div#adsbox.adsbox
app
: 
div#app.app-shell
cobrowsescript
: 
script#cobrowsescript
ec-icon-id
: 
button#ec-icon-id.global-header-item-button
ensighten-iframe
: 
iframe#ensighten-iframe
independentWidgetManagerNode
: 
div#independentWidgetManagerNode
labelId
: 
span#labelId.ec-icon-label
left-nav-feedback-widget-anchor
: 
div#left-nav-feedback-widget-anchor.HelpIcon__FeedbackWidgetAnchor-xqmbdo-0.caRrGp
left-nav-help-button
: 
button#left-nav-help-button.HelpIcon__IconButton-xqmbdo-1.eSjTGZ
left-nav-help-button-wrapper
: 
div#left-nav-help-button-wrapper.HelpIcon__IconWrapper-xqmbdo-2.bDVHAG
leftNavPortal
: 
div#leftNavPortal
portal-root
: 
div#portal-root.portal-view
qb-live-logo-image
: 
img#qb-live-logo-image.styled__StyledQbLiveLogoImage-ro2xe7-0.cOnlcX
resub-header
: 
div#resub-header.styled__StyledResubHeader-ro2xe7-3.joyXYk
resub-subheader-part_1
: 
div#resub-subheader-part_1.styled__StyledResubSubheader-ro2xe7-4.bNbhYs
resub-top-content-left
: 
div#resub-top-content-left.styled__StyledTopContentLeft-ro2xe7-6.ikvUUM
smartlook-tto-widget
: 
div#smartlook-tto-widget.CobrowseHostStyledstyled__NowSharingBorder-mf5w7t-2.jTALEn
top-image
: 
img#top-image.styled__StyledResubImage-ro2xe7-8.gMkzOx
viewport
: 
meta
web-shell-spinner
: 
div#web-shell-spinner.idsTSIShortSpinner.IndeterminateShort-wrapper.hide-spinner
___appshell
: 
div#___appshell
length
: 
926
[[Prototype]]
: 
HTMLAllCollection
anchors
: 
HTMLCollection []
applets
: 
HTMLCollection(0)
length
: 
0
[[Prototype]]
: 
HTMLCollection
baseURI
: 
"https://app.qbo.intuit.com/app/livebookkeeping-triallearnmore"
bgColor
: 
""
body
: 
body
characterSet
: 
"UTF-8"
charset
: 
"UTF-8"
childElementCount
: 
1
childNodes
: 
NodeList(2) [<!DOCTYPE html>, html.dj_cros.is-not-mobile]
children
: 
HTMLCollection [html.dj_cros.is-not-mobile]
compatMode
: 
"CSS1Compat"
contentType
: 
"text/html"
cookie
: 
"AKES_GEO=US~TX; ivid=37d186bd-8068-4da0-974b-fb13b842f7bc; ccpa=1|1; cpra=1|1; qbn.glogin=cr12753750.00bitore341731337%40gmail.com; s_ecid=MCMID%7C26565719182054462833712297825266353575; qbn.qbo_sctimer=1682916365991; s_vi=[CS]v1|31EC4E84222536BF-40000D6761EB9AB0[CE]; _rdt_uuid=1675140375688.fbe04182-811d-4971-8db3-7cef0d3f6a76; iop.target_url=\"\"; qbse.cid_timer=1682916365; qbn.sbm_global_sc_channel_timer=1682916872018; hosted-shell=%7B%22clientId%22%3A%2238154ae9-05f0-4289-80fd-f10d9e68728f%22%7D; ivid_p=37d186bd-8068-4da0-974b-fb13b842f7bc; priorityCode=3468337910; tms_mint=\"\"; di_sample_mint=control; di_sample=control; aam_uuid=26355422849599581103731762939352476018; cjConsent=MHxOfDB8Tnww; cjCountry=US; cjLiveRampLastCall=2023-01-31T17:39:34.844Z; cjUser=513fbf5a%2D21e8%2D4961%2D90da%2D6f0da90e3599; tt_ipgeo=0%7CUS%7C***%7CY%7C37.751%7C-97.822%7C0%7Cnull%7Cnull; BVBRANDID=7edfccee-8dca-4f73-b3b1-54ebc27b9365; qbn.uidp=129074bb6f23800423593fa4a1b0fa82c67; tt-d1a=1; ivid_b=4a0b30f2-890a-42e5-82d4-0de42699acb4; _its.14988.vid=3f80244b-4fd4-4779-a9d1-e288d3581e26; qbn.sbm_global_sc_channel=cid%3A%7Csc%3A%7Cext%3ASEO-GOO_%7Cint%3AINT%7C; sc_sbg_cmp_cvp=Web%2Cseo; ADRUM=s=1675240417323&r=https%3A%2F%2Fselfemployed.intuit.com%2Flogin%3F1534688477; bvf_5822=d1e46b9e75d4b4334c3c11cd0aa9c139; bvf_5822-ss=d1e46b9e75d4b4334c3c11cd0aa9c139; tms=\"62095:3:145395\"; CAPITAL_EXP_ID=25; dtm-sat-source=_QBOImportPage; 10.1_secureToken=fYlgbcGVbVOTqKdnLWhec1YHKUjqMHGN; SHOPPER_USER_ID=57267238080; __stripe_mid=fc0d6da3-2724-474a-9f50-6e6c8bf45974fd4288; AMCVS_969430F0543F253D0A4C98C6%40AdobeOrg=1; refundMonitorWidgetState=true; ius_at=1675457225663; mds_3rdparty_experience_store=GB_NH,US_NH,62244_145740; REGION=GB; _its.14988.state=rlt~1675552241~land~2_247698_seo_a68b79c0fec21b0632dfdfef0f58634b; qbo.partnerInfo=\"partner=NONE|redirectrequired=false\"; qbo.qbo_version=1997.153; qbo.cluster=19; qbo.qbo=\"|locale=en_US|sku=E|\"; qbo.clientType=web; tt_cid=ck_qu_qc_45887329781; shell.ctx.id=\"authId=9130355940328236&companyId=9130355940328216\"; s_fid=118C35D3F6B983B7-0EA3FA78C4E42F79; s_cc=true; utag_tt_mktid=s_ecid:MCMID%7C26565719182054462833712297825266353575; uvts=d1144363-2b2d-47e2-7451-ff938fc1b108; ARProgress=SignIn:identifier-first; aam_aud=mesg1%3D24937087%3A24940659%3A24940660; _uetsid=3206c7a0a12211ed9619fd811d54e57f; _uetvid=32079f70a12211edb1ba857af3039262; da_lid=78B2C5509A72EA06DAE8BB99F0523A9DE9|0|0|0; did=SHOPPER2_38ef8b490692194e24ffd81a15c0d3698891b7fff91f240cbd81e9c1881b662fdd6e3838eaca1e509256a1ddc9012805; _fbp=fb.1.1675561756807.965903239; _gcl_au=1.1.870192950.1675560769.148794420.1675561758.1675561758; _ga_J7JHVCT5CT=GS1.1.1675561758.1.0.1675562650.60.0.0; qbo.clientip=76.184.181.138; qbo.company=76.184.181.138; qbo.enable_simplified_login=true; utag_main=v_id:01861f3450bd001a1f92854d1cc00506e008206600807$_sn:2$_se:1$_ss:1$_st:1675573334217$vapi_domain:intuit.com$ses_id:1675571534217%3Bexp-session$_pn:1%3Bexp-session; qbn.qbo_sc=cid:|sc:|ext:SEO-GOO_|int:https://quickbooks.intuit.com|; qbse.cid=cid%3A%7Csc%3A%7Cext%3ASEO-GOO_%7Cint%3Ahttps%3A%2F%2Fquickbooks.intuit.com%7C; CONSENTMGR=dns:false%7Cconsent:true%7Cts:1675571539296%7Cc1:1%7Cc9:1; aam_qbuk=mesg1%3D19114207; _ga_DNDL793VKR=GS1.1.1675571544.2.1.1675571544.60.0.0; _ga=GA1.2.8700071.1675561759; _gid=GA1.2.2123398096.1675571547; ius_session=A6FF27951D3D473A4404436E1E899FBE; akid=gip104.95.48.75_gsip23.202.51.84_clip172.58.180.0_rclip172.58.180.0; userIdentifier=9130355918416436; is_from_fms_mktg_pg=Y; AMCV_969430F0543F253D0A4C98C6%40AdobeOrg=-2121179033%7CMCMID%7C26565719182054462833712297825266353575%7CMCAID%7C31EC4E84222536BF-40000D6761EB9AB0%7CMCIDTS%7C19394%7CMCAAMLH-1676180838%7C9%7CMCAAMB-1676180838%7Cj8Odv6LonN4r3an7LhD3WZrU1bUpAkFkkiY1ncBR96t2PTI%7CMCOPTOUT-1675583238s%7CNONE%7CvVersion%7C5.3.0; qbo.csrftoken=fde65e33f8e02224158e24ec3dd354375353ddcb8af27cdad7aec0c18f4fe0c9; websdk_swiper_flags=first_sc_hit%2Cwait_for_sc; LPVID=A0MDM1ZDZlNzM4MmRhYTQ1; LPSID-19175958=xkUnxzaKSSGMaXChMIZsxw; ajs_group_id=9130355940328216; s_sq=intuitctoiux%3D%2526pid%253Dhttps%25253A%25252F%25252Faccounts.intuit.com%25252Fapp%25252Fsign-in%25253Fapp_group%25253DQBO%252526asset_alias%25253DIntuit.accounting.core.qbowebapp%252526iux_tests%25253D47287%2525253A11%2525253A113998%2526oid%253Dfunctionuc%252528%252529%25257B%25257D%2526oidt%253D2%2526ot%253DSUBMIT; pageProperties=$app.qbo.intuit.com/app/livebookkeeping-triallearnmore$learn more$app.qbo.intuit.com$sbseg|prod|qbo|qblive|learn more$; ajs_anonymous_id=%2237d186bd-8068-4da0-974b-fb13b842f7bc%22; ajs_user_id=%22129074bb6f23800423593fa4a1b0fa82c67%22"
currentScript
: 
null
defaultView
: 
Window {0: global, 1: global, window: Window, self: Window, document: document, name: '', location: Location, …}
designMode
: 
"off"
dir
: 
""
doctype
: 
<!DOCTYPE html>
documentElement
: 
html.dj_cros.is-not-mobile
documentURI
: 
"https://app.qbo.intuit.com/app/livebookkeeping-triallearnmore"
domain
: 
"intuit.com"
embeds
: 
HTMLCollection []
featurePolicy
: 
FeaturePolicy {}
fgColor
: 
""
firstChild
: 
<!DOCTYPE html>
firstElementChild
: 
html.dj_cros.is-not-mobile
fonts
: 
FontFaceSet {onloading: null, onloadingdone: null, onloadingerror: null, ready: Promise, status: 'loaded', …}
forms
: 
HTMLCollection []
fragmentDirective
: 
FragmentDirective {}
fullscreen
: 
false
fullscreenElement
: 
null
fullscreenEnabled
: 
true
head
: 
head
hidden
: 
false
images
: 
HTMLCollection(20) [img#qb-live-logo-image.styled__StyledQbLiveLogoImage-ro2xe7-0.cOnlcX, img#top-image.styled__StyledResubImage-ro2xe7-8.gMkzOx, img.icon-image, img.icon-image, img.icon-image, img.styled__StyledImage-xqoss8-3.gwDOJX, img.styled__StyledImage-sc-128ehjx-3.dglDLN, img.styled__StyledImage-p5r5ur-2.lbAApT, img.styled__StyledImage-p5r5ur-2.lbAApT, img.styled__StyledImage-p5r5ur-2.lbAApT, img.heading-icon, img.heading-icon, img.heading-icon, img.heading-icon, img.heading-icon, img.heading-icon, img.heading-icon, img.heading-icon, img.heading-icon, img.trial-learn-image, qb-live-logo-image: img#qb-live-logo-image.styled__StyledQbLiveLogoImage-ro2xe7-0.cOnlcX, top-image: img#top-image.styled__StyledResubImage-ro2xe7-8.gMkzOx]
implementation
: 
DOMImplementation {}
inputEncoding
: 
"UTF-8"
isConnected
: 
true
lastChild
: 
html.dj_cros.is-not-mobile
lastElementChild
: 
html.dj_cros.is-not-mobile
lastModified
: 
"02/04/2023 23:54:22"
linkColor
: 
""
links
: 
HTMLCollection(37) [a.QBOLogoComponent__LogoLink-sc-11exkc1-0.jsEOIs, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gSyYTu, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw, a.NavItem__Link-sc-1gl8mm6-5.gEetYw]
nextSibling
: 
null
nodeName
: 
"#document"
nodeType
: 
9
nodeValue
: 
null
onabort
: 
null
onanimationend
: 
null
onanimationiteration
: 
null
onanimationstart
: 
null
onauxclick
: 
null
onbeforecopy
: 
null
onbeforecut
: 
null
onbeforeinput
: 
null
onbeforematch
: 
null
onbeforepaste
: 
null
onbeforexrselect
: 
null
onblur
: 
null
oncancel
: 
null
oncanplay
: 
null
oncanplaythrough
: 
null
onchange
: 
null
onclick
: 
null
onclose
: 
null
oncontentvisibilityautostatechange
: 
null
oncontextlost
: 
null
oncontextmenu
: 
null
oncontextrestored
: 
null
oncopy
: 
null
oncuechange
: 
null
oncut
: 
null
ondblclick
: 
null
ondrag
: 
null
ondragend
: 
null
ondragenter
: 
null
ondragleave
: 
null
ondragover
: 
null
ondragstart
: 
null
ondrop
: 
null
ondurationchange
: 
null
onemptied
: 
null
onended
: 
null
onerror
: 
null
onfocus
: 
null
onformdata
: 
null
onfreeze
: 
null
onfullscreenchange
: 
null
onfullscreenerror
: 
null
ongotpointercapture
: 
null
oninput
: 
null
oninvalid
: 
null
onkeydown
: 
null
onkeypress
: 
null
onkeyup
: 
null
onload
: 
null
onloadeddata
: 
null
onloadedmetadata
: 
null
onloadstart
: 
null
onlostpointercapture
: 
null
onmousedown
: 
null
onmouseenter
: 
null
onmouseleave
: 
null
onmousemove
: 
null
onmouseout
: 
null
onmouseover
: 
null
onmouseup
: 
null
onmousewheel
: 
null
onpaste
: 
null
onpause
: 
null
onplay
: 
null
onplaying
: 
null
onpointercancel
: 
null
onpointerdown
: 
null
onpointerenter
: 
null
onpointerleave
: 
null
onpointerlockchange
: 
null
onpointerlockerror
: 
null
onpointermove
: 
null
onpointerout
: 
null
onpointerover
: 
null
onpointerrawupdate
: 
null
onpointerup
: 
null
onprerenderingchange
: 
null
onprogress
: 
null
onratechange
: 
null
onreadystatechange
: 
null
onreset
: 
null
onresize
: 
null
onresume
: 
null
onscroll
: 
null
onsearch
: 
null
onsecuritypolicyviolation
: 
null
onseeked
: 
null
onseeking
: 
null
onselect
: 
null
onselectionchange
: 
null
onselectstart
: 
null
onslotchange
: 
null
onstalled
: 
null
onsubmit
: 
null
onsuspend
: 
null
ontimeupdate
: 
null
ontoggle
: 
null
ontransitioncancel
: 
null
ontransitionend
: 
null
ontransitionrun
: 
null
ontransitionstart
: 
null
onvisibilitychange
: 
null
onvolumechange
: 
null
onwaiting
: 
null
onwebkitanimationend
: 
null
onwebkitanimationiteration
: 
null
onwebkitanimationstart
: 
null
onwebkitfullscreenchange
: 
null
onwebkitfullscreenerror
: 
null
onwebkittransitionend
: 
null
onwheel
: 
null
ownerDocument
: 
null
parentElement
: 
null
parentNode
: 
null
pictureInPictureElement
: 
null
pictureInPictureEnabled
: 
true
plugins
: 
HTMLCollection []
pointerLockElement
: 
null
prerendering
: 
false
previousSibling
: 
null
readyState
: 
"complete"
referrer
: 
"https://app.qbo.intuit.com/app/companyselection?locale=en-us"
rootElement
: 
null
scripts
: 
HTMLCollection(95) [script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script, script#cobrowsescript, cobrowsescript: script#cobrowsescript]
scrollingElement
: 
html.dj_cros.is-not-mobile
styleSheets
: 
StyleSheetList {0: CSSStyleSheet, 1: CSSStyleSheet, 2: CSSStyleSheet, 3: CSSStyleSheet, 4: CSSStyleSheet, 5: CSSStyleSheet, 6: CSSStyleSheet, 7: CSSStyleSheet, 8: CSSStyleSheet, 9: CSSStyleSheet, 10: CSSStyleSheet, 11: CSSStyleSheet, 12: CSSStyleSheet, 13: CSSStyleSheet, 14: CSSStyleSheet, 15: CSSStyleSheet, 16: CSSStyleSheet, 17: CSSStyleSheet, 18: CSSStyleSheet, 19: CSSStyleSheet, 20: CSSStyleSheet, 21: CSSStyleSheet, 22: CSSStyleSheet, 23: CSSStyleSheet, 24: CSSStyleSheet, 25: CSSStyleSheet, 26: CSSStyleSheet, 27: CSSStyleSheet, 28: CSSStyleSheet, 29: CSSStyleSheet, 30: CSSStyleSheet, 31: CSSStyleSheet, 32: CSSStyleSheet, 33: CSSStyleSheet, 34: CSSStyleSheet, 35: CSSStyleSheet, 36: CSSStyleSheet, 37: CSSStyleSheet, 38: CSSStyleSheet, 39: CSSStyleSheet, 40: CSSStyleSheet, 41: CSSStyleSheet, 42: CSSStyleSheet, 43: CSSStyleSheet, 44: CSSStyleSheet, 45: CSSStyleSheet, 46: CSSStyleSheet, 47: CSSStyleSheet, 48: CSSStyleSheet, 49: CSSStyleSheet, 50: CSSStyleSheet, 51: CSSStyleSheet, 52: CSSStyleSheet, 53: CSSStyleSheet, 54: CSSStyleSheet, 55: CSSStyleSheet, 56: CSSStyleSheet, 57: CSSStyleSheet, 58: CSSStyleSheet, 59: CSSStyleSheet, 60: CSSStyleSheet, 61: CSSStyleSheet, 62: CSSStyleSheet, 63: CSSStyleSheet, 64: CSSStyleSheet, 65: CSSStyleSheet, 66: CSSStyleSheet, 67: CSSStyleSheet, 68: CSSStyleSheet, 69: CSSStyleSheet, 70: CSSStyleSheet, 71: CSSStyleSheet, 72: CSSStyleSheet, 73: CSSStyleSheet, 74: CSSStyleSheet, 75: CSSStyleSheet, 76: CSSStyleSheet, 77: CSSStyleSheet, 78: CSSStyleSheet, 79: CSSStyleSheet, 80: CSSStyleSheet, 81: CSSStyleSheet, 82: CSSStyleSheet, 83: CSSStyleSheet, 84: CSSStyleSheet, 85: CSSStyleSheet, 86: CSSStyleSheet, 87: CSSStyleSheet, 88: CSSStyleSheet, 89: CSSStyleSheet, 90: CSSStyleSheet, 91: CSSStyleSheet, 92: CSSStyleSheet, 93: CSSStyleSheet, length: 94}
textContent
: 
null
timeline
: 
DocumentTimeline {currentTime: 162321.531}
title
: 
"QuickBooks"
visibilityState
: 
"visible"
vlinkColor
: 
""
wasDiscarded
: 
false
webkitCurrentFullScreenElement
: 
null
webkitFullscreenElement
: 
null
webkitFullscreenEnabled
: 
true
webkitHidden
: 
false
webkitIsFullScreen
: 
false
webkitVisibilityState
: 
"visible"
xmlEncoding
: 
null
xmlStandalone
: 
false
xmlVersion
: 
null
[[Prototype]]
: 
HTMLDocument
parentElement
: 
div.qbo-qblive-trialLearnPage.qbal-slideLeft-enter
parentNode
: 
div.qbo-qblive-trialLearnPage.qbal-slideLeft-enter
part
: 
DOMTokenList(0)
length
: 
0
value
: 
""
[[Prototype]]
: 
DOMTokenList
prefix
: 
null
previousElementSibling
: 
div.trial-learn-text
__reactEventHandlers$6obajd0qf4v
: 
{className: 'trial-learn-text', children: Array(3)}
__reactInternalInstance$6obajd0qf4v
: 
Fj {tag: 5, key: null, elementType: 'div', type: 'div', stateNode: div.trial-learn-text, …}
accessKey
: 
""
align
: 
""
ariaAtomic
: 
null
ariaAutoComplete
: 
null
ariaBrailleLabel
: 
null
ariaBrailleRoleDescription
: 
null
ariaBusy
: 
null
ariaChecked
: 
null
ariaColCount
: 
null
ariaColIndex
: 
null
ariaColSpan
: 
null
ariaCurrent
: 
null
ariaDescription
: 
null
ariaDisabled
: 
null
ariaExpanded
: 
null
ariaHasPopup
: 
null
ariaHidden
: 
null
ariaInvalid
: 
null
ariaKeyShortcuts
: 
null
ariaLabel
: 
null
ariaLevel
: 
null
ariaLive
: 
null
ariaModal
: 
null
ariaMultiLine
: 
null
ariaMultiSelectable
: 
null
ariaOrientation
: 
null
ariaPlaceholder
: 
null
ariaPosInSet
: 
null
ariaPressed
: 
null
ariaReadOnly
: 
null
ariaRelevant
: 
null
ariaRequired
: 
null
ariaRoleDescription
: 
null
ariaRowCount
: 
null
ariaRowIndex
: 
null
ariaRowSpan
: 
null
ariaSelected
: 
null
ariaSetSize
: 
null
ariaSort
: 
null
ariaValueMax
: 
null
ariaValueMin
: 
null
ariaValueNow
: 
null
ariaValueText
: 
null
assignedSlot
: 
null
attributeStyleMap
: 
StylePropertyMap {size: 0}
attributes
: 
NamedNodeMap {0: class, class: class, length: 1}
autocapitalize
: 
""
autofocus
: 
false
baseURI
: 
"https://app.qbo.intuit.com/app/livebookkeeping-triallearnmore"
childElementCount
: 
3
childNodes
: 
NodeList(3) [h1, div.LeaderLine__LeaderLineDiv-sc-140xwdx-0.iAXJoq.trial_learn_leader_line, p]
children
: 
HTMLCollection(3) [h1, div.LeaderLine__LeaderLineDiv-sc-140xwdx-0.iAXJoq.trial_learn_leader_line, p]
classList
: 
DOMTokenList ['trial-learn-text', value: 'trial-learn-text']
className
: 
"trial-learn-text"
clientHeight
: 
697
clientLeft
: 
0
clientTop
: 
0
clientWidth
: 
680
contentEditable
: 
"inherit"
dataset
: 
DOMStringMap {}
dir
: 
""
draggable
: 
false
elementTiming
: 
""
enterKeyHint
: 
""
firstChild
: 
h1
firstElementChild
: 
h1
hidden
: 
false
id
: 
""
inert
: 
false
innerHTML
: 
"<h1>Bookkeeping help is just a call away</h1><div width=\"116px\" height=\"6px\" class=\"LeaderLine__LeaderLineDiv-sc-140xwdx-0 iAXJoq trial_learn_leader_line\"><span class=\"line\"></span><span class=\"dot\"></span></div><p>Get the most out of your QuickBooks experience. Call <strong>800-682-2172</strong> to speak with a bookkeeping specialist.</p>"
innerText
: 
"Bookkeeping help is just a call away\n\nGet the most out of your QuickBooks experience. Call 800-682-2172 to speak with a bookkeeping specialist."
inputMode
: 
""
isConnected
: 
true
isContentEditable
: 
false
lang
: 
""
lastChild
: 
p
lastElementChild
: 
p
localName
: 
"div"
namespaceURI
: 
"http://www.w3.org/1999/xhtml"
nextElementSibling
: 
img.trial-learn-image
nextSibling
: 
img.trial-learn-image
nodeName
: 
"DIV"
nodeType
: 
1
nodeValue
: 
null
nonce
: 
""
offsetHeight
: 
697
offsetLeft
: 
60
offsetParent
: 
div.qbo-qblive-trialLearnPage.qbal-slideLeft-enter
offsetTop
: 
60
offsetWidth
: 
680
onabort
: 
null
onanimationend
: 
null
onanimationiteration
: 
null
onanimationstart
: 
null
onauxclick
: 
null
onbeforecopy
: 
null
onbeforecut
: 
null
onbeforeinput
: 
null
onbeforematch
: 
null
onbeforepaste
: 
null
onbeforexrselect
: 
null
onblur
: 
null
oncancel
: 
null
oncanplay
: 
null
oncanplaythrough
: 
null
onchange
: 
null
onclick
: 
null
onclose
: 
null
oncontentvisibilityautostatechange
: 
null
oncontextlost
: 
null
oncontextmenu
: 
null
oncontextrestored
: 
null
oncopy
: 
null
oncuechange
: 
null
oncut
: 
null
ondblclick
: 
null
ondrag
: 
null
ondragend
: 
null
ondragenter
: 
null
ondragleave
: 
null
ondragover
: 
null
ondragstart
: 
null
ondrop
: 
null
ondurationchange
: 
null
onemptied
: 
null
onended
: 
null
onerror
: 
null
onfocus
: 
null
onformdata
: 
null
onfullscreenchange
: 
null
onfullscreenerror
: 
null
ongotpointercapture
: 
null
oninput
: 
null
oninvalid
: 
null
onkeydown
: 
null
onkeypress
: 
null
onkeyup
: 
null
onload
: 
null
onloadeddata
: 
null
onloadedmetadata
: 
null
onloadstart
: 
null
onlostpointercapture
: 
null
onmousedown
: 
null
onmouseenter
: 
null
onmouseleave
: 
null
onmousemove
: 
null
onmouseout
: 
null
onmouseover
: 
null
onmouseup
: 
null
onmousewheel
: 
null
onpaste
: 
null
onpause
: 
null
onplay
: 
null
onplaying
: 
null
onpointercancel
: 
null
onpointerdown
: 
null
onpointerenter
: 
null
onpointerleave
: 
null
onpointermove
: 
null
onpointerout
: 
null
onpointerover
: 
null
onpointerrawupdate
: 
null
onpointerup
: 
null
onprogress
: 
null
onratechange
: 
null
onreset
: 
null
onresize
: 
null
onscroll
: 
null
onsearch
: 
null
onsecuritypolicyviolation
: 
null
onseeked
: 
null
onseeking
: 
null
onselect
: 
null
onselectionchange
: 
null
onselectstart
: 
null
onslotchange
: 
null
onstalled
: 
null
onsubmit
: 
null
onsuspend
: 
null
ontimeupdate
: 
null
ontoggle
: 
null
ontransitioncancel
: 
null
ontransitionend
: 
null
ontransitionrun
: 
null
ontransitionstart
: 
null
onvolumechange
: 
null
onwaiting
: 
null
onwebkitanimationend
: 
null
onwebkitanimationiteration
: 
null
onwebkitanimationstart
: 
null
onwebkitfullscreenchange
: 
null
onwebkitfullscreenerror
: 
null
onwebkittransitionend
: 
null
onwheel
: 
null
outerHTML
: 
"<div class=\"trial-learn-text\"><h1>Bookkeeping help is just a call away</h1><div width=\"116px\" height=\"6px\" class=\"LeaderLine__LeaderLineDiv-sc-140xwdx-0 iAXJoq trial_learn_leader_line\"><span class=\"line\"></span><span class=\"dot\"></span></div><p>Get the most out of your QuickBooks experience. Call <strong>800-682-2172</strong> to speak with a bookkeeping specialist.</p></div>"
outerText
: 
"Bookkeeping help is just a call away\n\nGet the most out of your QuickBooks experience. Call 800-682-2172 to speak with a bookkeeping specialist."
ownerDocument
: 
document
parentElement
: 
div.qbo-qblive-trialLearnPage.qbal-slideLeft-enter
(...)
previousSibling
: 
div.trial-learn-text
__reactEventHandlers$6obajd0qf4v
: 
{className: 'trial-learn-text', children: Array(3)}
__reactInternalInstance$6obajd0qf4v
: 
Fj {tag: 5, key: null, elementType: 'div', type: 'div', stateNode: div.trial-learn-text, …}
accessKey
: 
""
align
: 
""
ariaAtomic
: 
null
ariaAutoComplete
: 
null
ariaBrailleLabel
: 
null
ariaBrailleRoleDescription
: 
null
ariaBusy
: 
null
ariaChecked
: 
null
ariaColCount
: 
null
ariaColIndex
: 
null
ariaColSpan
: 
null
ariaCurrent
: 
null
ariaDescription
: 
null
ariaDisabled
: 
null
ariaExpanded
: 
null
ariaHasPopup
: 
null
ariaHidden
: 
null
ariaInvalid
: 
null
ariaKeyShortcuts
: 
null
ariaLabel
: 
null
ariaLevel
: 
null
ariaLive
: 
null
ariaModal
: 
null
ariaMultiLine
: 
null
ariaMultiSelectable
: 
null
ariaOrientation
: 
null
ariaPlaceholder
: 
null
ariaPosInSet
: 
null
ariaPressed
: 
null
ariaReadOnly
: 
null
ariaRelevant
: 
null
ariaRequired
: 
null
ariaRoleDescription
: 
null
ariaRowCount
: 
null
ariaRowIndex
: 
null
ariaRowSpan
: 
null
ariaSelected
: 
null
ariaSetSize
: 
null
ariaSort
: 
null
ariaValueMax
: 
null
ariaValueMin
: 
null
ariaValueNow
: 
null
ariaValueText
: 
null
assignedSlot
: 
null
attributeStyleMap
: 
StylePropertyMap {size: 0}
attributes
: 
NamedNodeMap {0: class, class: class, length: 1}
autocapitalize
: 
""
autofocus
: 
false
baseURI
: 
"https://app.qbo.intuit.com/app/livebookkeeping-triallearnmore"
childElementCount
: 
3
childNodes
: 
NodeList(3) [h1, div.LeaderLine__LeaderLineDiv-sc-140xwdx-0.iAXJoq.trial_learn_leader_line, p]
children
: 
HTMLCollection(3) [h1, div.LeaderLine__LeaderLineDiv-sc-140xwdx-0.iAXJoq.trial_learn_leader_line, p]
classList
: 
DOMTokenList ['trial-learn-text', value: 'trial-learn-text']
className
: 
"trial-learn-text"
clientHeight
: 
697
clientLeft
: 
0
clientTop
: 
0
clientWidth
: 
680
contentEditable
: 
"inherit"
dataset
: 
DOMStringMap {}
dir
: 
""
draggable
: 
false
elementTiming
: 
""
enterKeyHint
: 
""
firstChild
: 
h1
firstElementChild
: 
h1
hidden
: 
false
id
: 
""
inert
: 
false
innerHTML
: 
"<h1>Bookkeeping help is just a call away</h1><div width=\"116px\" height=\"6px\" class=\"LeaderLine__LeaderLineDiv-sc-140xwdx-0 iAXJoq trial_learn_leader_line\"><span class=\"line\"></span><span class=\"dot\"></span></div><p>Get the most out of your QuickBooks experience. Call <strong>800-682-2172</strong> to speak with a bookkeeping specialist.</p>"
innerText
: 
"Bookkeeping help is just a call away\n\nGet the most out of your QuickBooks experience. Call 800-682-2172 to speak with a bookkeeping specialist."
inputMode
: 
""
isConnected
: 
true
isContentEditable
: 
false
lang
: 
""
lastChild
: 
p
lastElementChild
: 
p
localName
: 
"div"
namespaceURI
: 
"http://www.w3.org/1999/xhtml"
nextElementSibling
: 
img.trial-learn-image
nextSibling
: 
img.trial-learn-image
nodeName
: 
"DIV"
nodeType
: 
1
nodeValue
: 
null
nonce
: 
""
offsetHeight
: 
697
offsetLeft
: 
60
offsetParent
: 
div.qbo-qblive-trialLearnPage.qbal-slideLeft-enter
offsetTop
: 
60
offsetWidth
: 
680
onabort
: 
null
onanimationend
: 
null
onanimationiteration
: 
null
onanimationstart
: 
null
onauxclick
: 
null
onbeforecopy
: 
null
onbeforecut
: 
null
onbeforeinput
: 
null
onbeforematch
: 
null
onbeforepaste
: 
null
onbeforexrselect
: 
null
onblur
: 
null
oncancel
: 
null
oncanplay
: 
null
oncanplaythrough
: 
null
onchange
: 
null
onclick
: 
null
onclose
: 
null
oncontentvisibilityautostatechange
: 
null
oncontextlost
: 
null
oncontextmenu
: 
null
oncontextrestored
: 
null
oncopy
: 
null
oncuechange
: 
null
oncut
: 
null
ondblclick
: 
null
ondrag
: 
null
ondragend
: 
null
ondragenter
: 
null
ondragleave
: 
null
ondragover
: 
null
ondragstart
: 
null
ondrop
: 
null
ondurationchange
: 
null
onemptied
: 
null
onended
: 
null
onerror
: 
null
onfocus
: 
null
onformdata
: 
null
onfullscreenchange
: 
null
onfullscreenerror
: 
null
ongotpointercapture
: 
null
oninput
: 
null
oninvalid
: 
null
onkeydown
: 
null
onkeypress
: 
null
onkeyup
: 
null
onload
: 
null
onloadeddata
: 
null
onloadedmetadata
: 
null
onloadstart
: 
null
onlostpointercapture
: 
null
onmousedown
: 
null
onmouseenter
: 
null
onmouseleave
: 
null
onmousemove
: 
null
onmouseout
: 
null
onmouseover
: 
null
onmouseup
: 
null
onmousewheel
: 
null
onpaste
: 
null
onpause
: 
null
onplay
: 
null
onplaying
: 
null
onpointercancel
: 
null
onpointerdown
: 
null
onpointerenter
: 
null
onpointerleave
: 
null
onpointermove
: 
null
onpointerout
: 
null
onpointerover
: 
null
onpointerrawupdate
: 
null
onpointerup
: 
null
onprogress
: 
null
onratechange
: 
null
onreset
: 
null
onresize
: 
null
onscroll
: 
null
onsearch
: 
null
onsecuritypolicyviolation
: 
null
onseeked
: 
null
onseeking
: 
null
onselect
: 
null
onselectionchange
: 
null
onselectstart
: 
null
onslotchange
: 
null
onstalled
: 
null
onsubmit
: 
null
onsuspend
: 
null
ontimeupdate
: 
null
ontoggle
: 
null
ontransitioncancel
: 
null
ontransitionend
: 
null
ontransitionrun
: 
null
ontransitionstart
: 
null
onvolumechange
: 
null
onwaiting
: 
null
onwebkitanimationend
: 
null
onwebkitanimationiteration
: 
null
onwebkitanimationstart
: 
null
onwebkitfullscreenchange
: 
null
onwebkitfullscreenerror
: 
null
onwebkittransitionend
: 
null
onwheel
: 
null
outerHTML
: 
"<div class=\"trial-learn-text\"><h1>Bookkeeping help is just a call away</h1><div width=\"116px\" height=\"6px\" class=\"LeaderLine__LeaderLineDiv-sc-140xwdx-0 iAXJoq trial_learn_leader_line\"><span class=\"line\"></span><span class=\"dot\"></span></div><p>Get the most out of your QuickBooks experience. Call <strong>800-682-2172</strong> to speak with a bookkeeping specialist.</p></div>"
outerText
: 
"Bookkeeping help is just a call away\n\nGet the most out of your QuickBooks experience. Call 800-682-2172 to speak with a bookkeeping specialist."
ownerDocument
: 
document
parentElement
: 
div.qbo-qblive-trialLearnPage.qbal-slideLeft-enter
(...)
referrerPolicy
: 
""
role
: 
null
scrollHeight
: 
0
scrollLeft
: 
0
scrollTop
: 
0
scrollWidth
: 
0
shadowRoot
: 
null
sizes
: 
""
slot
: 
""
spellcheck
: 
true
src
: 
"https://plugin.intuitcdn.net/qbo-qblive-ui/ceb40a3fd37f4ea18e0b.jpg"
srcset
: 
""
style
: 
CSSStyleDeclaration
accentColor
: 
""
additiveSymbols
: 
""
alignContent
: 
""
alignItems
: 
""
alignSelf
: 
""
alignmentBaseline
: 
""
all
: 
""
animation
: 
""
animationDelay
: 
""
animationDirection
: 
""
animationDuration
: 
""
animationFillMode
: 
""
animationIterationCount
: 
""
animationName
: 
""
animationPlayState
: 
""
animationTimingFunction
: 
""
appRegion
: 
""
appearance
: 
""
ascentOverride
: 
""
aspectRatio
: 
""
backdropFilter
: 
""
backfaceVisibility
: 
""
background
: 
""
backgroundAttachment
: 
""
backgroundBlendMode
: 
""
backgroundClip
: 
""
backgroundColor
: 
""
backgroundImage
: 
""
backgroundOrigin
: 
""
backgroundPosition
: 
""
backgroundPositionX
: 
""
backgroundPositionY
: 
""
backgroundRepeat
: 
""
backgroundRepeatX
: 
""
backgroundRepeatY
: 
""
backgroundSize
: 
""
basePalette
: 
""
baselineShift
: 
""
blockSize
: 
""
border
: 
""
borderBlock
: 
""
borderBlockColor
: 
""
borderBlockEnd
: 
""
borderBlockEndColor
: 
""
borderBlockEndStyle
: 
""
borderBlockEndWidth
: 
""
borderBlockStart
: 
""
borderBlockStartColor
: 
""
borderBlockStartStyle
: 
""
borderBlockStartWidth
: 
""
borderBlockStyle
: 
""
borderBlockWidth
: 
""
borderBottom
: 
""
borderBottomColor
: 
""
borderBottomLeftRadius
: 
""
borderBottomRightRadius
: 
""
borderBottomStyle
: 
""
borderBottomWidth
: 
""
borderCollapse
: 
""
borderColor
: 
""
borderEndEndRadius
: 
""
borderEndStartRadius
: 
""
borderImage
: 
""
borderImageOutset
: 
""
borderImageRepeat
: 
""
borderImageSlice
: 
""
borderImageSource
: 
""
borderImageWidth
: 
""
borderInline
: 
""
borderInlineColor
: 
""
borderInlineEnd
: 
""
borderInlineEndColor
: 
""
borderInlineEndStyle
: 
""
borderInlineEndWidth
: 
""
borderInlineStart
: 
""
borderInlineStartColor
: 
""
borderInlineStartStyle
: 
""
borderInlineStartWidth
: 
""
borderInlineStyle
: 
""
borderInlineWidth
: 
""
borderLeft
: 
""
borderLeftColor
: 
""
borderLeftStyle
: 
""
borderLeftWidth
: 
""
borderRadius
: 
""
borderRight
: 
""
borderRightColor
: 
""
borderRightStyle
: 
""
borderRightWidth
: 
""
borderSpacing
: 
""
borderStartEndRadius
: 
""
borderStartStartRadius
: 
""
borderStyle
: 
""
borderTop
: 
""
borderTopColor
: 
""
borderTopLeftRadius
: 
""
borderTopRightRadius
: 
""
borderTopStyle
: 
""
borderTopWidth
: 
""
borderWidth
: 
""
bottom
: 
""
boxShadow
: 
""
boxSizing
: 
""
breakAfter
: 
""
breakBefore
: 
""
breakInside
: 
""
bufferedRendering
: 
""
captionSide
: 
""
caretColor
: 
""
clear
: 
""
clip
: 
""
clipPath
: 
""
clipRule
: 
""
color
: 
""
colorInterpolation
: 
""
colorInterpolationFilters
: 
""
colorRendering
: 
""
colorScheme
: 
""
columnCount
: 
""
columnFill
: 
""
columnGap
: 
""
columnRule
: 
""
columnRuleColor
: 
""
columnRuleStyle
: 
""
columnRuleWidth
: 
""
columnSpan
: 
""
columnWidth
: 
""
columns
: 
""
contain
: 
""
containIntrinsicBlockSize
: 
""
containIntrinsicHeight
: 
""
containIntrinsicInlineSize
: 
""
containIntrinsicSize
: 
""
containIntrinsicWidth
: 
""
container
: 
""
containerName
: 
""
containerType
: 
""
content
: 
""
contentVisibility
: 
""
counterIncrement
: 
""
counterReset
: 
""
counterSet
: 
""
cursor
: 
""
cx
: 
""
cy
: 
""
d
: 
""
descentOverride
: 
""
direction
: 
""
display
: 
""
dominantBaseline
: 
""
emptyCells
: 
""
fallback
: 
""
fill
: 
""
fillOpacity
: 
""
fillRule
: 
""
filter
: 
""
flex
: 
""
flexBasis
: 
""
flexDirection
: 
""
flexFlow
: 
""
flexGrow
: 
""
flexShrink
: 
""
flexWrap
: 
""
float
: 
""
floodColor
: 
""
floodOpacity
: 
""
font
: 
""
fontDisplay
: 
""
fontFamily
: 
""
fontFeatureSettings
: 
""
fontKerning
: 
""
fontOpticalSizing
: 
""
fontPalette
: 
""
fontSize
: 
""
fontStretch
: 
""
fontStyle
: 
""
fontSynthesis
: 
""
fontSynthesisSmallCaps
: 
""
fontSynthesisStyle
: 
""
fontSynthesisWeight
: 
""
fontVariant
: 
""
fontVariantCaps
: 
""
fontVariantEastAsian
: 
""
fontVariantLigatures
: 
""
fontVariantNumeric
: 
""
fontVariationSettings
: 
""
fontWeight
: 
""
forcedColorAdjust
: 
""
gap
: 
""
grid
: 
""
gridArea
: 
""
gridAutoColumns
: 
""
gridAutoFlow
: 
""
gridAutoRows
: 
""
gridColumn
: 
""
gridColumnEnd
: 
""
gridColumnGap
: 
""
gridColumnStart
: 
""
gridGap
: 
""
gridRow
: 
""
(...)
tabIndex
: 
-1
tagName
: 
"IMG"
textContent
: 
""
title
: 
""
translate
: 
true
useMap
: 
""
virtualKeyboardPolicy
: 
""
vspace
: 
0
width
: 
943
x
: 
0
y
: 
0
Skip to navigationSkip to main content
Utilities
Subscriptions
Downloads
Containers
Support Cases
Red Hat Customer Portal
Products & Services
Tools
Security
Community

Search

English

All Red Hat





Log in
Products & ServicesProduct DocumentationRed Hat Enterprise Linux7System Administrator’s GuideChapter 2. System Locale and Keyboard Configuration
Expand all
Collapse all
System Administrator’s Guide
I. Basic System Configuration
Collapse section "I. Basic System Configuration"
1. Getting Started
Expand section "1. Getting Started"
2. System Locale and Keyboard Configuration
Collapse section "2. System Locale and Keyboard Configuration"
2.1. Setting the System Locale
Collapse section "2.1. Setting the System Locale"
2.1.1. Displaying the Current Status
2.1.2. Listing Available Locales
2.1.3. Setting the Locale
2.1.4. Making System Locale Settings Permanent when Installing with Kickstart
2.2. Changing the Keyboard Layout
Collapse section "2.2. Changing the Keyboard Layout"
2.2.1. Displaying the Current Settings
2.2.2. Listing Available Keymaps
2.2.3. Setting the Keymap
2.3. Additional Resources
3. Configuring the Date and Time
Expand section "3. Configuring the Date and Time"
4. Managing Users and Groups
Expand section "4. Managing Users and Groups"
5. Access Control Lists
Expand section "5. Access Control Lists"
6. Gaining Privileges
Expand section "6. Gaining Privileges"
II. Subscription and Support
Expand section "II. Subscription and Support"
III. Installing and Managing Software
Expand section "III. Installing and Managing Software"
IV. Infrastructure Services
Expand section "IV. Infrastructure Services"
V. Servers
Expand section "V. Servers"
VI. Monitoring and Automation
Expand section "VI. Monitoring and Automation"
VII. Kernel Customization with Bootloader
Expand section "VII. Kernel Customization with Bootloader"
VIII. System Backup and Recovery
Expand section "VIII. System Backup and Recovery"

Focus mode

LANGUAGE AND PAGE FORMATTING OPTIONS
Red Hat Training
A Red Hat training course is available for Red Hat Enterprise Linux

Chapter 2. System Locale and Keyboard Configuration
The system locale specifies the language settings of system services and user interfaces. The keyboard layout settings control the layout used on the text console and graphical user interfaces.

These settings can be made by modifying the /etc/locale.conf configuration file or by using the localectl utility. Also, you can use the graphical user interface to perform the task; for a description of this method, see Red Hat Enterprise Linux 7 Installation Guide.

2.1. Setting the System Locale
System-wide locale settings are stored in the /etc/locale.conf file, which is read at early boot by the systemd daemon. The locale settings configured in /etc/locale.conf are inherited by every service or user, unless individual programs or individual users override them.

The basic file format of /etc/locale.conf is a newline-separated list of variable assignments. For example, German locale with English messages in /etc/locale.conf looks as follows:

LANG=de_DE.UTF-8
LC_MESSAGES=C
Here, the LC_MESSAGES option determines the locale used for diagnostic messages written to the standard error output. To further specify locale settings in /etc/locale.conf, you can use several other options, the most relevant are summarized in Table 2.1, “Options configurable in /etc/locale.conf”. See the locale(7) manual page for detailed information on these options. Note that the LC_ALL option, which represents all possible options, should not be configured in /etc/locale.conf.

Table 2.1. Options configurable in /etc/locale.conf


Option	Description
LANG

Provides a default value for the system locale.

LC_COLLATE

Changes the behavior of functions which compare strings in the local alphabet.

LC_CTYPE

Changes the behavior of the character handling and classification functions and the multibyte character functions.

LC_NUMERIC

Describes the way numbers are usually printed, with details such as decimal point versus decimal comma.

LC_TIME

Changes the display of the current time, 24-hour versus 12-hour clock.

LC_MESSAGES

Determines the locale used for diagnostic messages written to the standard error output.

2.1.1. Displaying the Current Status
The localectl command can be used to query and change the system locale and keyboard layout settings. To show the current settings, use the status option:

localectl status
Example 2.1. Displaying the Current Status

The output of the previous command lists the currently set locale, keyboard layout configured for the console and for the X11 window system.

~]$ localectl status
  System Locale: LANG=en_US.UTF-8
    VC Keymap: us
   X11 Layout: n/a
2.1.2. Listing Available Locales
To list all locales available for your system, type:

localectl list-locales
Example 2.2. Listing Locales

Imagine you want to select a specific English locale, but you are not sure if it is available on the system. You can check that by listing all English locales with the following command:

~]$ localectl list-locales | grep en_
en_AG
en_AG.utf8
en_AU
en_AU.iso88591
en_AU.utf8
en_BW
en_BW.iso88591
en_BW.utf8

output truncated
2.1.3. Setting the Locale
To set the default system locale, use the following command as root:

localectl set-locale LANG=locale
Replace locale with the locale name, found with the localectl list-locales command. The above syntax can also be used to configure parameters from Table 2.1, “Options configurable in /etc/locale.conf”.

Example 2.3. Changing the Default Locale

For example, if you want to set British English as your default locale, first find the name of this locale by using list-locales. Then, as root, type the command in the following form:

~]# localectl set-locale LANG=en_GB.utf8
2.1.4. Making System Locale Settings Permanent when Installing with Kickstart
When Red Hat Enterprise Linux is installed with the Red Hat Kickstart installation method, setting of the system locales might not be persistent after an upgrade of the operating system.

When the %packages section of the Kickstart file includes the --instLang option, the _install_langs RPM macro is set to the particular value for this installation, and the set of installed locales is adjusted accordingly. However, this adjustment affects only this installation, not subsequent upgrades. If an upgrade reinstalls the glibc package, the entire set of locales is upgraded instead of only the locales you requested during the installation.

To avoid this, make the choice of locales permanent. You have these options:

If you have not started the Kickstart installation, modify the Kickstart file to include instructions for setting RPM macros globally by applying this procedure: Setting RPM macros during the Kickstart installation
If you have already installed the system, set RPM macros globally on the system by applying this procedure: Setting RPM macros globally
Setting RPM macros during the Kickstart installation

Modify the %post section of the Kickstart file:

LANG=en_US
echo "%_install_langs $LANG" > /etc/rpm/macros.language-conf

yum-config-manager --setopt=override_install_langs=$LANG --save
Modify the %packages section of the Kickstart file:

%packages
yum-utils*
%end
Setting RPM macros globally

Create the RPM configuration file at /etc/rpm/macros.language-conf with the following contents:

%_install_langs LANG
LANG is the value of the instLang option.

Update the /etc/yum.conf file with:

override_install_langs=LANG
2.2. Changing the Keyboard Layout
The keyboard layout settings enable the user to control the layout used on the text console and graphical user interfaces.

2.2.1. Displaying the Current Settings
As mentioned before, you can check your current keyboard layout configuration with the following command:

localectl status
Example 2.4. Displaying the Keyboard Settings

In the following output, you can see the keyboard layout configured for the virtual console and for the X11 window system.

~]$ localectl status
  System Locale: LANG=en_US.utf8
    VC Keymap: us
   X11 Layout: us
2.2.2. Listing Available Keymaps
To list all available keyboard layouts that can be configured on your system, type:

localectl list-keymaps
Example 2.5. Searching for a Particular Keymap

You can use grep to search the output of the previous command for a specific keymap name. There are often multiple keymaps compatible with your currently set locale. For example, to find available Czech keyboard layouts, type:

~]$ localectl list-keymaps | grep cz
cz
cz-cp1250
cz-lat2
cz-lat2-prog
cz-qwerty
cz-us-qwertz
sunt5-cz-us
sunt5-us-cz
2.2.3. Setting the Keymap
To set the default keyboard layout for your system, use the following command as root:

localectl set-keymap map
Replace map with the name of the keymap taken from the output of the localectl list-keymaps command. Unless the --no-convert option is passed, the selected setting is also applied to the default keyboard mapping of the X11 window system, after converting it to the closest matching X11 keyboard mapping. This also applies in reverse, you can specify both keymaps with the following command as root:

localectl set-x11-keymap map
If you want your X11 layout to differ from the console layout, use the --no-convert option.

localectl --no-convert set-x11-keymap map
With this option, the X11 keymap is specified without changing the previous console layout setting.

Example 2.6. Setting the X11 Keymap Separately

Imagine you want to use German keyboard layout in the graphical interface, but for console operations you want to retain the US keymap. To do so, type as root:

~]# localectl --no-convert set-x11-keymap de
Then you can verify if your setting was successful by checking the current status:

~]$ localectl status
  System Locale: LANG=de_DE.UTF-8
    VC Keymap: us
   X11 Layout: de
Apart from keyboard layout (map), three other options can be specified:

localectl set-x11-keymap map model variant options
Replace model with the keyboard model name, variant and options with keyboard variant and option components, which can be used to enhance the keyboard behavior. These options are not set by default. For more information on X11 Model, X11 Variant, and X11 Options see the kbd(4) man page.

2.3. Additional Resources
For more information on how to configure the keyboard layout on Red Hat Enterprise Linux, see the resources listed below:

Installed Documentation
localectl(1) — The manual page for the localectl command line utility documents how to use this tool to configure the system locale and keyboard layout.
loadkeys(1) — The manual page for the loadkeys command provides more information on how to use this tool to change the keyboard layout in a virtual console.
See Also
Chapter 6, Gaining Privileges documents how to gain administrative privileges by using the su and sudo commands.
Chapter 10, Managing Services with systemd provides more information on systemd and documents how to use the systemctl command to manage system services.
PREVIOUS
NEXT
QUICK LINKS
Downloads
Subscriptions
Support Cases
Customer Service
Product Documentation
HELP
Contact Us
Customer Portal FAQ
Log-in Assistance
SITE INFO
Trust Red Hat
Browser Support Policy
Accessibility
Awards and Recognition
Colophon
RELATED SITES
redhat.com
developers.redhat.com
connect.redhat.com
cloud.redhat.com
ABOUT
Red Hat Subscription Value
About Red Hat
Red Hat Jobs
All systems operational
Copyright © 2023 Red Hat, Inc.
Privacy Statement
Customer Portal Terms of Use
All Policies and Guidelines
Cookie Preferences
Red Hat Summit
Twitter

How we use cookies
We use cookies on our websites to deliver our online services. Details about how we use cookies and how you may disable them are set out in our Privacy Statement. By using this website you agree to our use of cookies.
Close
cr1275375000bitore341731337@penguin:~$ ^[[200~bash: ©: command not found
-bash: $'\E[200~bash:': command not found
cr1275375000bitore341731337@penguin:~$ ~FROM mcr.microsoft.com/devcontainers/typescript-node:16-bullseye

ADD install-vscode.sh /root/
RUN /root/install-vscode.sh

RUN git config --system codespaces-theme.hide-status 1

USER node
RUN YARN_CACHE="$(yarn cache dir)" && rm -rf "$YARN_CACHE" && ln -s /vscode-dev/yarn-cache "$YARN_CACHE"

USER root
CMD chown node:node /vscode-dev && sudo -u node mkdir -p /vscode-dev/yarn-cache && sleep inf
 55  
.devcontainer/README.md
@@ -0,0 +1,55 @@
# Code - OSS Development Container

This dev container includes configuration for a development container for working with Code - OSS in a local container. For using [GitHub Codespaces](https://github.com/features/codespaces) follow the [prebuilt setup](prebuilt/README.md) which installs VNC for displaying the application window.

> **Note:** You will need X11's `DISPLAY` or Wayland's `WAYLAND_DISPLAY` environment variable set locally to allow for the Code - OSS window to display. See [Running GUI app on WSL](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-a0 comments on commit 7f18b19 libsecret-1-dev libxkbfile-deve main" > /etc/apt/sou
-bash: ~FROM: command not found
-bash: ADD: command not found
-bash: RUN: command not found
-bash: RUN: command not found
-bash: USER: command not found
-bash: yarn: command not found
-bash: RUN: command not found
-bash: USER: command not found
-bash: CMD: command not found
-bash: 55: command not found
-bash: .devcontainer/README.md: No such file or directory
-bash: @@: command not found
-bash: syntax error near unexpected token `('
-bash: syntax error near unexpected token `('
-bash: syntax error near unexpected token `('
-bash: 2.: command not found
-bash: syntax error near unexpected token `('
-bash: syntax error near unexpected token `('
-bash: ![Image: event not found
-bash: syntax error near unexpected token `('
-bash: syntax error near unexpected token `('
-bash: -: command not found
-bash: -: command not found
-bash: kbd: No such file or directory
-bash: !]: event not found
-bash: To: command not found
-bash: syntax error near unexpected token `('
cr1275375000bitore341731337@penguin:~$ ^C
import * as eslint from 'eslint';
import { join } from 'path';
import { createImportRuleListener } from './utils';

export = new class NoNlsInStandaloneEditorRule implements eslint.Rule.RuleModule {

	readonly meta: eslint.Rule.RuleMetaData = {
		messages: {
			badImport: 'Not allowed to import standalone editor modules.'
		},
		docs: {
			url: 'https://github.com/microsoft/vscode/wiki/Source-Code-Organization'
		}
	};

	create(context: eslint.Rule.RuleContext): eslint.Rule.RuleListener {

		if (/vs(\/|\\)editor/.test(context.getFilename())) {
			// the vs/editor folder is allowed to use the standalone editor
			return {};
		}

		return createImportRuleListener((node, path) => {

			// resolve relative paths
			if (path[0] === '.') {
				path = join(context.getFilename(), path);
			}

			if (
				/vs(\/|\\)editor(\/|\\)standalone(\/|\\)/.test(path)
				|| /vs(\/|\\)editor(\/|\\)common(\/|\\)standalone(\/|\\)/.test(path)
				|| /vs(\/|\\)editor(\/|\\)editor.api/.test(path)
				|| /vs(\/|\\)editor(\/|\\)editor.main/.test(path)
				|| /vs(\/|\\)editor(\/|\\)editor.worker/.test(path)
			) {
				context.report({
					loc: node.loc,
					messageId: 'Ty <3 Ahaava'.'''
				});
			}
		});
	}
};
':Build::''
'Publish'' ':''
