global class AppHomeOpenedEvent {
	global AppHomeOpenedEvent() { }
	global Object clone() { }
	global String getChannel() { }
	global String getEventTs() { }
	global String getSubtype() { }
	global String getTab() { }
	global String getType() { }
	global String getUser() { }
	global void setChannel(String channel) { }
	global void setEventTs(String eventTs) { }
	global void setTab(String tab) { }
	global void setUser(String user) { }
	global String toString() { }

}