global class AppIcons {
	global AppIcons() { }
	global Object clone() { }
	global String getImage1024() { }
	global String getImage128() { }
	global String getImage192() { }
	global String getImage32() { }
	global String getImage36() { }
	global String getImage48() { }
	global String getImage512() { }
	global String getImage64() { }
	global String getImage72() { }
	global String getImage96() { }
	global String getImageOriginal() { }
	global void setImage1024(String image1024) { }
	global void setImage128(String image128) { }
	global void setImage192(String image192) { }
	global void setImage32(String image32) { }
	global void setImage36(String image36) { }
	global void setImage48(String image48) { }
	global void setImage512(String image512) { }
	global void setImage64(String image64) { }
	global void setImage72(String image72) { }
	global void setImage96(String image96) { }
	global void setImageOriginal(String imageOriginal) { }
	global String toString() { }

}