global class AppScope {
	global AppScope() { }
	global Object clone() { }
	global String getDescription() { }
	global String getName() { }
	global String getTokenType() { }
	global Boolean isSensitive() { }
	global void setDescription(String description) { }
	global void setName(String name) { }
	global void setSensitive(Boolean sensitive) { }
	global void setTokenType(String tokenType) { }
	global String toString() { }

}