global class AuthTestResponse {
	global AuthTestResponse() { }
	global Object clone() { }
	global String getAppId() { }
	global String getAppName() { }
	global String getBotId() { }
	global String getEnterpriseId() { }
	global String getError() { }
	global Map<String,List<String>> getHttpResponseHeaders() { }
	global String getNeeded() { }
	global String getProvided() { }
	global String getTeam() { }
	global String getTeamId() { }
	global String getUrl() { }
	global String getUser() { }
	global String getUserId() { }
	global String getWarning() { }
	global Boolean isEnterpriseInstall() { }
	global Boolean isOk() { }
	global void setAppId(String appId) { }
	global void setAppName(String appName) { }
	global void setBotId(String botId) { }
	global void setEnterpriseId(String enterpriseId) { }
	global void setEnterpriseInstall(Boolean isEnterpriseInstall) { }
	global void setError(String error) { }
	global void setHttpResponseHeaders(Map<String,List<String>> httpResponseHeaders) { }
	global void setNeeded(String needed) { }
	global void setOk(Boolean ok) { }
	global void setProvided(String provided) { }
	global void setTeam(String team) { }
	global void setTeamId(String teamId) { }
	global void setUrl(String url) { }
	global void setUser(String user) { }
	global void setUserId(String userId) { }
	global void setWarning(String warning) { }
	global String toString() { }

}