global class BookmarksListRequest {
	global static Slack.BookmarksListRequest.Builder builder() { }
	global Object clone() { }
	global String getChannelId() { }
	global String toString() { }
global class Builder {
	global BookmarksListRequest.Builder() { }
	global Slack.BookmarksListRequest build() { }
	global Slack.BookmarksListRequest.Builder channelId(String channelId) { }
	global Object clone() { }

}

}