global class Bookmark {
	global Bookmark() { }
	global Object clone() { }
	global String getAppId() { }
	global String getChannelId() { }
	global Integer getDateCreated() { }
	global Integer getDateUpdated() { }
	global String getEmoji() { }
	global String getEntityId() { }
	global String getIconUrl() { }
	global String getId() { }
	global String getLastUpdatedByTeamId() { }
	global String getLastUpdatedByUserId() { }
	global String getLink() { }
	global String getRank() { }
	global String getShortcutId() { }
	global String getTitle() { }
	global String getType() { }
	global void setAppId(String appId) { }
	global void setChannelId(String channelId) { }
	global void setDateCreated(Integer dateCreated) { }
	global void setDateUpdated(Integer dateUpdated) { }
	global void setEmoji(String emoji) { }
	global void setEntityId(String entityId) { }
	global void setIconUrl(String iconUrl) { }
	global void setId(String id) { }
	global void setLastUpdatedByTeamId(String lastUpdatedByTeamId) { }
	global void setLastUpdatedByUserId(String lastUpdatedByUserId) { }
	global void setLink(String link) { }
	global void setRank(String rank) { }
	global void setShortcutId(String shortcutId) { }
	global void setTitle(String title) { }
	global void setType(String type) { }
	global String toString() { }

}