global class CallRejectedEvent {
	global CallRejectedEvent() { }
	global Object clone() { }
	global String getCallId() { }
	global String getChannelId() { }
	global String getExternalUniqueId() { }
	global String getSubtype() { }
	global String getType() { }
	global String getUserId() { }
	global void setCallId(String callId) { }
	global void setChannelId(String channelId) { }
	global void setExternalUniqueId(String externalUniqueId) { }
	global void setUserId(String userId) { }
	global String toString() { }

}