global class CallParticipant {
	global CallParticipant() { }
	global Object clone() { }
	global String getAvatarUrl() { }
	global String getDisplayName() { }
	global String getExternalId() { }
	global String getSlackId() { }
	global void setAvatarUrl(String avatarUrl) { }
	global void setDisplayName(String displayName) { }
	global void setExternalId(String externalId) { }
	global void setSlackId(String slackId) { }
	global String toString() { }

}