global class ChannelUnsharedEvent {
	global ChannelUnsharedEvent() { }
	global Object clone() { }
	global String getChannel() { }
	global String getEventTs() { }
	global String getPreviouslyConnectedTeamId() { }
	global String getSubtype() { }
	global String getType() { }
	global Boolean isExtShared() { }
	global void setChannel(String channel) { }
	global void setEventTs(String eventTs) { }
	global void setExtShared(Boolean isExtShared) { }
	global void setPreviouslyConnectedTeamId(String previouslyConnectedTeamId) { }
	global String toString() { }

}