global class ChannelSharedEvent {
	global ChannelSharedEvent() { }
	global Object clone() { }
	global String getChannel() { }
	global String getConnectedTeamId() { }
	global String getEventTs() { }
	global String getSubtype() { }
	global String getType() { }
	global void setChannel(String channel) { }
	global void setConnectedTeamId(String connectedTeamId) { }
	global void setEventTs(String eventTs) { }
	global String toString() { }

}