global class ChannelIdChangedEvent {
	global ChannelIdChangedEvent() { }
	global Object clone() { }
	global String getEventTs() { }
	global String getNewChannelId() { }
	global String getOldChannelId() { }
	global String getSubtype() { }
	global String getType() { }
	global void setEventTs(String eventTs) { }
	global void setNewChannelId(String newChannelId) { }
	global void setOldChannelId(String oldChannelId) { }
	global String toString() { }

}