global class ChannelArchiveEvent {
	global ChannelArchiveEvent() { }
	global Object clone() { }
	global String getChannel() { }
	global String getEventTs() { }
	global Integer getIsMoved() { }
	global String getSubtype() { }
	global String getType() { }
	global String getUser() { }
	global void setChannel(String channel) { }
	global void setEventTs(String eventTs) { }
	global void setIsMoved(Integer isMoved) { }
	global void setUser(String user) { }
	global String toString() { }

}