global class ChatPostEphemeralResponse {
	global ChatPostEphemeralResponse() { }
	global Object clone() { }
	global String getDeprecatedArgument() { }
	global String getError() { }
	global Map<String,List<String>> getHttpResponseHeaders() { }
	global String getMessageTs() { }
	global String getNeeded() { }
	global String getProvided() { }
	global String getWarning() { }
	global Boolean isOk() { }
	global void setDeprecatedArgument(String deprecatedArgument) { }
	global void setError(String error) { }
	global void setHttpResponseHeaders(Map<String,List<String>> httpResponseHeaders) { }
	global void setMessageTs(String messageTs) { }
	global void setNeeded(String needed) { }
	global void setOk(Boolean ok) { }
	global void setProvided(String provided) { }
	global void setWarning(String warning) { }
	global String toString() { }

}