global class ChatDeleteResponse {
	global ChatDeleteResponse() { }
	global Object clone() { }
	global String getChannel() { }
	global String getDeprecatedArgument() { }
	global String getError() { }
	global Map<String,List<String>> getHttpResponseHeaders() { }
	global String getNeeded() { }
	global String getProvided() { }
	global String getTs() { }
	global String getWarning() { }
	global Boolean isOk() { }
	global void setChannel(String channel) { }
	global void setDeprecatedArgument(String deprecatedArgument) { }
	global void setError(String error) { }
	global void setHttpResponseHeaders(Map<String,List<String>> httpResponseHeaders) { }
	global void setNeeded(String needed) { }
	global void setOk(Boolean ok) { }
	global void setProvided(String provided) { }
	global void setTs(String ts) { }
	global void setWarning(String warning) { }
	global String toString() { }

}