global class ConnectUserProfile {
	global ConnectUserProfile() { }
	global Object clone() { }
	global String getAvatarHash() { }
	global String getDisplayName() { }
	global String getDisplayNameNormalized() { }
	global String getEmail() { }
	global String getImage1024() { }
	global String getImage192() { }
	global String getImage24() { }
	global String getImage32() { }
	global String getImage48() { }
	global String getImage512() { }
	global String getImage72() { }
	global String getImageOriginal() { }
	global Boolean getIsCustomImage() { }
	global String getRealName() { }
	global String getRealNameNormalized() { }
	global String getTeam() { }
	global void setAvatarHash(String avatarHash) { }
	global void setDisplayName(String displayName) { }
	global void setDisplayNameNormalized(String displayNameNormalized) { }
	global void setEmail(String email) { }
	global void setImage1024(String image1024) { }
	global void setImage192(String image192) { }
	global void setImage24(String image24) { }
	global void setImage32(String image32) { }
	global void setImage48(String image48) { }
	global void setImage512(String image512) { }
	global void setImage72(String image72) { }
	global void setImageOriginal(String imageOriginal) { }
	global void setIsCustomImage(Boolean isCustomImage) { }
	global void setRealName(String realName) { }
	global void setRealNameNormalized(String realNameNormalized) { }
	global void setTeam(String team) { }
	global String toString() { }

}