global class ConnectTeam {
	global ConnectTeam() { }
	global Object clone() { }
	global String getAvatarBaseUrl() { }
	global Integer getDateCreated() { }
	global String getDomain() { }
	global Slack.TeamIcon getIcon() { }
	global String getId() { }
	global String getName() { }
	global Boolean isVerified() { }
	global void setAvatarBaseUrl(String avatarBaseUrl) { }
	global void setDateCreated(Integer dateCreated) { }
	global void setDomain(String domain) { }
	global void setIcon(Slack.TeamIcon icon) { }
	global void setId(String id) { }
	global void setName(String name) { }
	global void setVerified(Boolean isVerified) { }
	global String toString() { }

}