global class ConnectUser {
	global ConnectUser() { }
	global Object clone() { }
	global String getId() { }
	global String getName() { }
	global Slack.ConnectUserProfile getProfile() { }
	global String getTeamId() { }
	global Integer getUpdated() { }
	global String getWhoCanShareContactCard() { }
	global void setId(String id) { }
	global void setName(String name) { }
	global void setProfile(Slack.ConnectUserProfile profile) { }
	global void setTeamId(String teamId) { }
	global void setUpdated(Integer updated) { }
	global void setWhoCanShareContactCard(String whoCanShareContactCard) { }
	global String toString() { }

}