global class EmojiListRequest {
	global static Slack.EmojiListRequest.Builder builder() { }
	global Object clone() { }
	global Boolean getIncludeCategories() { }
	global String toString() { }
global class Builder {
	global EmojiListRequest.Builder() { }
	global Slack.EmojiListRequest build() { }
	global Object clone() { }
	global Slack.EmojiListRequest.Builder includeCategories(Boolean includeCategories) { }

}

}