global class EmojiChangedEvent {
	global EmojiChangedEvent() { }
	global Object clone() { }
	global String getEventTs() { }
	global String getName() { }
	global List<String> getNames() { }
	global String getNewName() { }
	global String getOldName() { }
	global String getSubtype() { }
	global String getType() { }
	global String getValue() { }
	global void setEventTs(String eventTs) { }
	global void setName(String name) { }
	global void setNames(List<String> names) { }
	global void setNewName(String newName) { }
	global void setOldName(String oldName) { }
	global void setSubtype(String subtype) { }
	global void setValue(String value) { }
	global String toString() { }

}