global class FilesRevokePublicURLRequest {
	global static Slack.FilesRevokePublicURLRequest.Builder builder() { }
	global Object clone() { }
	global String getFile() { }
	global String toString() { }
global class Builder {
	global FilesRevokePublicURLRequest.Builder() { }
	global Slack.FilesRevokePublicURLRequest build() { }
	global Object clone() { }
	global Slack.FilesRevokePublicURLRequest.Builder file(String file) { }

}

}