global class FileComment {
	global FileComment() { }
	global Object clone() { }
	global String getChannel() { }
	global String getComment() { }
	global Integer getCreated() { }
	global String getId() { }
	global Integer getTimestamp() { }
	global String getUser() { }
	global Boolean isIntro() { }
	global void setChannel(String channel) { }
	global void setComment(String comment) { }
	global void setCreated(Integer created) { }
	global void setId(String id) { }
	global void setIntro(Boolean intro) { }
	global void setTimestamp(Integer timestamp) { }
	global void setUser(String user) { }
	global String toString() { }

}