global class FilesSharedPublicURLRequest {
	global static Slack.FilesSharedPublicURLRequest.Builder builder() { }
	global Object clone() { }
	global String getFile() { }
	global String toString() { }
global class Builder {
	global FilesSharedPublicURLRequest.Builder() { }
	global Slack.FilesSharedPublicURLRequest build() { }
	global Object clone() { }
	global Slack.FilesSharedPublicURLRequest.Builder file(String file) { }

}

}