global class GroupDeletedEvent {
	global GroupDeletedEvent() { }
	global Object clone() { }
	global String getActorId() { }
	global String getChannel() { }
	global Integer getDateDeleted() { }
	global String getEventTs() { }
	global String getSubtype() { }
	global String getType() { }
	global void setActorId(String actorId) { }
	global void setChannel(String channel) { }
	global void setDateDeleted(Integer dateDeleted) { }
	global void setEventTs(String eventTs) { }
	global String toString() { }

}