global class GroupUnarchiveEvent {
	global GroupUnarchiveEvent() { }
	global Object clone() { }
	global String getActorId() { }
	global String getChannel() { }
	global String getEventTs() { }
	global String getSubtype() { }
	global String getType() { }
	global void setActorId(String actorId) { }
	global void setChannel(String channel) { }
	global void setEventTs(String eventTs) { }
	global String toString() { }

}