global class GroupHistoryChangedEvent {
	global GroupHistoryChangedEvent() { }
	global Object clone() { }
	global String getEventTs() { }
	global String getLatest() { }
	global String getSubtype() { }
	global String getTs() { }
	global String getType() { }
	global void setEventTs(String eventTs) { }
	global void setLatest(String latest) { }
	global void setTs(String ts) { }
	global String toString() { }

}