global class IntegrationLog {
	global IntegrationLog() { }
	global Object clone() { }
	global String getAppId() { }
	global String getAppType() { }
	global String getChangeType() { }
	global String getChannel() { }
	global Integer getDate() { }
	global String getReason() { }
	global String getResolution() { }
	global String getRssFeedChangeType() { }
	global String getRssFeedTitle() { }
	global String getRssFeedUrl() { }
	global String getScope() { }
	global String getServiceId() { }
	global String getServiceType() { }
	global String getUserId() { }
	global String getUserName() { }
	global Boolean isRssFeed() { }
	global void setAppId(String appId) { }
	global void setAppType(String appType) { }
	global void setChangeType(String changeType) { }
	global void setChannel(String channel) { }
	global void setDate(Integer dateValue) { }
	global void setReason(String reason) { }
	global void setResolution(String resolution) { }
	global void setRssFeed(Boolean rssFeed) { }
	global void setRssFeedChangeType(String rssFeedChangeType) { }
	global void setRssFeedTitle(String rssFeedTitle) { }
	global void setRssFeedUrl(String rssFeedUrl) { }
	global void setScope(String scope) { }
	global void setServiceId(String serviceId) { }
	global void setServiceType(String serviceType) { }
	global void setUserId(String userId) { }
	global void setUserName(String userName) { }
	global String toString() { }

}