global class Login {
	global Login() { }
	global Object clone() { }
	global Integer getCount() { }
	global String getCountry() { }
	global Integer getDateFirst() { }
	global Integer getDateLast() { }
	global String getIp() { }
	global String getIsp() { }
	global String getRegion() { }
	global String getUserAgent() { }
	global String getUserId() { }
	global String getUsername() { }
	global void setCount(Integer count) { }
	global void setCountry(String country) { }
	global void setDateFirst(Integer dateFirst) { }
	global void setDateLast(Integer dateLast) { }
	global void setIp(String ip) { }
	global void setIsp(String isp) { }
	global void setRegion(String region) { }
	global void setUserAgent(String userAgent) { }
	global void setUserId(String userId) { }
	global void setUsername(String username) { }
	global String toString() { }

}