global class MemberJoinedChannelEvent {
	global MemberJoinedChannelEvent() { }
	global Object clone() { }
	global String getChannel() { }
	global String getChannelType() { }
	global String getEventTs() { }
	global String getInviter() { }
	global String getSubtype() { }
	global String getTeam() { }
	global String getType() { }
	global String getUser() { }
	global void setChannel(String channel) { }
	global void setChannelType(String channelType) { }
	global void setEventTs(String eventTs) { }
	global void setInviter(String inviter) { }
	global void setTeam(String team) { }
	global void setUser(String user) { }
	global String toString() { }

}