global class MessageBotEvent {
	global MessageBotEvent() { }
	global Object clone() { }
	global String getBotId() { }
	global String getChannel() { }
	global String getChannelType() { }
	global String getEventTs() { }
	global String getSubtype() { }
	global String getText() { }
	global String getThreadTs() { }
	global String getTs() { }
	global String getType() { }
	global String getUsername() { }
	global void setBotId(String botId) { }
	global void setChannel(String channel) { }
	global void setChannelType(String channelType) { }
	global void setEventTs(String eventTs) { }
	global void setText(String text) { }
	global void setThreadTs(String threadTs) { }
	global void setTs(String ts) { }
	global void setUsername(String username) { }
	global String toString() { }

}