global class MessageChannelJoinEvent {
	global MessageChannelJoinEvent() { }
	global Object clone() { }
	global String getChannel() { }
	global String getChannelType() { }
	global String getEventTs() { }
	global String getInviter() { }
	global String getSubtype() { }
	global String getTeam() { }
	global String getText() { }
	global String getTs() { }
	global String getType() { }
	global String getUser() { }
	global void setChannel(String channel) { }
	global void setChannelType(String channelType) { }
	global void setEventTs(String eventTs) { }
	global void setInviter(String inviter) { }
	global void setTeam(String team) { }
	global void setText(String text) { }
	global void setTs(String ts) { }
	global void setUser(String user) { }
	global String toString() { }

}