global class MessageFileShareEvent {
	global MessageFileShareEvent() { }
	global Object clone() { }
	global String getChannel() { }
	global String getChannelType() { }
	global Boolean getDisplayAsBot() { }
	global String getEventTs() { }
	global List<Slack.File> getFiles() { }
	global String getParentUserId() { }
	global String getSubtype() { }
	global String getText() { }
	global String getThreadTs() { }
	global String getTs() { }
	global String getType() { }
	global Boolean getUpload() { }
	global String getUser() { }
	global List<String> getXFiles() { }
	global void setChannel(String channel) { }
	global void setChannelType(String channelType) { }
	global void setDisplayAsBot(Boolean displayAsBot) { }
	global void setEventTs(String eventTs) { }
	global void setFiles(List<Slack.File> files) { }
	global void setParentUserId(String parentUserId) { }
	global void setText(String text) { }
	global void setThreadTs(String threadTs) { }
	global void setTs(String ts) { }
	global void setUpload(Boolean upload) { }
	global void setUser(String user) { }
	global void setXFiles(List<String> xFiles) { }
	global String toString() { }

}