global class Paging {
	global Paging() { }
	global Object clone() { }
	global Integer getCount() { }
	global String getIid() { }
	global Integer getPage() { }
	global Integer getPages() { }
	global Integer getPerPage() { }
	global Integer getSpill() { }
	global Integer getTotal() { }
	global void setCount(Integer count) { }
	global void setIid(String iid) { }
	global void setPage(Integer page) { }
	global void setPages(Integer pages) { }
	global void setPerPage(Integer perPage) { }
	global void setSpill(Integer spill) { }
	global void setTotal(Integer total) { }
	global String toString() { }

}