global class RequestedApp {
	global RequestedApp() { }
	global Object clone() { }
	global String getAdditionalInfo() { }
	global String getAppDirectoryUrl() { }
	global String getAppHomepageUrl() { }
	global String getDescription() { }
	global String getHelpUrl() { }
	global Slack.AppIcons getIcons() { }
	global String getId() { }
	global String getName() { }
	global String getPrivacyPolicyUrl() { }
	global Boolean isAppDirectoryApproved() { }
	global Boolean isInternal() { }
	global void setAdditionalInfo(String additionalInfo) { }
	global void setAppDirectoryApproved(Boolean appDirectoryApproved) { }
	global void setAppDirectoryUrl(String appDirectoryUrl) { }
	global void setAppHomepageUrl(String appHomepageUrl) { }
	global void setDescription(String description) { }
	global void setHelpUrl(String helpUrl) { }
	global void setIcons(Slack.AppIcons icons) { }
	global void setId(String id) { }
	global void setInternal(Boolean internal) { }
	global void setName(String name) { }
	global void setPrivacyPolicyUrl(String privacyPolicyUrl) { }
	global String toString() { }

}