global class TeamIcon {
	global TeamIcon() { }
	global Object clone() { }
	global String getImage102() { }
	global String getImage132() { }
	global String getImage230() { }
	global String getImage34() { }
	global String getImage44() { }
	global String getImage68() { }
	global String getImage88() { }
	global String getImageOriginal() { }
	global Boolean isImageDefault() { }
	global void setImage102(String image102) { }
	global void setImage132(String image132) { }
	global void setImage230(String image230) { }
	global void setImage34(String image34) { }
	global void setImage44(String image44) { }
	global void setImage68(String image68) { }
	global void setImage88(String image88) { }
	global void setImageDefault(Boolean imageDefault) { }
	global void setImageOriginal(String imageOriginal) { }
	global String toString() { }

}