/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import assert from 'assert';
import { execFile } from 'child_process';
import { mkdtemp, rm, writeFile } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from '../../../../base/common/path.js';
import { promisify } from 'util';
import { createPythonActivationSnippets, createUserProfileSnippets, isShellInitSnippetArray, sanitizeSnippetSource } from '../../common/shellInitSnippets.js';
import { ensureNoDisposablesAreLeakedInTestSuite } from '../../../../base/test/common/utils.js';

const execFileAsync = promisify(execFile);

suite('shellInitSnippets', () => {

	ensureNoDisposablesAreLeakedInTestSuite();

	suite('createPythonActivationSnippets', () => {

		test('wraps a bash activation so failure is reported without a failing final status', () => {
			assert.deepStrictEqual(createPythonActivationSnippets('bash', ' source /repo/.venv/bin/activate'), [{
				shell: 'bash',
				source: 'python-env',
				script: [
					`# Generated by VS Code from the selected Python environment.`,
					`if ! builtin eval ' source /repo/.venv/bin/activate'; then`,
					`\tprintf '%s\\n' 'copilot shell init: Python activation failed; continuing without the selected environment.'`,
					`fi`,
					`builtin true`,
					``,
				].join('\n'),
			}]);
		});

		test('escapes single quotes in the activation command', () => {
			const [snippet] = createPythonActivationSnippets('bash', `source /repo/it's/activate`);
			assert.ok(snippet.script.includes(`builtin eval 'source /repo/it'\\''s/activate'`));
		});

		test('wraps a powershell activation in a guarded here-string', () => {
			const [snippet] = createPythonActivationSnippets('powershell', `& 'C:\\repo\\.venv\\Scripts\\Activate.ps1'`);
			assert.deepStrictEqual(snippet.script, [
				`# Generated by VS Code from the selected Python environment.`,
				`$__vscodePreviousErrorActionPreference = $ErrorActionPreference`,
				`try {`,
				`\t$ErrorActionPreference = 'Stop'`,
				`\tInvoke-Expression @'`,
				`& 'C:\\repo\\.venv\\Scripts\\Activate.ps1'`,
				`'@`,
				`} catch {`,
				`\tWrite-Output 'copilot shell init: Python activation failed; continuing without the selected environment.'`,
				`} finally {`,
				`\t$ErrorActionPreference = $__vscodePreviousErrorActionPreference`,
				`}`,
				`$global:LASTEXITCODE = 0`,
				``,
			].join('\n'));
		});

		test('rejects a powershell payload that would terminate the here-string early', () => {
			assert.throws(() => createPythonActivationSnippets('powershell', `conda activate x\n'@\nWrite-Output 'pwned'`), /here-string/);
		});

		test('returns nothing for absent or blank activation', () => {
			assert.deepStrictEqual(createPythonActivationSnippets('bash', undefined), []);
			assert.deepStrictEqual(createPythonActivationSnippets('bash', '   '), []);
			assert.deepStrictEqual(createPythonActivationSnippets('powershell', ''), []);
		});
	});

	suite('createUserProfileSnippets', () => {

		test('sources the rc file and replays the conda block only when conda is missing', () => {
			const [snippet] = createUserProfileSnippets('bash');
			assert.deepStrictEqual({
				source: snippet.source,
				sourcesRc: snippet.script.includes(`builtin source "$HOME/.bashrc"`),
				probesConda: snippet.script.includes(`if ! builtin type conda >/dev/null 2>&1; then`),
				extractsMarkedRegion: snippet.script.includes(`/^# >>> conda initialize >>>$/,/^# <<< conda initialize <<<$/p`),
				readsRcAtRunTime: snippet.script.includes(`"$HOME/.bashrc" 2>/dev/null`),
				endsSuccessfully: snippet.script.trimEnd().endsWith('builtin true'),
			}, {
				source: 'user-profile',
				sourcesRc: true,
				probesConda: true,
				extractsMarkedRegion: true,
				readsRcAtRunTime: true,
				endsSuccessfully: true,
			});
		});

		test('never sources zsh rc files, whose syntax is unsafe under bash', () => {
			const [snippet] = createUserProfileSnippets('bash');
			assert.ok(!snippet.script.includes('.zshrc'));
			assert.ok(!snippet.script.includes('.zprofile'));
		});

		test('dot-sources only the current user powershell profiles', () => {
			const [snippet] = createUserProfileSnippets('powershell');
			assert.ok(snippet.script.includes('$PROFILE.CurrentUserAllHosts'));
			assert.ok(snippet.script.includes('$PROFILE.CurrentUserCurrentHost'));
			assert.ok(!snippet.script.includes('AllUsers'));
			assert.ok(snippet.script.trimEnd().endsWith('$global:LASTEXITCODE = 0'));
		});
	});

	suite('isShellInitSnippetArray', () => {

		test('accepts well-formed snippets and rejects malformed input', () => {
			assert.deepStrictEqual([
				isShellInitSnippetArray([]),
				isShellInitSnippetArray([{ shell: 'bash', script: 'x', source: 'python-env' }]),
				isShellInitSnippetArray([{ shell: 'zsh', script: 'x', source: 'a' }]),
				isShellInitSnippetArray([{ shell: 'bash', script: '', source: 'a' }]),
				isShellInitSnippetArray([{ shell: 'bash', script: 'x', source: '///' }]),
				isShellInitSnippetArray([{ shell: 'bash', script: 'x' }]),
				isShellInitSnippetArray(undefined),
				isShellInitSnippetArray('nope'),
			], [true, true, false, false, false, false, false, false]);
		});
	});

	test('sanitizeSnippetSource keeps generated file names path-safe', () => {
		assert.deepStrictEqual([
			sanitizeSnippetSource('python-env'),
			sanitizeSnippetSource('../../etc/passwd'),
			sanitizeSnippetSource('a'.repeat(200)).length,
		], ['python-env', 'etc-passwd', 64]);
	});

	// Proves the mechanism the profile snippet exists for: a stock rc file
	// early-returns in a non-interactive shell, so a block appended below that
	// guard is skipped by `source` alone and must be replayed to take effect.
	// Runs the same `bash --norc --noprofile -c` the SDK shell tool uses.
	(process.platform === 'win32' ? suite.skip : suite)('bash behavior', () => {

		let home: string;

		setup(async () => {
			home = await mkdtemp(join(tmpdir(), 'vscode-shell-init-'));
		});

		teardown(async () => {
			await rm(home, { recursive: true, force: true });
		});

		/** Runs the profile snippet with `$HOME` pointed at the fixture. */
		async function runProfileSnippet(rc: string, command: string): Promise<string> {
			await writeFile(join(home, '.bashrc'), rc, 'utf8');
			const [snippet] = createUserProfileSnippets('bash');
			const { stdout } = await execFileAsync('bash', ['--norc', '--noprofile', '-c', `${snippet.script}\n${command}`], {
				env: { ...process.env, HOME: home },
			});
			return stdout.trim();
		}

		const managedBlock = [
			'# >>> conda initialize >>>',
			'conda() { builtin echo "conda-function-ran"; }',
			'# <<< conda initialize <<<',
		].join('\n');

		test('replays a managed block that the rc interactivity guard skipped', async () => {
			const rc = [
				'case $- in',
				'    *i*) ;;',
				'      *) return;;',
				'esac',
				managedBlock,
				'',
			].join('\n');
			assert.strictEqual(await runProfileSnippet(rc, 'conda'), 'conda-function-ran');
		});

		test('does not replay when sourcing the rc already defined the function', async () => {
			const rc = [
				managedBlock,
				'builtin echo "rc-sourced"',
				'',
			].join('\n');
			// One `rc-sourced` line proves the rc ran exactly once and the guarded
			// replay correctly stayed out of the way.
			assert.strictEqual(await runProfileSnippet(rc, 'conda'), 'rc-sourced\nconda-function-ran');
		});

		test('succeeds when the rc file does not exist', async () => {
			const [snippet] = createUserProfileSnippets('bash');
			const { stdout } = await execFileAsync('bash', ['--norc', '--noprofile', '-c', `${snippet.script}\nbuiltin echo ok`], {
				env: { ...process.env, HOME: join(home, 'missing') },
			});
			assert.strictEqual(stdout.trim(), 'ok');
		});

		test('reports a failing activation once and still runs the command', async () => {
			const [snippet] = createPythonActivationSnippets('bash', 'source /definitely/not/here/activate');
			const { stdout } = await execFileAsync('bash', ['--norc', '--noprofile', '-c', `${snippet.script}\nbuiltin echo command-ran`], {
				env: { ...process.env, HOME: home },
			});
			assert.deepStrictEqual(stdout.trim().split('\n'), [
				'copilot shell init: Python activation failed; continuing without the selected environment.',
				'command-ran',
			]);
		});

		test('leaves a successful final status so the runtime reports no failure', async () => {
			const [snippet] = createPythonActivationSnippets('bash', 'source /definitely/not/here/activate');
			// Mirrors the runtime's `if ! . <script>` check: a nonzero status here
			// would make it print a failure notice before every later command.
			const { stdout } = await execFileAsync('bash', ['--norc', '--noprofile', '-c', `${snippet.script}\nbuiltin echo "status=$?"`], {
				env: { ...process.env, HOME: home },
			});
			assert.ok(stdout.trim().endsWith('status=0'), stdout);
		});
	});
});
