/**
 * KernelBridge API
 * KernelBridge is a Jupyter kernel gateway and supervisor
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@lotas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Connection information for an existing session
*/
export class ConnectionInfo {
    /**
    * The port for control messages
    */
    'controlPort': number;
    /**
    * The port for shell messages
    */
    'shellPort': number;
    /**
    * The port for stdin messages
    */
    'stdinPort': number;
    /**
    * The port for heartbeat messages
    */
    'hbPort': number;
    /**
    * The port for IOPub messages
    */
    'iopubPort': number;
    /**
    * The signature scheme for messages
    */
    'signatureScheme': string;
    /**
    * The key for messages
    */
    'key': string;
    /**
    * The transport protocol
    */
    'transport': string;
    /**
    * The IP address for the connection
    */
    'ip': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "controlPort",
            "baseName": "control_port",
            "type": "number"
        },
        {
            "name": "shellPort",
            "baseName": "shell_port",
            "type": "number"
        },
        {
            "name": "stdinPort",
            "baseName": "stdin_port",
            "type": "number"
        },
        {
            "name": "hbPort",
            "baseName": "hb_port",
            "type": "number"
        },
        {
            "name": "iopubPort",
            "baseName": "iopub_port",
            "type": "number"
        },
        {
            "name": "signatureScheme",
            "baseName": "signature_scheme",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "transport",
            "baseName": "transport",
            "type": "string"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionInfo.attributeTypeMap;
    }
}

