/**
 * KernelBridge API
 * KernelBridge is a Jupyter kernel gateway and supervisor
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@lotas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The mechansim for interrupting the session
*/
export enum InterruptMode {
    Signal = <any> 'signal',
    Message = <any> 'message'
}
