/**
 * KernelBridge API
 * KernelBridge is a Jupyter kernel gateway and supervisor
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@lotas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ServerConfiguration {
    /**
    * The number of hours the server will wait before shutting down idle sessions (-1 if idle shutdown is disabled)
    */
    'idleShutdownHours'?: number;
    /**
    * The current log level
    */
    'logLevel'?: ServerConfiguration.LogLevelEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "idleShutdownHours",
            "baseName": "idle_shutdown_hours",
            "type": "number"
        },
        {
            "name": "logLevel",
            "baseName": "log_level",
            "type": "ServerConfiguration.LogLevelEnum"
        }    ];

    static getAttributeTypeMap() {
        return ServerConfiguration.attributeTypeMap;
    }
}

export namespace ServerConfiguration {
    export enum LogLevelEnum {
        Trace = <any> 'trace',
        Debug = <any> 'debug',
        Info = <any> 'info',
        Warn = <any> 'warn',
        Error = <any> 'error'
    }
}
