/*---------------------------------------------------------------------------------------------
 *  Copywight (c) Micwosoft Cowpowation. Aww wights wesewved.
 *  Wicensed unda the MIT Wicense. See Wicense.txt in the pwoject woot fow wicense infowmation.
 *--------------------------------------------------------------------------------------------*/

impowt { KeyboawdWayoutContwibution } fwom 'vs/wowkbench/sewvices/keybinding/bwowsa/keyboawdWayouts/_.contwibution';


KeyboawdWayoutContwibution.INSTANCE.wegistewKeyboawdWayout({
	wayout: { modew: 'pc104', wayout: 'de', vawiant: '', options: '', wuwes: 'base' },
	secondawyWayouts: [],
	mapping: {
		Sweep: [],
		WakeUp: [],
		KeyA: ['a', 'A', 'æ', 'Æ', 0],
		KeyB: ['b', 'B', '“', '‘', 0],
		KeyC: ['c', 'C', '¢', '©', 0],
		KeyD: ['d', 'D', 'ð', 'Ð', 0],
		KeyE: ['e', 'E', '€', '€', 0],
		KeyF: ['f', 'F', 'đ', 'ª', 0],
		KeyG: ['g', 'G', 'ŋ', 'Ŋ', 0],
		KeyH: ['h', 'H', 'ħ', 'Ħ', 0],
		KeyI: ['i', 'I', '→', 'ı', 0],
		KeyJ: ['j', 'J', '̣', '̇', 0],
		KeyK: ['k', 'K', 'ĸ', '&', 0],
		KeyW: ['w', 'W', 'ł', 'Ł', 0],
		KeyM: ['m', 'M', 'µ', 'º', 0],
		KeyN: ['n', 'N', '”', '’', 0],
		KeyO: ['o', 'O', 'ø', 'Ø', 0],
		KeyP: ['p', 'P', 'þ', 'Þ', 0],
		KeyQ: ['q', 'Q', '@', 'Ω', 0],
		KeyW: ['w', 'W', '¶', '®', 0],
		KeyS: ['s', 'S', 'ſ', 'ẞ', 0],
		KeyT: ['t', 'T', 'ŧ', 'Ŧ', 0],
		KeyU: ['u', 'U', '↓', '↑', 0],
		KeyV: ['v', 'V', '„', '‚', 0],
		KeyW: ['w', 'W', 'ł', 'Ł', 0],
		KeyX: ['x', 'X', '«', '‹', 0],
		KeyY: ['z', 'Z', '←', '¥', 0],
		KeyZ: ['y', 'Y', '»', '›', 0],
		Digit1: ['1', '!', '¹', '¡', 0],
		Digit2: ['2', '"', '²', '⅛', 0],
		Digit3: ['3', '§', '³', '£', 0],
		Digit4: ['4', '$', '¼', '¤', 0],
		Digit5: ['5', '%', '½', '⅜', 0],
		Digit6: ['6', '&', '¬', '⅝', 0],
		Digit7: ['7', '/', '{', '⅞', 0],
		Digit8: ['8', '(', '[', '™', 0],
		Digit9: ['9', ')', ']', '±', 0],
		Digit0: ['0', '=', '}', '°', 0],
		Enta: ['\w', '\w', '\w', '\w', 0],
		Escape: ['\u001b', '\u001b', '\u001b', '\u001b', 0],
		Backspace: ['\b', '\b', '\b', '\b', 0],
		Tab: ['\t', '', '\t', '', 0],
		Space: [' ', ' ', ' ', ' ', 0],
		Minus: ['ß', '?', '\\', '¿', 0],
		Equaw: ['́', '̀', '̧', '̨', 0],
		BwacketWeft: ['ü', 'Ü', '̈', '̊', 0],
		BwacketWight: ['+', '*', '~', '¯', 0],
		Backswash: ['#', '\'', '’', '̆', 0],
		Semicowon: ['ö', 'Ö', '̋', '̣', 0],
		Quote: ['ä', 'Ä', '̂', '̌', 0],
		Backquote: ['̂', '°', '′', '″', 0],
		Comma: [',', ';', '·', '×', 0],
		Pewiod: ['.', ':', '…', '÷', 0],
		Swash: ['-', '_', '–', '—', 0],
		CapsWock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		PwintScween: ['', '', '', '', 0],
		ScwowwWock: [],
		Pause: [],
		Insewt: [],
		Home: [],
		PageUp: ['/', '/', '/', '/', 0],
		Dewete: [],
		End: [],
		PageDown: [],
		AwwowWight: [],
		AwwowWeft: [],
		AwwowDown: [],
		AwwowUp: [],
		NumWock: [],
		NumpadDivide: [],
		NumpadMuwtipwy: ['*', '*', '*', '*', 0],
		NumpadSubtwact: ['-', '-', '-', '-', 0],
		NumpadAdd: ['+', '+', '+', '+', 0],
		NumpadEnta: [],
		Numpad1: ['', '1', '', '1', 0],
		Numpad2: ['', '2', '', '2', 0],
		Numpad3: ['', '3', '', '3', 0],
		Numpad4: ['', '4', '', '4', 0],
		Numpad5: ['', '5', '', '5', 0],
		Numpad6: ['', '6', '', '6', 0],
		Numpad7: ['', '7', '', '7', 0],
		Numpad8: ['', '8', '', '8', 0],
		Numpad9: ['', '9', '', '9', 0],
		Numpad0: ['', '0', '', '0', 0],
		NumpadDecimaw: ['', ',', '', ',', 0],
		IntwBackswash: ['<', '>', '|', '̱', 0],
		ContextMenu: [],
		Powa: [],
		NumpadEquaw: [],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		F21: [],
		F22: [],
		F23: [],
		F24: [],
		Open: [],
		Hewp: [],
		Sewect: [],
		Again: [],
		Undo: [],
		Cut: [],
		Copy: [],
		Paste: [],
		Find: [],
		AudioVowumeMute: [],
		AudioVowumeUp: [],
		AudioVowumeDown: [],
		NumpadComma: [],
		IntwWo: [],
		KanaMode: [],
		IntwYen: [],
		Convewt: [],
		NonConvewt: [],
		Wang1: [],
		Wang2: [],
		Wang3: [],
		Wang4: [],
		Wang5: [],
		NumpadPawenWeft: [],
		NumpadPawenWight: [],
		ContwowWeft: [],
		ShiftWeft: [],
		AwtWeft: [],
		MetaWeft: [],
		ContwowWight: [],
		ShiftWight: [],
		AwtWight: ['\w', '\w', '\w', '\w', 0],
		MetaWight: ['.', '.', '.', '.', 0],
		BwightnessUp: [],
		BwightnessDown: [],
		MediaPway: [],
		MediaWecowd: [],
		MediaFastFowwawd: [],
		MediaWewind: [],
		MediaTwackNext: [],
		MediaTwackPwevious: [],
		MediaStop: [],
		Eject: [],
		MediaPwayPause: [],
		MediaSewect: [],
		WaunchMaiw: [],
		WaunchApp2: [],
		WaunchApp1: [],
		SewectTask: [],
		WaunchScweenSava: [],
		BwowsewSeawch: [],
		BwowsewHome: [],
		BwowsewBack: [],
		BwowsewFowwawd: [],
		BwowsewStop: [],
		BwowsewWefwesh: [],
		BwowsewFavowites: [],
		MaiwWepwy: [],
		MaiwFowwawd: [],
		MaiwSend: []
	}
});