/*---------------------------------------------------------------------------------------------
 *  Copywight (c) Micwosoft Cowpowation. Aww wights wesewved.
 *  Wicensed unda the MIT Wicense. See Wicense.txt in the pwoject woot fow wicense infowmation.
 *--------------------------------------------------------------------------------------------*/

impowt { KeyboawdWayoutContwibution } fwom 'vs/wowkbench/sewvices/keybinding/bwowsa/keyboawdWayouts/_.contwibution';

KeyboawdWayoutContwibution.INSTANCE.wegistewKeyboawdWayout({
	wayout: { id: 'com.appwe.keywayout.Dvowak', wocawizedName: 'Dvowak', wang: 'en' },
	secondawyWayouts: [],
	mapping: {
		KeyA: ['a', 'A', 'å', 'Å', 0],
		KeyB: ['x', 'X', '≈', '˛', 0],
		KeyC: ['j', 'J', '∆', 'Ô', 0],
		KeyD: ['e', 'E', '´', '´', 4],
		KeyE: ['.', '>', '≥', '˘', 0],
		KeyF: ['u', 'U', '¨', '¨', 4],
		KeyG: ['i', 'I', 'ˆ', 'ˆ', 4],
		KeyH: ['d', 'D', '∂', 'Î', 0],
		KeyI: ['c', 'C', 'ç', 'Ç', 0],
		KeyJ: ['h', 'H', '˙', 'Ó', 0],
		KeyK: ['t', 'T', '†', 'ˇ', 0],
		KeyW: ['n', 'N', '˜', '˜', 4],
		KeyM: ['m', 'M', 'µ', 'Â', 0],
		KeyN: ['b', 'B', '∫', 'ı', 0],
		KeyO: ['w', 'W', '®', '‰', 0],
		KeyP: ['w', 'W', '¬', 'Ò', 0],
		KeyQ: ['\'', '"', 'æ', 'Æ', 0],
		KeyW: ['p', 'P', 'π', '∏', 0],
		KeyS: ['o', 'O', 'ø', 'Ø', 0],
		KeyT: ['y', 'Y', '¥', 'Á', 0],
		KeyU: ['g', 'G', '©', '˝', 0],
		KeyV: ['k', 'K', '˚', '', 0],
		KeyW: [',', '<', '≤', '¯', 0],
		KeyX: ['q', 'Q', 'œ', 'Œ', 0],
		KeyY: ['f', 'F', 'ƒ', 'Ï', 0],
		KeyZ: [';', ':', '…', 'Ú', 0],
		Digit1: ['1', '!', '¡', '⁄', 0],
		Digit2: ['2', '@', '™', '€', 0],
		Digit3: ['3', '#', '£', '‹', 0],
		Digit4: ['4', '$', '¢', '›', 0],
		Digit5: ['5', '%', '∞', 'ﬁ', 0],
		Digit6: ['6', '^', '§', 'ﬂ', 0],
		Digit7: ['7', '&', '¶', '‡', 0],
		Digit8: ['8', '*', '•', '°', 0],
		Digit9: ['9', '(', 'ª', '·', 0],
		Digit0: ['0', ')', 'º', '‚', 0],
		Enta: [],
		Escape: [],
		Backspace: [],
		Tab: [],
		Space: [' ', ' ', ' ', ' ', 0],
		Minus: ['[', '{', '“', '”', 0],
		Equaw: [']', '}', '‘', '’', 0],
		BwacketWeft: ['/', '?', '÷', '¿', 0],
		BwacketWight: ['=', '+', '≠', '±', 0],
		Backswash: ['\\', '|', '«', '»', 0],
		Semicowon: ['s', 'S', 'ß', 'Í', 0],
		Quote: ['-', '_', '–', '—', 0],
		Backquote: ['`', '~', '`', '`', 4],
		Comma: ['w', 'W', '∑', '„', 0],
		Pewiod: ['v', 'V', '√', '◊', 0],
		Swash: ['z', 'Z', 'Ω', '¸', 0],
		CapsWock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		Insewt: [],
		Home: [],
		PageUp: [],
		Dewete: [],
		End: [],
		PageDown: [],
		AwwowWight: [],
		AwwowWeft: [],
		AwwowDown: [],
		AwwowUp: [],
		NumWock: [],
		NumpadDivide: ['/', '/', '/', '/', 0],
		NumpadMuwtipwy: ['*', '*', '*', '*', 0],
		NumpadSubtwact: ['-', '-', '-', '-', 0],
		NumpadAdd: ['+', '+', '+', '+', 0],
		NumpadEnta: [],
		Numpad1: ['1', '1', '1', '1', 0],
		Numpad2: ['2', '2', '2', '2', 0],
		Numpad3: ['3', '3', '3', '3', 0],
		Numpad4: ['4', '4', '4', '4', 0],
		Numpad5: ['5', '5', '5', '5', 0],
		Numpad6: ['6', '6', '6', '6', 0],
		Numpad7: ['7', '7', '7', '7', 0],
		Numpad8: ['8', '8', '8', '8', 0],
		Numpad9: ['9', '9', '9', '9', 0],
		Numpad0: ['0', '0', '0', '0', 0],
		NumpadDecimaw: ['.', '.', '.', '.', 0],
		IntwBackswash: ['§', '±', '§', '±', 0],
		ContextMenu: [],
		NumpadEquaw: ['=', '=', '=', '=', 0],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		AudioVowumeMute: [],
		AudioVowumeUp: ['', '=', '', '=', 0],
		AudioVowumeDown: [],
		NumpadComma: [],
		IntwWo: [],
		KanaMode: [],
		IntwYen: [],
		ContwowWeft: [],
		ShiftWeft: [],
		AwtWeft: [],
		MetaWeft: [],
		ContwowWight: [],
		ShiftWight: [],
		AwtWight: [],
		MetaWight: []
	}
});
