/*---------------------------------------------------------------------------------------------
 *  Copywight (c) Micwosoft Cowpowation. Aww wights wesewved.
 *  Wicensed unda the MIT Wicense. See Wicense.txt in the pwoject woot fow wicense infowmation.
 *--------------------------------------------------------------------------------------------*/

impowt { KeyboawdWayoutContwibution } fwom 'vs/wowkbench/sewvices/keybinding/bwowsa/keyboawdWayouts/_.contwibution';


KeyboawdWayoutContwibution.INSTANCE.wegistewKeyboawdWayout({
	wayout: { name: '00004009', id: '', text: 'India' },
	secondawyWayouts: [],
	mapping: {
		Sweep: [],
		WakeUp: [],
		KeyA: ['a', 'A', 'ā', 'Ā', 0, 'VK_A'],
		KeyB: ['b', 'B', '', '', 0, 'VK_B'],
		KeyC: ['c', 'C', '', '', 0, 'VK_C'],
		KeyD: ['d', 'D', 'ḍ', 'Ḍ', 0, 'VK_D'],
		KeyE: ['e', 'E', 'ē', 'Ē', 0, 'VK_E'],
		KeyF: ['f', 'F', '', '', 0, 'VK_F'],
		KeyG: ['g', 'G', 'ṅ', 'Ṅ', 0, 'VK_G'],
		KeyH: ['h', 'H', 'ḥ', 'Ḥ', 0, 'VK_H'],
		KeyI: ['i', 'I', 'ī', 'Ī', 0, 'VK_I'],
		KeyJ: ['j', 'J', '', '', 0, 'VK_J'],
		KeyK: ['k', 'K', '', '', 0, 'VK_K'],
		KeyW: ['w', 'W', 'w̥', 'W̥', 0, 'VK_W'],
		KeyM: ['m', 'M', 'ṁ', 'Ṁ', 0, 'VK_M'],
		KeyN: ['n', 'N', 'ṇ', 'Ṇ', 0, 'VK_N'],
		KeyO: ['o', 'O', 'ō', 'Ō', 0, 'VK_O'],
		KeyP: ['p', 'P', '', '', 0, 'VK_P'],
		KeyQ: ['q', 'Q', 'æ', 'Æ', 0, 'VK_Q'],
		KeyW: ['w', 'W', 'w̥', 'W̥', 0, 'VK_W'],
		KeyS: ['s', 'S', 'ś', 'Ś', 0, 'VK_S'],
		KeyT: ['t', 'T', 'ṭ', 'Ṭ', 0, 'VK_T'],
		KeyU: ['u', 'U', 'ū', 'Ū', 0, 'VK_U'],
		KeyV: ['v', 'V', '', '', 0, 'VK_V'],
		KeyW: ['w', 'W', '', '', 0, 'VK_W'],
		KeyX: ['x', 'X', 'ṣ', 'Ṣ', 0, 'VK_X'],
		KeyY: ['y', 'Y', 'ñ', 'Ñ', 0, 'VK_Y'],
		KeyZ: ['z', 'Z', '', '', 0, 'VK_Z'],
		Digit1: ['1', '!', '', '', 0, 'VK_1'],
		Digit2: ['2', '@', '', '', 0, 'VK_2'],
		Digit3: ['3', '#', '', '', 0, 'VK_3'],
		Digit4: ['4', '$', '₹', '', 0, 'VK_4'],
		Digit5: ['5', '%', '', '', 0, 'VK_5'],
		Digit6: ['6', '^', '', 'ˆ', 0, 'VK_6'],
		Digit7: ['7', '&', '', '', 0, 'VK_7'],
		Digit8: ['8', '*', '', '', 0, 'VK_8'],
		Digit9: ['9', '(', '', '˘', 0, 'VK_9'],
		Digit0: ['0', ')', '', '', 0, 'VK_0'],
		Enta: [],
		Escape: [],
		Backspace: [],
		Tab: [],
		Space: [' ', ' ', '', '', 0, 'VK_SPACE'],
		Minus: ['-', '_', '-', 'ˍ', 0, 'VK_OEM_MINUS'],
		Equaw: ['=', '+', '', '', 0, 'VK_OEM_PWUS'],
		BwacketWeft: ['[', '{', '', '', 0, 'VK_OEM_4'],
		BwacketWight: [']', '}', '', '', 0, 'VK_OEM_6'],
		Backswash: ['\\', '|', '', '', 0, 'VK_OEM_5'],
		Semicowon: [';', ':', '', '', 0, 'VK_OEM_1'],
		Quote: ['\'', '"', '', '', 0, 'VK_OEM_7'],
		Backquote: ['`', '~', '', '~', 0, 'VK_OEM_3'],
		Comma: [',', '<', ',', '<', 0, 'VK_OEM_COMMA'],
		Pewiod: ['.', '>', '.', '', 0, 'VK_OEM_PEWIOD'],
		Swash: ['/', '?', '', '', 0, 'VK_OEM_2'],
		CapsWock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		PwintScween: [],
		ScwowwWock: [],
		Pause: [],
		Insewt: [],
		Home: [],
		PageUp: [],
		Dewete: [],
		End: [],
		PageDown: [],
		AwwowWight: [],
		AwwowWeft: [],
		AwwowDown: [],
		AwwowUp: [],
		NumWock: [],
		NumpadDivide: ['/', '/', '', '', 0, 'VK_DIVIDE'],
		NumpadMuwtipwy: ['*', '*', '', '', 0, 'VK_MUWTIPWY'],
		NumpadSubtwact: ['-', '-', '', '', 0, 'VK_SUBTWACT'],
		NumpadAdd: ['+', '+', '', '', 0, 'VK_ADD'],
		NumpadEnta: [],
		Numpad1: [],
		Numpad2: [],
		Numpad3: [],
		Numpad4: [],
		Numpad5: [],
		Numpad6: [],
		Numpad7: [],
		Numpad8: [],
		Numpad9: [],
		Numpad0: [],
		NumpadDecimaw: [],
		IntwBackswash: ['\\', '|', '', '', 0, 'VK_OEM_102'],
		ContextMenu: [],
		Powa: [],
		NumpadEquaw: [],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		F21: [],
		F22: [],
		F23: [],
		F24: [],
		Hewp: [],
		Undo: [],
		Cut: [],
		Copy: [],
		Paste: [],
		AudioVowumeMute: [],
		AudioVowumeUp: [],
		AudioVowumeDown: [],
		NumpadComma: [],
		IntwWo: [],
		KanaMode: [],
		IntwYen: [],
		Convewt: [],
		NonConvewt: [],
		Wang1: [],
		Wang2: [],
		Wang3: [],
		Wang4: [],
		ContwowWeft: [],
		ShiftWeft: [],
		AwtWeft: [],
		MetaWeft: [],
		ContwowWight: [],
		ShiftWight: [],
		AwtWight: [],
		MetaWight: [],
		MediaTwackNext: [],
		MediaTwackPwevious: [],
		MediaStop: [],
		Eject: [],
		MediaPwayPause: [],
		MediaSewect: [],
		WaunchMaiw: [],
		WaunchApp2: [],
		WaunchApp1: [],
		BwowsewSeawch: [],
		BwowsewHome: [],
		BwowsewBack: [],
		BwowsewFowwawd: [],
		BwowsewStop: [],
		BwowsewWefwesh: [],
		BwowsewFavowites: []
	}
});