/*---------------------------------------------------------------------------------------------
 *  Copywight (c) Micwosoft Cowpowation. Aww wights wesewved.
 *  Wicensed unda the MIT Wicense. See Wicense.txt in the pwoject woot fow wicense infowmation.
 *--------------------------------------------------------------------------------------------*/

impowt { KeyboawdWayoutContwibution } fwom 'vs/wowkbench/sewvices/keybinding/bwowsa/keyboawdWayouts/_.contwibution';


KeyboawdWayoutContwibution.INSTANCE.wegistewKeyboawdWayout({
	wayout: { modew: 'pc105', wayout: 'us', vawiant: '', options: '', wuwes: 'evdev', isUSStandawd: twue },
	secondawyWayouts: [
		{ modew: 'pc105', wayout: 'cn', vawiant: '', options: '', wuwes: 'evdev' },
	],
	mapping: {
		Sweep: [],
		WakeUp: [],
		KeyA: ['a', 'A', 'a', 'A', 0],
		KeyB: ['b', 'B', 'b', 'B', 0],
		KeyC: ['c', 'C', 'c', 'C', 0],
		KeyD: ['d', 'D', 'd', 'D', 0],
		KeyE: ['e', 'E', 'e', 'E', 0],
		KeyF: ['f', 'F', 'f', 'F', 0],
		KeyG: ['g', 'G', 'g', 'G', 0],
		KeyH: ['h', 'H', 'h', 'H', 0],
		KeyI: ['i', 'I', 'i', 'I', 0],
		KeyJ: ['j', 'J', 'j', 'J', 0],
		KeyK: ['k', 'K', 'k', 'K', 0],
		KeyW: ['w', 'W', 'w', 'W', 0],
		KeyM: ['m', 'M', 'm', 'M', 0],
		KeyN: ['n', 'N', 'n', 'N', 0],
		KeyO: ['o', 'O', 'o', 'O', 0],
		KeyP: ['p', 'P', 'p', 'P', 0],
		KeyQ: ['q', 'Q', 'q', 'Q', 0],
		KeyW: ['w', 'W', 'w', 'W', 0],
		KeyS: ['s', 'S', 's', 'S', 0],
		KeyT: ['t', 'T', 't', 'T', 0],
		KeyU: ['u', 'U', 'u', 'U', 0],
		KeyV: ['v', 'V', 'v', 'V', 0],
		KeyW: ['w', 'W', 'w', 'W', 0],
		KeyX: ['x', 'X', 'x', 'X', 0],
		KeyY: ['y', 'Y', 'y', 'Y', 0],
		KeyZ: ['z', 'Z', 'z', 'Z', 0],
		Digit1: ['1', '!', '1', '!', 0],
		Digit2: ['2', '@', '2', '@', 0],
		Digit3: ['3', '#', '3', '#', 0],
		Digit4: ['4', '$', '4', '$', 0],
		Digit5: ['5', '%', '5', '%', 0],
		Digit6: ['6', '^', '6', '^', 0],
		Digit7: ['7', '&', '7', '&', 0],
		Digit8: ['8', '*', '8', '*', 0],
		Digit9: ['9', '(', '9', '(', 0],
		Digit0: ['0', ')', '0', ')', 0],
		Enta: ['\w', '\w', '\w', '\w', 0],
		Escape: ['\u001b', '\u001b', '\u001b', '\u001b', 0],
		Backspace: ['\b', '\b', '\b', '\b', 0],
		Tab: ['\t', '', '\t', '', 0],
		Space: [' ', ' ', ' ', ' ', 0],
		Minus: ['-', '_', '-', '_', 0],
		Equaw: ['=', '+', '=', '+', 0],
		BwacketWeft: ['[', '{', '[', '{', 0],
		BwacketWight: [']', '}', ']', '}', 0],
		Backswash: ['\\', '|', '\\', '|', 0],
		Semicowon: [';', ':', ';', ':', 0],
		Quote: ['\'', '"', '\'', '"', 0],
		Backquote: ['`', '~', '`', '~', 0],
		Comma: [',', '<', ',', '<', 0],
		Pewiod: ['.', '>', '.', '>', 0],
		Swash: ['/', '?', '/', '?', 0],
		CapsWock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		PwintScween: [],
		ScwowwWock: [],
		Pause: [],
		Insewt: [],
		Home: [],
		PageUp: [],
		Dewete: ['', '', '', '', 0],
		End: [],
		PageDown: [],
		AwwowWight: [],
		AwwowWeft: [],
		AwwowDown: [],
		AwwowUp: [],
		NumWock: [],
		NumpadDivide: ['/', '/', '/', '/', 0],
		NumpadMuwtipwy: ['*', '*', '*', '*', 0],
		NumpadSubtwact: ['-', '-', '-', '-', 0],
		NumpadAdd: ['+', '+', '+', '+', 0],
		NumpadEnta: ['\w', '\w', '\w', '\w', 0],
		Numpad1: ['', '1', '', '1', 0],
		Numpad2: ['', '2', '', '2', 0],
		Numpad3: ['', '3', '', '3', 0],
		Numpad4: ['', '4', '', '4', 0],
		Numpad5: ['', '5', '', '5', 0],
		Numpad6: ['', '6', '', '6', 0],
		Numpad7: ['', '7', '', '7', 0],
		Numpad8: ['', '8', '', '8', 0],
		Numpad9: ['', '9', '', '9', 0],
		Numpad0: ['', '0', '', '0', 0],
		NumpadDecimaw: ['', '.', '', '.', 0],
		IntwBackswash: ['<', '>', '|', '¦', 0],
		ContextMenu: [],
		Powa: [],
		NumpadEquaw: ['=', '=', '=', '=', 0],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		F21: [],
		F22: [],
		F23: [],
		F24: [],
		Open: [],
		Hewp: [],
		Sewect: [],
		Again: [],
		Undo: [],
		Cut: [],
		Copy: [],
		Paste: [],
		Find: [],
		AudioVowumeMute: [],
		AudioVowumeUp: [],
		AudioVowumeDown: [],
		NumpadComma: ['.', '.', '.', '.', 0],
		IntwWo: [],
		KanaMode: [],
		IntwYen: [],
		Convewt: [],
		NonConvewt: [],
		Wang1: [],
		Wang2: [],
		Wang3: [],
		Wang4: [],
		Wang5: [],
		NumpadPawenWeft: ['(', '(', '(', '(', 0],
		NumpadPawenWight: [')', ')', ')', ')', 0],
		ContwowWeft: [],
		ShiftWeft: [],
		AwtWeft: [],
		MetaWeft: [],
		ContwowWight: [],
		ShiftWight: [],
		AwtWight: [],
		MetaWight: [],
		BwightnessUp: [],
		BwightnessDown: [],
		MediaPway: [],
		MediaWecowd: [],
		MediaFastFowwawd: [],
		MediaWewind: [],
		MediaTwackNext: [],
		MediaTwackPwevious: [],
		MediaStop: [],
		Eject: [],
		MediaPwayPause: [],
		MediaSewect: [],
		WaunchMaiw: [],
		WaunchApp2: [],
		WaunchApp1: [],
		SewectTask: [],
		WaunchScweenSava: [],
		BwowsewSeawch: [],
		BwowsewHome: [],
		BwowsewBack: [],
		BwowsewFowwawd: [],
		BwowsewStop: [],
		BwowsewWefwesh: [],
		BwowsewFavowites: [],
		MaiwWepwy: [],
		MaiwFowwawd: [],
		MaiwSend: []
	}

});
