/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { KeyboardLayoutProvider, KeyboardLayoutInfo } from 'vs/workbench/services/keybinding/browser/keyboardLayoutProvider';

KeyboardLayoutProvider.INSTANCE.registerKeyboardLayout((new KeyboardLayoutInfo(
	{ name: '0000040E', id: '', text: 'Hungarian' },
	[],
	{
		Sleep: [],
		WakeUp: [],
		KeyA: ['a', 'A', 'ä', '', 0],
		KeyB: ['b', 'B', '{', '', 0],
		KeyC: ['c', 'C', '&', '', 0],
		KeyD: ['d', 'D', 'Đ', '', 0],
		KeyE: ['e', 'E', 'Ä', '', 0],
		KeyF: ['f', 'F', '[', '', 0],
		KeyG: ['g', 'G', ']', '', 0],
		KeyH: ['h', 'H', '', '', 0],
		KeyI: ['i', 'I', 'Í', '', 0],
		KeyJ: ['j', 'J', 'í', '', 0],
		KeyK: ['k', 'K', 'ł', '', 0],
		KeyL: ['l', 'L', 'Ł', '', 0],
		KeyM: ['m', 'M', '<', '', 0],
		KeyN: ['n', 'N', '}', '', 0],
		KeyO: ['o', 'O', '', '', 0],
		KeyP: ['p', 'P', '', '', 0],
		KeyQ: ['q', 'Q', '\\', '', 0],
		KeyR: ['r', 'R', '', '', 0],
		KeyS: ['s', 'S', 'đ', '', 0],
		KeyT: ['t', 'T', '', '', 0],
		KeyU: ['u', 'U', '€', '', 0],
		KeyV: ['v', 'V', '@', '', 0],
		KeyW: ['w', 'W', '|', '', 0],
		KeyX: ['x', 'X', '#', '', 0],
		KeyY: ['z', 'Z', '', '', 0],
		KeyZ: ['y', 'Y', '>', '', 0],
		Digit1: ['1', '\'', '~', '', 0],
		Digit2: ['2', '"', 'ˇ', '', 0],
		Digit3: ['3', '+', '^', '', 0],
		Digit4: ['4', '!', '˘', '', 0],
		Digit5: ['5', '%', '°', '', 0],
		Digit6: ['6', '/', '˛', '', 0],
		Digit7: ['7', '=', '`', '', 0],
		Digit8: ['8', '(', '˙', '', 0],
		Digit9: ['9', ')', '´', '', 0],
		Digit0: ['ö', 'Ö', '˝', '', 0],
		Enter: [],
		Escape: [],
		Backspace: [],
		Tab: [],
		Space: [' ', ' ', '', '', 0],
		Minus: ['ü', 'Ü', '¨', '', 0],
		Equal: ['ó', 'Ó', '¸', '', 0],
		BracketLeft: ['ő', 'Ő', '÷', '', 0],
		BracketRight: ['ú', 'Ú', '×', '', 0],
		Backslash: ['ű', 'Ű', '¤', '', 0],
		Semicolon: ['é', 'É', '$', '', 0],
		Quote: ['á', 'Á', 'ß', '', 0],
		Backquote: ['0', '§', '', '', 0],
		Comma: [',', '?', ';', '', 0],
		Period: ['.', ':', '>', '', 0],
		Slash: ['-', '_', '*', '', 0],
		CapsLock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		PrintScreen: [],
		ScrollLock: [],
		Pause: [],
		Insert: [],
		Home: [],
		PageUp: [],
		Delete: [],
		End: [],
		PageDown: [],
		ArrowRight: [],
		ArrowLeft: [],
		ArrowDown: [],
		ArrowUp: [],
		NumLock: [],
		NumpadDivide: ['/', '/', '', '', 0],
		NumpadMultiply: ['*', '*', '', '', 0],
		NumpadSubtract: ['-', '-', '', '', 0],
		NumpadAdd: ['+', '+', '', '', 0],
		NumpadEnter: [],
		Numpad1: [],
		Numpad2: [],
		Numpad3: [],
		Numpad4: [],
		Numpad5: [],
		Numpad6: [],
		Numpad7: [],
		Numpad8: [],
		Numpad9: [],
		Numpad0: [],
		NumpadDecimal: [],
		IntlBackslash: ['í', 'Í', '<', '', 0],
		ContextMenu: [],
		Power: [],
		NumpadEqual: [],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		F21: [],
		F22: [],
		F23: [],
		F24: [],
		Help: [],
		Undo: [],
		Cut: [],
		Copy: [],
		Paste: [],
		AudioVolumeMute: [],
		AudioVolumeUp: [],
		AudioVolumeDown: [],
		NumpadComma: [],
		IntlRo: [],
		KanaMode: [],
		IntlYen: [],
		Convert: [],
		NonConvert: [],
		Lang1: [],
		Lang2: [],
		Lang3: [],
		Lang4: [],
		ControlLeft: [],
		ShiftLeft: [],
		AltLeft: [],
		MetaLeft: [],
		ControlRight: [],
		ShiftRight: [],
		AltRight: [],
		MetaRight: [],
		MediaTrackNext: [],
		MediaTrackPrevious: [],
		MediaStop: [],
		Eject: [],
		MediaPlayPause: [],
		MediaSelect: [],
		LaunchMail: [],
		LaunchApp2: [],
		LaunchApp1: [],
		BrowserSearch: [],
		BrowserHome: [],
		BrowserBack: [],
		BrowserForward: [],
		BrowserStop: [],
		BrowserRefresh: [],
		BrowserFavorites: []
	}
)));
