/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { KeyboardLayoutProvider, KeyboardLayoutInfo } from 'vs/workbench/services/keybinding/browser/keyboardLayoutProvider';

KeyboardLayoutProvider.INSTANCE.registerKeyboardLayout((new KeyboardLayoutInfo(
	{ name: '00000419', id: '', text: 'Russian' },
	[],
	{
		Sleep: [],
		WakeUp: [],
		KeyA: ['ф', 'Ф', '', '', 0],
		KeyB: ['и', 'И', '', '', 0],
		KeyC: ['с', 'С', '', '', 0],
		KeyD: ['в', 'В', '', '', 0],
		KeyE: ['у', 'У', '', '', 0],
		KeyF: ['а', 'А', '', '', 0],
		KeyG: ['п', 'П', '', '', 0],
		KeyH: ['р', 'Р', '', '', 0],
		KeyI: ['ш', 'Ш', '', '', 0],
		KeyJ: ['о', 'О', '', '', 0],
		KeyK: ['л', 'Л', '', '', 0],
		KeyL: ['д', 'Д', '', '', 0],
		KeyM: ['ь', 'Ь', '', '', 0],
		KeyN: ['т', 'Т', '', '', 0],
		KeyO: ['щ', 'Щ', '', '', 0],
		KeyP: ['з', 'З', '', '', 0],
		KeyQ: ['й', 'Й', '', '', 0],
		KeyR: ['к', 'К', '', '', 0],
		KeyS: ['ы', 'Ы', '', '', 0],
		KeyT: ['е', 'Е', '', '', 0],
		KeyU: ['г', 'Г', '', '', 0],
		KeyV: ['м', 'М', '', '', 0],
		KeyW: ['ц', 'Ц', '', '', 0],
		KeyX: ['ч', 'Ч', '', '', 0],
		KeyY: ['н', 'Н', '', '', 0],
		KeyZ: ['я', 'Я', '', '', 0],
		Digit1: ['1', '!', '', '', 0],
		Digit2: ['2', '"', '', '', 0],
		Digit3: ['3', '№', '', '', 0],
		Digit4: ['4', ';', '', '', 0],
		Digit5: ['5', '%', '', '', 0],
		Digit6: ['6', ':', '', '', 0],
		Digit7: ['7', '?', '', '', 0],
		Digit8: ['8', '*', '₽', '', 0],
		Digit9: ['9', '(', '', '', 0],
		Digit0: ['0', ')', '', '', 0],
		Enter: [],
		Escape: [],
		Backspace: [],
		Tab: [],
		Space: [' ', ' ', '', '', 0],
		Minus: ['-', '_', '', '', 0],
		Equal: ['=', '+', '', '', 0],
		BracketLeft: ['х', 'Х', '', '', 0],
		BracketRight: ['ъ', 'Ъ', '', '', 0],
		Backslash: ['\\', '/', '', '', 0],
		Semicolon: ['ж', 'Ж', '', '', 0],
		Quote: ['э', 'Э', '', '', 0],
		Backquote: ['ё', 'Ё', '', '', 0],
		Comma: ['б', 'Б', '', '', 0],
		Period: ['ю', 'Ю', '', '', 0],
		Slash: ['.', ',', '', '', 0],
		CapsLock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		PrintScreen: [],
		ScrollLock: [],
		Pause: [],
		Insert: [],
		Home: [],
		PageUp: [],
		Delete: [],
		End: [],
		PageDown: [],
		ArrowRight: [],
		ArrowLeft: [],
		ArrowDown: [],
		ArrowUp: [],
		NumLock: [],
		NumpadDivide: ['/', '/', '', '', 0],
		NumpadMultiply: ['*', '*', '', '', 0],
		NumpadSubtract: ['-', '-', '', '', 0],
		NumpadAdd: ['+', '+', '', '', 0],
		NumpadEnter: [],
		Numpad1: [],
		Numpad2: [],
		Numpad3: [],
		Numpad4: [],
		Numpad5: [],
		Numpad6: [],
		Numpad7: [],
		Numpad8: [],
		Numpad9: [],
		Numpad0: [],
		NumpadDecimal: [],
		IntlBackslash: ['\\', '/', '', '', 0],
		ContextMenu: [],
		Power: [],
		NumpadEqual: [],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		F21: [],
		F22: [],
		F23: [],
		F24: [],
		Help: [],
		Undo: [],
		Cut: [],
		Copy: [],
		Paste: [],
		AudioVolumeMute: [],
		AudioVolumeUp: [],
		AudioVolumeDown: [],
		NumpadComma: [],
		IntlRo: [],
		KanaMode: [],
		IntlYen: [],
		Convert: [],
		NonConvert: [],
		Lang1: [],
		Lang2: [],
		Lang3: [],
		Lang4: [],
		ControlLeft: [],
		ShiftLeft: [],
		AltLeft: [],
		MetaLeft: [],
		ControlRight: [],
		ShiftRight: [],
		AltRight: [],
		MetaRight: [],
		MediaTrackNext: [],
		MediaTrackPrevious: [],
		MediaStop: [],
		Eject: [],
		MediaPlayPause: [],
		MediaSelect: [],
		LaunchMail: [],
		LaunchApp2: [],
		LaunchApp1: [],
		BrowserSearch: [],
		BrowserHome: [],
		BrowserBack: [],
		BrowserForward: [],
		BrowserStop: [],
		BrowserRefresh: [],
		BrowserFavorites: []
	}
)));