/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { KeyboardLayoutProvider, KeyboardLayoutInfo } from 'vs/workbench/services/keybinding/browser/keyboardLayoutProvider';

KeyboardLayoutProvider.INSTANCE.registerKeyboardLayout((new KeyboardLayoutInfo(
	{ name: '0000041E', id: '', text: 'Thai Kedmanee' },
	[],
	{
		Sleep: [],
		WakeUp: [],
		KeyA: ['ฟ', 'ฤ', '', '', 0],
		KeyB: ['ิ', 'ฺ', '', '', 0],
		KeyC: ['แ', 'ฉ', '', '', 0],
		KeyD: ['ก', 'ฏ', '', '', 0],
		KeyE: ['ำ', 'ฎ', '', '', 0],
		KeyF: ['ด', 'โ', '', '', 0],
		KeyG: ['เ', 'ฌ', '', '', 0],
		KeyH: ['้', '็', '', '', 0],
		KeyI: ['ร', 'ณ', '', '', 0],
		KeyJ: ['่', '๋', '', '', 0],
		KeyK: ['า', 'ษ', '', '', 0],
		KeyL: ['ส', 'ศ', '', '', 0],
		KeyM: ['ท', '?', '', '', 0],
		KeyN: ['ื', '์', '', '', 0],
		KeyO: ['น', 'ฯ', '', '', 0],
		KeyP: ['ย', 'ญ', '', '', 0],
		KeyQ: ['ๆ', '๐', '', '', 0],
		KeyR: ['พ', 'ฑ', '', '', 0],
		KeyS: ['ห', 'ฆ', '', '', 0],
		KeyT: ['ะ', 'ธ', '', '', 0],
		KeyU: ['ี', '๊', '', '', 0],
		KeyV: ['อ', 'ฮ', '', '', 0],
		KeyW: ['ไ', '"', '', '', 0],
		KeyX: ['ป', ')', '', '', 0],
		KeyY: ['ั', 'ํ', '', '', 0],
		KeyZ: ['ผ', '(', '', '', 0],
		Digit1: ['ๅ', '+', '', '', 0],
		Digit2: ['/', '๑', '', '', 0],
		Digit3: ['-', '๒', '', '', 0],
		Digit4: ['ภ', '๓', '', '', 0],
		Digit5: ['ถ', '๔', '', '', 0],
		Digit6: ['ุ', 'ู', '', '', 0],
		Digit7: ['ึ', '฿', '', '', 0],
		Digit8: ['ค', '๕', '', '', 0],
		Digit9: ['ต', '๖', '', '', 0],
		Digit0: ['จ', '๗', '', '', 0],
		Enter: [],
		Escape: [],
		Backspace: [],
		Tab: [],
		Space: [' ', ' ', '', '', 0],
		Minus: ['ข', '๘', '', '', 0],
		Equal: ['ช', '๙', '', '', 0],
		BracketLeft: ['บ', 'ฐ', '', '', 0],
		BracketRight: ['ล', ',', '', '', 0],
		Backslash: ['ฃ', 'ฅ', '', '', 0],
		Semicolon: ['ว', 'ซ', '', '', 0],
		Quote: ['ง', '.', '', '', 0],
		Backquote: ['_', '%', '', '', 0],
		Comma: ['ม', 'ฒ', '', '', 0],
		Period: ['ใ', 'ฬ', '', '', 0],
		Slash: ['ฝ', 'ฦ', '', '', 0],
		CapsLock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		PrintScreen: [],
		ScrollLock: [],
		Pause: [],
		Insert: [],
		Home: [],
		PageUp: [],
		Delete: [],
		End: [],
		PageDown: [],
		ArrowRight: [],
		ArrowLeft: [],
		ArrowDown: [],
		ArrowUp: [],
		NumLock: [],
		NumpadDivide: ['/', '/', '', '', 0],
		NumpadMultiply: ['*', '*', '', '', 0],
		NumpadSubtract: ['-', '-', '', '', 0],
		NumpadAdd: ['+', '+', '', '', 0],
		NumpadEnter: [],
		Numpad1: [],
		Numpad2: [],
		Numpad3: [],
		Numpad4: [],
		Numpad5: [],
		Numpad6: [],
		Numpad7: [],
		Numpad8: [],
		Numpad9: [],
		Numpad0: [],
		NumpadDecimal: [],
		IntlBackslash: ['ฃ', 'ฅ', '', '', 0],
		ContextMenu: [],
		Power: [],
		NumpadEqual: [],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		F21: [],
		F22: [],
		F23: [],
		F24: [],
		Help: [],
		Undo: [],
		Cut: [],
		Copy: [],
		Paste: [],
		AudioVolumeMute: [],
		AudioVolumeUp: [],
		AudioVolumeDown: [],
		NumpadComma: [],
		IntlRo: [],
		KanaMode: [],
		IntlYen: [],
		Convert: [],
		NonConvert: [],
		Lang1: [],
		Lang2: [],
		Lang3: [],
		Lang4: [],
		ControlLeft: [],
		ShiftLeft: [],
		AltLeft: [],
		MetaLeft: [],
		ControlRight: [],
		ShiftRight: [],
		AltRight: [],
		MetaRight: [],
		MediaTrackNext: [],
		MediaTrackPrevious: [],
		MediaStop: [],
		Eject: [],
		MediaPlayPause: [],
		MediaSelect: [],
		LaunchMail: [],
		LaunchApp2: [],
		LaunchApp1: [],
		BrowserSearch: [],
		BrowserHome: [],
		BrowserBack: [],
		BrowserForward: [],
		BrowserStop: [],
		BrowserRefresh: [],
		BrowserFavorites: []
	}
)));
