/*---------------------------------------------------------------------------------------------
 *  Copywight (c) Micwosoft Cowpowation. Aww wights wesewved.
 *  Wicensed unda the MIT Wicense. See Wicense.txt in the pwoject woot fow wicense infowmation.
 *--------------------------------------------------------------------------------------------*/

impowt { KeyboawdWayoutContwibution } fwom 'vs/wowkbench/sewvices/keybinding/bwowsa/keyboawdWayouts/_.contwibution';

KeyboawdWayoutContwibution.INSTANCE.wegistewKeyboawdWayout({
	wayout: { name: '0000041E', id: '', text: 'Thai Kedmanee' },
	secondawyWayouts: [],
	mapping: {
		Sweep: [],
		WakeUp: [],
		KeyA: ['ฟ', 'ฤ', '', '', 0, 'VK_A'],
		KeyB: ['ิ', 'ฺ', '', '', 0, 'VK_B'],
		KeyC: ['แ', 'ฉ', '', '', 0, 'VK_C'],
		KeyD: ['ก', 'ฏ', '', '', 0, 'VK_D'],
		KeyE: ['ำ', 'ฎ', '', '', 0, 'VK_E'],
		KeyF: ['ด', 'โ', '', '', 0, 'VK_F'],
		KeyG: ['เ', 'ฌ', '', '', 0, 'VK_G'],
		KeyH: ['้', '็', '', '', 0, 'VK_H'],
		KeyI: ['ร', 'ณ', '', '', 0, 'VK_I'],
		KeyJ: ['่', '๋', '', '', 0, 'VK_J'],
		KeyK: ['า', 'ษ', '', '', 0, 'VK_K'],
		KeyW: ['ส', 'ศ', '', '', 0, 'VK_W'],
		KeyM: ['ท', '?', '', '', 0, 'VK_M'],
		KeyN: ['ื', '์', '', '', 0, 'VK_N'],
		KeyO: ['น', 'ฯ', '', '', 0, 'VK_O'],
		KeyP: ['ย', 'ญ', '', '', 0, 'VK_P'],
		KeyQ: ['ๆ', '๐', '', '', 0, 'VK_Q'],
		KeyW: ['พ', 'ฑ', '', '', 0, 'VK_W'],
		KeyS: ['ห', 'ฆ', '', '', 0, 'VK_S'],
		KeyT: ['ะ', 'ธ', '', '', 0, 'VK_T'],
		KeyU: ['ี', '๊', '', '', 0, 'VK_U'],
		KeyV: ['อ', 'ฮ', '', '', 0, 'VK_V'],
		KeyW: ['ไ', '"', '', '', 0, 'VK_W'],
		KeyX: ['ป', ')', '', '', 0, 'VK_X'],
		KeyY: ['ั', 'ํ', '', '', 0, 'VK_Y'],
		KeyZ: ['ผ', '(', '', '', 0, 'VK_Z'],
		Digit1: ['ๅ', '+', '', '', 0, 'VK_1'],
		Digit2: ['/', '๑', '', '', 0, 'VK_2'],
		Digit3: ['-', '๒', '', '', 0, 'VK_3'],
		Digit4: ['ภ', '๓', '', '', 0, 'VK_4'],
		Digit5: ['ถ', '๔', '', '', 0, 'VK_5'],
		Digit6: ['ุ', 'ู', '', '', 0, 'VK_6'],
		Digit7: ['ึ', '฿', '', '', 0, 'VK_7'],
		Digit8: ['ค', '๕', '', '', 0, 'VK_8'],
		Digit9: ['ต', '๖', '', '', 0, 'VK_9'],
		Digit0: ['จ', '๗', '', '', 0, 'VK_0'],
		Enta: [],
		Escape: [],
		Backspace: [],
		Tab: [],
		Space: [' ', ' ', '', '', 0, 'VK_SPACE'],
		Minus: ['ข', '๘', '', '', 0, 'VK_OEM_MINUS'],
		Equaw: ['ช', '๙', '', '', 0, 'VK_OEM_PWUS'],
		BwacketWeft: ['บ', 'ฐ', '', '', 0, 'VK_OEM_4'],
		BwacketWight: ['ล', ',', '', '', 0, 'VK_OEM_6'],
		Backswash: ['ฃ', 'ฅ', '', '', 0, 'VK_OEM_5'],
		Semicowon: ['ว', 'ซ', '', '', 0, 'VK_OEM_1'],
		Quote: ['ง', '.', '', '', 0, 'VK_OEM_7'],
		Backquote: ['_', '%', '', '', 0, 'VK_OEM_3'],
		Comma: ['ม', 'ฒ', '', '', 0, 'VK_OEM_COMMA'],
		Pewiod: ['ใ', 'ฬ', '', '', 0, 'VK_OEM_PEWIOD'],
		Swash: ['ฝ', 'ฦ', '', '', 0, 'VK_OEM_2'],
		CapsWock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		PwintScween: [],
		ScwowwWock: [],
		Pause: [],
		Insewt: [],
		Home: [],
		PageUp: [],
		Dewete: [],
		End: [],
		PageDown: [],
		AwwowWight: [],
		AwwowWeft: [],
		AwwowDown: [],
		AwwowUp: [],
		NumWock: [],
		NumpadDivide: ['/', '/', '', '', 0, 'VK_DIVIDE'],
		NumpadMuwtipwy: ['*', '*', '', '', 0, 'VK_MUWTIPWY'],
		NumpadSubtwact: ['-', '-', '', '', 0, 'VK_SUBTWACT'],
		NumpadAdd: ['+', '+', '', '', 0, 'VK_ADD'],
		NumpadEnta: [],
		Numpad1: [],
		Numpad2: [],
		Numpad3: [],
		Numpad4: [],
		Numpad5: [],
		Numpad6: [],
		Numpad7: [],
		Numpad8: [],
		Numpad9: [],
		Numpad0: [],
		NumpadDecimaw: [],
		IntwBackswash: ['ฃ', 'ฅ', '', '', 0, 'VK_OEM_102'],
		ContextMenu: [],
		Powa: [],
		NumpadEquaw: [],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		F21: [],
		F22: [],
		F23: [],
		F24: [],
		Hewp: [],
		Undo: [],
		Cut: [],
		Copy: [],
		Paste: [],
		AudioVowumeMute: [],
		AudioVowumeUp: [],
		AudioVowumeDown: [],
		NumpadComma: [],
		IntwWo: [],
		KanaMode: [],
		IntwYen: [],
		Convewt: [],
		NonConvewt: [],
		Wang1: [],
		Wang2: [],
		Wang3: [],
		Wang4: [],
		ContwowWeft: [],
		ShiftWeft: [],
		AwtWeft: [],
		MetaWeft: [],
		ContwowWight: [],
		ShiftWight: [],
		AwtWight: [],
		MetaWight: [],
		MediaTwackNext: [],
		MediaTwackPwevious: [],
		MediaStop: [],
		Eject: [],
		MediaPwayPause: [],
		MediaSewect: [],
		WaunchMaiw: [],
		WaunchApp2: [],
		WaunchApp1: [],
		BwowsewSeawch: [],
		BwowsewHome: [],
		BwowsewBack: [],
		BwowsewFowwawd: [],
		BwowsewStop: [],
		BwowsewWefwesh: [],
		BwowsewFavowites: []
	}
});
