/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// Remember to include this file in vscode/src/vs/platform/theme/common/sizeRegistry.ts

import * as nls from '../../../../nls.js';
import { registerSize } from '../sizeUtils.js';

export const actionbarActionlabelCornerRadius = registerSize('actionbar.actionlabel.corner.radius', { default: '5px' }, nls.localize('actionbarActionlabelCornerRadius', "Corner Radius"));
export const actionbarActionlabelHeight = registerSize('actionbar.actionlabel.height', { default: '16px' }, nls.localize('actionbarActionlabelHeight', "Height"));
export const actionbarActionlabelHorizontalSpacing = registerSize('actionbar.actionlabel.horizontal.spacing', { default: '5px' }, nls.localize('actionbarActionlabelHorizontalSpacing', "Horizontal Spacing"));
export const actionbarSelectcontainerMaxWidth = registerSize('actionbar.selectcontainer.max.width', { default: '170px' }, nls.localize('actionbarSelectcontainerMaxWidth', "Max Width"));
export const actionbarSelectcontainerMinWidth = registerSize('actionbar.selectcontainer.min.width', { default: '60px' }, nls.localize('actionbarSelectcontainerMinWidth', "Min Width"));
export const badgeCornerRadius = registerSize('badge.corner.radius', { default: '2px' }, nls.localize('badgeCornerRadius', "Corner Radius"));
export const badgeHorizontalSpacing = registerSize('badge.horizontal.spacing', { default: '6px' }, nls.localize('badgeHorizontalSpacing', "Horizontal Spacing"));
export const badgeLongHorizontalSpacing = registerSize('badge.long.horizontal.spacing', { default: '3px' }, nls.localize('badgeLongHorizontalSpacing', "Horizontal Spacing"));
export const badgeLongVerticalSpacing = registerSize('badge.long.vertical.spacing', { default: '2px' }, nls.localize('badgeLongVerticalSpacing', "Vertical Spacing"));
export const badgeMinHeight = registerSize('badge.min.height', { default: '18px' }, nls.localize('badgeMinHeight', "Min Height"));
export const badgeMinWidth = registerSize('badge.min.width', { default: '18px' }, nls.localize('badgeMinWidth', "Min Width"));
export const badgeVerticalSpacing = registerSize('badge.vertical.spacing', { default: '3px' }, nls.localize('badgeVerticalSpacing', "Vertical Spacing"));
export const baseDefaultControlSize = registerSize('base.default.control.size', { default: '22px' }, nls.localize('baseDefaultControlSize', "Control Height"));
export const buttonCornerRadius = registerSize('button.corner.radius', { default: '2px' }, nls.localize('buttonCornerRadius', "Corner Radius"));
export const buttonFocusOutlineOffset = registerSize('button.focus.outline.offset', { default: '4px' }, nls.localize('buttonFocusOutlineOffset', "Focus Outline Offset"));
export const buttonGap = registerSize('button.gap', { default: '4px' }, nls.localize('buttonGap', "Gap"));
export const buttonHorizontalSpacing = registerSize('button.horizontal.spacing', { default: '12px' }, nls.localize('buttonHorizontalSpacing', "Padding Horizontal"));
export const buttonLineHeight = registerSize('button.line.height', { default: '18px' }, nls.localize('buttonLineHeight', "Line Height"));
export const buttonVerticalSpacing = registerSize('button.vertical.spacing', { default: '4px' }, nls.localize('buttonVerticalSpacing', "Padding Vertical"));
export const chatMessageCornerRadius = registerSize('chat.message.corner.radius', { default: '4px' }, nls.localize('chatMessageCornerRadius', "Corner Radius"));
export const chatMessageSpacing = registerSize('chat.message.spacing', { default: '8px' }, nls.localize('chatMessageSpacing', "Padding"));
export const chatSpacing = registerSize('chat.spacing', { default: '16px' }, nls.localize('chatSpacing', "Padding"));
export const checkboxCornerRadius = registerSize('checkbox.corner.radius', { default: '3px' }, nls.localize('checkboxCornerRadius', "Corner Radius"));
export const checkboxFontSize = registerSize('checkbox.font.size', { default: '12px' }, nls.localize('checkboxFontSize', "Font Size"));
export const checkboxHeight = registerSize('checkbox.height', { default: '18px' }, nls.localize('checkboxHeight', "Height"));
export const checkboxWidth = registerSize('checkbox.width', { default: '18px' }, nls.localize('checkboxWidth', "Width"));
export const dialogHeaderFontSize = registerSize('dialog.header.font.size', { default: '18px' }, nls.localize('dialogHeaderFontSize', "Message Font Size"));
export const dialogMinHeight = registerSize('dialog.min.height', { default: '75px' }, nls.localize('dialogMinHeight', "Min Height"));
export const dialogMinWidth = registerSize('dialog.min.width', { default: '500px' }, nls.localize('dialogMinWidth', "Min Width"));
export const dialogSpacingL = registerSize('dialog.spacing.l', { default: '15px' }, nls.localize('dialogSpacingL', "Spacing L"));
export const dialogSpacingM = registerSize('dialog.spacing.m', { default: '10px' }, nls.localize('dialogSpacingM', "Padding"));
export const dialogSpacingS = registerSize('dialog.spacing.s', { default: '5px' }, nls.localize('dialogSpacingS', "Spacing S"));
export const dialogSpacingXl = registerSize('dialog.spacing.xl', { default: '20px' }, nls.localize('dialogSpacingXl', "Spacing XL"));
export const dialogToolbarHeight = registerSize('dialog.toolbar.height', { default: '22px' }, nls.localize('dialogToolbarHeight', "Toolbar Height"));
export const dialogVerticalorientationMinWidth = registerSize('dialog.verticalorientation.min.width', { default: '350px' }, nls.localize('dialogVerticalorientationMinWidth', "Min Width"));
export const dragimageCornerRadius = registerSize('dragimage.corner.radius', { default: '10px' }, nls.localize('dragimageCornerRadius', "Corner Radius"));
export const dragimageHorizontalSpacing = registerSize('dragimage.horizontal.spacing', { default: '7px' }, nls.localize('dragimageHorizontalSpacing', "Horizontal Spacing"));
export const dragimageMaxWidth = registerSize('dragimage.max.width', { default: '120px' }, nls.localize('dragimageMaxWidth', "Max Width"));
export const dragimageVerticalSpacing = registerSize('dragimage.vertical.spacing', { default: '1px' }, nls.localize('dragimageVerticalSpacing', "Vertical Spacing"));
export const dropdownCornerRadius = registerSize('dropdown.corner.radius', { default: '5px' }, nls.localize('dropdownCornerRadius', "Corner Radius"));
export const dropdownFontSize = registerSize('dropdown.font.size', { default: '12px' }, nls.localize('dropdownFontSize', "Font Size"));
export const dropdownLineHeight = registerSize('dropdown.line.height', { default: '16px' }, nls.localize('dropdownLineHeight', "Line Height"));
export const hoverContentHorizontalSpacing = registerSize('hover.content.horizontal.spacing', { default: '0px' }, nls.localize('hoverContentHorizontalSpacing', "Horizontal Spacing"));
export const hoverContentVerticalSpacing = registerSize('hover.content.vertical.spacing', { default: '8px' }, nls.localize('hoverContentVerticalSpacing', "Vertical Spacing"));
export const hoverMarkupcontentHoriztonalSpacing = registerSize('hover.markupcontent.horiztonal.spacing', { default: '20px' }, nls.localize('hoverMarkupcontentHoriztonalSpacing', "Horiztonal Spacing"));
export const hoverMaxWidth = registerSize('hover.max.width', { default: '500px' }, nls.localize('hoverMaxWidth', "Max Width"));
export const hoverStatusbarHorizontalSpacing = registerSize('hover.statusbar.horizontal.spacing', { default: '8px' }, nls.localize('hoverStatusbarHorizontalSpacing', "Horizontal Spacing"));
export const hoverTooltipHorizontalSpacing = registerSize('hover.tooltip.horizontal.spacing', { default: '8px' }, nls.localize('hoverTooltipHorizontalSpacing', "Horizontal Padding"));
export const hoverTooltipVerticalSpacing = registerSize('hover.tooltip.vertical.spacing', { default: '4px' }, nls.localize('hoverTooltipVerticalSpacing', "Vertical Padding"));
export const iconlabelHeight = registerSize('iconlabel.height', { default: '0px' }, nls.localize('iconlabelHeight', "Height"));
export const iconselectboxCornerRadius = registerSize('iconselectbox.corner.radius', { default: '5px' }, nls.localize('iconselectboxCornerRadius', "Corner Radius"));
export const iconselectboxFontSize = registerSize('iconselectbox.font.size', { default: '20px' }, nls.localize('iconselectboxFontSize', "Font Size"));
export const inputboxLineHeight = registerSize('inputbox.line.height', { default: '17px' }, nls.localize('inputboxLineHeight', "Line Height"));
export const keybindingChordGap = registerSize('keybinding.chord.gap', { default: '6px' }, nls.localize('keybindingChordGap', "Chord Gap"));
export const keybindingKeyHorizontalSpacing = registerSize('keybinding.key.horizontal.spacing', { default: '5px' }, nls.localize('keybindingKeyHorizontalSpacing', "Horizontal Spacing"));
export const keybindingKeyLineHeight = registerSize('keybinding.key.line.height', { default: '10px' }, nls.localize('keybindingKeyLineHeight', "Line Height"));
export const keybindingKeyVerticalSpacing = registerSize('keybinding.key.vertical.spacing', { default: '3px' }, nls.localize('keybindingKeyVerticalSpacing', "Vertical Spacing"));
export const menubarCornerRadius = registerSize('menubar.corner.radius', { default: '5px' }, nls.localize('menubarCornerRadius', "Corner Radius"));
export const menubarHorizontalSpacing = registerSize('menubar.horizontal.spacing', { default: '5px' }, nls.localize('menubarHorizontalSpacing', "Horizontal Spacing"));
export const menubarOverflowWidth = registerSize('menubar.overflow.width', { default: '38px' }, nls.localize('menubarOverflowWidth', "Width"));
export const menubarToggleHeight = registerSize('menubar.toggle.height', { default: '22px' }, nls.localize('menubarToggleHeight', "Height"));
export const menubarToggleWidth = registerSize('menubar.toggle.width', { default: '22px' }, nls.localize('menubarToggleWidth', "Width"));
export const menubarVerticalSpacing = registerSize('menubar.vertical.spacing', { default: '4px' }, nls.localize('menubarVerticalSpacing', "Vertical Spacing"));
export const paneviewHeaderHeight = registerSize('paneview.header.height', { default: '22px' }, nls.localize('paneviewHeaderHeight', "Height"));
export const paneviewHeaderWidth = registerSize('paneview.header.width', { default: '22px' }, nls.localize('paneviewHeaderWidth', "Width"));
export const paneviewOverlayIndicatorMinHeight = registerSize('paneview.overlay.indicator.min.height', { default: '22px' }, nls.localize('paneviewOverlayIndicatorMinHeight', "Min Height"));
export const paneviewOverlayIndicatorMinWidth = registerSize('paneview.overlay.indicator.min.width', { default: '19px' }, nls.localize('paneviewOverlayIndicatorMinWidth', "Min Width"));
export const paneviewSelectboxMinWidth = registerSize('paneview.selectbox.min.width', { default: '110px' }, nls.localize('paneviewSelectboxMinWidth', "Min Width"));
export const progressHeight = registerSize('progress.height', { default: '2px' }, nls.localize('progressHeight', "Height"));
export const scrollableelementShadowHeight = registerSize('scrollableelement.shadow.height', { default: '3px' }, nls.localize('scrollableelementShadowHeight', "Height"));
export const scrollableelementShadowSpacing = registerSize('scrollableelement.shadow.spacing', { default: '3px' }, nls.localize('scrollableelementShadowSpacing', "Spacing"));
export const scrollableelementShadowWidth = registerSize('scrollableelement.shadow.width', { default: '3px' }, nls.localize('scrollableelementShadowWidth', "Width"));
export const selectboxCornerRadius = registerSize('selectbox.corner.radius', { default: '2px' }, nls.localize('selectboxCornerRadius', "Corner Radius"));
export const selectboxMacCornerRadius = registerSize('selectbox.mac.corner.radius', { default: '5px' }, nls.localize('selectboxMacCornerRadius', "Corner Radius"));
export const selectboxMinHeight = registerSize('selectbox.min.height', { default: '18px' }, nls.localize('selectboxMinHeight', "Min Height"));
export const selectboxMinWidth = registerSize('selectbox.min.width', { default: '100px' }, nls.localize('selectboxMinWidth', "Min Width"));
export const toggleCornerRadius = registerSize('toggle.corner.radius', { default: '3px' }, nls.localize('toggleCornerRadius', "Corder Radius"));
export const toggleHeight = registerSize('toggle.height', { default: '20px' }, nls.localize('toggleHeight', "Height"));
export const toggleWidth = registerSize('toggle.width', { default: '20px' }, nls.localize('toggleWidth', "Width"));
export const treeFilterMaxWidth = registerSize('tree.filter.max.width', { default: '200px' }, nls.localize('treeFilterMaxWidth', "Max Width"));
export const treeTwistieFontSize = registerSize('tree.twistie.font.size', { default: '10px' }, nls.localize('treeTwistieFontSize', "Font Size"));
