global class Type {
	global Object clone() { }
	global Boolean equals(Object o) { }
	global static System.Type forName(String namespace, String clsName) { }
	global static System.Type forName(String clsName) { }
	global String getName() { }
	global Integer hashCode() { }
	global Boolean isAssignableFrom(System.Type comparableType) { }
	global Object newInstance() { }
	global String toString() { }

}