/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

const fs = require('fs');
const path = require('path');
const product = require('../product.json');
const package = require('../package.json');
const cp = require('child_process');
const vm = require('vm');

const PREFIX = [
	'vs/loader.js',
	'vs/css.js',
	'vs/nls.js',
];

const CONTENTS = [
	'vs/base/browser/iframe',
	'vs/base/browser/ui/list/rangeMap',
	'vs/base/browser/ui/scrollbar/scrollbarState',
	'vs/base/common/assert',
	'vs/base/common/collections',
	'vs/base/common/color',
	'vs/base/common/date',
	'vs/base/common/decorators',
	'vs/base/common/diff/diffChange',
	'vs/base/common/diff/diff',
	'vs/base/common/functional',
	'vs/base/common/hash',
	'vs/base/common/idGenerator',
	'vs/base/common/iterator',
	'vs/base/common/history',
	'vs/base/common/json',
	'vs/base/common/jsonFormatter',
	'vs/base/common/jsonEdit',
	'vs/base/common/keyCodes',
	'vs/base/common/lifecycle',
	'vs/base/common/linkedList',
	'vs/base/common/marked/raw.marked',
	'vs/base/common/marked/marked',
	'vs/base/common/network',
	'vs/base/common/numbers',
	'vs/base/common/performance',
	'vs/base/common/platform',
	'vs/base/common/diagnostics',
	'vs/base/common/processes',
	'vs/base/common/stopwatch',
	'vs/base/common/types',
	'vs/base/common/graph',
	'vs/base/common/objects',
	'vs/base/common/parsers',
	'vs/base/common/uri',
	'vs/base/common/map',
	'vs/base/common/marshalling',
	'vs/base/common/strings',
	'vs/base/common/filters',
	'vs/base/common/octicon',
	'vs/base/common/paths',
	'vs/base/common/comparers',
	'vs/base/common/labels',
	'vs/base/common/resources',
	'vs/base/common/uuid',
	'vs/base/common/winjs.base.raw',
	'vs/base/common/winjs.base',
	'vs/base/common/arrays',
	'vs/base/common/cache',
	'vs/base/common/errors',
	'vs/base/common/event',
	'vs/base/browser/browser',
	'vs/base/browser/event',
	'vs/base/browser/keyboardEvent',
	'vs/base/browser/mouseEvent',
	'vs/base/common/actions',
	'vs/base/common/cancellation',
	'vs/base/common/async',
	'vs/base/browser/dom',
	'vs/base/browser/fastDomNode',
	'vs/base/browser/globalMouseMoveMonitor',
	'vs/base/browser/touch',
	'vs/base/browser/ui/list/rowCache',
	'vs/base/browser/ui/selectBox/selectBoxNative',
	'vs/base/browser/ui/widget',
	'vs/base/browser/ui/scrollbar/scrollbarArrow',
	'vs/base/common/glob',
	'vs/base/common/htmlContent',
	'vs/base/browser/htmlContentRenderer',
	'vs/base/common/mime',
	'vs/base/common/paging',
	'vs/base/common/scrollable',
	'vs/base/browser/ui/scrollbar/scrollbarVisibilityController',
	'vs/base/browser/ui/scrollbar/abstractScrollbar',
	'vs/base/browser/ui/scrollbar/horizontalScrollbar',
	'vs/base/browser/ui/scrollbar/verticalScrollbar',
	'vs/base/common/sequence',
	'vs/base/common/worker/simpleWorker',
	'vs/base/node/console',
	'vs/base/node/decoder',
	'vs/base/node/flow',
	'vs/base/node/id',
	'vs/base/node/ports',
	'vs/base/node/proxy',
	'vs/base/node/stdFork',
	'vs/base/node/stream',
	'vs/base/node/encoding',
	'vs/base/node/extfs',
	'vs/base/node/config',
	'vs/base/node/mime',
	'vs/base/node/pfs',
	'vs/base/parts/ipc/common/ipc',
	'vs/base/parts/ipc/common/ipc.electron',
	'vs/base/parts/ipc/electron-browser/ipc.electron-browser',
	'vs/base/parts/ipc/node/ipc.net',
	'vs/base/parts/quickopen/browser/quickOpenViewer',
	'vs/base/parts/quickopen/common/quickOpen',
	'vs/base/parts/quickopen/common/quickOpenScorer',
	'vs/base/parts/tree/browser/tree',
	'vs/base/parts/tree/browser/treeDnd',
	'vs/base/parts/tree/browser/treeModel',
	'vs/base/parts/tree/browser/treeViewModel',
	'vs/base/worker/defaultWorkerFactory',
	'vs/base/browser/builder',
	'vs/base/browser/dnd',
	'vs/base/browser/ui/button/button',
	'vs/base/browser/ui/checkbox/checkbox',
	'vs/base/browser/ui/contextview/contextview',
	'vs/base/browser/ui/countBadge/countBadge',
	'vs/base/browser/ui/dropdown/dropdown',
	'vs/base/browser/ui/octiconLabel/octiconLabel',
	'vs/base/browser/ui/highlightedlabel/highlightedLabel',
	'vs/base/browser/ui/iconLabel/iconLabel',
	'vs/base/browser/ui/progressbar/progressbar',
	'vs/base/browser/ui/sash/sash',
	'vs/base/browser/ui/scrollbar/scrollableElement',
	'vs/base/browser/ui/list/listView',
	'vs/base/browser/ui/list/listWidget',
	'vs/base/browser/ui/list/listPaging',
	'vs/base/parts/tree/browser/treeView',
	'vs/base/browser/ui/splitview/splitview',
	'vs/base/browser/ui/splitview/panelview',
	'vs/editor/browser/config/charWidthReader',
	'vs/editor/browser/config/elementSizeObserver',
	'vs/editor/browser/core/editorState',
	'vs/editor/browser/editorDom',
	'vs/editor/browser/services/abstractCodeEditorService',
	'vs/editor/common/config/editorZoom',
	'vs/editor/common/controller/cursorEvents',
	'vs/editor/common/core/position',
	'vs/editor/common/core/range',
	'vs/editor/browser/widget/diffNavigator',
	'vs/editor/common/core/editOperation',
	'vs/editor/common/commands/trimTrailingWhitespaceCommand',
	'vs/editor/common/core/rgba',
	'vs/editor/common/core/selection',
	'vs/editor/common/commands/replaceCommand',
	'vs/editor/common/commands/surroundSelectionCommand',
	'vs/editor/common/core/stringBuilder',
	'vs/editor/browser/view/viewLayer',
	'vs/editor/common/core/token',
	'vs/editor/common/core/uint',
	'vs/editor/common/core/characterClassifier',
	'vs/editor/common/controller/wordCharacterClassifier',
	'vs/editor/common/diff/diffComputer',
	'vs/editor/common/editorAction',
	'vs/editor/common/editorCommon',
	'vs/editor/browser/editorBrowser',
	'vs/editor/common/model',
	'vs/editor/browser/controller/textAreaState',
	'vs/editor/browser/controller/textAreaInput',
	'vs/editor/common/model/chunksTextBuffer/bufferPiece',
	'vs/editor/common/model/chunksTextBuffer/chunksTextBuffer',
	'vs/editor/common/model/chunksTextBuffer/chunksTextBufferBuilder',
	'vs/editor/common/model/editStack',
	'vs/editor/common/model/indentationGuesser',
	'vs/editor/common/model/intervalTree',
	'vs/editor/common/model/linesTextBuffer/textSource',
	'vs/editor/common/model/pieceTreeTextBuffer/rbTreeBase',
	'vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase',
	'vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBuffer',
	'vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBufferBuilder',
	'vs/editor/common/model/textModelEvents',
	'vs/editor/common/model/textModelSearch',
	'vs/editor/common/model/wordHelper',
	'vs/editor/common/modes/abstractMode',
	'vs/editor/common/modes/languageConfiguration',
	'vs/editor/common/modes/languageSelector',
	'vs/editor/common/modes/languageFeatureRegistry',
	'vs/editor/common/modes/linkComputer',
	'vs/editor/common/modes/supports/characterPair',
	'vs/editor/common/modes/supports/indentRules',
	'vs/editor/common/modes/supports/inplaceReplaceSupport',
	'vs/editor/common/modes/supports/onEnter',
	'vs/editor/common/modes/supports/richEditBrackets',
	'vs/editor/common/modes/supports/tokenization',
	'vs/editor/common/modes/tokenizationRegistry',
	'vs/editor/common/modes',
	'vs/editor/common/core/lineTokens',
	'vs/editor/common/modes/nullMode',
	'vs/editor/common/model/textModelTokens',
	'vs/editor/common/modes/supports',
	'vs/editor/common/modes/supports/electricCharacter',
	'vs/editor/common/modes/languageConfigurationRegistry',
	'vs/editor/common/modes/textToHtmlTokenizer',
	'vs/editor/common/standalone/standaloneBase',
	'vs/editor/common/view/minimapCharRenderer',
	'vs/editor/common/view/overviewZoneManager',
	'vs/editor/common/view/renderingContext',
	'vs/editor/browser/viewParts/lines/rangeUtil',
	'vs/editor/common/view/runtimeMinimapCharRenderer',
	'vs/editor/common/view/viewContext',
	'vs/editor/common/view/viewEventDispatcher',
	'vs/editor/common/view/viewEvents',
	'vs/editor/common/viewLayout/lineDecorations',
	'vs/editor/common/viewLayout/viewLineRenderer',
	'vs/editor/common/viewLayout/viewLinesViewportData',
	'vs/editor/common/viewLayout/whitespaceComputer',
	'vs/editor/common/viewLayout/linesLayout',
	'vs/editor/common/viewModel/prefixSumComputer',
	'vs/editor/common/model/linesTextBuffer/linesTextBuffer',
	'vs/editor/common/model/linesTextBuffer/linesTextBufferBuilder',
	'vs/editor/common/model/mirrorTextModel',
	'vs/editor/common/services/editorSimpleWorker',
	'vs/editor/common/viewModel/viewEventHandler',
	'vs/editor/browser/view/dynamicViewOverlay',
	'vs/editor/browser/view/viewPart',
	'vs/editor/browser/viewParts/contentWidgets/contentWidgets',
	'vs/editor/browser/viewParts/decorations/decorations',
	'vs/editor/browser/viewParts/glyphMargin/glyphMargin',
	'vs/editor/browser/viewParts/linesDecorations/linesDecorations',
	'vs/editor/browser/viewParts/margin/margin',
	'vs/editor/browser/viewParts/marginDecorations/marginDecorations',
	'vs/editor/browser/viewParts/overlayWidgets/overlayWidgets',
	'vs/editor/browser/viewParts/overviewRuler/overviewRuler',
	'vs/editor/browser/viewParts/viewZones/viewZones',
	'vs/editor/common/viewModel/viewModel',
	'vs/editor/common/viewLayout/viewLayout',
	'vs/editor/common/viewModel/viewModelDecorations',
	'vs/editor/contrib/caretOperations/moveCaretCommand',
	'vs/editor/contrib/colorPicker/color',
	'vs/editor/contrib/colorPicker/colorPickerModel',
	'vs/editor/contrib/comment/blockCommentCommand',
	'vs/editor/contrib/comment/lineCommentCommand',
	'vs/editor/contrib/dnd/dragAndDropCommand',
	'vs/editor/contrib/find/findState',
	'vs/editor/contrib/find/replaceAllCommand',
	'vs/editor/contrib/find/replacePattern',
	'vs/editor/contrib/folding/foldingRanges',
	'vs/editor/contrib/folding/foldingModel',
	'vs/editor/contrib/folding/hiddenRangeModel',
	'vs/editor/contrib/format/formatCommand',
	'vs/editor/contrib/goToDeclaration/clickLinkGesture',
	'vs/editor/contrib/hover/hoverOperation',
	'vs/editor/contrib/hover/hoverWidgets',
	'vs/editor/contrib/hover/modesGlyphHover',
	'vs/editor/contrib/inPlaceReplace/inPlaceReplaceCommand',
	'vs/editor/contrib/indentation/indentUtils',
	'vs/editor/contrib/linesOperations/copyLinesCommand',
	'vs/editor/contrib/linesOperations/deleteLinesCommand',
	'vs/editor/contrib/linesOperations/sortLinesCommand',
	'vs/editor/contrib/quickFix/codeActionTrigger',
	'vs/editor/contrib/quickFix/quickFixWidget',
	'vs/editor/contrib/smartSelect/tokenTree',
	'vs/editor/contrib/snippet/snippetParser',
	'vs/editor/contrib/snippet/snippetVariables',
	'vs/editor/contrib/suggest/completionModel',
	'vs/base/browser/ui/aria/aria',
	'vs/base/browser/ui/findinput/findInputCheckboxes',
	'vs/base/browser/ui/selectBox/selectBoxCustom',
	'vs/base/browser/ui/selectBox/selectBox',
	'vs/base/browser/ui/actionbar/actionbar',
	'vs/base/browser/ui/inputbox/inputBox',
	'vs/base/browser/ui/findinput/findInput',
	'vs/base/browser/ui/toolbar/toolbar',
	'vs/base/common/errorMessage',
	'vs/base/common/jsonErrorMessages',
	'vs/base/common/keybindingLabels',
	'vs/base/browser/ui/keybindingLabel/keybindingLabel',
	'vs/base/common/severity',
	'vs/base/node/processes',
	'vs/base/parts/ipc/node/ipc.cp',
	'vs/base/parts/quickopen/browser/quickOpenModel',
	'vs/base/parts/tree/browser/treeDefaults',
	'vs/base/parts/tree/browser/treeImpl',
	'vs/base/parts/quickopen/browser/quickOpenWidget',
	'vs/editor/common/config/editorOptions',
	'vs/editor/common/config/fontInfo',
	'vs/editor/common/model/textModel',
	'vs/editor/common/controller/cursorCommon',
	'vs/editor/common/commands/shiftCommand',
	'vs/editor/common/controller/cursorColumnSelection',
	'vs/editor/common/controller/cursorMoveOperations',
	'vs/editor/common/controller/cursorDeleteOperations',
	'vs/editor/common/controller/cursorTypeOperations',
	'vs/editor/common/controller/cursorWordOperations',
	'vs/editor/common/controller/cursorMoveCommands',
	'vs/editor/common/controller/oneCursor',
	'vs/editor/common/controller/cursorCollection',
	'vs/editor/common/viewModel/splitLinesCollection',
	'vs/editor/common/viewModel/characterHardWrappingLineMapper',
	'vs/editor/common/viewModel/viewModelImpl',
	'vs/editor/contrib/folding/foldingDecorations',
	'vs/editor/contrib/folding/indentRangeProvider',
	'vs/editor/contrib/linesOperations/moveLinesCommand',
	'vs/editor/contrib/quickFix/lightBulbWidget',
	'vs/editor/contrib/zoneWidget/zoneWidget',
	'vs/editor/common/controller/cursor',
	'vs/editor/contrib/referenceSearch/referencesModel',
	'vs/platform/clipboard/electron-browser/clipboardService',
	'vs/platform/extensionManagement/common/extensionManagementIpc',
	'vs/platform/extensions/common/extensionHost',
	'vs/platform/extensions/node/extensionValidator',
	'vs/platform/files/node/files',
	'vs/platform/instantiation/common/descriptors',
	'vs/platform/instantiation/common/extensions',
	'vs/platform/instantiation/common/instantiation',
	'vs/editor/browser/services/codeEditorService',
	'vs/editor/common/services/editorWorkerService',
	'vs/editor/common/services/modeService',
	'vs/editor/common/services/modelService',
	'vs/editor/common/services/resolverService',
	'vs/editor/common/services/resourceConfiguration',
	'vs/editor/common/services/editorWorkerServiceImpl',
	'vs/editor/common/services/webWorker',
	'vs/editor/contrib/smartSelect/tokenSelectionSupport',
	'vs/platform/clipboard/common/clipboardService',
	'vs/editor/contrib/snippet/snippetSession',
	'vs/platform/commands/common/commands',
	'vs/editor/contrib/links/getLinks',
	'vs/platform/contextkey/common/contextkey',
	'vs/editor/common/editorContextKeys',
	'vs/platform/actions/common/actions',
	'vs/platform/actions/common/menu',
	'vs/platform/contextview/browser/contextView',
	'vs/platform/editor/common/editor',
	'vs/platform/environment/common/environment',
	'vs/platform/extensionManagement/common/extensionManagement',
	'vs/platform/extensionManagement/common/extensionManagementUtil',
	'vs/platform/extensionManagement/node/extensionManagementUtil',
	'vs/platform/extensions/common/extensions',
	'vs/platform/actions/common/menuService',
	'vs/platform/files/common/files',
	'vs/platform/instantiation/common/serviceCollection',
	'vs/editor/common/commonCodeEditor',
	'vs/platform/instantiation/common/instantiationService',
	'vs/platform/integrity/common/integrity',
	'vs/platform/issue/common/issue',
	'vs/platform/issue/common/issueIpc',
	'vs/platform/keybinding/common/abstractKeybindingService',
	'vs/platform/keybinding/common/keybinding',
	'vs/platform/keybinding/common/keybindingResolver',
	'vs/platform/keybinding/common/resolvedKeybindingItem',
	'vs/platform/keybinding/common/usLayoutResolvedKeybinding',
	'vs/platform/lifecycle/common/lifecycle',
	'vs/platform/localizations/common/localizations',
	'vs/platform/localizations/common/localizationsIpc',
	'vs/platform/log/common/log',
	'vs/platform/broadcast/electron-browser/broadcastService',
	'vs/platform/commands/common/commandService',
	'vs/platform/log/common/logIpc',
	'vs/platform/log/node/spdlogService',
	'vs/platform/markers/common/markerService',
	'vs/platform/markers/common/markers',
	'vs/platform/message/common/message',
	'vs/platform/actions/browser/menuItemActionItem',
	'vs/platform/message/common/messageIpc',
	'vs/platform/node/package',
	'vs/base/node/paths',
	'vs/platform/node/product',
	'vs/platform/environment/node/environmentService',
	'vs/platform/opener/common/opener',
	'vs/editor/contrib/markdown/markdownRenderer',
	'vs/platform/progress/common/progress',
	'vs/editor/browser/services/bulkEdit',
	'vs/platform/quickOpen/common/quickOpen',
	'vs/platform/registry/common/platform',
	'vs/editor/common/modes/modesRegistry',
	'vs/platform/jsonschemas/common/jsonContributionRegistry',
	'vs/platform/configuration/common/configurationRegistry',
	'vs/editor/common/config/commonEditorConfig',
	'vs/editor/common/services/languagesRegistry',
	'vs/editor/common/services/modeServiceImpl',
	'vs/platform/configuration/common/configuration',
	'vs/editor/common/services/resourceConfigurationImpl',
	'vs/platform/configuration/common/configurationModels',
	'vs/platform/configuration/node/configuration',
	'vs/platform/contextkey/browser/contextKeyService',
	'vs/platform/extensions/common/extensionsRegistry',
	'vs/platform/actions/electron-browser/menusExtensionPoint',
	'vs/platform/jsonschemas/common/jsonValidationExtensionPoint',
	'vs/platform/keybinding/common/keybindingsRegistry',
	'vs/platform/markers/common/problemMatcher',
	'vs/platform/request/node/request',
	'vs/platform/search/common/replace',
	'vs/platform/search/common/search',
	'vs/platform/statusbar/common/statusbar',
	'vs/platform/storage/common/storage',
	'vs/editor/browser/config/configuration',
	'vs/editor/browser/view/viewOverlays',
	'vs/editor/browser/viewParts/viewCursors/viewCursor',
	'vs/editor/contrib/suggest/suggestMemory',
	'vs/platform/integrity/node/integrityServiceImpl',
	'vs/platform/storage/common/storageService',
	'vs/platform/storage/common/migration',
	'vs/platform/telemetry/browser/errorTelemetry',
	'vs/platform/telemetry/common/experiments',
	'vs/platform/telemetry/common/telemetry',
	'vs/editor/browser/editorExtensions',
	'vs/editor/browser/controller/coreCommands',
	'vs/editor/browser/view/viewController',
	'vs/editor/contrib/caretOperations/caretOperations',
	'vs/editor/contrib/caretOperations/transpose',
	'vs/editor/contrib/clipboard/clipboard',
	'vs/editor/contrib/codelens/codelens',
	'vs/editor/contrib/colorPicker/colorDetector',
	'vs/editor/contrib/comment/comment',
	'vs/editor/contrib/contextmenu/contextmenu',
	'vs/editor/contrib/cursorUndo/cursorUndo',
	'vs/editor/contrib/dnd/dnd',
	'vs/editor/contrib/folding/folding',
	'vs/editor/contrib/format/format',
	'vs/editor/contrib/format/formatActions',
	'vs/editor/contrib/goToDeclaration/goToDeclaration',
	'vs/editor/contrib/hover/getHover',
	'vs/editor/contrib/indentation/indentation',
	'vs/editor/contrib/linesOperations/linesOperations',
	'vs/editor/contrib/parameterHints/provideSignatureHelp',
	'vs/editor/contrib/quickFix/quickFix',
	'vs/editor/contrib/quickFix/quickFixModel',
	'vs/editor/contrib/quickFix/quickFixCommands',
	'vs/editor/contrib/quickOpen/quickOpen',
	'vs/editor/contrib/smartSelect/smartSelect',
	'vs/editor/contrib/suggest/suggest',
	'vs/editor/contrib/snippet/snippetController2',
	'vs/editor/contrib/suggest/suggestModel',
	'vs/editor/contrib/toggleTabFocusMode/toggleTabFocusMode',
	'vs/editor/contrib/wordOperations/wordOperations',
	'vs/platform/contextview/browser/contextViewService',
	'vs/platform/telemetry/common/telemetryIpc',
	'vs/platform/telemetry/common/telemetryService',
	'vs/platform/telemetry/common/telemetryUtils',
	'vs/platform/opener/browser/openerService',
	'vs/platform/opener/browser/opener.contribution',
	'vs/platform/telemetry/node/commonProperties',
	'vs/platform/telemetry/node/telemetryNodeUtils',
	'vs/platform/telemetry/node/workbenchCommonProperties',
	'vs/platform/theme/common/colorRegistry',
	'vs/platform/theme/common/colorExtensionPoint',
	'vs/platform/theme/common/styler',
	'vs/platform/theme/common/themeService',
	'vs/editor/browser/services/codeEditorServiceImpl',
	'vs/editor/browser/viewParts/editorScrollbar/editorScrollbar',
	'vs/editor/browser/viewParts/lines/viewLine',
	'vs/editor/browser/controller/mouseTarget',
	'vs/editor/browser/controller/mouseHandler',
	'vs/editor/browser/controller/pointerHandler',
	'vs/editor/browser/view/viewOutgoingEvents',
	'vs/editor/browser/viewParts/lines/viewLines',
	'vs/editor/browser/viewParts/minimap/minimap',
	'vs/editor/browser/viewParts/scrollDecoration/scrollDecoration',
	'vs/editor/browser/viewParts/selections/selections',
	'vs/editor/common/view/editorColorRegistry',
	'vs/editor/browser/viewParts/currentLineHighlight/currentLineHighlight',
	'vs/editor/browser/viewParts/currentLineMarginHighlight/currentLineMarginHighlight',
	'vs/editor/browser/viewParts/indentGuides/indentGuides',
	'vs/editor/browser/viewParts/lineNumbers/lineNumbers',
	'vs/editor/browser/controller/textAreaHandler',
	'vs/editor/browser/viewParts/overviewRuler/decorationsOverviewRuler',
	'vs/editor/browser/viewParts/rulers/rulers',
	'vs/editor/browser/viewParts/viewCursors/viewCursors',
	'vs/editor/browser/view/viewImpl',
	'vs/editor/browser/widget/codeEditorWidget',
	'vs/editor/browser/codeEditor',
	'vs/editor/browser/widget/diffReview',
	'vs/editor/browser/widget/diffEditorWidget',
	'vs/editor/browser/widget/embeddedCodeEditorWidget',
	'vs/editor/common/services/modelServiceImpl',
	'vs/editor/contrib/bracketMatching/bracketMatching',
	'vs/editor/contrib/codelens/codelensWidget',
	'vs/editor/contrib/codelens/codelensController',
	'vs/editor/contrib/colorPicker/colorPickerWidget',
	'vs/editor/contrib/find/findDecorations',
	'vs/editor/contrib/find/findModel',
	'vs/editor/contrib/find/findOptionsWidget',
	'vs/editor/contrib/find/findWidget',
	'vs/editor/contrib/find/findController',
	'vs/editor/contrib/find/simpleFindWidget',
	'vs/editor/contrib/gotoError/gotoError',
	'vs/editor/contrib/hover/modesContentHover',
	'vs/editor/contrib/hover/hover',
	'vs/editor/contrib/inPlaceReplace/inPlaceReplace',
	'vs/editor/contrib/links/links',
	'vs/editor/contrib/message/messageController',
	'vs/editor/contrib/multicursor/multicursor',
	'vs/editor/contrib/parameterHints/parameterHintsWidget',
	'vs/editor/contrib/parameterHints/parameterHints',
	'vs/editor/contrib/referenceSearch/peekViewWidget',
	'vs/editor/contrib/rename/renameInputField',
	'vs/editor/contrib/rename/rename',
	'vs/editor/contrib/suggest/suggestWidget',
	'vs/editor/contrib/suggest/suggestController',
	'vs/editor/contrib/wordHighlighter/wordHighlighter',
	'vs/platform/update/common/update',
	'vs/platform/update/common/updateIpc',
	'vs/platform/update/node/update.config.contribution',
	'vs/platform/url/common/url',
	'vs/platform/windows/common/windows',
	'vs/platform/lifecycle/electron-browser/lifecycleService',
	'vs/platform/url/common/urlIpc',
	'vs/platform/windows/common/windowsIpc',
	'vs/platform/windows/electron-browser/windowService',
	'vs/platform/workbench/common/contextkeys',
	'vs/platform/list/browser/listService',
	'vs/platform/workspaces/common/workspaces',
	'vs/platform/workspace/common/workspace',
	'vs/editor/contrib/referenceSearch/referencesWidget',
	'vs/editor/contrib/referenceSearch/referencesController',
	'vs/editor/contrib/goToDeclaration/goToDeclarationCommands',
	'vs/editor/contrib/goToDeclaration/goToDeclarationMouse',
	'vs/editor/contrib/referenceSearch/referenceSearch',
	'vs/editor/editor.all',
	'vs/platform/extensionManagement/common/extensionEnablementService',
	'vs/platform/workspaces/common/workspacesIpc',
	'vs/platform/workspaces/node/workspaces',
	'vs/workbench/api/electron-browser/extHostCustomers',
	'vs/workbench/api/node/extHostTypes',
	'vs/workbench/browser/actions',
	'vs/workbench/browser/parts/quickopen/quickopen',
	'vs/workbench/browser/parts/statusbar/statusbar',
	'vs/workbench/common/actions',
	'vs/workbench/browser/actions/toggleTabsVisibility',
	'vs/workbench/common/activity',
	'vs/workbench/common/contributions',
	'vs/workbench/common/editor',
	'vs/workbench/browser/quickopen',
	'vs/workbench/common/editor/diffEditorModel',
	'vs/workbench/common/editor/editorStacksModel',
	'vs/workbench/common/editor/textDiffEditorModel',
	'vs/workbench/common/editor/textEditorModel',
	'vs/workbench/common/editor/diffEditorInput',
	'vs/workbench/common/editor/resourceEditorModel',
	'vs/workbench/common/memento',
	'vs/workbench/common/resources',
	'vs/workbench/common/editor/binaryEditorModel',
	'vs/workbench/common/editor/dataUriEditorInput',
	'vs/workbench/common/theme',
	'vs/workbench/common/component',
	'vs/workbench/browser/composite',
	'vs/workbench/browser/panel',
	'vs/workbench/browser/part',
	'vs/workbench/browser/parts/editor/baseEditor',
	'vs/workbench/browser/editor',
	'vs/workbench/browser/parts/editor/sideBySideEditor',
	'vs/workbench/browser/parts/editor/webviewEditor',
	'vs/workbench/common/views',
	'vs/workbench/electron-browser/resources',
	'vs/workbench/parts/cache/node/nodeCachedDataManager',
	'vs/workbench/parts/cache/node/cache.contribution',
	'vs/workbench/parts/cli/electron-browser/cli.contribution',
	'vs/workbench/parts/codeEditor/electron-browser/accessibility',
	'vs/workbench/parts/codeEditor/electron-browser/menuPreventer',
	'vs/workbench/parts/codeEditor/electron-browser/selectionClipboard',
	'vs/workbench/parts/codeEditor/electron-browser/toggleMinimap',
	'vs/workbench/parts/codeEditor/electron-browser/toggleMultiCursorModifier',
	'vs/workbench/parts/codeEditor/electron-browser/toggleRenderControlCharacter',
	'vs/workbench/parts/codeEditor/electron-browser/toggleRenderWhitespace',
	'vs/workbench/parts/codeEditor/electron-browser/toggleWordWrap',
	'vs/workbench/parts/debug/common/debug',
	'vs/workbench/parts/debug/browser/breakpointWidget',
	'vs/workbench/parts/debug/browser/debugActionItems',
	'vs/workbench/parts/debug/browser/debugEditorModelManager',
	'vs/workbench/parts/debug/browser/debugStatus',
	'vs/workbench/parts/debug/common/debugSource',
	'vs/workbench/parts/debug/browser/debugContentProvider',
	'vs/workbench/parts/debug/common/debugModel',
	'vs/workbench/parts/debug/common/debugViewModel',
	'vs/workbench/parts/debug/common/replHistory',
	'vs/workbench/parts/debug/electron-browser/baseDebugView',
	'vs/workbench/parts/debug/electron-browser/electronDebugActions',
	'vs/workbench/parts/debug/electron-browser/terminalSupport',
	'vs/workbench/parts/debug/node/debugAdapter',
	'vs/workbench/parts/debug/node/v8Protocol',
	'vs/workbench/parts/emmet/browser/actions/showEmmetCommands',
	'vs/workbench/parts/emmet/browser/emmet.browser.contribution',
	'vs/workbench/parts/execution/common/execution',
	'vs/workbench/parts/execution/electron-browser/terminal',
	'vs/workbench/parts/execution/electron-browser/terminalService',
	'vs/workbench/parts/extensions/common/extensionQuery',
	'vs/workbench/parts/extensions/common/extensions',
	'vs/workbench/parts/extensions/browser/dependenciesViewer',
	'vs/workbench/parts/extensions/browser/extensionsWidgets',
	'vs/workbench/parts/extensions/common/extensionsFileTemplate',
	'vs/workbench/parts/extensions/common/extensionsInput',
	'vs/workbench/parts/extensions/electron-browser/extensionsUtils',
	'vs/workbench/parts/files/common/explorerModel',
	'vs/workbench/parts/files/browser/files',
	'vs/workbench/parts/files/electron-browser/views/explorerDecorationsProvider',
	'vs/workbench/parts/html/browser/webviewFindWidget',
	'vs/workbench/parts/html/browser/webview',
	'vs/workbench/parts/logs/common/logConstants',
	'vs/workbench/parts/markers/common/constants',
	'vs/workbench/parts/markers/common/messages',
	'vs/workbench/parts/markers/common/markersModel',
	'vs/workbench/parts/markers/browser/markersTreeController',
	'vs/workbench/parts/output/common/output',
	'vs/workbench/parts/logs/electron-browser/logsActions',
	'vs/workbench/parts/logs/electron-browser/logs.contribution',
	'vs/workbench/parts/output/common/outputLinkProvider',
	'vs/workbench/parts/performance/electron-browser/stats',
	'vs/workbench/parts/preferences/browser/keybindingWidgets',
	'vs/workbench/parts/preferences/browser/preferencesWidgets',
	'vs/workbench/parts/preferences/common/keybindingsEditorModel',
	'vs/workbench/parts/preferences/common/preferences',
	'vs/workbench/parts/preferences/common/preferencesModels',
	'vs/workbench/parts/preferences/common/smartSnippetInserter',
	'vs/workbench/parts/quickopen/browser/helpHandler',
	'vs/workbench/parts/relauncher/electron-browser/relauncher.contribution',
	'vs/workbench/parts/scm/common/scm',
	'vs/workbench/parts/scm/electron-browser/scmUtil',
	'vs/workbench/parts/scm/electron-browser/scmMenus',
	'vs/workbench/parts/search/browser/patternInputWidget',
	'vs/workbench/parts/search/common/constants',
	'vs/workbench/parts/search/common/queryBuilder',
	'vs/workbench/parts/search/common/replace',
	'vs/workbench/parts/search/common/search',
	'vs/workbench/parts/search/common/searchModel',
	'vs/workbench/parts/search/browser/replaceService',
	'vs/workbench/parts/search/browser/replaceContributions',
	'vs/workbench/parts/snippets/electron-browser/snippets.contribution',
	'vs/workbench/parts/snippets/electron-browser/configureSnippets',
	'vs/workbench/parts/snippets/electron-browser/snippetsFile',
	'vs/workbench/parts/snippets/electron-browser/insertSnippet',
	'vs/workbench/parts/stats/node/workspaceStats',
	'vs/workbench/parts/stats/node/stats.contribution',
	'vs/workbench/parts/surveys/electron-browser/languageSurveys.contribution',
	'vs/workbench/parts/surveys/electron-browser/nps.contribution',
	'vs/workbench/parts/tasks/common/problemCollectors',
	'vs/workbench/parts/tasks/common/taskDefinitionRegistry',
	'vs/workbench/parts/tasks/common/taskSystem',
	'vs/workbench/parts/tasks/common/taskTemplates',
	'vs/workbench/parts/tasks/common/tasks',
	'vs/workbench/parts/tasks/common/taskService',
	'vs/workbench/parts/tasks/browser/quickOpen',
	'vs/workbench/parts/tasks/browser/taskQuickOpen',
	'vs/workbench/parts/tasks/electron-browser/jsonSchemaCommon',
	'vs/workbench/parts/tasks/electron-browser/jsonSchema_v1',
	'vs/workbench/parts/tasks/electron-browser/jsonSchema_v2',
	'vs/workbench/parts/tasks/electron-browser/terminalTaskSystem',
	'vs/workbench/parts/tasks/node/processRunnerDetector',
	'vs/workbench/parts/tasks/node/processTaskSystem',
	'vs/workbench/parts/tasks/node/taskConfiguration',
	'vs/workbench/parts/terminal/browser/terminalWidgetManager',
	'vs/workbench/parts/terminal/common/terminal',
	'vs/workbench/parts/debug/electron-browser/rawDebugSession',
	'vs/workbench/parts/terminal/browser/terminalQuickOpen',
	'vs/workbench/parts/terminal/electron-browser/terminal',
	'vs/workbench/parts/terminal/electron-browser/terminalColorRegistry',
	'vs/workbench/parts/terminal/electron-browser/terminalCommands',
	'vs/workbench/parts/terminal/electron-browser/terminalFindWidget',
	'vs/workbench/parts/terminal/electron-browser/terminalLinkHandler',
	'vs/workbench/parts/terminal/electron-browser/windowsShellHelper',
	'vs/workbench/parts/update/electron-browser/releaseNotesInput',
	'vs/workbench/parts/welcome/gettingStarted/electron-browser/gettingStarted',
	'vs/workbench/parts/welcome/gettingStarted/electron-browser/gettingStarted.contribution',
	'vs/workbench/parts/welcome/page/electron-browser/vs_code_welcome_page',
	'vs/workbench/parts/welcome/walkThrough/node/walkThroughUtils',
	'vs/workbench/services/activity/common/activity',
	'vs/workbench/browser/parts/compositebar/compositeBarActions',
	'vs/workbench/browser/parts/compositebar/compositeBar',
	'vs/workbench/parts/markers/common/markers',
	'vs/workbench/services/backup/common/backup',
	'vs/workbench/common/editor/untitledEditorModel',
	'vs/workbench/services/backup/node/backupFileService',
	'vs/workbench/services/configuration/common/configuration',
	'vs/workbench/parts/feedback/electron-browser/feedback',
	'vs/workbench/parts/feedback/electron-browser/feedbackStatusbarItem',
	'vs/workbench/parts/feedback/electron-browser/feedback.contribution',
	'vs/workbench/parts/terminal/electron-browser/terminalConfigHelper',
	'vs/workbench/parts/trust/electron-browser/unsupportedWorkspaceSettings.contribution',
	'vs/workbench/services/configuration/common/configurationExtensionPoint',
	'vs/workbench/services/configuration/common/configurationModels',
	'vs/workbench/services/configuration/common/jsonEditing',
	'vs/workbench/services/configuration/node/configuration',
	'vs/workbench/services/configurationResolver/common/configurationResolver',
	'vs/workbench/services/contextview/electron-browser/contextmenuService',
	'vs/workbench/services/crashReporter/electron-browser/crashReporterService',
	'vs/workbench/services/decorations/browser/decorations',
	'vs/workbench/parts/markers/browser/markersFileDecorations',
	'vs/workbench/services/decorations/browser/decorationsService',
	'vs/workbench/services/extensions/electron-browser/extensionHost',
	'vs/workbench/services/extensions/electron-browser/extensionHostProfiler',
	'vs/workbench/services/extensions/node/extensionDescriptionRegistry',
	'vs/workbench/services/extensions/node/extensionPoints',
	'vs/workbench/services/extensions/node/lazyPromise',
	'vs/workbench/services/extensions/node/proxyIdentifier',
	'vs/workbench/api/node/extHost.protocol',
	'vs/workbench/api/electron-browser/mainThreadCommands',
	'vs/workbench/api/electron-browser/mainThreadConfiguration',
	'vs/workbench/api/electron-browser/mainThreadDebugService',
	'vs/workbench/api/electron-browser/mainThreadDecorations',
	'vs/workbench/api/electron-browser/mainThreadDiagnostics',
	'vs/workbench/api/electron-browser/mainThreadDialogs',
	'vs/workbench/api/electron-browser/mainThreadEditor',
	'vs/workbench/api/electron-browser/mainThreadErrors',
	'vs/workbench/api/electron-browser/mainThreadFileSystemEventService',
	'vs/workbench/api/electron-browser/mainThreadHeapService',
	'vs/workbench/api/electron-browser/mainThreadLanguages',
	'vs/workbench/api/electron-browser/mainThreadLogService',
	'vs/workbench/api/electron-browser/mainThreadMessageService',
	'vs/workbench/api/electron-browser/mainThreadProgress',
	'vs/workbench/api/electron-browser/mainThreadQuickOpen',
	'vs/workbench/api/electron-browser/mainThreadStatusBar',
	'vs/workbench/api/electron-browser/mainThreadStorage',
	'vs/workbench/api/electron-browser/mainThreadTask',
	'vs/workbench/api/electron-browser/mainThreadTelemetry',
	'vs/workbench/api/electron-browser/mainThreadTerminalService',
	'vs/workbench/api/electron-browser/mainThreadTreeViews',
	'vs/workbench/api/electron-browser/mainThreadWindow',
	'vs/workbench/services/extensions/node/rpcProtocol',
	'vs/workbench/services/files/node/watcher/common',
	'vs/workbench/services/files/node/watcher/nsfw/watcherIpc',
	'vs/workbench/services/files/node/watcher/nsfw/watcherService',
	'vs/workbench/services/files/node/watcher/unix/watcherIpc',
	'vs/workbench/services/files/node/watcher/unix/watcherService',
	'vs/workbench/services/files/node/watcher/win32/csharpWatcherService',
	'vs/workbench/services/files/node/watcher/win32/watcherService',
	'vs/workbench/services/files/node/fileService',
	'vs/workbench/services/files/electron-browser/fileService',
	'vs/workbench/services/files/electron-browser/remoteFileService',
	'vs/workbench/services/group/common/groupService',
	'vs/workbench/api/electron-browser/mainThreadDocumentContentProviders',
	'vs/workbench/browser/actions/toggleEditorLayout',
	'vs/workbench/browser/parts/editor/resourceViewer',
	'vs/workbench/browser/parts/editor/binaryEditor',
	'vs/workbench/browser/parts/editor/binaryDiffEditor',
	'vs/workbench/parts/preferences/common/preferencesContribution',
	'vs/workbench/services/hash/common/hashService',
	'vs/workbench/common/editor/resourceEditorInput',
	'vs/workbench/parts/html/common/htmlInput',
	'vs/workbench/parts/welcome/walkThrough/node/walkThroughInput',
	'vs/workbench/parts/welcome/walkThrough/electron-browser/walkThroughPart',
	'vs/workbench/services/hash/node/hashService',
	'vs/workbench/services/history/common/history',
	'vs/workbench/services/issue/common/issue',
	'vs/workbench/services/issue/electron-browser/workbenchIssueService',
	'vs/workbench/services/keybinding/common/keyboardMapper',
	'vs/workbench/services/keybinding/common/scanCode',
	'vs/workbench/services/keybinding/common/keybindingIO',
	'vs/workbench/services/keybinding/common/macLinuxFallbackKeyboardMapper',
	'vs/workbench/services/keybinding/common/macLinuxKeyboardMapper',
	'vs/workbench/services/keybinding/common/windowsKeyboardMapper',
	'vs/workbench/parts/preferences/browser/keybindingsEditorContribution',
	'vs/workbench/services/keybinding/electron-browser/keybindingService',
	'vs/workbench/services/message/browser/messageList',
	'vs/workbench/services/message/browser/messageService',
	'vs/workbench/services/message/electron-browser/messageService',
	'vs/workbench/services/mode/common/workbenchModeService',
	'vs/workbench/parts/snippets/electron-browser/snippetsService',
	'vs/workbench/parts/snippets/electron-browser/tabCompletion',
	'vs/workbench/parts/debug/electron-browser/replEditor',
	'vs/workbench/services/panel/common/panelService',
	'vs/workbench/parts/output/electron-browser/outputServices',
	'vs/workbench/parts/terminal/electron-browser/terminalInstance',
	'vs/workbench/services/activity/browser/activityService',
	'vs/workbench/services/part/common/partService',
	'vs/workbench/api/electron-browser/mainThreadOutputService',
	'vs/workbench/browser/actions/toggleActivityBarVisibility',
	'vs/workbench/browser/actions/toggleSidebarPosition',
	'vs/workbench/browser/actions/toggleSidebarVisibility',
	'vs/workbench/browser/actions/toggleStatusbarVisibility',
	'vs/workbench/browser/actions/toggleZenMode',
	'vs/workbench/browser/parts/panel/panelActions',
	'vs/workbench/parts/debug/electron-browser/statusbarColorProvider',
	'vs/workbench/parts/markers/browser/markersPanelActions',
	'vs/workbench/parts/output/browser/outputActions',
	'vs/workbench/parts/terminal/common/terminalService',
	'vs/workbench/parts/terminal/electron-browser/terminalService',
	'vs/workbench/services/scm/common/scm',
	'vs/workbench/api/electron-browser/mainThreadSCM',
	'vs/workbench/parts/scm/electron-browser/scmActivity',
	'vs/workbench/services/scm/common/scmService',
	'vs/workbench/services/search/node/searchIpc',
	'vs/workbench/services/textMate/electron-browser/TMGrammars',
	'vs/workbench/parts/emmet/electron-browser/emmetActions',
	'vs/workbench/parts/emmet/electron-browser/actions/expandAbbreviation',
	'vs/workbench/parts/emmet/electron-browser/emmet.contribution',
	'vs/workbench/services/textMate/electron-browser/TMHelper',
	'vs/workbench/services/textMate/electron-browser/textMateService',
	'vs/workbench/parts/codeEditor/electron-browser/languageConfiguration/languageConfigurationExtensionPoint',
	'vs/workbench/services/textfile/common/textfiles',
	'vs/workbench/api/node/extHostTypeConverters',
	'vs/workbench/api/electron-browser/mainThreadLanguageFeatures',
	'vs/workbench/browser/parts/editor/textEditor',
	'vs/workbench/common/editor/untitledEditorInput',
	'vs/workbench/browser/parts/editor/textResourceEditor',
	'vs/workbench/parts/files/common/files',
	'vs/workbench/parts/files/browser/editors/binaryFileEditor',
	'vs/workbench/parts/files/common/editors/fileEditorInput',
	'vs/workbench/parts/output/browser/logViewer',
	'vs/workbench/parts/output/browser/outputPanel',
	'vs/workbench/parts/welcome/walkThrough/node/walkThroughContentProvider',
	'vs/workbench/services/configuration/node/jsonEditingService',
	'vs/workbench/services/keybinding/common/keybindingEditing',
	'vs/workbench/services/textfile/common/textFileEditorModel',
	'vs/workbench/api/electron-browser/mainThreadSaveParticipant',
	'vs/workbench/services/textfile/common/textFileEditorModelManager',
	'vs/workbench/services/textfile/common/textFileService',
	'vs/workbench/services/themes/common/colorThemeSchema',
	'vs/workbench/services/themes/common/fileIconThemeSchema',
	'vs/workbench/services/themes/common/workbenchThemeService',
	'vs/workbench/parts/codeEditor/electron-browser/textMate/inspectTMScopes',
	'vs/workbench/services/textMate/electron-browser/TMSyntax',
	'vs/workbench/services/themes/electron-browser/fileIconThemeData',
	'vs/workbench/services/themes/electron-browser/fileIconThemeStore',
	'vs/workbench/services/themes/electron-browser/themeCompatibility',
	'vs/workbench/services/themes/electron-browser/colorThemeData',
	'vs/workbench/services/themes/electron-browser/colorThemeStore',
	'vs/workbench/services/themes/electron-browser/workbenchThemeService',
	'vs/workbench/services/timer/common/timerService',
	'vs/workbench/services/timer/node/timerService',
	'vs/workbench/services/title/common/titleService',
	'vs/workbench/services/untitled/common/untitledEditorService',
	'vs/workbench/api/electron-browser/mainThreadDocuments',
	'vs/workbench/browser/labels',
	'vs/workbench/parts/backup/common/backupModelTracker',
	'vs/workbench/parts/markers/browser/markersTreeViewer',
	'vs/workbench/services/editor/common/editorService',
	'vs/workbench/api/electron-browser/mainThreadEditors',
	'vs/workbench/api/electron-browser/mainThreadDocumentsAndEditors',
	'vs/workbench/browser/dnd',
	'vs/workbench/browser/parts/editor/editorPicker',
	'vs/workbench/browser/parts/editor/editorStatus',
	'vs/workbench/browser/parts/editor/rangeDecorations',
	'vs/workbench/browser/parts/editor/textDiffEditor',
	'vs/workbench/browser/parts/editor/editorCommands',
	'vs/workbench/browser/parts/editor/editorActions',
	'vs/workbench/browser/parts/editor/editor.contribution',
	'vs/workbench/browser/parts/editor/titleControl',
	'vs/workbench/browser/parts/editor/noTabsTitleControl',
	'vs/workbench/browser/parts/editor/tabsTitleControl',
	'vs/workbench/browser/parts/editor/editorGroupsControl',
	'vs/workbench/browser/parts/quickopen/quickOpenController',
	'vs/workbench/browser/parts/quickopen/quickopen.contribution',
	'vs/workbench/browser/parts/statusbar/statusbarPart',
	'vs/workbench/browser/parts/titlebar/titlebarPart',
	'vs/workbench/parts/backup/common/backupRestorer',
	'vs/workbench/parts/backup/common/backup.contribution',
	'vs/workbench/parts/codeEditor/electron-browser/inspectKeybindings',
	'vs/workbench/parts/codeEditor/codeEditor.contribution',
	'vs/workbench/parts/debug/browser/debugActions',
	'vs/workbench/parts/debug/browser/debugActionsWidget',
	'vs/workbench/parts/debug/browser/debugQuickOpen',
	'vs/workbench/parts/debug/browser/linkDetector',
	'vs/workbench/parts/debug/browser/exceptionWidget',
	'vs/workbench/parts/debug/electron-browser/debugConfigurationManager',
	'vs/workbench/parts/debug/electron-browser/replViewer',
	'vs/workbench/parts/debug/electron-browser/repl',
	'vs/workbench/parts/execution/electron-browser/execution.contribution',
	'vs/workbench/parts/extensions/node/extensionsWorkbenchService',
	'vs/workbench/parts/files/browser/editors/fileEditorTracker',
	'vs/workbench/parts/files/common/dirtyFilesTracker',
	'vs/workbench/parts/html/browser/webviewEditor',
	'vs/workbench/parts/html/browser/htmlPreviewPart',
	'vs/workbench/parts/html/browser/html.contribution',
	'vs/workbench/parts/localizations/browser/localizationsActions',
	'vs/workbench/parts/localizations/browser/localizations.contribution',
	'vs/workbench/parts/markers/browser/markersPanel',
	'vs/workbench/parts/markers/browser/markersWorkbenchContributions',
	'vs/workbench/parts/markers/electron-browser/markersElectronContributions',
	'vs/workbench/parts/markers/markers.contribution',
	'vs/workbench/parts/output/electron-browser/output.contribution',
	'vs/workbench/parts/preferences/browser/keybindingsEditor',
	'vs/workbench/parts/preferences/browser/preferencesRenderers',
	'vs/workbench/parts/preferences/browser/preferencesEditor',
	'vs/workbench/parts/preferences/browser/preferencesService',
	'vs/workbench/parts/quickopen/browser/commandsHandler',
	'vs/workbench/parts/quickopen/browser/gotoLineHandler',
	'vs/workbench/parts/quickopen/browser/gotoSymbolHandler',
	'vs/workbench/parts/scm/electron-browser/dirtydiffDecorator',
	'vs/workbench/parts/search/browser/openFileHandler',
	'vs/workbench/parts/search/browser/openSymbolHandler',
	'vs/workbench/parts/search/browser/openAnythingHandler',
	'vs/workbench/parts/themes/test/electron-browser/themes.test.contribution',
	'vs/workbench/parts/update/electron-browser/releaseNotesEditor',
	'vs/workbench/parts/welcome/overlay/browser/welcomeOverlay',
	'vs/workbench/parts/welcome/page/electron-browser/welcomePage',
	'vs/workbench/parts/welcome/page/electron-browser/welcomePage.contribution',
	'vs/workbench/parts/welcome/walkThrough/electron-browser/editor/editorWalkThrough',
	'vs/workbench/parts/welcome/walkThrough/electron-browser/walkThroughActions',
	'vs/workbench/parts/welcome/walkThrough/electron-browser/walkThrough.contribution',
	'vs/workbench/services/configuration/node/configurationEditingService',
	'vs/workbench/services/configuration/node/configurationService',
	'vs/workbench/services/configurationResolver/electron-browser/configurationResolverService',
	'vs/workbench/services/history/electron-browser/history',
	'vs/workbench/services/search/node/searchService',
	'vs/workbench/services/textfile/electron-browser/textFileService',
	'vs/workbench/services/textmodelResolver/common/textModelResolverService',
	'vs/workbench/services/viewlet/browser/viewlet',
	'vs/workbench/browser/layout',
	'vs/workbench/browser/parts/activitybar/activitybarActions',
	'vs/workbench/browser/parts/activitybar/activitybarPart',
	'vs/workbench/browser/viewlet',
	'vs/workbench/browser/parts/views/panelViewlet',
	'vs/workbench/browser/parts/views/viewsViewlet',
	'vs/workbench/browser/parts/views/customView',
	'vs/workbench/browser/parts/views/customViewPanel',
	'vs/workbench/api/browser/viewsExtensionPoint',
	'vs/workbench/electron-browser/actions',
	'vs/workbench/parts/debug/browser/debugEditorActions',
	'vs/workbench/parts/debug/browser/debugViewlet',
	'vs/workbench/parts/debug/electron-browser/breakpointsView',
	'vs/workbench/parts/debug/electron-browser/callStackView',
	'vs/workbench/parts/debug/electron-browser/debugCommands',
	'vs/workbench/parts/debug/electron-browser/debugService',
	'vs/workbench/parts/debug/electron-browser/variablesView',
	'vs/workbench/parts/debug/electron-browser/debugHover',
	'vs/workbench/parts/debug/electron-browser/debugEditorContribution',
	'vs/workbench/parts/debug/electron-browser/watchExpressionsView',
	'vs/workbench/parts/debug/electron-browser/debug.contribution',
	'vs/workbench/parts/extensions/browser/extensionsQuickOpen',
	'vs/workbench/parts/extensions/electron-browser/extensionsActions',
	'vs/workbench/parts/files/browser/editors/textFileEditor',
	'vs/workbench/parts/performance/electron-browser/startupProfiler',
	'vs/workbench/parts/performance/electron-browser/performance.contribution',
	'vs/workbench/parts/quickopen/browser/viewPickerHandler',
	'vs/workbench/parts/quickopen/browser/quickopen.contribution',
	'vs/workbench/parts/scm/electron-browser/scmViewlet',
	'vs/workbench/parts/scm/electron-browser/scm.contribution',
	'vs/workbench/parts/search/browser/searchActions',
	'vs/workbench/parts/search/browser/searchResultsView',
	'vs/workbench/parts/search/browser/searchWidget',
	'vs/workbench/parts/tasks/electron-browser/task.contribution',
	'vs/workbench/parts/themes/electron-browser/themes.contribution',
	'vs/workbench/services/extensions/electron-browser/extensionService',
	'vs/workbench/api/electron-browser/mainThreadExtensionService',
	'vs/workbench/services/progress/browser/progressService',
	'vs/workbench/browser/parts/compositePart',
	'vs/workbench/browser/parts/editor/editorPart',
	'vs/workbench/browser/parts/panel/panelPart',
	'vs/workbench/browser/parts/sidebar/sidebarPart',
	'vs/workbench/services/progress/browser/progressService2',
	'vs/workbench/services/viewlet/browser/viewletService',
	'vs/workbench/services/workspace/common/workspaceEditing',
	'vs/workbench/api/electron-browser/mainThreadFileSystem',
	'vs/workbench/api/electron-browser/mainThreadWorkspace',
	'vs/workbench/api/electron-browser/extensionHost.contribution',
	'vs/workbench/browser/actions/workspaceCommands',
	'vs/workbench/browser/actions/workspaceActions',
	'vs/workbench/electron-browser/window',
	'vs/workbench/parts/extensions/browser/extensionsActions',
	'vs/workbench/parts/extensions/browser/extensionEditor',
	'vs/workbench/parts/extensions/browser/extensionsList',
	'vs/workbench/parts/extensions/electron-browser/runtimeExtensionsEditor',
	'vs/workbench/parts/extensions/electron-browser/extensionProfileService',
	'vs/workbench/parts/files/electron-browser/fileCommands',
	'vs/workbench/parts/files/electron-browser/fileActions',
	'vs/workbench/parts/files/electron-browser/saveErrorHandler',
	'vs/workbench/parts/files/electron-browser/views/emptyView',
	'vs/workbench/parts/files/electron-browser/views/explorerViewer',
	'vs/workbench/parts/files/electron-browser/views/explorerView',
	'vs/workbench/parts/files/electron-browser/views/openEditorsView',
	'vs/workbench/parts/files/electron-browser/explorerViewlet',
	'vs/workbench/parts/files/electron-browser/files.contribution',
	'vs/workbench/parts/preferences/browser/preferencesActions',
	'vs/workbench/parts/extensions/electron-browser/extensionsViews',
	'vs/workbench/parts/extensions/electron-browser/extensionsViewlet',
	'vs/workbench/parts/files/electron-browser/fileActions.contribution',
	'vs/workbench/parts/search/browser/searchViewlet',
	'vs/workbench/parts/search/electron-browser/search.contribution',
	'vs/workbench/parts/terminal/electron-browser/terminalActions',
	'vs/workbench/parts/terminal/electron-browser/terminalPanel',
	'vs/workbench/parts/terminal/electron-browser/terminal.contribution',
	'vs/workbench/parts/watermark/electron-browser/watermark',
	'vs/workbench/services/workspace/node/workspaceEditingService',
	'vs/workbench/electron-browser/workbench',
	'vs/workbench/electron-browser/commands',
	'vs/workbench/electron-browser/main.contribution',
	'vs/base/node/request',
	'vs/platform/extensionManagement/node/extensionGalleryService',
	'vs/platform/request/node/requestService',
	'vs/platform/request/electron-browser/requestService',
	'vs/workbench/electron-browser/shell',
	'vs/workbench/electron-browser/main',
	'vs/workbench/parts/extensions/electron-browser/extensionTipsService',
	'vs/workbench/parts/extensions/electron-browser/extensions.contribution',
	'vs/workbench/parts/preferences/electron-browser/preferencesSearch',
	'vs/workbench/parts/preferences/electron-browser/preferences.contribution',
	'vs/workbench/parts/update/electron-browser/update',
	'vs/workbench/parts/update/electron-browser/update.contribution',
	'vs/workbench/workbench.main'
];

let loader = [];
let results = [];

function getFileContents(file) {
	const filePath = path.join(__dirname, '../out', file);
	const fileContents = fs.readFileSync(filePath);
	return fileContents.toString('utf8');
}

PREFIX.forEach((file) => {
	const fileContents = getFileContents(file);
	loader.push(fileContents);
});

var CSS = [];
CONTENTS.forEach((file) => {
	let fileContents = getFileContents(file + '.js');
	fileContents = fileContents.replace(/define\(\[/g, `define("${file}", [`);

	let changed = false;
	do {
		changed = false;
		let m = fileContents.match(/, "vs\/css!([^"]+)"/);
		if (m) {
			let cssPath = m[1];
			let result = cssPath;
			if (/^(\.\/)|(\.\.\/)/.test(result)) {
				result = path.join(file + '/../', result);
			}
			// console.log(`${file} + ${cssPath} ===> ${result}`);
			CSS.push(`vs/css!${result}`);
			fileContents = fileContents.replace(/, "vs\/css!([^"]+)"/, '');
			changed = true;
		}
	} while(changed);

	results.push(fileContents);
});

// TODO@snapshot
const productNameLong = product.nameLong;
// if (!false || process.env['VSCODE_DEV']) {
// 	product.nameShort += ' Dev';
// 	product.nameLong += ' Dev';
// 	product.dataFolderName += '-dev';
// }


product.commit = "05ea088890f0b0a70fa883047b67bf64c005b5b1";
product.date = "2018-02-13T16:38:50.446Z";
product.settingsSearchBuildId = 121000243;

// TODO@snapshot
package.name = 'Code - OSS';

const startupFileContents = `
var Monaco_Loader_Init;
var Monaco_LOG = [];
var Monaco_CSS = ${JSON.stringify(CSS)};
var Monaco_Node_Modules = null;
(function() {
	var doNotInitLoader = true;
	var MonacoSnapshotPlatform = '${process.platform}';
	var MonacoSnapshotArch = '${process.arch}';
	var MonacoSnapshotGlobal = this;
	var MonacoSnapshotPackage = ${JSON.stringify(package)};
	var MonacoSnapshotProduct = ${JSON.stringify(product)};
	var MonacoSnapshotInitializeCallbacks = [];
	var navigator = {
		userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) code-oss-dev/1.21.0 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36'
	};
	${loader.join('\n;\n').toString()};
	(function() {
		var NODE_MODULES = [
			'assert',
			'child_process',
			'crypto',
			'electron',
			'fs',
			'graceful-fs',
			'iconv-lite',
			'native-keymap',
			'net',
			'os',
			'path',
			'semver',
			'spdlog',
			'stream',
			'string_decoder',
			'url',
			'util',
			'zlib',
		];
		Monaco_Node_Modules = Object.create(null);
		var bindModule = function(moduleName) {
			define(moduleName, function() {
				// Monaco_Node_Modules[moduleName] = {};
				// return Monaco_Node_Modules[moduleName];

				var loaded = false;
				var actual = null;
				var cache = Object.create(null);
				var cached = Object.create(null);
				var handler = {
					get: (target, name) => {
						// console.log('get for ' + moduleName + '.' + name);
						// console.log(typeof require.__$__nodeRequire);
						if (!loaded) {
							loaded = true;
							if (moduleName === 'fs') {
								actual = require.__$__nodeRequire('original-fs');
							} else {
								actual = require.__$__nodeRequire(moduleName);
							}
						}

						if (!cached[name]) {
							let result = actual[name];
							// console.log('===> ' + typeof actual[name]);
							if (typeof result === 'function') {
								result = result.bind(actual);
							}
							cache[name] = result;
							cached[name] = true;
						}


						return cache[name];
					},
					set: (target, name, value) => {
						// console.log('set for ' + moduleName + '.' + name);
						cache[name] = value;
						cached[name] = true;
					}
				};
				return new Proxy(Object.create(null), handler);

			});
		};
		NODE_MODULES.forEach(bindModule);
	})();
	${results.join('\n;\n').toString()};
	Monaco_Loader_Init = function() {
		AMDLoader.init();
		Object.keys(Monaco_Node_Modules).forEach(function(moduleName) {
			var actual = require.__$__nodeRequire(moduleName);
			var target = Monaco_Node_Modules[moduleName];

			//console.log('required ' + moduleName);
			Object.keys(actual).forEach(function(key) {
				if (moduleName === 'crypto') {
					if (key === 'createCredentials' || key === 'Credentials') {
						return;
					}
				}
				target[key] = actual[key];
			});
		});
		MonacoSnapshotInitializeCallbacks.forEach(function(callback) {
			callback();
		});
		[
			'assert',
			'child_process',
			'crypto',
			'electron',
			'fs',
			'graceful-fs',
			'iconv-lite',
			'native-keymap',
			'net',
			'os',
			'path',
			'semver',
			'spdlog',
			'stream',
			'string_decoder',
			'url',
			'util',
			'zlib',
		].forEach(function(moduleName) {
			require.__$__nodeRequire(moduleName);
		});
		return { define, require };
	};
})();
`;

const startupFile = path.join(__dirname, 'start.js');
fs.writeFileSync(startupFile, startupFileContents);

const startupBlobFilepath = path.join(__dirname, `../.build/electron/${productNameLong}.app/Contents/Frameworks/Electron Framework.framework/Resources/snapshot_blob.bin`);
// startupBlobFilepath = `VSCode-${process.platform}-${arch}/snapshot_blob.bin`;

// Restore original
try { fs.unlinkSync(startupBlobFilepath); } catch (err) { /**/ }
// fs.copyFileSync(startupBlobFilepath + '.original', startupBlobFilepath);
// process.exit(0);

// Check that the file works!
vm.runInNewContext(startupFileContents, undefined, { filename: startupFile, displayErrors: true });

const mksnapshot = path.join(__dirname, `../node_modules/.bin/${process.platform === 'win32' ? 'mksnapshot.cmd' : 'mksnapshot'}`);
cp.execFileSync(mksnapshot, [`--no-use_ic`, `--no-lazy`, startupFile, `--startup_blob`, startupBlobFilepath]);

// --ignition --turbo

console.log(`FILE SIZE: ${fs.statSync(startupBlobFilepath).size}`);


// Extra copy
const startupBlobFilepath2 = path.join(__dirname, `../../VSCode-darwin/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Resources/snapshot_blob.bin`);
try { fs.unlinkSync(startupBlobFilepath2); } catch (err) { /**/ }
fs.copyFileSync(startupBlobFilepath, startupBlobFilepath2);
