global class GetAppointmentSlotsInputBuilder {
	global GetAppointmentSlotsInputBuilder() { }
	global lxscheduler.GetAppointmentSlotsInput build() { }
	global Object clone() { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setAccountId(String accountId) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setAllowConcurrentScheduling(Boolean allowConcurrentScheduling) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setApiVersion(Double apiVersion) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setCorrelationId(String correlationId) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setEndTime(String endTime) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setEngagementChannelTypeIds(List<String> engagementChannelTypeIds) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setPrimaryResourceId(String primaryResourceId) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setRequiredResourceIds(List<String> requiredResourceIds) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setSchedulingPolicyId(String schedulingPolicyId) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setStartTime(String startTime) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setTerritoryIds(List<String> territoryIds) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setWorkType(lxscheduler.WorkType workType) { }
	global lxscheduler.GetAppointmentSlotsInputBuilder setWorkTypeGroupId(String workTypeGroupId) { }

}