global class GetAppointmentCandidatesInputBuilder {
	global GetAppointmentCandidatesInputBuilder() { }
	global lxscheduler.GetAppointmentCandidatesInput build() { }
	global Object clone() { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setAccountId(String accountId) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setAllowConcurrent(Boolean allowConcurrent) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setApiVersion(Double apiVersion) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setCorrelationId(String correlationId) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setEndTime(String endTime) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setEngagementChannelTypeIds(List<String> engagementChannelTypeIds) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setFilterByResources(List<String> filterByResources) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setResourceLimitApptDistribution(Integer resourceLimitApptDistribution) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setSchedulingPolicyId(String schedulingPolicyId) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setStartTime(String startTime) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setTerritoryIds(List<String> territoryIds) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setWorkType(lxscheduler.WorkType workType) { }
	global lxscheduler.GetAppointmentCandidatesInputBuilder setWorkTypeGroupId(String workTypeGroupId) { }

}