/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { PolicyName } from '../../../../base/common/policy.js';

export const CORE_POLICY_NAMES = [
	'AllowedExtensions',
	'BrowserChatTools',
	'ChatAgentAllowedNetworkDomains',
	'ChatAgentDeniedNetworkDomains',
	'ChatAgentExtensionTools',
	'ChatAgentMode',
	'ChatAgentNetworkFilter',
	'ChatAgentSandboxAllowAutoApprove',
	'ChatAgentSandboxAllowNetwork',
	'ChatAgentSandboxAllowUnsandboxedCommands',
	'ChatAgentSandboxEnabled',
	'ChatAllowManagedHooksOnly',
	'ChatAllowManagedMcpServersOnly',
	'ChatAllowedMcpServers',
	'ChatApprovedAccountOrganizations',
	'ChatDefaultModel',
	'ChatDeniedMcpServers',
	'ChatEditorPreferCopilotHarness',
	'ChatEnabledPlugins',
	'ChatExtraMarketplaces',
	'ChatHooks',
	'ChatMCP',
	'ChatPluginsEnabled',
	'ChatStrictMarketplaces',
	'ChatStrictPluginOnlyCustomization',
	'ChatToolsAutoApprove',
	'ChatToolsEligibleForAutoApproval',
	'ChatToolsTerminalEnableAutoApprove',
	'Claude3PIntegration',
	'Codex3PIntegration',
	'CopilotNextEditSuggestions',
	'CopilotOtelCaptureContent',
	'CopilotOtelEnabled',
	'CopilotOtelEndpoint',
	'CopilotOtelHeaders',
	'CopilotOtelOtlpProtocol',
	'CopilotOtelOutfile',
	'CopilotOtelProtocol',
	'CopilotOtelResourceAttributes',
	'CopilotOtelServiceName',
	'CopilotReviewAgent',
	'CopilotReviewSelection',
	'CopilotSessionSync',
	'DictationEnabled',
	'EnableFeedback',
	'ExtensionGalleryServiceUrl',
	'ExtensionsAutoUpdate',
	'ExtensionsAutoUpdateDelay',
	'McpEnterpriseManagedAuthIdp',
	'McpGalleryServiceUrl',
	'TelemetryLevel',
	'UpdateMode',
] as const satisfies readonly PolicyName[];
