global class InvalidSnapshotDateException extends Exception {
	global InvalidSnapshotDateException(String param0, Exception param1) { }
	global InvalidSnapshotDateException(Exception param0) { }
	global InvalidSnapshotDateException(String param0) { }
	global InvalidSnapshotDateException() { }
	global Object clone() { }
	global List<String> getSnapshotDateErrors() { }
	global String getTypeName() { }

}