global class InvalidReportMetadataException extends Exception {
	global InvalidReportMetadataException(String param0, Exception param1) { }
	global InvalidReportMetadataException(Exception param0) { }
	global InvalidReportMetadataException(String param0) { }
	global InvalidReportMetadataException() { }
	global Object clone() { }
	global List<String> getReportMetadataErrors() { }
	global String getTypeName() { }

}