global class ReportCsf {
	global ReportCsf(String label, String description, reports.FormulaType formulaType, Integer decimalPlaces, String downGroup, reports.CsfGroupType downGroupType, String acrossGroup, reports.CsfGroupType acrossGroupType, String formula) { }
	global ReportCsf() { }
	global Object clone() { }
	global String getAcrossGroup() { }
	global reports.CsfGroupType getAcrossGroupType() { }
	global Integer getDecimalPlaces() { }
	global String getDescription() { }
	global String getDownGroup() { }
	global reports.CsfGroupType getDownGroupType() { }
	global String getFormula() { }
	global reports.FormulaType getFormulaType() { }
	global String getLabel() { }
	global void setAcrossGroup(String acrossGroup) { }
	global void setAcrossGroupType(String value) { }
	global void setAcrossGroupType(reports.CsfGroupType acrossGroupType) { }
	global void setDecimalPlaces(Integer decimalPlaces) { }
	global void setDescription(String description) { }
	global void setDownGroup(String downGroup) { }
	global void setDownGroupType(String value) { }
	global void setDownGroupType(reports.CsfGroupType downGroupType) { }
	global void setFormula(String formula) { }
	global void setFormulaType(String value) { }
	global void setFormulaType(reports.FormulaType formulaType) { }
	global void setLabel(String label) { }
	global String toString() { }

}