global class SortColumn {
	global SortColumn(String sortColumn, reports.ColumnSortOrder sortOrder) { }
	global SortColumn() { }
	global Object clone() { }
	global String getSortColumn() { }
	global reports.ColumnSortOrder getSortOrder() { }
	global void setSortColumn(String sortColumn) { }
	global void setSortOrder(String value) { }
	global void setSortOrder(reports.ColumnSortOrder sortOrder) { }
	global String toString() { }

}