global class StandardDateFilter {
	global StandardDateFilter(String column, String durationValue, String startDate, String endDate) { }
	global StandardDateFilter() { }
	global Object clone() { }
	global String getColumn() { }
	global String getDurationValue() { }
	global String getEndDate() { }
	global String getStartDate() { }
	global void setColumn(String column) { }
	global void setDurationValue(String durationValue) { }
	global void setEndDate(String endDate) { }
	global void setStartDate(String startDate) { }
	global String toString() { }

}