global class TopRows {
	global TopRows(Integer rowLimit, reports.ColumnSortOrder direction) { }
	global TopRows() { }
	global Object clone() { }
	global reports.ColumnSortOrder getDirection() { }
	global Integer getRowLimit() { }
	global void setDirection(String value) { }
	global void setDirection(reports.ColumnSortOrder direction) { }
	global void setRowLimit(Integer rowLimit) { }
	global String toString() { }

}