/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// DO NOT EDIT -- generated by scripts/generate-agent-host-uri-projections.ts

import { URI } from '../../../../base/common/uri.js';
import type { AnnotationsEntryRemovedAction, AnnotationsEntrySetAction, AnnotationsRemovedAction, AnnotationsSetAction, AnnotationsUpdatedAction } from './protocol/channels-annotations/actions.js';
import type { Annotation, AnnotationOrigin, AnnotationsState } from './protocol/channels-annotations/state.js';
import { ActionType, type ActionEnvelope } from './protocol/common/actions.js';
import type { InitializeResult } from './protocol/common/commands.js';

export interface IAgentHostUriProjectionContext {
	decodeUri(value: string): URI;
	encodeUri(value: URI): string;
}

export type NativeAnnotationsState = Omit<AnnotationsState, 'annotations'> & {
	readonly annotations: NativeAnnotation[];
};

export type NativeAnnotation = Omit<Annotation, 'origin' | 'resource'> & {
	readonly origin: NativeAnnotationOrigin;
	readonly resource: URI;
};

export type NativeAnnotationOrigin = Omit<AnnotationOrigin, 'session' | 'chat'> & {
	readonly session: URI;
	readonly chat?: URI;
};

export type NativeInitializeResult = Omit<InitializeResult, 'defaultDirectory'> & {
	readonly defaultDirectory?: URI;
};

export type NativeAnnotationsSetAction = Omit<AnnotationsSetAction, 'annotation'> & {
	readonly annotation: NativeAnnotation;
};

export type NativeAnnotationsUpdatedAction = Omit<AnnotationsUpdatedAction, 'origin' | 'resource'> & {
	readonly origin?: NativeAnnotationOrigin;
	readonly resource?: URI;
};

export type NativeClientAnnotationsAction =
	| NativeAnnotationsSetAction
	| NativeAnnotationsUpdatedAction
	| AnnotationsRemovedAction
	| AnnotationsEntrySetAction
	| AnnotationsEntryRemovedAction;

export type NativeAnnotationsActionEnvelope = Omit<ActionEnvelope, 'channel' | 'action'> & {
	readonly channel: URI;
	readonly action: NativeClientAnnotationsAction;
};

export function decodeAnnotationsState(annotationsState: AnnotationsState, context: IAgentHostUriProjectionContext): NativeAnnotationsState {
	return {
		...annotationsState,
		annotations: annotationsState.annotations.map(value => decodeAnnotation(value, context)),
	};
}

export function encodeAnnotationsState(annotationsState: NativeAnnotationsState, context: IAgentHostUriProjectionContext): AnnotationsState {
	return {
		...annotationsState,
		annotations: annotationsState.annotations.map(value => encodeAnnotation(value, context)),
	};
}

function decodeAnnotation(annotation: Annotation, context: IAgentHostUriProjectionContext): NativeAnnotation {
	return {
		...annotation,
		origin: decodeAnnotationOrigin(annotation.origin, context),
		resource: context.decodeUri(annotation.resource),
	};
}

function encodeAnnotation(annotation: NativeAnnotation, context: IAgentHostUriProjectionContext): Annotation {
	return {
		...annotation,
		origin: encodeAnnotationOrigin(annotation.origin, context),
		resource: context.encodeUri(annotation.resource),
	};
}

function decodeAnnotationOrigin(annotationOrigin: AnnotationOrigin, context: IAgentHostUriProjectionContext): NativeAnnotationOrigin {
	return {
		...annotationOrigin,
		session: context.decodeUri(annotationOrigin.session),
		chat: annotationOrigin.chat === undefined ? undefined : context.decodeUri(annotationOrigin.chat),
	};
}

function encodeAnnotationOrigin(annotationOrigin: NativeAnnotationOrigin, context: IAgentHostUriProjectionContext): AnnotationOrigin {
	return {
		...annotationOrigin,
		session: context.encodeUri(annotationOrigin.session),
		chat: annotationOrigin.chat === undefined ? undefined : context.encodeUri(annotationOrigin.chat),
	};
}

export function decodeInitializeResult(initializeResult: InitializeResult, context: IAgentHostUriProjectionContext): NativeInitializeResult {
	return {
		...initializeResult,
		defaultDirectory: initializeResult.defaultDirectory === undefined ? undefined : context.decodeUri(initializeResult.defaultDirectory),
	};
}

function decodeAnnotationsSetAction(annotationsSetAction: AnnotationsSetAction, context: IAgentHostUriProjectionContext): NativeAnnotationsSetAction {
	return {
		...annotationsSetAction,
		annotation: decodeAnnotation(annotationsSetAction.annotation, context),
	};
}

function encodeAnnotationsSetAction(annotationsSetAction: NativeAnnotationsSetAction, context: IAgentHostUriProjectionContext): AnnotationsSetAction {
	return {
		...annotationsSetAction,
		annotation: encodeAnnotation(annotationsSetAction.annotation, context),
	};
}

function decodeAnnotationsUpdatedAction(annotationsUpdatedAction: AnnotationsUpdatedAction, context: IAgentHostUriProjectionContext): NativeAnnotationsUpdatedAction {
	return {
		...annotationsUpdatedAction,
		origin: annotationsUpdatedAction.origin === undefined ? undefined : decodeAnnotationOrigin(annotationsUpdatedAction.origin, context),
		resource: annotationsUpdatedAction.resource === undefined ? undefined : context.decodeUri(annotationsUpdatedAction.resource),
	};
}

function encodeAnnotationsUpdatedAction(annotationsUpdatedAction: NativeAnnotationsUpdatedAction, context: IAgentHostUriProjectionContext): AnnotationsUpdatedAction {
	return {
		...annotationsUpdatedAction,
		origin: annotationsUpdatedAction.origin === undefined ? undefined : encodeAnnotationOrigin(annotationsUpdatedAction.origin, context),
		resource: annotationsUpdatedAction.resource === undefined ? undefined : context.encodeUri(annotationsUpdatedAction.resource),
	};
}

export function decodeClientAnnotationsAction(action: AnnotationsSetAction | AnnotationsUpdatedAction | AnnotationsRemovedAction | AnnotationsEntrySetAction | AnnotationsEntryRemovedAction, context: IAgentHostUriProjectionContext): NativeClientAnnotationsAction {
	switch (action.type) {
		case ActionType.AnnotationsSet:
			return decodeAnnotationsSetAction(action, context);
		case ActionType.AnnotationsUpdated:
			return decodeAnnotationsUpdatedAction(action, context);
		default:
			return action;
	}
}

export function encodeClientAnnotationsAction(action: NativeClientAnnotationsAction, context: IAgentHostUriProjectionContext): AnnotationsSetAction | AnnotationsUpdatedAction | AnnotationsRemovedAction | AnnotationsEntrySetAction | AnnotationsEntryRemovedAction {
	switch (action.type) {
		case ActionType.AnnotationsSet:
			return encodeAnnotationsSetAction(action, context);
		case ActionType.AnnotationsUpdated:
			return encodeAnnotationsUpdatedAction(action, context);
		default:
			return action;
	}
}

export function decodeAnnotationsActionEnvelope(envelope: ActionEnvelope, context: IAgentHostUriProjectionContext): NativeAnnotationsActionEnvelope {
	return {
		...envelope,
		channel: context.decodeUri(envelope.channel),
		action: decodeClientAnnotationsAction(envelope.action as AnnotationsSetAction | AnnotationsUpdatedAction | AnnotationsRemovedAction | AnnotationsEntrySetAction | AnnotationsEntryRemovedAction, context),
	};
}
