global class DescribeQuickActionResult {
	global String accesslevelrequired;
	global String canvasapplicationid;
	global String canvasapplicationname;
	global List<Schema.DescribeColorResult> colors;
	global String contextsobjecttype;
	global List<QuickAction.DescribeQuickActionDefaultValue> defaultvalues;
	global String flowdevname;
	global String flowrecordidvar;
	global Integer height;
	global String iconname;
	global List<Schema.DescribeIconResult> icons;
	global String iconurl;
	global QuickAction.DescribeLayoutSection layout;
	global String lightningcomponentbundleid;
	global String lightningcomponentbundlename;
	global String lightningcomponentqualifiedname;
	global String lightningwebcomponentbundleid;
	global String lightningwebcomponentbundlename;
	global String lightningwebcomponentqualifiedname;
	global String miniiconurl;
	global String mobileextensionid;
	global List<QuickAction.DescribeQuickActionParameter> parameters;
	global Boolean showquickactionlcheader;
	global Boolean showquickactionvfheader;
	global String targetparentfield;
	global String targetrecordtypeid;
	global String targetsobjecttype;
	global String visualforcepagename;
	global String visualforcepageurl;
	global Integer width;
	global Boolean equals(Object obj) { }
	global String getAccessLevelRequired() { }
	global String getActionEnumOrId() { }
	global String getCanvasApplicationId() { }
	global String getCanvasApplicationName() { }
	global List<Schema.DescribeColorResult> getColors() { }
	global String getContextSobjectType() { }
	global List<QuickAction.DescribeQuickActionDefaultValue> getDefaultValues() { }
	global String getFlowDevName() { }
	global String getFlowRecordIdVar() { }
	global Integer getHeight() { }
	global String getIconName() { }
	global String getIconUrl() { }
	global List<Schema.DescribeIconResult> getIcons() { }
	global String getLabel() { }
	global QuickAction.DescribeLayoutSection getLayout() { }
	global String getLightningComponentBundleId() { }
	global String getLightningComponentBundleName() { }
	global String getLightningComponentQualifiedName() { }
	global String getLightningWebComponentBundleId() { }
	global String getLightningWebComponentBundleName() { }
	global String getLightningWebComponentQualifiedName() { }
	global String getMiniIconUrl() { }
	global String getMobileExtensionId() { }
	global String getName() { }
	global List<QuickAction.DescribeQuickActionParameter> getParameters() { }
	global Boolean getShowQuickActionLcHeader() { }
	global Boolean getShowQuickActionVfHeader() { }
	global String getTargetParentField() { }
	global String getTargetRecordTypeId() { }
	global String getTargetSobjectType() { }
	global String getType() { }
	global String getVisualforcePageName() { }
	global String getVisualforcePageUrl() { }
	global Integer getWidth() { }
	global Integer hashCode() { }
	global String toString() { }

}