global class DescribeLayoutItem {
	global Boolean editablefornew;
	global Boolean editableforupdate;
	global String label;
	global List<QuickAction.DescribeLayoutComponent> layoutcomponents;
	global Boolean placeholder;
	global Boolean required;
	global String uibehavior;
	global Boolean equals(Object obj) { }
	global String getLabel() { }
	global List<QuickAction.DescribeLayoutComponent> getLayoutComponents() { }
	global String getUiBehavior() { }
	global Integer hashCode() { }
	global Boolean isEditableForNew() { }
	global Boolean isEditableForUpdate() { }
	global Boolean isPlaceholder() { }
	global Boolean isRequired() { }
	global String toString() { }

}