global class DescribeLayoutSection {
	global Boolean collapsed;
	global Integer columns;
	global String heading;
	global List<QuickAction.DescribeLayoutRow> layoutrows;
	global Id layoutsectionid;
	global Id parentlayoutid;
	global Integer rows;
	global String taborder;
	global Boolean usecollapsiblesection;
	global Boolean useheading;
	global Boolean equals(Object obj) { }
	global Integer getColumns() { }
	global String getHeading() { }
	global List<QuickAction.DescribeLayoutRow> getLayoutRows() { }
	global Id getLayoutSectionId() { }
	global Id getParentLayoutId() { }
	global Integer getRows() { }
	global String getTabOrder() { }
	global Integer hashCode() { }
	global Boolean isCollapsed() { }
	global Boolean isUseCollapsibleSection() { }
	global Boolean isUseHeading() { }
	global String toString() { }

}