global class QuickActionTemplateResult {
	global String contextid;
	global SObject defaultvalueformulas;
	global SObject defaultvalues;
	global List<Database.Error> errors;
	global Boolean success;
	global Boolean equals(Object obj) { }
	global String getContextId() { }
	global SObject getDefaultValueFormulas() { }
	global SObject getDefaultValues() { }
	global List<Database.Error> getErrors() { }
	global Integer hashCode() { }
	global Boolean isSuccess() { }
	global String toString() { }

}