global class QuickActionRequest {
	global Id contextid;
	global String quickactionname;
	global SObject record;
	global QuickActionRequest() { }
	global Boolean equals(Object obj) { }
	global Id getContextId() { }
	global String getQuickActionName() { }
	global SObject getRecord() { }
	global Integer hashCode() { }
	global void setContextId(Id param0) { }
	global void setQuickActionName(String param0) { }
	global void setRecord(SObject param0) { }
	global String toString() { }

}