global class ReportChartComponent {
	global Boolean cachedata;
	global String contextfilterablefield;
	global String error;
	global Boolean hideonerror;
	global Boolean includecontext;
	global Boolean showtitle;
	global String size;
	global Boolean equals(Object obj) { }
	global Boolean getCacheData() { }
	global String getContextFilterableField() { }
	global Integer getDisplayLines() { }
	global String getError() { }
	global Boolean getHideOnError() { }
	global Boolean getIncludeContext() { }
	global Boolean getShowTitle() { }
	global String getSize() { }
	global Integer getTabOrder() { }
	global String getType() { }
	global String getValue() { }
	global Integer hashCode() { }
	global String toString() { }

}