global class EmailAttachment {
	global Blob body;
	global String contentid;
	global String contenttype;
	global String filename;
	global EmailAttachment() { }
	global Boolean equals(Object obj) { }
	global Blob getBody() { }
	global String getContentId() { }
	global String getContentType() { }
	global String getFileName() { }
	global Integer hashCode() { }
	global void setBody(Blob param0) { }
	global void setContentId(String param0) { }
	global void setContentType(String param0) { }
	global void setFileName(String param0) { }
	global String toString() { }

}