global class Email {
	global Boolean bccsender;
	global String emailpriority;
	global String replyto;
	global Boolean saveasactivity;
	global String senderdisplayname;
	global String subject;
	global Boolean usesignature;
	global Boolean equals(Object obj) { }
	global Boolean getBccSender() { }
	global String getEmailPriority() { }
	global String getReplyTo() { }
	global Boolean getSaveAsActivity() { }
	global String getSenderDisplayName() { }
	global String getSubject() { }
	global Boolean getUseSignature() { }
	global Integer hashCode() { }
	global void setBccSender(Boolean param0) { }
	global void setEmailPriority(String param0) { }
	global void setReplyTo(String param0) { }
	global void setSaveAsActivity(Boolean param0) { }
	global void setSenderDisplayName(String param0) { }
	global void setSubject(String param0) { }
	global void setUseSignature(Boolean param0) { }
	global String toString() { }

}