/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

const {
	assert,
	path,
	glob,
	util,
	fs,
	setRun,
	xterm,
	stringDecoder,
	url,
	net,
	stream,
	events,
	vscodeRegexpp,
	vscodeSqlite3,
	cookie,
	crypto,
	zlib,
	sinon,
	os,
	nativeKeymap,
	parcelWatcher,
	kerberos,
	electron,
	minimist,
	vscodeRipgrep,
	nativeIsElevated,
	nativeWatchdog,
	gracefulFs,
	sinonTest,
	childProcess,
	yauzl,
	jschardet,
	xtermHeadless,
	xtermAddonCanvas
} = globalThis.testGlobals;


export {
	assert,
	path,
	glob,
	xterm,
	util,
	fs,
	setRun,
	url,
	stringDecoder,
	events,
	vscodeRipgrep,
	vscodeRegexpp,
	stream,
	net,
	nativeIsElevated,
	kerberos,
	nativeKeymap,
	crypto,
	zlib,
	parcelWatcher,
	nativeWatchdog,
	cookie,
	vscodeSqlite3,
	yauzl,
	os,
	sinon,
	electron,
	sinonTest,
	minimist,
	gracefulFs,
	childProcess,
	xtermAddonCanvas,
	jschardet,
	xtermHeadless
};
