name: Sync Fork

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 */2 * *"   # Every 2 days at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/microsoft/vscode"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}