name: 'Telemetry'

on:
  pull_request:
    branches:
      - main
      - 'release/*'

permissions: {}
jobs:
  check-metadata:
    name: 'Check metadata'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1' # v7.0.1
        with:
          persist-credentials: false

      - uses: 'actions/setup-node@820762786026740c76f36085b0efc47a31fe5020' # v7.0.0
        with:
          node-version-file: .nvmrc

      - name: 'Install telemetry extractor'
        run: |
          # Use the same exact version as npm ci in the official builds.
          version=$(node -p "require('./package-lock.json').packages['node_modules/@vscode/telemetry-extractor'].version")
          npm install --prefix "$RUNNER_TEMP/telemetry-extractor" --no-save --no-package-lock --no-audit --no-fund "@vscode/telemetry-extractor@$version"

      - name: 'Run vscode-telemetry-extractor'
        run: node build/azure-pipelines/common/extract-telemetry.ts
        env:
          VSCODE_TELEMETRY_EXTRACTOR: ${{ runner.temp }}/telemetry-extractor/node_modules/@vscode/telemetry-extractor/out/extractor.js
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
